"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const read=file=>fs.readFileSync(path.join(__dirname,"..",file),"utf8");
test("admin dashboard exposes both readiness destinations through canonically revealed controls",()=>{const html=read("public/dashboard.html"),js=read("public/dashboard.js");assert.match(html,/id="developmentLaunchCard"[^>]*hidden/);assert.match(html,/href="\/admin-launch-readiness\.html"/);assert.match(html,/href="\/admin-avatar-development\.html"/);assert.match(js,/roles\.some\(\(role\) => role === "admin" \|\| role === "super_admin"\)/);assert.match(js,/developmentLaunchCard\.hidden = !hasObservabilityAccess/)});
test("global menu role policy includes both boards and excludes an ordinary member",()=>{const source=read("public/global-nav.js");for(const [label,href] of [["Launch Readiness","/admin-launch-readiness.html"],["Avatar Development Board","/admin-avatar-development.html"]]){assert.match(source,new RegExp(`label:"${label}".*href:"${href.replaceAll("/","\\/")}".*roles:\\["admin","super_admin"\\]`))}assert.match(source,/item\.roles\.some\(role=>roleSet\(state\.user\)\.has\(role\)\)/)});
test("avatar board has a dedicated route while sharing the protected readiness API",()=>{const html=read("public/admin-avatar-development.html"),server=read("server.js");assert.match(html,/data-default-board="avatar"/);assert.match(html,/Avatar Development Board/);assert.match(server,/app\.get\("\/admin-avatar-development\.html"/);assert.match(server,/app\.get\("\/api\/admin\/launch-readiness", requireAuth, permission/);assert.match(server,/app\.patch\("\/api\/admin\/launch-readiness\/:board\/:cardId", requireAuth, permission/)});
test("avatar card IDs are stable and canonical status cannot be manually overridden",()=>{const service=read("src/services/launchReadinessService.js");assert.match(service,/id: slug\(`avatar-\$\{category\}-\$\{title\}`\)/);assert.match(service,/canonical: true/);assert.match(service,/canonical_status_immutable/);assert.match(service,/human_requirement_immutable/);assert.match(service,/"evidence".*"blocker".*"tester".*"verifiedAt"/)});
test("both readiness boards restore canonical auth before protected requests and distinguish denial",()=>{const js=read("public/admin-launch-readiness.js");for(const html of [read("public/admin-launch-readiness.html"),read("public/admin-avatar-development.html")])assert.match(html,/auth-state-runtime[\s\S]+auth-navigation[\s\S]+admin-launch-readiness/);assert.equal((js.match(/AuthNavigation\.requireUser\(\{redirect:false\}\)/g)||[]).length,1);assert.doesNotMatch(js,/AuthStateRuntime\?\.whenReady/);assert.ok(js.indexOf("AuthNavigation.requireUser")<js.indexOf('request("\/api\/admin\/launch-readiness")'));assert.match(js,/response\.status===403\?"Access denied/);assert.match(js,/credentials:"same-origin"/);assert.match(js,/dataset\.authState=error\.status===403\?"access-denied"/)});
test("admin board guard has one restoration owner and preserves all terminal states",()=>{const js=read("public/admin-launch-readiness.js");assert.equal((js.match(/AuthNavigation\.requireUser\(\{redirect:false\}\)/g)||[]).length,1,"one canonical guard shared by Launch Readiness and Avatar Development");assert.doesNotMatch(js,/AuthStateRuntime\?\.whenReady/,"page must not start a second readiness flow");assert.match(js,/result\.retryable[\s\S]+state:"restoring"/);assert.match(js,/state:"unauthenticated"[\s\S]+Sign in/);assert.match(js,/response\.status===403\?"Access denied/);assert.match(js,/state=await request\("\/api\/admin\/launch-readiness"\);render\(\)/)});

function adminBoardHarness({board="launch",guardResult={ok:true},httpStatus=200}={}){
  const elements=new Map(),element=id=>{if(!elements.has(id))elements.set(id,{id,dataset:{},className:"",innerHTML:"",addEventListener(){},querySelector(){return null}});return elements.get(id)};
  const document={body:{dataset:{defaultBoard:board}},querySelector:selector=>element(selector),querySelectorAll:()=>[],addEventListener(){}};
  let guardCalls=0,fetchCalls=0;
  const window={document,location:{pathname:board==="avatar"?"/admin-avatar-development.html":"/admin-launch-readiness.html",reload(){}},AuthStateRuntime:{getCanonicalAuthState:()=>({token:"test-token"})},AuthNavigation:{requireUser:async options=>{guardCalls++;assert.equal(options.redirect,false);return guardResult},loginUrl:returnTo=>`/login.html?returnTo=${encodeURIComponent(returnTo)}`},fetch:async()=>{fetchCalls++;return{ok:httpStatus>=200&&httpStatus<300,status:httpStatus,json:async()=>({data:{summaries:{launch:{counts:{},remaining:0},avatar:{counts:{},remaining:0}},boards:{launch:[],avatar:[]}}})}}};
  window.window=window;
  vm.runInNewContext(read("public/admin-launch-readiness.js"),{window,document,location:window.location,fetch:window.fetch,console});
  return{board:element("#board"),counts:()=>({guardCalls,fetchCalls})};
}
const settle=()=>new Promise(resolve=>setImmediate(()=>setImmediate(resolve)));

test("Launch Readiness and Avatar Development each execute one canonical guard",async()=>{for(const board of ["launch","avatar"]){const harness=adminBoardHarness({board,guardResult:{ok:false,retryable:true}});assert.match(harness.board.innerHTML,/Restoring your Pocket PT session/);await settle();assert.deepEqual(harness.counts(),{guardCalls:1,fetchCalls:0});assert.equal(harness.board.dataset.authState,"restoring");assert.match(harness.board.innerHTML,/Retry/)}});
test("admin board terminal states render from the single guard and protected response",async()=>{const signedOut=adminBoardHarness({guardResult:{ok:false,reason:"missing_token",retryable:false}});await settle();assert.equal(signedOut.counts().guardCalls,1);assert.match(signedOut.board.innerHTML,/Sign in/);const denied=adminBoardHarness({httpStatus:403});await settle();assert.deepEqual(denied.counts(),{guardCalls:1,fetchCalls:1});assert.equal(denied.board.dataset.authState,"access-denied");assert.match(denied.board.innerHTML,/Access denied/);assert.doesNotMatch(denied.board.innerHTML,/>Sign in</);const ready=adminBoardHarness();await settle();assert.deepEqual(ready.counts(),{guardCalls:1,fetchCalls:1});assert.match(ready.board.innerHTML,/class="column"/) });
