"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const {createGooglePlacesTrailProvider,deduplicateAndRank,DISCOVERY_QUERIES}=require("../src/services/nearbyTrailService");
const {METERS_PER_MILE,planVerifiedRoute,unavailableRoute}=require("../src/services/goalRoutePlanner");
const response=body=>new Response(JSON.stringify(body),{status:200,headers:{"content-type":"application/json"}});

test("manual text search supports named parks, neighborhoods, cities, ZIP codes, and addresses",async()=>{const queries=[];const provider=createGooglePlacesTrailProvider({apiKey:"server-only",logger:{info(){},warn(){}},fetchImpl:async(url,options)=>{queries.push(JSON.parse(options.body).textQuery);assert.match(url,/searchText$/);return response({places:[{id:"vitruvian",displayName:{text:"Vitruvian Park"},location:{latitude:32.94,longitude:-96.83},primaryType:"park"}]});}});for(const query of ["Vitruvian Trail","Vitruvian Park, Addison, TX","Brookhaven trails","parks near 75244","walking trails in Addison","123 Main St, Addison TX"]){const found=await provider.searchText(query);assert.equal(found[0].routeSourceLabel,"Place location only");}assert.deepEqual(queries,["Vitruvian Trail","Vitruvian Park, Addison, TX","Brookhaven trails","parks near 75244","walking trails in Addison","123 Main St, Addison TX"]);});

test("layered nearby discovery includes trail, park, and recreation concepts",()=>{assert.ok(DISCOVERY_QUERIES.includes("walking trails"));assert.ok(DISCOVERY_QUERIES.includes("greenways"));assert.ok(DISCOVERY_QUERIES.includes("recreation areas"));});

test("deduplication uses provider IDs and normalized nearby names while ranking verified geometry first",()=>{const items=[{id:"a",providerId:"same",name:"Vitruvian Park",latitude:1,longitude:2,distanceFromUserMeters:30},{id:"b",providerId:"same",name:"Vitruvian Trail",latitude:1,longitude:2,distanceFromUserMeters:20},{id:"c",name:"Brookhaven Trail",latitude:1.01,longitude:2,distanceFromUserMeters:100,trailRouteId:"verified"},{id:"d",name:"brookhaven trail",latitude:1.0101,longitude:2,distanceFromUserMeters:110}];const found=deduplicateAndRank(items);assert.equal(found.length,2);assert.equal(found[0].trailRouteId,"verified");});

test("half-mile and one-mile verified out-and-back routes turn at half distance",()=>{const geometry=[{latitude:0,longitude:0},{latitude:0,longitude:.02}];for(const target of [.5*METERS_PER_MILE,METERS_PER_MILE]){const route=planVerifiedRoute({targetDistanceMeters:target,geometry,routeType:"out_and_back"})[0];assert.equal(route.routeSourceLabel,"Verified trail route");assert.ok(route.turnaroundPoint);assert.ok(Math.abs(route.estimatedDistanceMeters-target)<1);assert.equal(route.withinTolerance,true);assert.equal(route.polyline[0].longitude,route.polyline[route.polyline.length-1].longitude);}});

test("loop planner provides exact partial-loop and full-loop alternatives ranked by error",()=>{const loop=[{latitude:0,longitude:0},{latitude:0,longitude:.006},{latitude:.006,longitude:.006},{latitude:0,longitude:0}],target=2*METERS_PER_MILE;const routes=planVerifiedRoute({targetDistanceMeters:target,geometry:loop,routeType:"loop"});assert.ok(routes.length>=2);assert.ok(routes[0].distanceErrorPercent<.01);assert.ok(routes[0].loopCount%1>0);assert.equal(routes[0].withinTolerance,true);});

test("place-only fallback never fabricates geometry",()=>{const route=unavailableRoute({latitude:1,longitude:2},804.672);assert.equal(route.routeSource,"place_only");assert.deepEqual(route.polyline,[]);assert.match(route.warnings[0],/reliable route could not be generated/);});
