"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const {createMemorySystem,safePayload}=require("../src/business-os/memory/system");
const {createContextEngine}=require("../src/business-os/memory/context-engine");
const {deriveDiagnostics}=require("../src/business-os/memory/diagnostics");
const {phase3Readiness,REQUIREMENTS}=require("../src/business-os/memory/phase3-readiness");

const actor=(id="reader",permissionTags=["TEAM"],organizationId="org")=>( {id,permissionTags,organizationId} );
const base=(overrides={})=>({id:"m1",memoryType:"EPISODIC",organizationId:"org",scope:"general",subjectRefs:["subject:1"],workRefs:["work:1"],sourceRefs:["source:1"],evidenceRefs:["evidence:1"],provenanceRefs:["provenance:1"],createdAt:"2026-09-22T00:00:00.000Z",observedAt:"2026-09-22T00:00:00.000Z",retentionClass:"STANDARD",permissionTags:["TEAM"],sensitivityTags:["INTERNAL"],content:{observation:"event"},...overrides});
function fixture(){let current=new Date("2026-09-22T00:00:30.000Z");return {system:createMemorySystem({clock:()=>current,id:(()=>{let n=0;return()=>`id-${++n}`})(),freshnessPolicies:{VOLATILE:60_000,STANDARD:86_400_000,STABLE:null}}),setTime:value=>{current=new Date(value)}}}

test("episodic memory round trip preserves evidence, provenance and identity",()=>{const {system}=fixture();assert.equal(system.writeMemory(base()).ok,true);assert.deepEqual(system.retrieve({actor:actor(),subjectRefs:["subject:1"]}).records[0],system.getMemory("m1"));system.writeMemory(base({id:"m2",subjectRefs:["subject:1-duplicate"]}));assert.equal(system.listMemories().length,2)});
test("working memory is task isolated, bounded and expires without promotion",()=>{const {system,setTime}=fixture();system.writeMemory(base({id:"w",memoryType:"WORKING",sourceRefs:[],evidenceRefs:[],provenanceRefs:[],taskRef:"task:1",maxSize:100,expiryAt:"2026-09-22T00:01:00.000Z"}));assert.throws(()=>system.writeMemory(base({id:"large",memoryType:"WORKING",sourceRefs:[],evidenceRefs:[],provenanceRefs:[],taskRef:"task:1",maxSize:1,expiryAt:"2026-09-22T00:01:00.000Z"})),/size_exceeded/);assert.equal(system.retrieve({actor:actor(),taskRef:"task:2"}).records.length,0);assert.equal(system.retrieve({actor:actor(),taskRef:"task:1"}).records.length,1);setTime("2026-09-22T00:02:00.000Z");assert.equal(system.retrieve({actor:actor(),taskRef:"task:1"}).records.length,0);assert.equal(system.listClaims().length,0)});
test("procedures are immutable versions and do not grant authority",()=>{const {system}=fixture();system.writeMemory(base({id:"p1",memoryType:"PROCEDURAL",content:{procedureId:"qa",version:1,steps:["inspect"]}}));system.writeMemory(base({id:"p2",memoryType:"PROCEDURAL",content:{procedureId:"qa",version:2,steps:["inspect","record"]},supersessionRefs:["p1"]}));assert.equal(system.listMemories().length,2);assert.equal(system.getMemory("p2").authorityGrant,undefined)});
test("decision memory strips hidden reasoning and keeps safe summary",()=>{const {system}=fixture();system.writeMemory(base({id:"d",memoryType:"DECISION",content:{decision:"wait",alternatives:["act"],chainOfThought:"secret",nested:{scratchpad:"secret",assumption:"traffic"}}}));assert.deepEqual(system.getMemory("d").content,{decision:"wait",alternatives:["act"],nested:{assumption:"traffic"}});assert.deepEqual(safePayload({hiddenReasoning:"x",safe:"y"}),{safe:"y"})});
test("durable observation requires provenance and never automatically becomes knowledge",()=>{const {system}=fixture();const result=system.writeMemory(base({provenanceRefs:[],evidenceRefs:[],sourceRefs:[]}));assert.equal(result.code,"MISSING_PROVENANCE");assert.equal(result.diagnostics.firstFailure.checkId,"PROVENANCE_VALIDATION");assert.equal(system.listClaims().length,0)});
test("knowledge follows candidate evidence validation pipeline and cannot self-promote",()=>{const {system}=fixture();const claim=system.proposeClaim({organizationId:"org",subjectRef:"s",scope:"general",proposition:{key:"value"},claimType:"FACT",permissionTags:["TEAM"],sensitivityTags:[]});assert.equal(claim.status,"CANDIDATE");assert.throws(()=>system.promoteClaim(claim.id,{status:"VALIDATED",validationRuleRef:"rule",actorAuthorityRef:"grant"}),/evidence_required/);assert.throws(()=>system.proposeClaim({...claim,id:"bad",status:"VALIDATED"}),/claim_must_begin_candidate/);const evidenced=system.proposeClaim({...claim,id:"c2",supportingEvidenceRefs:["e1"]});assert.equal(system.promoteClaim(evidenced.id,{status:"VALIDATED",validationRuleRef:"rule:1",actorAuthorityRef:"grant:1"}).status,"VALIDATED")});
test("contradictions and superseded claims remain reconstructable",()=>{const {system}=fixture();system.writeMemory(base({id:"monday",content:{website:"broken"}}));system.writeMemory(base({id:"tuesday",content:{website:"working"}}));system.addRelation({fromRef:"tuesday",toRef:"monday",relation:"CONTRADICTS"});const old=system.proposeClaim({id:"old",organizationId:"org",subjectRef:"site",scope:"general",proposition:{state:"broken"},claimType:"STATE",permissionTags:["TEAM"],sensitivityTags:[]});system.supersedeClaim(old.id,{id:"new",organizationId:"org",subjectRef:"site",scope:"general",proposition:{state:"working"},claimType:"STATE",permissionTags:["TEAM"],sensitivityTags:[]});assert.equal(system.listMemories().length,2);assert.equal(system.getClaim("old").status,"SUPERSEDED");assert.equal(system.getRelations().length,2)});
test("volatile and stable freshness differ; fresh-only retrieval excludes stale",()=>{const {system,setTime}=fixture();system.writeMemory(base({id:"volatile",freshnessClass:"VOLATILE"}));system.writeMemory(base({id:"stable",freshnessClass:"STABLE"}));setTime("2026-09-23T00:00:00.000Z");assert.deepEqual(system.retrieve({actor:actor(),requireFresh:true}).records.map(x=>x.id),["stable"])});
test("archive and privacy tombstone are explicit without payload retention",()=>{const {system}=fixture();system.writeMemory(base());assert.equal(system.setMemoryStatus("m1","ARCHIVED").status,"ARCHIVED");assert.equal(system.retrieve({actor:actor()}).records.length,0);assert.equal(system.retrieve({actor:actor(),includeHistorical:true}).records.length,1);const tomb=system.tombstone("m1");assert.equal(tomb.status,"TOMBSTONED");assert.equal(tomb.content,null);assert.ok(tomb.contentHash)});
test("permission filters sensitive payload before retrieval and reports safe redaction",()=>{const {system}=fixture();system.writeMemory(base({permissionTags:["SECRET"],content:{secret:"do not expose"}}));const result=system.retrieve({actor:actor("outsider",["TEAM"])});assert.equal(result.records.length,0);assert.deepEqual(result.redactions,[{recordId:"m1",reason:"PERMISSION_DENIED",payloadExposed:false}]);assert.doesNotMatch(JSON.stringify(result),/do not expose/)});
test("retrieval deterministically filters by subject, work, type and tags",()=>{const {system}=fixture();system.writeMemory(base({tags:["urgent"]}));system.writeMemory(base({id:"other",subjectRefs:["subject:2"],workRefs:["work:2"]}));assert.deepEqual(system.retrieve({actor:actor(),subjectRefs:["subject:1"],workRefs:["work:1"],memoryTypes:["EPISODIC"],tags:["urgent"]}).records.map(x=>x.id),["m1"])});
test("derived index rebuilds canonical records and cannot mutate truth",()=>{const {system}=fixture();system.writeMemory(base());const rebuilt=system.rebuildIndex();assert.ok(rebuilt.length);const indexed=system.indexLookup("subject:1");indexed[0].content.observation="tampered";assert.equal(system.getMemory("m1").content.observation,"event")});
test("context ranking and budget truncation are deterministic and attributable",()=>{const {system}=fixture();system.writeMemory(base({id:"z",priority:0}));system.writeMemory(base({id:"a",priority:0}));system.writeMemory(base({id:"high",priority:5}));const engine=createContextEngine({memorySystem:system,id:()=>"pkg"});const result=engine.build({id:"ctx",requestingActorId:"reader",actor:actor(),purpose:"decide",scope:"general",subjectRefs:["subject:1"],workRefs:["work:1"],budget:2,correlationId:"corr"});assert.equal(result.ok,true);assert.deepEqual(result.package.items.map(x=>x.record.id),["high","a"]);assert.deepEqual(result.package.omissions,[{recordId:"z",reason:"CONTEXT_BUDGET",payloadExposed:false}]);assert.ok(result.package.items.every(x=>x.selection.reasons.length&&Array.isArray(x.selection.provenanceRefs)))});
test("context reports contradictions and never includes denied memory",()=>{const {system}=fixture();system.writeMemory(base({id:"visible"}));system.writeMemory(base({id:"secret",permissionTags:["SECRET"],content:{secret:"classified"}}));system.addRelation({fromRef:"visible",toRef:"secret",relation:"CONTRADICTS"});const result=createContextEngine({memorySystem:system}).build({id:"ctx",requestingActorId:"reader",actor:actor(),purpose:"review",scope:"general",budget:10,correlationId:"corr"});assert.deepEqual(result.package.items.map(x=>x.record.id),["visible"]);assert.equal(result.package.redactions[0].payloadExposed,false);assert.doesNotMatch(JSON.stringify(result.package),/classified/)});
test("stale-only and denied fresh requests produce truthful FIRST FAILURE",()=>{const {system,setTime}=fixture();system.writeMemory(base({freshnessClass:"VOLATILE"}));setTime("2026-09-23T00:00:00.000Z");const engine=createContextEngine({memorySystem:system});const stale=engine.build({id:"ctx",requestingActorId:"reader",actor:actor(),purpose:"review",scope:"general",budget:1,requireFresh:true,correlationId:"corr"});assert.equal(stale.diagnostics.firstFailure.checkId,"FRESHNESS_FILTER");assert.equal(stale.code,"STALE_ONLY_CONTEXT");const denied=engine.build({id:"ctx2",requestingActorId:"x",actor:actor("x",["NONE"]),purpose:"review",scope:"general",budget:1,requireFresh:true,correlationId:"corr"});assert.equal(denied.code,"DENIED_RETRIEVAL");assert.equal(denied.diagnostics.firstFailure.checkId,"PERMISSION_FILTER")});
test("ContextPackage integrates with canonical CognitiveRequest using safe references",()=>{const {system}=fixture();system.writeMemory(base());const engine=createContextEngine({memorySystem:system,id:()=>"pkg"});const built=engine.build({id:"ctx",requestingActorId:"reader",actor:actor(),purpose:"analyze",scope:"general",budget:1,correlationId:"corr"});const handoff=engine.toCognitiveRequest(built.package,{id:"cog",purpose:"analyze",taskType:"EVIDENCE_GROUNDED_ANALYSIS",promptTemplateVersionId:"prompt/1",cognitiveConfigVersionId:"config/1",requiredOutputSchema:{type:"object"},requiredCapabilities:["analysis"],constitutionalAuthorityRef:"grant",policyVersionRef:"policy"});assert.equal(handoff.ok,true);assert.equal(handoff.request.kind,"CognitiveRequest");assert.deepEqual(handoff.request.inputRefs,["pkg","m1"])});
test("CognitiveResult candidates cannot self-promote memory or knowledge",()=>{const {system}=fixture();const result=system.acceptCognitiveProposal({authoritative:false,content:{candidateMemory:{x:1},candidateKnowledgeClaim:{y:2}}});assert.equal(result.accepted,false);assert.equal(system.listMemories().length,0);assert.equal(system.listClaims().length,0);assert.throws(()=>system.acceptCognitiveProposal({authoritative:true}),/forbidden/)});
test("FIRST FAILURE blocks downstream stages rather than falsely failing them",()=>{const result=deriveDiagnostics({MEMORY_WRITE:{status:"PASS"},PROVENANCE_VALIDATION:{status:"PASS"},PERMISSION_CLASSIFICATION:{status:"FAIL",reason:"DENIED"},INDEX_UPDATE:{status:"FAIL",reason:"should_not_surface"}},"now");assert.equal(result.firstFailure.checkId,"PERMISSION_CLASSIFICATION");assert.equal(result.checks.find(x=>x.id==="INDEX_UPDATE").status,"BLOCKED")});
test("context construction failure is classified at retrieval request",()=>{const {system}=fixture();const result=createContextEngine({memorySystem:system}).build({});assert.equal(result.diagnostics.firstFailure.checkId,"RETRIEVAL_REQUEST")});
test("Phase 3 readiness keeps human acceptance pending after all machine checks pass",()=>{const automated=Object.fromEntries(REQUIREMENTS.map(x=>[x,"PASS"]));const result=phase3Readiness({automated});assert.equal(result.gate,"CONDITIONAL_GO");assert.equal(result.humanAcceptance.status,"PENDING");assert.ok(result.exclusions.includes("PHASE_4"))});

test("organization boundary blocks cross-tenant memory and knowledge before permission evaluation",()=>{const {system}=fixture();system.writeMemory(base({id:"other-org-memory",organizationId:"org-b",permissionTags:["PUBLIC"],content:{secret:"tenant-b"}}));system.proposeClaim({id:"other-org-claim",organizationId:"org-b",subjectRef:"s",scope:"general",proposition:{secret:"tenant-b-claim"},claimType:"FACT",permissionTags:["PUBLIC"],sensitivityTags:[]});const reader=actor("reader",["TEAM"],"org");const memories=system.retrieve({actor:reader});const claims=system.retrieveClaims({actor:reader});assert.equal(memories.records.length,0);assert.equal(memories.redactions.length,0);assert.equal(claims.length,0);assert.doesNotMatch(JSON.stringify({memories,claims}),/tenant-b/);});
test("actor without organizational identity cannot retrieve organization-owned memory",()=>{const {system}=fixture();system.writeMemory(base());const result=system.retrieve({actor:{id:"reader",permissionTags:["TEAM"]}});assert.equal(result.records.length,0);assert.equal(result.redactions.length,0);});
