"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const C=require("../src/business-os/cognition/contracts");
const {createModelGateway,selectModel}=require("../src/business-os/cognition/gateway");
const {createFakeAdapter}=require("../src/business-os/cognition/fake-adapter");
const {createCognitiveCore,TASKS}=require("../src/business-os/cognition/core");
const {REQUIREMENTS,phase2Readiness}=require("../src/business-os/cognition/phase2-readiness");

const schema={type:"object",required:["answer"],properties:{answer:{type:"string"},metacognitiveState:{type:"string",enum:C.METACOGNITIVE_STATES},structuredIntentCandidate:{type:"object"}},additionalProperties:false};
const profile=(overrides={})=>C.ModelProfile({id:"fake-primary",provider:"fake",model:"deterministic",version:"1",enabled:true,capabilities:["JSON"],structuredOutput:true,contextLimit:1000,outputLimit:200,taskTiers:["LOW"],riskTier:"LOW",priority:1,pricing:{source:"fixture",version:"1",currency:"USD",inputPerToken:.001,outputPerToken:.002},...overrides});
let sequence=0;
const request=(overrides={})=>({id:`request-${++sequence}`,requestingActorId:"actor",purpose:"certification",taskType:"CLASSIFICATION",promptTemplateVersionId:"prompt@1",cognitiveConfigVersionId:"config@1",inputRefs:["sha256:input"],evidenceRefs:["evidence-1"],requiredOutputSchema:schema,requiredCapabilities:["JSON"],requiredStructuredOutput:true,contextTokens:10,outputTokens:10,taskTier:"LOW",budgetCeiling:1,latencyCeilingMs:100,correlationId:"correlation",causationId:"cause",constitutionalAuthorityRef:"grant-ai",policyVersionRef:"ai-policy@1",...overrides});
const gateway=(options={})=>createModelGateway({profiles:[profile()],adapters:{fake:createFakeAdapter(options.fake)},authorize:async()=>({allowed:true}),clock:()=>new Date("2026-09-22T21:00:00Z"),id:(()=>{let n=0;return()=>`id-${++n}`})(),...options});

test("Phase 2 contracts are versioned, frozen, and CognitiveResult is non-authoritative",()=>{const result=C.assertContract(C.CognitiveResult({id:"r",requestId:"q",invocationIds:["i"],resultType:"x",content:{},metacognitiveState:"INSUFFICIENT_EVIDENCE",evidenceRefs:[],limitations:[],createdAt:"t",authoritative:false}));assert.equal(result.contractVersion,C.CONTRACT_VERSION);assert.ok(Object.isFrozen(result));assert.throws(()=>C.assertContract(C.CognitiveResult({...result,authoritative:true})),/authoritative/)});
test("Phase 2 readiness keeps independent human acceptance pending",()=>{const automated=Object.fromEntries(REQUIREMENTS.map(id=>[id,"PASS"]));const readiness=phase2Readiness({automated});assert.equal(readiness.gate,"CONDITIONAL_GO");assert.equal(readiness.humanAcceptance.status,"PENDING");assert.ok(readiness.exclusions.includes("MEMORY_ENGINE"))});
test("deterministic selection filters capability, limits, tier, budget, latency, enabled and health",()=>{const selected=selectModel(request(),[profile({id:"disabled",enabled:false}),profile({id:"slow",expectedLatencyMs:999}),profile()],{},"selection@1");assert.equal(selected.selectedProfileId,"fake-primary");assert.equal(selected.policyVersion,"selection@1")});
test("structured success records lineage, usage, versioned cost, audit, and inference evidence",async()=>{const audits=[],evidence=[];const g=gateway({fake:{script:[{response:{content:JSON.stringify({answer:"yes",metacognitiveState:"SUFFICIENT_EVIDENCE"}),usage:{inputTokens:10,outputTokens:5},finishReason:"stop"}}]},audit:x=>audits.push(x),recordEvidence:x=>(evidence.push(x),"inference-1")});const out=await g.invoke(request());assert.equal(out.ok,true);assert.equal(out.result.authoritative,false);assert.equal(out.result.systemConfidence,null);assert.deepEqual(out.result.evidenceRefs,["evidence-1","inference-1"]);assert.equal(out.invocations[0].cost.amount,.02);assert.equal(out.invocations[0].schemaValidation,"PASS");assert.equal(audits[0].outcome,"SUCCEEDED");assert.equal(evidence[0].type,"INFERENCE");assert.equal(out.diagnostics.firstFailure,null)});
test("authority and policy denial happen before adapters",async()=>{const adapter=createFakeAdapter();for(const permission of [{allowed:false,code:"MISSING_AUTHORITY"},{allowed:false,code:"POLICY_DENY"}]){const g=createModelGateway({profiles:[profile()],adapters:{fake:adapter},authorize:async()=>permission});const out=await g.invoke(request());assert.equal(out.ok,false);assert.equal(out.diagnostics.firstFailure.checkId,"INVOCATION_AUTHORITY")}assert.equal(adapter.callCount,0)});
test("disabled or unavailable models fail truthful selection",async()=>{for(const options of [{profiles:[profile({enabled:false})]},{profiles:[profile()],health:{"fake-primary":"UNAVAILABLE"}}]){const out=await createModelGateway({...options,adapters:{fake:createFakeAdapter()},authorize:async()=>({allowed:true})}).invoke(request());assert.equal(out.error.code,"NO_ELIGIBLE_MODEL");assert.equal(out.diagnostics.firstFailure.checkId,"MODEL_SELECTION")}});
test("unsupported provider and budget ceiling fail at their truthful boundary",async()=>{let out=await createModelGateway({profiles:[profile({provider:"missing"})],adapters:{},authorize:async()=>({allowed:true})}).invoke(request());assert.equal(out.diagnostics.firstFailure.checkId,"PROVIDER_ADAPTER");out=await createModelGateway({profiles:[profile({maxEstimatedCost:2})],adapters:{fake:createFakeAdapter()},authorize:async()=>({allowed:true})}).invoke(request({budgetCeiling:1}));assert.equal(out.error.code,"BUDGET_EXCEEDED");assert.equal(out.diagnostics.firstFailure.checkId,"MODEL_SELECTION")});
test("timeout retries are bounded and exhaustion is not fabricated success",async()=>{const adapter={provider:"fake",calls:0,invoke(){this.calls++;return new Promise(()=>{})}};const out=await createModelGateway({profiles:[profile()],adapters:{fake:adapter},authorize:async()=>({allowed:true}),maxAttempts:2,timeoutMs:2}).invoke(request({latencyCeilingMs:2}));assert.equal(out.ok,false);assert.equal(out.error.code,"TIMEOUT");assert.equal(out.invocations.length,2);assert.equal(adapter.calls,2)});
test("retryable failure succeeds on retry while non-retryable failure does not retry",async()=>{let out=await gateway({fake:{script:[{error:{code:"RATE_LIMIT",message:"later",retryable:true}},{response:{content:'{"answer":"ok"}'}}]}}).invoke(request());assert.equal(out.ok,true);assert.equal(out.invocations.length,2);const adapter=createFakeAdapter({script:[{error:{code:"AUTHENTICATION",message:"no",retryable:false}}]});out=await createModelGateway({profiles:[profile()],adapters:{fake:adapter},authorize:async()=>({allowed:true}),maxAttempts:3}).invoke(request());assert.equal(out.ok,false);assert.equal(adapter.callCount,1)});
test("explicit fallback is visible in invocation lineage",async()=>{const primary=profile(),backup=profile({id:"fake-backup",provider:"backup",model:"backup",priority:2});const out=await createModelGateway({profiles:[primary,backup],adapters:{fake:createFakeAdapter({script:[{error:{code:"PROVIDER_UNAVAILABLE",retryable:true}}]}),backup:createFakeAdapter({script:[{response:{content:'{"answer":"fallback"}'}}]})},authorize:async()=>({allowed:true}),maxAttempts:1}).invoke(request());assert.equal(out.ok,true);assert.equal(out.invocations[1].substitutionOf,"fake-primary");assert.equal(out.selection.selectedProfileId,"fake-primary")});
test("malformed and schema-invalid responses are never accepted",async()=>{let out=await gateway({fake:{script:[{response:{content:"not json"}}]}}).invoke(request());assert.equal(out.error.code,"MALFORMED_RESPONSE");assert.equal(out.diagnostics.firstFailure.checkId,"RESPONSE_PARSE");out=await gateway({fake:{script:[{response:{content:'{"wrong":true}'}}]}}).invoke(request());assert.equal(out.error.code,"SCHEMA_INVALID");assert.equal(out.diagnostics.firstFailure.checkId,"SCHEMA_VALIDATION")});
test("unknown usage remains unknown and no cost is invented",async()=>{const out=await gateway({fake:{script:[{response:{content:'{"answer":"ok"}'}}]}}).invoke(request());assert.equal(out.invocations[0].usage,null);assert.equal(out.invocations[0].cost,null)});
test("metacognitive stops and StructuredIntent candidates remain inert data",async()=>{const custom={...schema,properties:{...schema.properties,structuredIntentCandidate:{type:"object"}}};const out=await gateway({fake:{script:[{response:{content:JSON.stringify({answer:"stop",metacognitiveState:"CONFLICTING_EVIDENCE",structuredIntentCandidate:{actionType:"synthetic.echo"}})}}]}}).invoke(request({requiredOutputSchema:custom}));assert.equal(out.result.metacognitiveState,"CONFLICTING_EVIDENCE");assert.deepEqual(out.result.structuredIntentCandidate,{actionType:"synthetic.echo"});assert.equal(out.result.authoritative,false)});
test("all minimum cognitive operations route through the one gateway",async()=>{const calls=[];const core=createCognitiveCore({gateway:{invoke:value=>(calls.push(value),value)}});core.extract({});core.classify({});core.analyze({});core.recommend({});core.draftPlan({});core.assessUncertainty({});assert.deepEqual(calls.map(x=>x.taskType),TASKS)});
test("diagnostic and audit material does not contain prompt text or secrets",async()=>{const secret="sk-secret-raw-prompt";const audits=[];const out=await gateway({audit:x=>audits.push(x)}).invoke(request({inputRefs:[`sha256:${secret.length}`]}));assert.equal(JSON.stringify({out,audits}).includes(secret),false)});

test("model kill switch blocks before selection and provider invocation",async()=>{const adapter=createFakeAdapter();const out=await createModelGateway({profiles:[profile()],adapters:{fake:adapter},authorize:async()=>({allowed:true}),isKillSwitchActive:async()=>true}).invoke(request());assert.equal(out.ok,false);assert.equal(out.error.code,"KILL_SWITCH_ACTIVE");assert.equal(out.diagnostics.firstFailure.checkId,"INVOCATION_AUTHORITY");assert.equal(out.diagnostics.checks.find(x=>x.id==="MODEL_SELECTION").status,"BLOCKED");assert.equal(adapter.callCount,0)});
test("null object output is rejected as schema invalid instead of throwing",async()=>{const nullSchema={type:"object",required:["payload"],properties:{payload:{type:"object",required:["value"],properties:{value:{type:"string"}}}},additionalProperties:false};const out=await gateway({fake:{script:[{response:{content:'{"payload":null}'}}]}}).invoke(request({requiredOutputSchema:nullSchema}));assert.equal(out.ok,false);assert.equal(out.error.code,"SCHEMA_INVALID");assert.equal(out.diagnostics.firstFailure.checkId,"SCHEMA_VALIDATION")});
