"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const E=require("../src/business-os/economics"),W=require("../src/business-os/organization/economic-workflow"),O=require("../src/business-os/organization/contracts"),X=require("../src/business-os/experiment-manager/contracts");
const {proposalDigest}=require("../src/business-os/experiment-manager/approval");
const EXPECTED_AT="2025-02-02T12:00:00.000Z";
const ORG="org:eco5d",WORK="work:eco5d",period={start:"2025-01-01T00:00:00.000Z",end:"2025-02-01T00:00:00.000Z"},ASOF="2025-02-03T00:00:00.000Z";
function economicInput(prefix,category,amountMinor){return E.EconomicInput({id:`${prefix}:input:${category}`,organizationId:ORG,productRef:"product",campaignRef:"campaign",currency:"USD",reportingPeriod:period,version:1,category,classification:"ACTUAL",amountMinor,assumptions:[],evidenceRefs:[`${prefix}:evidence:${category}`],source:{system:"FIXTURE",recordRef:`${prefix}:record:${category}`,recordVersion:1,payloadHash:`${prefix}:hash:${category}`,observedAt:"2025-01-31T00:00:00.000Z"}})}
function evidence(prefix,category,amountMinor,patch={}){return E.EconomicEvidenceRecord({id:`${prefix}:evidence:${category}`,evidenceType:"OBSERVED_FACT",source:{type:"ACCOUNTING_SYSTEM",system:"FIXTURE",recordRef:`${prefix}:record:${category}`,availability:"AVAILABLE"},actorId:"books",recordedAt:"2025-02-02T00:00:00.000Z",observedAt:"2025-01-31T00:00:00.000Z",version:1,scope:{organizationId:ORG,productRef:"product",campaignRef:"campaign",currency:"USD",reportingPeriod:period},claim:{category,classification:"ACTUAL",amountMinor},payloadHash:`${prefix}:hash:${category}`,supersededBy:null,...patch})}
function assessment(prefix,revenue,cost,{unknownCost=false,newCustomers=2,reverse=false}={}){const categories=[["REVENUE",revenue],["REFUND",0],["DISCOUNT",0],["ACQUISITION_COST",cost],["FULFILLMENT_COST",unknownCost?null:0]], inputs=categories.map(([c,v])=>v===null?E.EconomicInput({...economicInput(prefix,c,0),classification:"UNKNOWN",amountMinor:null,evidenceRefs:[]}):economicInput(prefix,c,v)),records=categories.filter(([,v])=>v!==null).map(([c,v])=>evidence(prefix,c,v));const assessmentAt=prefix.startsWith("forecast")?EXPECTED_AT:ASOF;return E.calculateEvidenceBackedAssessment({id:`${prefix}:assessment`,workId:WORK,financialInputs:reverse?[...inputs].reverse():inputs,coverage:{requiredCostCategories:["ACQUISITION_COST","FULFILLMENT_COST"],newCustomers}},{clock:()=>assessmentAt,asOf:assessmentAt,evidenceRecords:reverse?[...records].reverse():records,freshnessPolicies:categories.map(([c])=>({id:`history:${c}`,category:c,sourceType:"ACCOUNTING_SYSTEM",mode:"HISTORICAL"}))});}
function fixture({baseline=assessment("forecast",100000,20000),actual=assessment("actual",80000,25000),resultClass="SUPPORTED"}={}){
 const proposalArtifact=W.sealArtifact({id:"proposal:1",artifactType:"ExperimentProposal",organizationId:ORG,workId:WORK,version:1,producingRoleId:"EXPERIMENT_MANAGER",status:"PROPOSED",createdAt:EXPECTED_AT,managerProposalDigest:proposalDigest({id:"proposal:1",version:1})});
 const baselineArtifact=W.sealArtifact({id:"baseline:1",artifactType:"EconomicAssessment",organizationId:ORG,workId:WORK,version:1,assessmentId:baseline.id,assessmentDigest:E.economicArtifactDigest(baseline),producingRoleId:"ECONOMICS",status:"ACCEPTED",createdAt:EXPECTED_AT});
 const actualArtifact=W.sealArtifact({id:"actual:1",artifactType:"EconomicAssessment",organizationId:ORG,workId:WORK,version:1,assessmentId:actual.id,assessmentDigest:E.economicArtifactDigest(actual),producingRoleId:"ECONOMICS",status:"ACCEPTED",createdAt:ASOF});
 const decision=O.GovernedDecision({id:"decision:1",organizationId:ORG,workId:WORK,decisionType:"AUTHORIZE_EXPERIMENT",result:"APPROVE",economicAssessmentRef:W.reference(baselineArtifact),experimentProposalRef:W.reference(proposalArtifact),chainRefs:[W.reference(proposalArtifact),W.reference(baselineArtifact)],decidedAt:EXPECTED_AT,decisionMakerRef:"human:owner",authorityRef:"grant:owner",authorityType:"HUMAN",authorizationScope:"EXPERIMENT_EXECUTION",conditions:[],reason:"approved",version:1});
 const approval=X.ExperimentApproval({id:"approval:1",organizationId:ORG,proposalRef:"proposal:1",proposalVersion:1,proposalDigest:proposalArtifact.managerProposalDigest,actorType:"HUMAN",actorId:"owner",authorityRef:"grant:owner",scope:"EXPERIMENT_RUN_INTERNAL",budgetCeiling:500,decisionRef:decision.id,evidenceRefs:["approval:evidence"],status:"APPROVED",approvedAt:ASOF});
 const run=X.ExperimentRun({id:"run:1",organizationId:ORG,proposalRef:"proposal:1",proposalVersion:1,approvalRef:approval.id,budget:500,boundary:"INTERNAL",status:"COMPLETED",idempotencyKey:"run",startedAt:ASOF,history:[]});
 const experimentResult=X.ExperimentResult({id:"result:1",organizationId:ORG,workId:WORK,proposalRef:"proposal:1",proposalVersion:1,runRef:run.id,resultClass,measurements:[],evidenceRefs:["result:evidence"],limitations:[],status:"PROPOSED",createdAt:ASOF});
 return{organizationId:ORG,workId:WORK,proposalArtifact,baselineArtifact,baselineAssessment:baseline,decision,approval,run,experimentResult,actualArtifact,actualAssessment:actual,authorizedAmountMinor:50000,reservedAmountMinor:50000,asOf:ASOF};
}
const reconcile=(f=fixture())=>E.createEconomicReconciliation(f,{clock:()=>"2025-02-04T00:00:00.000Z",validateExperimentResult:result=>structuredClone(result)});
const observation=(metric="grossRevenue",f=fixture())=>{const reconciliation=reconcile(f);return E.createEconomicCalibrationObservation({metric,...f,reconciliation,reconciliationRef:{artifactId:reconciliation.id,version:reconciliation.version,digest:E.economicCalibrationDigest(reconciliation)}},{clock:()=>"2025-02-05T00:00:00.000Z"})};
const bindDecision=(reconciliation,decision,patch={})=>({...reconciliation,decisionDigest:E.economicCalibrationDigest(decision),expectationDesignatedAt:decision.decidedAt,...patch});
const cohort=(metric="grossRevenue")=>({organizationId:ORG,metric,currency:"USD",productRef:"product",campaignRef:"campaign",expectationType:"AUTHORIZED_BASELINE",engineVersion:E.ECONOMICS_ENGINE_VERSION,reportingPeriodSemantics:"EXACT_DURATION_MS",reportingPeriodDurationMs:31*86400000,asOf:"2025-02-06T00:00:00.000Z"});

test("authorized historical baseline produces immutable signed, absolute, relative and direction evidence",()=>{const f=fixture(),before=structuredClone(f),o=observation("grossRevenue",f);assert.deepEqual(f,before);assert.deepEqual([o.signedError.value,o.absoluteError.value,o.relativeError.value,o.direction],[20000,20000,2500,"EXPECTED_ABOVE_ACTUAL"]);assert.equal(o.comparisonStatus,"CALCULATED");assert.equal(o.forecast,undefined);assert.equal(o.authorization,undefined);assert.equal(Object.isFrozen(o),true)});
test("negative error and exact match retain one sign convention",()=>{assert.equal(observation("grossRevenue",fixture({baseline:assessment("forecast-low",50000,20000),actual:assessment("actual-high",80000,25000)})).direction,"EXPECTED_BELOW_ACTUAL");assert.equal(observation("grossRevenue",fixture({baseline:assessment("forecast-same",80000,20000),actual:assessment("actual-same",80000,25000)})).direction,"EXACT_MATCH")});
test("zero actual keeps absolute error but relative error is not applicable",()=>{const o=observation("grossRevenue",fixture({baseline:assessment("forecast-zero-actual",10000,0),actual:assessment("actual-zero",0,0)}));assert.equal(o.absoluteError.value,10000);assert.deepEqual(o.relativeError,{status:"NOT_APPLICABLE",value:null,unit:"BASIS_POINTS"})});
test("unknown, partial, invalid, and not-applicable remain distinct and non-comparable",()=>{const base={value:null,unit:"MINOR_CURRENCY",missingInputs:[]};for(const status of ["UNKNOWN","PARTIAL","INVALID","NOT_APPLICABLE"]){const f=fixture(),r=reconcile(f),expected={...base,status,value:status==="PARTIAL"?1:null},actual={...base,status:"CALCULATED",value:2};f.baselineAssessment={...f.baselineAssessment,metrics:{...f.baselineAssessment.metrics,grossRevenue:expected},calculationLineage:f.baselineAssessment.calculationLineage.map(x=>x.metric==="grossRevenue"?{...x,status}:x)};f.baselineArtifact=W.sealArtifact({...f.baselineArtifact,assessmentDigest:E.economicArtifactDigest(f.baselineAssessment),digest:undefined});const comparison={...r.metricComparisons.find(x=>x.metric==="grossRevenue"),expected};f.decision={...f.decision,economicAssessmentRef:W.reference(f.baselineArtifact)};const reconciliation=bindDecision(r,f.decision,{baselineEconomicAssessmentRef:W.reference(f.baselineArtifact),metricComparisons:r.metricComparisons.map(x=>x.metric==="grossRevenue"?comparison:x)});const o=E.createEconomicCalibrationObservation({metric:"grossRevenue",...f,reconciliation,reconciliationRef:{artifactId:reconciliation.id,version:1,digest:E.economicCalibrationDigest(reconciliation)}},{clock:()=>"2025-02-05T00:00:00.000Z"});assert.equal(o.comparisonStatus,status);assert.equal(o.signedError.value,null)}});
test("exact bindings reject scope, currency, period, ids, versions, digests, artifacts and reconciliation mutation",()=>{const mutations=[x=>x.baselineArtifact={...x.baselineArtifact,digest:"bad"},x=>x.actualArtifact={...x.actualArtifact,digest:"bad"},x=>x.actualAssessment={...x.actualAssessment,organizationId:"other"},x=>x.actualAssessment={...x.actualAssessment,workId:"other"},x=>x.actualAssessment={...x.actualAssessment,productRef:"other"},x=>x.actualAssessment={...x.actualAssessment,campaignRef:"other"},x=>x.actualAssessment={...x.actualAssessment,currency:"EUR"},x=>x.actualAssessment={...x.actualAssessment,reportingPeriod:{...period,end:"2025-03-01T00:00:00.000Z"}},x=>x.baselineArtifact={...x.baselineArtifact,id:"other"},x=>x.baselineArtifact={...x.baselineArtifact,version:2},x=>x.actualArtifact={...x.actualArtifact,id:"other"},x=>x.actualArtifact={...x.actualArtifact,version:2}];for(const mutate of mutations){const f=fixture(),r=reconcile(f),input={metric:"grossRevenue",...f,reconciliation:r,reconciliationRef:{artifactId:r.id,version:r.version,digest:E.economicCalibrationDigest(r)}};mutate(input);assert.throws(()=>E.createEconomicCalibrationObservation(input),/invalid_economic/);}const f=fixture(),r=reconcile(f),mutated={...r,status:"INVALID"};assert.throws(()=>E.createEconomicCalibrationObservation({metric:"grossRevenue",...f,reconciliation:mutated,reconciliationRef:{artifactId:r.id,version:r.version,digest:E.economicCalibrationDigest(r)}}),/reconciliation_binding/)});
test("temporal integrity and operative pre-outcome designation prevent hindsight substitution",()=>{for(const decidedAt of ["2025-02-03T00:00:00.000Z","2099-01-01T00:00:00.000Z"]){const f=fixture(),r=reconcile(f);f.decision={...f.decision,decidedAt};const reconciliation=bindDecision(r,f.decision);assert.throws(()=>E.createEconomicCalibrationObservation({metric:"grossRevenue",...f,reconciliation,reconciliationRef:{artifactId:reconciliation.id,version:1,digest:E.economicCalibrationDigest(reconciliation)}}),/expectation_not_before_actual|future_dated/)}const f=fixture(),r=reconcile(f);f.decision={...f.decision,economicAssessmentRef:W.reference(f.actualArtifact)};assert.throws(()=>E.createEconomicCalibrationObservation({metric:"grossRevenue",...f,reconciliation:r,reconciliationRef:{artifactId:r.id,version:1,digest:E.economicCalibrationDigest(r)}}),/operative_expectation/)});
test("profile is order independent, exposes sample sizes, descriptive directions and deterministic statistics",()=>{const a=observation(),b=observation("grossRevenue",fixture({baseline:assessment("forecast-b",50000,20000),actual:assessment("actual-b",80000,25000)})),c=observation("grossRevenue",fixture({baseline:assessment("forecast-c",80000,20000),actual:assessment("actual-c",80000,25000)}));const x=E.createEconomicCalibrationProfile({cohort:cohort(),observations:[a,b,c]},{clock:()=>"2025-02-06T00:00:00.000Z"}),y=E.createEconomicCalibrationProfile({cohort:cohort(),observations:[c,a,b]},{clock:()=>"2025-02-06T00:00:00.000Z"});assert.deepEqual(x,y);assert.deepEqual([x.totalObservationCount,x.comparableObservationCount,x.nonComparableObservationCount,x.percentageErrorObservationCount],[3,3,0,3]);assert.deepEqual(x.directionCounts,{expectedAboveActual:1,expectedBelowActual:1,exactMatch:1});assert.equal(x.statistics.meanSignedError.value,-3333);assert.equal(x.statistics.meanAbsoluteError.value,16667);assert.deepEqual([x.statistics.minimumAbsoluteError.value,x.statistics.maximumAbsoluteError.value],[0,30000]);assert.equal(x.authorization,null);assert.equal(x.probabilityModel,null)});
test("zero and one-observation profiles are truthful and MAPE excludes zero actual",()=>{const empty=E.createEconomicCalibrationProfile({cohort:cohort(),observations:[]},{clock:()=>"2025-02-06T00:00:00.000Z"});assert.equal(empty.totalObservationCount,0);assert.equal(empty.statistics.meanAbsoluteError.status,"NOT_APPLICABLE");const zero=observation("grossRevenue",fixture({baseline:assessment("forecast-z",10000,0),actual:assessment("actual-z",0,0)})),p=E.createEconomicCalibrationProfile({cohort:cohort(),observations:[zero]},{clock:()=>"2025-02-06T00:00:00.000Z"});assert.deepEqual([p.comparableObservationCount,p.percentageErrorObservationCount],[1,0]);assert.equal(p.statistics.meanAbsolutePercentageError.status,"NOT_APPLICABLE")});
test("duplicates, cohort substitutions, engine mismatch, unsupported ratios and arithmetic overflow fail closed",()=>{const o=observation();assert.throws(()=>E.createEconomicCalibrationProfile({cohort:cohort(),observations:[o,o]}),/duplicate_observation/);for(const patch of [{organizationId:"other"},{productRef:"other"},{campaignRef:"other"},{currency:"EUR"},{reportingPeriodDurationMs:1},{engineVersion:"other"}])assert.throws(()=>E.createEconomicCalibrationProfile({cohort:{...cohort(),...patch},observations:[o]}),/cohort_/);assert.throws(()=>observation("roi"),/unsupported_metric/);const metric=v=>({status:"CALCULATED",value:v,unit:"MINOR_CURRENCY",missingInputs:[]});assert.throws(()=>E.compareEconomicMetric("grossRevenue",metric(Number.MIN_SAFE_INTEGER),metric(Number.MAX_SAFE_INTEGER)),/overflow/)});
test("repository prevents duplicate observations and protects stored history",()=>{const repo=new E.EconomicCalibrationObservationRepository(),o=observation();repo.save(o);assert.throws(()=>repo.save(o),/duplicate_observation/);const copy=repo.get(o.id);copy.direction="EXACT_MATCH";assert.equal(repo.get(o.id).direction,"EXPECTED_ABOVE_ACTUAL")});

test("caller cannot override the governed expectation designation time",()=>{const f=fixture(),r=reconcile(f);const normal=E.createEconomicCalibrationObservation({metric:"grossRevenue",...f,reconciliation:r,reconciliationRef:{artifactId:r.id,version:r.version,digest:E.economicCalibrationDigest(r)}});const attempted=E.createEconomicCalibrationObservation({metric:"grossRevenue",...f,expectationDesignatedAt:"1900-01-01T00:00:00.000Z",reconciliation:r,reconciliationRef:{artifactId:r.id,version:r.version,digest:E.economicCalibrationDigest(r)}});assert.equal(attempted.expectationDesignatedAt,f.decision.decidedAt);assert.equal(attempted.id,normal.id);assert.equal(attempted.digest,normal.digest)})

test("mutated governed decision cannot alter historical calibration lineage",()=>{const f=fixture(),r=reconcile(f);const mutated={...f.decision,decidedAt:"2025-02-02T13:00:00.000Z"};assert.throws(()=>E.createEconomicCalibrationObservation({metric:"grossRevenue",...f,decision:mutated,reconciliation:r,reconciliationRef:{artifactId:r.id,version:r.version,digest:E.economicCalibrationDigest(r)}}),/decision_binding/)})
