"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const {createConstitutionalKernel}=require("../src/business-os/kernel/kernel");
const {createRoleConfigurationRegistry,ROLE_IDS}=require("../src/business-os/organization/roles");
const {createOrganizationalCoordinator}=require("../src/business-os/organization/coordinator");
const C=require("../src/business-os/organization/contracts");
const {deriveOrganizationDiagnostics,deriveRoleDiagnostics}=require("../src/business-os/organization/diagnostics");
const {phase6Readiness,REQUIREMENTS}=require("../src/business-os/organization/phase6-readiness");
function fixture(customInvoker){let n=0;const id=()=>`id-${++n}`,kernel=createConstitutionalKernel({id});kernel.registerActor({id:"SYSTEM",type:"SYSTEM",status:"ACTIVE"});kernel.registerActor({id:"actor",type:"AI_AGENT",status:"ACTIVE"});kernel.issueGrant({id:"grant",issuerActorId:"SYSTEM",subjectActorId:"actor",actionScopes:["organization.assign"],resourceScopes:["organization:org"],constraints:{}});const roles=createRoleConfigurationRegistry({organizationId:"org"});roles.registerDefaults();let invocations=0;const runtimeInvoker=customInvoker|| (async({work,assignment,role,input})=>{invocations++;return {runRef:`run:${work.id}`,artifacts:[artifact(work,assignment,role.outputArtifactTypes[0],input)]}});const coordinator=createOrganizationalCoordinator({organizationId:"org",roleRegistry:roles,runtimeInvoker,kernel,id,clock:()=>new Date("2026-01-01T00:00:00Z")});coordinator.objective({id:"objective",organizationId:"org",objective:"synthetic only",successCriteria:["verified"],priority:"HIGH",scope:["synthetic"],budget:{currency:"USD",maxCost:20},riskBoundary:"LOW",authorityRefs:["grant"],evidenceRefs:["human:intent"],status:"ACTIVE"});return {roles,coordinator,kernel,get invocations(){return invocations}}}
function work(c,role,id="work",deps=[]){const mission=c.roles.get(role).missionTypes[0];return c.coordinator.createWork({id,organizationId:"org",objectiveRef:"objective",missionType:mission,eligibleRoleIds:[role],inputArtifactRefs:["source"],dependencyWorkRefs:deps,authorityRefs:["grant"],policyRefs:["policy"],budget:{currency:"USD",maxCost:5},riskBoundary:"LOW",correlationId:"corr",causationId:"objective",idempotencyKey:`create:${id}`})}
function artifact(w,a,type,extra={}){return {id:`artifact:${w.id}`,artifactType:type,organizationId:"org",workId:w.id,missionRunRef:`run:${w.id}`,producingRoleId:a.roleId,producingRoleVersion:a.roleVersion,producingActorRef:a.actorRef,sourceEvidenceRefs:["evidence:synthetic"],provenance:{inputRefs:w.inputArtifactRefs,correlation:"DERIVED_FROM"},status:"PROPOSED",version:1,limitations:["synthetic"],applicableScope:["synthetic"],...extra}}
function assign(c,w,role){return c.coordinator.assign(w.id,{roleId:role,actorRef:"actor",authorityRefs:["grant"]})}
test("all nine roles are complete configurations of one shared runtime seam",()=>{const f=fixture();assert.deepEqual(f.roles.list().map(x=>x.id),ROLE_IDS);for(const role of f.roles.list()){assert.ok(role.missionTypes.length);assert.ok(role.inputArtifactTypes.length);assert.ok(role.outputArtifactTypes.length);assert.ok(role.contextProfile&&role.memoryProfile&&role.knowledgeProfile);assert.ok(role.authorityReferences&&role.policyReferences&&role.reportingRequirements);assert.equal(role.autonomyCeiling,"RECOMMEND")}assert.notEqual(f.roles.get("SALES").contextProfile.sensitivity[0],f.roles.get("PRODUCTION").contextProfile.sensitivity[0])});
test("work routes by eligibility and role compatibility without role-to-role calls",async()=>{const f=fixture(),scout=work(f,"SMART_SCOUT","scout"),analysis=work(f,"SMART_ANALYST","analysis",["scout"]);assert.equal(analysis.state,"CREATED");const a=assign(f,scout,"SMART_SCOUT"),result=await f.coordinator.execute(a.id);assert.equal(result.work.state,"COMPLETED");assert.equal(f.coordinator.getWork("analysis").state,"ELIGIBLE");assert.equal(f.invocations,1);assert.equal(f.coordinator.events().filter(x=>x.type==="WORK_ELIGIBLE").length,2)});
test("duplicate Work creation and execution are idempotently controlled",async()=>{const f=fixture(),w=work(f,"SMART_SCOUT"),same=work(f,"SMART_SCOUT");assert.equal(same.id,w.id);const a=assign(f,w,"SMART_SCOUT"),one=await f.coordinator.execute(a.id),two=await f.coordinator.execute(a.id);assert.equal(one.replayed,false);assert.equal(two.replayed,true);assert.equal(f.invocations,1)});
test("artifacts require attribution and provenance and expose version conflict",async()=>{let mode="missing";const f=fixture(async({work,assignment,role})=>({runRef:"run",artifacts:[artifact(work,assignment,role.outputArtifactTypes[0],mode==="missing"?{sourceEvidenceRefs:[]}:{id:"same",version:mode==="v2"?2:1})]})),w=work(f,"SMART_SCOUT"),a=assign(f,w,"SMART_SCOUT");await assert.rejects(()=>f.coordinator.execute(a.id),/artifact_provenance_required/);const g=fixture(async({work,assignment,role})=>({runRef:"run",artifacts:[artifact(work,assignment,role.outputArtifactTypes[0],{id:"same"})]})),w1=work(g,"SMART_SCOUT","one"),a1=assign(g,w1,"SMART_SCOUT");await g.coordinator.execute(a1.id);const w2=work(g,"SMART_SCOUT","two"),a2=assign(g,w2,"SMART_SCOUT");await assert.rejects(()=>g.coordinator.execute(a2.id),/artifact_version_conflict/)});
test("dissent remains as separate attributable immutable artifacts",async()=>{const f=fixture(),s=work(f,"SMART_SCOUT","s"),sa=assign(f,s,"SMART_SCOUT");await f.coordinator.execute(sa.id);const an=work(f,"SMART_ANALYST","a"),aa=assign(f,an,"SMART_ANALYST");await f.coordinator.execute(aa.id);const arts=f.coordinator.listArtifacts();assert.equal(arts.length,2);assert.notEqual(arts[0].producingRoleId,arts[1].producingRoleId);assert.ok(Object.isFrozen(f.coordinator.data.artifacts.get(arts[0].id)))});
test("closed synthetic organization records discovery through remediation, independent QA, learning, and management",async()=>{const outputs={scout:"OpportunityCandidate",analysis:"AnalystAssessment",experiment:"ExperimentProposal",result:"ExperimentResult",economics:"EconomicAssessment",sales:"SalesProposal",production:"ProductionPlan",output1:"SyntheticOutput",qa1:"QAAssessment",remediation:"SyntheticOutput",qa2:"QAAssessment",learning:"LearningProposal",manager:"ManagementDirective"};const roles={scout:"SMART_SCOUT",analysis:"SMART_ANALYST",experiment:"EXPERIMENT_MANAGER",result:"EXPERIMENT_MANAGER",economics:"ECONOMICS",sales:"SALES",production:"PRODUCTION",output1:"PRODUCTION",qa1:"INDEPENDENT_QA",remediation:"PRODUCTION",qa2:"INDEPENDENT_QA",learning:"LEARNING",manager:"MANAGER"};const f=fixture(async({work,assignment})=>({runRef:`shared-runtime:${work.id}`,artifacts:[Object.assign(artifact(work,assignment,outputs[work.id],work.id==="qa1"?{verdict:"FAIL",acceptanceCriteria:["correct"],evidenceExaminedRefs:["defect"]}:work.id==="qa2"?{verdict:"PASS",acceptanceCriteria:["correct"],evidenceExaminedRefs:["fixed"],provenance:{inputRefs:["remediation"],productionActorRef:"producer"}}:{}),{missionRunRef:`shared-runtime:${work.id}`})]}));const executed=[];for(const name of Object.keys(outputs)){const w=work(f,roles[name],name),a=assign(f,w,roles[name]);await f.coordinator.execute(a.id);executed.push(f.coordinator.getArtifact(`artifact:${name}`))}assert.equal(executed.length,13);assert.equal(executed.find(x=>x.id==="artifact:qa1").verdict,"FAIL");assert.equal(executed.find(x=>x.id==="artifact:qa2").verdict,"PASS");assert.equal(executed.find(x=>x.id==="artifact:learning").status,"PROPOSED");assert.equal(executed.find(x=>x.id==="artifact:manager").status,"PROPOSED");assert.ok(executed.every(x=>x.missionRunRef.startsWith("shared-runtime:")))});
test("adversarial role outputs fail closed",async(t)=>{const cases=[
 ["SMART_SCOUT",{observations:[{classification:"OBSERVED_FACT"}]},/scout_observed/],
 ["EXPERIMENT_MANAGER",{prohibitedAction:true},/experiment_prohibited/],
 ["ECONOMICS",{unknownCostTreatedAsZero:true},/economic_classification/],
 ["ECONOMICS",{projectedRevenueRecordedAsActual:true},/economic_classification/],
 ["SALES",{unsupportedCapability:true},/sales_truth/],["SALES",{unsupportedGuarantee:true},/sales_truth/],["SALES",{realCustomerContact:true},/sales_truth/],
 ["PRODUCTION",{selfQaVerdict:"PASS"},/production_boundary/],["PRODUCTION",{obligationOutsideCapability:true,escalated:false},/production_boundary/],
 ["INDEPENDENT_QA",{verdict:"PASS",acceptanceCriteria:[],evidenceExaminedRefs:[]},/qa_independence/],
 ["LEARNING",{appliedChange:true},/learning_cannot/],["LEARNING",{promotedKnowledge:true},/learning_cannot/],
 ["MANAGER",{overrideQa:true},/manager_override/],["MANAGER",{grantedAuthority:true},/manager_override/]
 ];for(let i=0;i<cases.length;i++){const [role,bad,re]=cases[i];await t.test(`${role}-${i}`,async()=>{const f=fixture(async({work,assignment,role:r})=>({runRef:"run",artifacts:[artifact(work,assignment,r.outputArtifactTypes[0],bad)]})),w=work(f,role),a=assign(f,w,role);await assert.rejects(()=>f.coordinator.execute(a.id),re)})}});
test("independent QA cannot share producer identity and cannot PASS without evidence",()=>{const f=fixture(),p=work(f,"PRODUCTION"),a=assign(f,p,"PRODUCTION");f.coordinator.data.artifacts.set("output",C.WorkArtifact(artifact(p,a,"SyntheticOutput",{id:"output",createdAt:"now",correlationId:"corr",causationId:"p"})));assert.throws(()=>f.coordinator.review({artifactRef:"output",reviewerRoleId:"INDEPENDENT_QA",reviewerActorRef:"actor",verdict:"PASS",evidenceRefs:["e"]}),/qa_independence/);assert.throws(()=>f.coordinator.review({artifactRef:"output",reviewerRoleId:"INDEPENDENT_QA",reviewerActorRef:"qa-actor",verdict:"PASS",evidenceRefs:[]}),/qa_pass_requires/)});
test("organization isolation and authority boundaries fail closed",()=>{const f=fixture();assert.throws(()=>f.coordinator.createWork({organizationId:"other"}),/cross_organization/);const w=work(f,"SALES");assert.throws(()=>f.coordinator.assign(w.id,{roleId:"PRODUCTION",actorRef:"actor",authorityRefs:["grant"]}),/role_not_eligible/);assert.throws(()=>f.coordinator.assign(w.id,{roleId:"SALES",actorRef:"actor",authorityRefs:[]}),/role_authority_missing/);assert.equal(f.coordinator.getWork(w.id.replace("work","other")),null)});
test("organizational and role FIRST FAILURE block only causal downstream checks",()=>{const d=deriveOrganizationDiagnostics({OBJECTIVE:{status:"PASS"},WORK_CREATED:{status:"PASS"},WORK_ELIGIBLE:{status:"FAIL",reason:"dependency"},QA:{status:"PASS"}},"now");assert.equal(d.firstFailure.checkId,"WORK_ELIGIBLE");assert.equal(d.checks.find(x=>x.id==="QA").status,"BLOCKED");const r=deriveRoleDiagnostics("INDEPENDENT_QA",{ARTIFACT:{status:"PASS"},ACCEPTANCE_CRITERIA:{status:"FAIL",reason:"missing"}},"now");assert.equal(r.firstFailure.checkId,"ACCEPTANCE_CRITERIA");assert.equal(r.checks.at(-1).status,"BLOCKED")});
test("economic and experiment contracts preserve unknowns and failure class",()=>{const e=C.EconomicAssessment({id:"e",organizationId:"org",workId:"w",knownCost:1,estimatedCost:2,unknownCosts:["capacity"],expectedValue:10,actualValue:{classification:"UNKNOWN"},grossContribution:{classification:"UNKNOWN"},capacityCost:{classification:"UNKNOWN"},riskExposure:"UNKNOWN",breakEvenAssumptions:["estimate"],sensitivity:[],disposition:"NEEDS_MORE_EVIDENCE",evidenceRefs:["source"],limitations:["synthetic"],createdAt:"now"});assert.deepEqual(e.unknownCosts,["capacity"]);const x=C.ExperimentResult({id:"x",organizationId:"org",workId:"w",proposalRef:"p",resultClass:"TECHNICAL_FAILURE",evidenceRefs:["log"],limitations:[],status:"PROPOSED",createdAt:"now"});assert.notEqual(x.resultClass,"MARKET_FAILURE")});
test("Phase 6 readiness is conditional and Phase 7 stays prohibited pending human acceptance",()=>{const automated=Object.fromEntries(REQUIREMENTS.map(x=>[x,"PASS"])),r=phase6Readiness({automated});assert.equal(r.gate,"CONDITIONAL_GO");assert.equal(r.humanAcceptance.status,"PENDING");assert.equal(r.phase7Allowed,false)});

test("invalid runtime output cannot leave organizational Work stuck RUNNING",async()=>{const f=fixture(async({work,assignment,role})=>({runRef:"run",artifacts:[artifact(work,assignment,role.outputArtifactTypes[0],{sourceEvidenceRefs:[]})]})),w=work(f,"SMART_SCOUT"),a=assign(f,w,"SMART_SCOUT");await assert.rejects(()=>f.coordinator.execute(a.id),/artifact_provenance_required/);assert.equal(f.coordinator.getWork(w.id).state,"FAILED");assert.equal(f.coordinator.events().at(-1).type,"WORK_FAILED")});
test("prohibited direct role invocation fails the authoritative Work state",async()=>{const f=fixture(async()=>({directRoleInvocation:true,artifacts:[]})),w=work(f,"SMART_SCOUT"),a=assign(f,w,"SMART_SCOUT");await assert.rejects(()=>f.coordinator.execute(a.id),/direct_role_invocation_prohibited/);assert.equal(f.coordinator.getWork(w.id).state,"FAILED")});
test("concurrent execution calls share one reservation and cannot duplicate effects",async()=>{let release;const gate=new Promise(resolve=>{release=resolve});const f=fixture(async({work,assignment,role})=>{await gate;return {runRef:"run",artifacts:[artifact(work,assignment,role.outputArtifactTypes[0])]}}),w=work(f,"SMART_SCOUT"),a=assign(f,w,"SMART_SCOUT");const one=f.coordinator.execute(a.id),two=f.coordinator.execute(a.id);release();const [x,y]=await Promise.all([one,two]);assert.equal(f.invocations,0);assert.equal(x.replayed,false);assert.equal(y.replayed,true);assert.equal(f.coordinator.listArtifacts().length,1)});
test("multi-artifact results are fully validated before publication",async()=>{const f=fixture(async({work,assignment,role})=>({runRef:"run",artifacts:[artifact(work,assignment,role.outputArtifactTypes[0],{id:"valid"}),artifact(work,assignment,role.outputArtifactTypes[0],{id:"invalid",sourceEvidenceRefs:[]})]})),w=work(f,"SMART_SCOUT"),a=assign(f,w,"SMART_SCOUT");await assert.rejects(()=>f.coordinator.execute(a.id),/artifact_provenance_required/);assert.equal(f.coordinator.listArtifacts().length,0)});
test("assignment grants resolve to active actor and organization authority",()=>{const f=fixture(),w=work(f,"SMART_SCOUT");f.kernel.revokeGrant("grant","SYSTEM");assert.throws(()=>assign(f,w,"SMART_SCOUT"),/missing_or_inactive/)});
test("QA artifacts and reviews require canonical verdicts",async()=>{const f=fixture(async({work,assignment})=>({runRef:"run",artifacts:[artifact(work,assignment,"QAAssessment",{verdict:"LOOKS_GOOD",acceptanceCriteria:["x"],evidenceExaminedRefs:["e"],provenance:{inputRefs:["source"],productionActorRef:"producer"}})]})),w=work(f,"INDEPENDENT_QA"),a=assign(f,w,"INDEPENDENT_QA");await assert.rejects(()=>f.coordinator.execute(a.id),/invalid_qa_verdict/)});
