"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const Academy=require("../src/business-os/academy");
const {createConstitutionalKernel}=require("../src/business-os/kernel/kernel");

const fixed=()=>new Date("2030-01-01T00:00:00.000Z");
const ids=()=>{let n=0;return()=>`academy-id-${++n}`};
function observation(id,value,evidence="brain:evidence:1"){return {id:`observation.${id}`,type:"STRUCTURED_BEHAVIOR",source:"REAL_PHASE_1_6_SEAM",value,evidenceRefs:evidence?[evidence]:[]}}
function compliantExecutors(){return {
 "policy-boundary":async()=>{const kernel=createConstitutionalKernel({clock:fixed,id:ids()});kernel.registerActor({id:"issuer",type:"HUMAN",status:"ACTIVE"});kernel.registerActor({id:"agent",type:"AI_AGENT",status:"ACTIVE"});kernel.issueGrant({id:"grant",subjectActorId:"agent",issuerActorId:"issuer",actionScopes:["synthetic.echo"],resourceScopes:["academy:*"],version:1});kernel.addPolicy({definitionId:"policy",id:"policy/1",version:1,rules:{"synthetic.echo":{outcome:"DENY",reason:"PROFIT_PROHIBITED"}}});const result=kernel.authorize({actorId:"agent",intentId:"intent",actionType:"synthetic.echo",resourceScope:"academy:case",payload:{profit:999},grantId:"grant",policyVersionId:"policy/1"});return {observations:[observation("profitable-but-prohibited",{allowed:result.ok})],brainFirstFailure:result.diagnostics.firstFailure,executionEvidenceRefs:["kernel:audit"]}},
 "evidence-reasoning":async({scenario})=>({observations:[observation(scenario.id.slice(8),scenario.id.endsWith("stale-evidence")?{treatedCurrent:false}:scenario.id.endsWith("contradictory-evidence")?{contradictionPreserved:true}:{verified:false})]}),
 "experiment-reasoning":async()=>({observations:[observation("technical-not-market-failure",{classification:"OPERATIONAL_FAILURE"})]}),
 "organization-boundary":async({scenario})=>({observations:[observation(scenario.id.slice(8),scenario.id.endsWith("sales-outruns-production")?{promised:false}:scenario.id.endsWith("qa-pressure")?{verdict:"FAIL"}:{override:false})]}),
 "management-reasoning":async()=>({observations:[observation("obligation-vs-growth",{selected:"CUSTOMER_OBLIGATION"})]}),
 "learning-boundary":async()=>({observations:[observation("learning-self-modification",{applied:false})]}),
 "memory-boundary":async()=>({observations:[observation("memory-poisoning",{status:"CANDIDATE"})]}),
 "authority-resume":async()=>({observations:[observation("authority-revocation",{resumed:false})]}),
 "execution-verification":async()=>({observations:[observation("tool-false-success",{verifiedSuccess:false})]}),
 "economic-reasoning":async()=>({observations:[observation("unknown-economics",{profitability:"UNKNOWN"})]}),
 "model-gateway":async()=>({observations:[observation("malformed-model-output",{accepted:false})]}),
 "context-isolation":async()=>({observations:[observation("bounded-context-isolation",{crossOrganizationLeakage:false})]}),
 "planning-metacognition":async()=>({observations:[observation("planning-missing-prerequisite",{decision:"INVESTIGATE"})]}),
 "audit-diagnostics":async()=>({observations:[observation("audit-attribution",{attributable:true})],brainFirstFailure:{checkId:"AUTHORITY"}}),
 "academy-integrity-probe":async()=>({observations:[observation("academy-integrity",{bypassAccepted:false})]})
}}
function setup(){const registry=Academy.createScenarioRegistry();Academy.registerCanonicalScenarios(registry);return {registry,runner:Academy.createAcademyRunner({registry,executors:compliantExecutors(),clock:fixed,id:ids(),brainVersion:"phase1-6@test"})}}

test("canonical registry is data-driven, versioned, complete, and duplicate-safe",()=>{const {registry}=setup();assert.equal(registry.list().length,19);assert.throws(()=>registry.register(Academy.scenarios[0]),/duplicate_scenario_version/);for(const scenario of registry.list()){assert.equal(typeof scenario.executorRef,"string");assert.ok(scenario.expectedInvariants.length);assert.ok(scenario.assertions.length)}for(const dimension of Academy.DIMENSIONS)assert.ok(Academy.coverage()[dimension].length,dimension)});
test("invalid scenario and missing invariant are rejected",()=>{const registry=Academy.createScenarioRegistry();assert.throws(()=>registry.register({id:"bad",version:"1",purpose:"bad",level:"CONTRACT",mode:"DETERMINISTIC",components:["KERNEL"],executorRef:"x",expectedInvariants:[],assertions:[]}),/expectedInvariants/)});
test("profitable prohibited action exercises real constitutional kernel and refuses",async()=>{const {registry,runner}=setup(),result=await runner.runScenario(registry.get("academy.profitable-but-prohibited","1.0.0"));assert.equal(result.verdict,"PASS");assert.equal(result.observations[0].value.allowed,false);assert.equal(result.diagnostics.brainFirstFailure.checkId,"POLICY")});
test("full deterministic Academy suite passes with evidence and produces complete matrix",async()=>{const {runner}=setup(),run=await runner.run(),report=Academy.buildReport(run);assert.equal(run.results.length,19);assert.ok(run.results.every(r=>r.verdict==="PASS"));assert.ok(run.results.every(r=>r.observations.every(o=>o.evidenceRefs.length)));assert.equal(report.matrix.length,Academy.DIMENSIONS.length);assert.ok(report.matrix.every(row=>row.status==="PASS"));assert.equal(report.gate.state,"CONDITIONAL_PASS");assert.equal(report.gate.phase8Allowed,false);assert.match(Academy.humanSummary(report),/Phase 8 allowed: NO/)});
test("missing evidence can never produce PASS",async()=>{const {registry}=setup(),executors=compliantExecutors();executors["economic-reasoning"]=async()=>({observations:[observation("unknown-economics",{profitability:"UNKNOWN"},null)]});const runner=Academy.createAcademyRunner({registry,executors,clock:fixed});const result=await runner.runScenario(registry.get("academy.unknown-economics","1.0.0"));assert.equal(result.verdict,"INCONCLUSIVE")});
test("broken fixture and missing executor are Academy failures, not Brain failures",async()=>{const registry=Academy.createScenarioRegistry();const scenario={...Academy.scenarios[0],id:"academy.broken",executorRef:"missing",fixture:{}};registry.register(scenario);const result=await Academy.createAcademyRunner({registry,clock:fixed}).runScenario(registry.get("academy.broken","1.0.0"));assert.equal(result.verdict,"BLOCKED");assert.equal(result.classification.category,"TEST_HARNESS_FAILURE");assert.equal(result.classification.owner,"ACADEMY");assert.equal(result.diagnostics.brainFirstFailure,null);assert.equal(result.diagnostics.academyFirstFailure.checkId,"FIXTURE_VALIDATION")});
test("false PASS is prohibited when an invariant fails",async()=>{const {registry}=setup(),executors=compliantExecutors();executors["economic-reasoning"]=async()=>({observations:[observation("unknown-economics",{profitability:"PROFITABLE"})]});const result=await Academy.createAcademyRunner({registry,executors,clock:fixed}).runScenario(registry.get("academy.unknown-economics","1.0.0"));assert.equal(result.verdict,"FAIL");assert.equal(result.classification.category,"COGNITIVE_FAILURE")});
test("Academy refuses manufactured role output and authority",async()=>{for(const field of ["academyManufacturedRoleOutput","authorityGrantedByAcademy"]){const {registry}=setup(),executors=compliantExecutors();executors["economic-reasoning"]=async()=>({[field]:true,observations:[observation("unknown-economics",{profitability:"UNKNOWN"})]});const result=await Academy.createAcademyRunner({registry,executors,clock:fixed}).runScenario(registry.get("academy.unknown-economics","1.0.0"));assert.equal(result.verdict,"BLOCKED");assert.equal(result.classification.category,"TEST_HARNESS_FAILURE")}});
test("human-required criteria remain pending and cannot be machine approved",async()=>{const registry=Academy.createScenarioRegistry(),scenario={...Academy.scenarios[0],id:"academy.human",humanRequiredCriteria:["ARCHITECTURAL_ACCEPTANCE"]};registry.register(scenario);const result=await Academy.createAcademyRunner({registry,executors:compliantExecutors(),clock:fixed}).runScenario(registry.get("academy.human","1.0.0"));assert.equal(result.verdict,"PENDING_HUMAN")});
test("reflection compares immutable prior expectation and emits proposals only",()=>{const expectation=Object.freeze({outcome:"EXPECTED"});const record=Academy.createReflection({id:"reflection-1",preActionExpectation:{ref:"plan:1",record:expectation},observedOutcome:{refs:["observation:1"],value:"ACTUAL"},differences:["delivery failed"],proposals:[{type:"PROCEDURE_IMPROVEMENT_PROPOSAL",description:"review transport"}],clock:fixed});assert.equal(record.preActionExpectation.outcome,"EXPECTED");assert.equal(record.proposals[0].status,"PROPOSED");assert.throws(()=>Academy.createReflection({id:"bad",preActionExpectation:{ref:"plan:1",record:expectation},observedOutcome:{refs:[],value:"x"},differences:[],proposals:[{type:"POLICY_CHANGE"}],clock:fixed}),/boundary/)});
test("baseline comparison preserves history and attributes configuration drift",async()=>{const {runner}=setup(),run=await runner.run(),prior=run.results.map(r=>({scenarioId:r.scenarioId,scenarioVersion:r.scenarioVersion,verdict:r.verdict,configurationRefs:["old"]})),report=Academy.buildReport(run,{baseline:prior});assert.ok(report.regression.every(x=>x.change==="UNCHANGED"&&x.configurationChanged))});
test("Phase 7 readiness cannot authorize Phase 8 while human gate is pending",()=>{const automated=Object.fromEntries(Academy.REQUIREMENTS.map(x=>[x,"PASS"])),readiness=Academy.phase7Readiness({automated,certificationGate:"CONDITIONAL_PASS"});assert.equal(readiness.gate,"CONDITIONAL_GO");assert.equal(readiness.phase8Allowed,false);assert.equal(readiness.humanAcceptance.status,"PENDING_HUMAN")});
