"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const E=require("../src/business-os/economics");

const ORG="org:scenario",WORK="work:scenario",PRODUCT="product:scenario",CAMPAIGN="campaign:scenario",AT="2035-02-01T00:00:00.000Z";
const PERIOD={start:"2035-01-01T00:00:00.000Z",end:"2035-02-01T00:00:00.000Z"};
const values={REVENUE:100000,REFUND:5000,DISCOUNT:0,ACQUISITION_COST:20000,PAYMENT_FEE:3000,FULFILLMENT_COST:30000,FIXED_COST:10000};
const costs=["ACQUISITION_COST","PAYMENT_FEE","FULFILLMENT_COST","FIXED_COST"];
const coverage={requiredCostCategories:costs,units:100,newCustomers:20};
function input(category,amount=values[category],classification="ACTUAL") {return E.EconomicInput({id:`input:${category}`,organizationId:ORG,productRef:PRODUCT,campaignRef:CAMPAIGN,currency:"USD",reportingPeriod:PERIOD,version:1,category,classification,amountMinor:classification==="UNKNOWN"?null:amount,assumptions:classification==="ESTIMATED"?["Baseline estimate."]:[],evidenceRefs:classification==="UNKNOWN"?[]:[`evidence:${category}`],source:{system:"SYNTHETIC_ACCOUNTING",recordRef:`record:${category}`,recordVersion:1,payloadHash:`hash:${category}`,observedAt:PERIOD.end}});}
function baseline(patch={}) {const inputs=Object.keys(values).map(category=>category===patch.unknown?input(category,null,"UNKNOWN"):input(category));return E.calculateEconomicAssessment({id:"assessment:baseline",version:3,workId:WORK,financialInputs:inputs,coverage},{clock:()=>AT});}
function declared(input,transformationType,transformationAmount,reason=`Assume ${input.category} changes.`){let scenarioAmountMinor=null,scenarioClassification="UNKNOWN";if(transformationType==="ABSOLUTE_REPLACEMENT")scenarioAmountMinor=transformationAmount;else if(input.amountMinor!==null){scenarioAmountMinor=transformationType==="ABSOLUTE_DELTA"?input.amountMinor+transformationAmount:Number((BigInt(input.amountMinor)*BigInt(10000+transformationAmount)+5000n)/10000n);}if(scenarioAmountMinor!==null)scenarioClassification="ESTIMATED";return{targetInputId:input.id,category:input.category,originalClassification:input.classification,originalAmountMinor:input.amountMinor,scenarioClassification,scenarioAmountMinor,transformationType,transformationAmount,unit:transformationType==="PERCENTAGE_DELTA"?"BASIS_POINTS":"MINOR_CURRENCY",reason,baselineProvenance:{inputId:input.id,evidenceRefs:input.evidenceRefs}};}
function definition(base,overrides=[],patch={}){return{id:"scenario:1",organizationId:ORG,workId:WORK,productRef:PRODUCT,campaignRef:CAMPAIGN,name:"Explicit downside",description:"User-supplied deterministic conditional case.",version:1,baselineAssessmentRef:E.baselineReference(base),engineVersion:E.ECONOMICS_ENGINE_VERSION,policyVersion:E.SCENARIO_POLICY_VERSION,reportingPeriod:PERIOD,currency:"USD",type:"DOWNSIDE",assumptions:overrides.map(x=>x.reason),overrides,createdAt:AT,createdBy:"user:analyst",status:"DEFINED",...patch};}
const run=(base,overrides,patch)=>E.createEconomicScenarioResult({scenario:definition(base,overrides,patch),baselineAssessment:base,coverage});

test("absolute replacement, delta, and basis-point transformations derive ESTIMATED inputs and reuse ECO-2",()=>{const base=baseline(),by=c=>base.financialInputs.find(x=>x.category===c);const result=run(base,[declared(by("REVENUE"),"ABSOLUTE_REPLACEMENT",120000),declared(by("ACQUISITION_COST"),"ABSOLUTE_DELTA",5000),declared(by("REFUND"),"PERCENTAGE_DELTA",5000)]);assert.equal(result.assessment.engineVersion,E.ECONOMICS_ENGINE_VERSION);assert.deepEqual(result.scenarioInputs.filter(x=>x.classification==="ESTIMATED").map(x=>[x.category,x.amountMinor]),[["ACQUISITION_COST",25000],["REFUND",7500],["REVENUE",120000]]);assert.equal(result.assessment.metrics.netRevenue.value,112500);assert.equal(result.assessment.metrics.contribution.value,44500);assert.equal(result.assessment.actualValue.classification,"UNKNOWN");assert.equal(result.assessment.grossContribution.classification,"ESTIMATED");});

test("realistic downside and upside scenarios calculate all ECO-2 metrics",()=>{const base=baseline(),by=c=>base.financialInputs.find(x=>x.category===c);const downside=run(base,[declared(by("REVENUE"),"PERCENTAGE_DELTA",-2000),declared(by("ACQUISITION_COST"),"PERCENTAGE_DELTA",2500),declared(by("REFUND"),"PERCENTAGE_DELTA",5000),declared(by("FULFILLMENT_COST"),"PERCENTAGE_DELTA",1000)]);assert.deepEqual([downside.assessment.metrics.netRevenue.value,downside.assessment.metrics.totalKnownCost.value,downside.assessment.metrics.contribution.value,downside.assessment.metrics.contributionMargin.value,downside.assessment.metrics.cac.value,downside.assessment.metrics.roas.value,downside.assessment.metrics.roi.value,downside.assessment.metrics.breakEvenUnits.value],[72500,71000,1500,207,1250,29000,211,87]);const upside=run(base,[declared(by("REVENUE"),"PERCENTAGE_DELTA",2000),declared(by("ACQUISITION_COST"),"PERCENTAGE_DELTA",-1000),declared(by("REFUND"),"PERCENTAGE_DELTA",-2000)]);assert.equal(upside.assessment.metrics.contribution.value,55000);});

test("UNKNOWN plus a relative change remains UNKNOWN while replacement is an explicit assumption",()=>{const base=baseline({unknown:"ACQUISITION_COST"}),unknown=base.financialInputs.find(x=>x.category==="ACQUISITION_COST");const relative=run(base,[declared(unknown,"PERCENTAGE_DELTA",2000)]);assert.equal(relative.scenarioInputs.find(x=>x.category==="ACQUISITION_COST").classification,"UNKNOWN");assert.equal(relative.assessment.metrics.contribution.value,null);const assumed=run(base,[declared(unknown,"ABSOLUTE_REPLACEMENT",30000,"Assume acquisition cost is USD 300.")]);assert.deepEqual([assumed.scenarioInputs.find(x=>x.category==="ACQUISITION_COST").classification,assumed.assessment.metrics.cac.value],["ESTIMATED",1500]);});

test("zero baseline is deterministic and relative comparison is not applicable",()=>{const base=baseline(),revenue=base.financialInputs.find(x=>x.category==="DISCOUNT"),result=run(base,[declared(revenue,"ABSOLUTE_REPLACEMENT",1000)]);const comparison=result.comparisons.find(x=>x.metric==="discounts");assert.deepEqual([comparison.absoluteDelta.value,comparison.relativeDelta.status,comparison.interpretation],[1000,"NOT_APPLICABLE","UNFAVORABLE"]);});

test("duplicates, negative results, and unsafe integer transformations fail closed",()=>{const base=baseline(),revenue=base.financialInputs.find(x=>x.category==="REVENUE"),one=declared(revenue,"ABSOLUTE_REPLACEMENT",1),two=declared(revenue,"ABSOLUTE_REPLACEMENT",2);assert.throws(()=>run(base,[one,two]),/duplicate_override/);assert.throws(()=>run(base,[declared(revenue,"ABSOLUTE_DELTA",-100001)]),/scenario_amount|unsafe_transformation/);assert.throws(()=>run(base,[declared(revenue,"ABSOLUTE_DELTA",Number.MAX_SAFE_INTEGER)]),/unsafe_transformation|scenario_amount/);});

test("scope and exact baseline identity substitutions fail closed",()=>{const base=baseline();for(const patch of [{organizationId:"org:other"},{workId:"work:other"},{productRef:"product:other"},{campaignRef:"campaign:other"},{currency:"EUR"},{reportingPeriod:{start:PERIOD.start,end:"2035-03-01T00:00:00.000Z"}},{baselineAssessmentRef:{...E.baselineReference(base),assessmentId:"other"}},{baselineAssessmentRef:{...E.baselineReference(base),version:4}},{baselineAssessmentRef:{...E.baselineReference(base),digest:"bad"}},{engineVersion:"economics-v9"}])assert.throws(()=>run(base,[],patch),/invalid_economic_scenario/);});

test("baseline and scenario definitions remain immutable and reconciliation history is untouched",()=>{const base=baseline(),snapshot=structuredClone(base),revenue=base.financialInputs.find(x=>x.category==="REVENUE"),scenario=definition(base,[declared(revenue,"PERCENTAGE_DELTA",-1000)]),scenarioSnapshot=structuredClone(scenario),history=Object.freeze([{id:"reconciliation:historical"}]);const result=E.createEconomicScenarioResult({scenario,baselineAssessment:base,coverage});assert.deepEqual(base,snapshot);assert.deepEqual(scenario,scenarioSnapshot);assert.deepEqual(history,[{id:"reconciliation:historical"}]);assert.throws(()=>{result.assessment.metrics.netRevenue.value=0},TypeError);});

test("override order, replay, and serialization are deterministic for multi-variable scenarios",()=>{const base=baseline(),by=c=>base.financialInputs.find(x=>x.category===c),overrides=[declared(by("REVENUE"),"PERCENTAGE_DELTA",-1500),declared(by("ACQUISITION_COST"),"PERCENTAGE_DELTA",2000),declared(by("REFUND"),"PERCENTAGE_DELTA",500),declared(by("FULFILLMENT_COST"),"PERCENTAGE_DELTA",1000)];const a=run(base,overrides),b=run(structuredClone(base),[...overrides].reverse());assert.deepEqual(a,b);assert.deepEqual(JSON.parse(JSON.stringify(a)),a);});

test("comparison is baseline versus hypothetical and never grants execution authority",()=>{const base=baseline(),revenue=base.financialInputs.find(x=>x.category==="REVENUE"),result=run(base,[declared(revenue,"PERCENTAGE_DELTA",2000)]);assert.equal(result.comparisons.find(x=>x.metric==="contribution").interpretation,"FAVORABLE");assert.equal(result.authorization,undefined);assert.equal(result.forecast,undefined);assert.equal(result.probability,undefined);assert.equal(result.assessment.provenance,undefined);assert.match(result.limitations.join(" "),/not a forecast.*actual.*prediction.*authorization/);});

test("declared result, category, baseline provenance, and hypothetical ACTUAL claims fail closed",()=>{const base=baseline(),revenue=base.financialInputs.find(x=>x.category==="REVENUE"),valid=declared(revenue,"PERCENTAGE_DELTA",1000);for(const override of [{...valid,scenarioAmountMinor:1},{...valid,category:"REFUND"},{...valid,baselineProvenance:{...valid.baselineProvenance,evidenceRefs:["other"]}},{...valid,scenarioClassification:"ACTUAL"}])assert.throws(()=>run(base,[override]),/invalid_economic_scenario/);});
