"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const E=require("../src/business-os/economics"),W=require("../src/business-os/organization/economic-workflow"),O=require("../src/business-os/organization/contracts"),X=require("../src/business-os/experiment-manager/contracts");
const {proposalDigest}=require("../src/business-os/experiment-manager/approval");
const ORG="org:eco4b",WORK="work:eco4b",period={start:"2035-01-01T00:00:00.000Z",end:"2035-02-01T00:00:00.000Z"},ASOF="2035-02-03T00:00:00.000Z";
function economicInput(prefix,category,amountMinor){return E.EconomicInput({id:`${prefix}:input:${category}`,organizationId:ORG,productRef:"product",campaignRef:"campaign",currency:"USD",reportingPeriod:period,version:1,category,classification:"ACTUAL",amountMinor,assumptions:[],evidenceRefs:[`${prefix}:evidence:${category}`],source:{system:"FIXTURE",recordRef:`${prefix}:record:${category}`,recordVersion:1,payloadHash:`${prefix}:hash:${category}`,observedAt:"2035-01-31T00:00:00.000Z"}})}
function evidence(prefix,category,amountMinor,patch={}){return E.EconomicEvidenceRecord({id:`${prefix}:evidence:${category}`,evidenceType:"OBSERVED_FACT",source:{type:"ACCOUNTING_SYSTEM",system:"FIXTURE",recordRef:`${prefix}:record:${category}`,availability:"AVAILABLE"},actorId:"books",recordedAt:"2035-02-02T00:00:00.000Z",observedAt:"2035-01-31T00:00:00.000Z",version:1,scope:{organizationId:ORG,productRef:"product",campaignRef:"campaign",currency:"USD",reportingPeriod:period},claim:{category,classification:"ACTUAL",amountMinor},payloadHash:`${prefix}:hash:${category}`,supersededBy:null,...patch})}
function assessment(prefix,revenue,cost,{unknownCost=false,newCustomers=2,reverse=false}={}){const categories=[["REVENUE",revenue],["REFUND",0],["DISCOUNT",0],["ACQUISITION_COST",cost],["FULFILLMENT_COST",unknownCost?null:0]], inputs=categories.map(([c,v])=>v===null?E.EconomicInput({...economicInput(prefix,c,0),classification:"UNKNOWN",amountMinor:null,evidenceRefs:[]}):economicInput(prefix,c,v)),records=categories.filter(([,v])=>v!==null).map(([c,v])=>evidence(prefix,c,v));return E.calculateEvidenceBackedAssessment({id:`${prefix}:assessment`,workId:WORK,financialInputs:reverse?[...inputs].reverse():inputs,coverage:{requiredCostCategories:["ACQUISITION_COST","FULFILLMENT_COST"],newCustomers}},{clock:()=>ASOF,asOf:ASOF,evidenceRecords:reverse?[...records].reverse():records,freshnessPolicies:categories.map(([c])=>({id:`history:${c}`,category:c,sourceType:"ACCOUNTING_SYSTEM",mode:"HISTORICAL"}))});}
function fixture({baseline=assessment("forecast",100000,20000),actual=assessment("actual",80000,25000),resultClass="SUPPORTED"}={}){
 const proposalArtifact=W.sealArtifact({id:"proposal:1",artifactType:"ExperimentProposal",organizationId:ORG,workId:WORK,version:1,producingRoleId:"EXPERIMENT_MANAGER",status:"PROPOSED",createdAt:ASOF});
 const baselineArtifact=W.sealArtifact({id:"baseline:1",artifactType:"EconomicAssessment",organizationId:ORG,workId:WORK,version:1,assessmentId:baseline.id,assessmentDigest:E.economicArtifactDigest(baseline),producingRoleId:"ECONOMICS",status:"ACCEPTED",createdAt:ASOF});
 const actualArtifact=W.sealArtifact({id:"actual:1",artifactType:"EconomicAssessment",organizationId:ORG,workId:WORK,version:1,assessmentId:actual.id,assessmentDigest:E.economicArtifactDigest(actual),producingRoleId:"ECONOMICS",status:"ACCEPTED",createdAt:ASOF});
 const decision=O.GovernedDecision({id:"decision:1",organizationId:ORG,workId:WORK,decisionType:"AUTHORIZE_EXPERIMENT",result:"APPROVE",economicAssessmentRef:W.reference(baselineArtifact),experimentProposalRef:W.reference(proposalArtifact),chainRefs:[W.reference(proposalArtifact),W.reference(baselineArtifact)],decidedAt:ASOF,decisionMakerRef:"human:owner",authorityRef:"grant:owner",authorityType:"HUMAN",authorizationScope:"EXPERIMENT_EXECUTION",conditions:[],reason:"approved",version:1});
 const approval=X.ExperimentApproval({id:"approval:1",organizationId:ORG,proposalRef:"proposal:1",proposalVersion:1,proposalDigest:proposalDigest(proposalArtifact),actorType:"HUMAN",actorId:"owner",authorityRef:"grant:owner",scope:"EXPERIMENT_RUN_INTERNAL",budgetCeiling:500,decisionRef:decision.id,evidenceRefs:["approval:evidence"],status:"APPROVED",approvedAt:ASOF});
 const run=X.ExperimentRun({id:"run:1",organizationId:ORG,proposalRef:"proposal:1",proposalVersion:1,approvalRef:approval.id,budget:500,boundary:"INTERNAL",status:"COMPLETED",idempotencyKey:"run",startedAt:ASOF,history:[]});
 const experimentResult=X.ExperimentResult({id:"result:1",organizationId:ORG,workId:WORK,proposalRef:"proposal:1",proposalVersion:1,runRef:run.id,resultClass,measurements:[],evidenceRefs:["result:evidence"],limitations:[],status:"PROPOSED",createdAt:ASOF});
 return{organizationId:ORG,workId:WORK,proposalArtifact,baselineArtifact,baselineAssessment:baseline,decision,approval,run,experimentResult,actualArtifact,actualAssessment:actual,authorizedAmountMinor:50000,reservedAmountMinor:50000,asOf:ASOF};
}
const reconcile=(f=fixture())=>E.createEconomicReconciliation(f,{clock:()=>"2035-02-04T00:00:00.000Z"});
test("authorized forecast reconciles to evidence-backed actuals deterministically without changing the experimental result",()=>{const f=fixture(),a=reconcile(f),b=reconcile(structuredClone(f));assert.deepEqual(a,b);assert.deepEqual(JSON.parse(JSON.stringify(a)),a);assert.equal(a.status,"PARTIALLY_RECONCILED");assert.equal(a.experimentResultClass,"SUPPORTED");assert.equal(f.experimentResult.profit,undefined);assert.equal(a.budget.actualSpendMinor,null);assert.equal(a.budget.unusedAuthorizationMinor,null);assert.equal(a.budget.reservedAmountMinor,50000);assert.equal(a.runRef.runId,f.run.id);assert.equal(a.experimentResultRef.artifactId,f.experimentResult.id);assert.match(a.runRef.digest,/^[a-f0-9]{64}$/);assert.match(a.experimentResultRef.digest,/^[a-f0-9]{64}$/);});
test("input order does not affect assessments or reconciliation",()=>{const a=reconcile(fixture({baseline:assessment("forecast",100000,20000),actual:assessment("actual",80000,25000)})),b=reconcile(fixture({baseline:assessment("forecast",100000,20000,{reverse:true}),actual:assessment("actual",80000,25000,{reverse:true})}));assert.deepEqual(b,a);});
test("revenue, cost, refunds and CAC use metric-aware direction",()=>{const r=reconcile(),by=n=>r.metricComparisons.find(x=>x.metric===n);assert.equal(by("grossRevenue").comparisonStatus,"UNFAVORABLE");assert.equal(by("totalKnownCost").comparisonStatus,"UNFAVORABLE");assert.equal(by("cac").comparisonStatus,"UNFAVORABLE");const favorable=reconcile(fixture({actual:assessment("actual-low-cost",120000,10000)}));assert.equal(favorable.metricComparisons.find(x=>x.metric==="grossRevenue").comparisonStatus,"FAVORABLE");assert.equal(favorable.metricComparisons.find(x=>x.metric==="totalKnownCost").comparisonStatus,"FAVORABLE");});
test("unknown values are never converted to zero and partial costs remain visible",()=>{const r=reconcile(fixture({actual:assessment("actual-unknown",80000,25000,{unknownCost:true})})),c=r.metricComparisons.find(x=>x.metric==="contribution");assert.deepEqual([c.actual.status,c.absoluteVariance.status,c.absoluteVariance.value,c.comparisonStatus],["UNKNOWN","UNKNOWN",null,"UNKNOWN"]);assert.equal(r.status,"PARTIALLY_RECONCILED");});
test("zero expected denominator preserves absolute variance and makes relative variance not applicable",()=>{for(const actualValue of [0,20000]){const r=reconcile(fixture({baseline:assessment(`forecast-zero-${actualValue}`,0,0),actual:assessment(`actual-zero-${actualValue}`,actualValue,0)})),m=r.metricComparisons.find(x=>x.metric==="grossRevenue");assert.equal(m.absoluteVariance.value,actualValue);assert.equal(m.relativeVariance.status,"NOT_APPLICABLE");}});
test("scope, proposal, version, run, result, baseline and decision substitutions fail closed",()=>{const changes=[f=>f.proposalArtifact={...f.proposalArtifact,organizationId:"other"},f=>f.actualAssessment={...f.actualAssessment,workId:"other"},f=>f.run={...f.run,proposalRef:"other"},f=>f.run={...f.run,proposalVersion:2},f=>f.experimentResult={...f.experimentResult,runRef:"other"},f=>f.experimentResult={...f.experimentResult,proposalRef:"other"},f=>f.baselineArtifact={...f.baselineArtifact,digest:"tampered"},f=>f.actualArtifact={...f.actualArtifact,digest:"tampered"},f=>f.approval={...f.approval,decisionRef:"other"},f=>f.approval={...f.approval,proposalDigest:"tampered"},f=>f.approval={...f.approval,proposalVersion:2},f=>f.authorizedAmountMinor=49999,f=>f.reservedAmountMinor=49999];for(const change of changes){const f=fixture();change(f);assert.throws(()=>reconcile(f),/invalid_economic_reconciliation/);}});
test("superseded assessments, canceled and unauthorized runs fail closed",()=>{for(const change of [f=>f.baselineArtifact={...f.baselineArtifact,status:"SUPERSEDED"},f=>f.actualArtifact={...f.actualArtifact,status:"SUPERSEDED"},f=>f.run={...f.run,status:"CANCELLED"},f=>f.approval={...f.approval,status:"REVOKED"}]){const f=fixture();change(f);assert.throws(()=>reconcile(f),/invalid_economic_reconciliation/);}});
test("technical failure and inconclusive remain experiment classifications, not financial declarations",()=>{for(const resultClass of ["TECHNICAL_FAILURE","INCONCLUSIVE"]){const r=reconcile(fixture({resultClass}));assert.equal(r.experimentResultClass,resultClass);assert.equal(r.economicSuccess,undefined);}});
test("reporting windows, missing provenance and future as-of fail closed while late-recorded in-window evidence is accepted by ECO-3",()=>{let actual=assessment("period-mismatch",80000,25000);let f=fixture({actual:{...actual,reportingPeriod:{...period,end:"2035-03-01T00:00:00.000Z"}}});assert.throws(()=>reconcile(f),/reporting_period/);actual=assessment("no-provenance",80000,25000);f=fixture({actual:{...actual,provenance:undefined}});assert.throws(()=>reconcile(f),/actual_provenance/);assert.equal(reconcile().status,"PARTIALLY_RECONCILED");f=fixture();f.asOf="2035-02-01T00:00:00.000Z";assert.throws(()=>reconcile(f),/future_actual_evidence/);});
test("checked variance rejects overflow and non-finite values",()=>{const metric=(value,status="CALCULATED")=>({value,unit:"MINOR_CURRENCY",status,missingInputs:[]});assert.throws(()=>E.compareEconomicMetric("grossRevenue",metric(Number.MIN_SAFE_INTEGER),metric(Number.MAX_SAFE_INTEGER)),/overflow/);assert.throws(()=>E.compareEconomicMetric("grossRevenue",metric(NaN),metric(1)),/metric_value/);});
test("partial variance is only numeric when both sides omit the same dependencies",()=>{const metric=(value,missingInputs)=>({value,unit:"MINOR_CURRENCY",status:"PARTIAL",missingInputs});const unlike=E.compareEconomicMetric("totalKnownCost",metric(100,["fulfillment"]),metric(80,["labor"]));assert.deepEqual([unlike.absoluteVariance.status,unlike.absoluteVariance.value,unlike.comparisonStatus],["PARTIAL",null,"PARTIAL"]);const like=E.compareEconomicMetric("totalKnownCost",metric(100,["fulfillment"]),metric(80,["fulfillment"]));assert.deepEqual([like.absoluteVariance.status,like.absoluteVariance.value,like.comparisonStatus],["PARTIAL",-20,"PARTIAL"]);});

test("running, paused, and canceled executions cannot be reconciled as post-execution outcomes",()=>{for(const status of ["RUNNING","PAUSED","CANCELLED"]){const f=fixture();f.run={...f.run,status};assert.throws(()=>reconcile(f),/run_lineage/);}});
test("repository rejects duplicate identities and preserves immutable historical records",()=>{const repo=new E.EconomicReconciliationRepository(),r=reconcile();repo.save(r);assert.deepEqual(repo.get(r.id),r);assert.throws(()=>repo.save(r),/duplicate_reconciliation_identity/);const copy=repo.get(r.id);copy.status="INVALID";assert.equal(repo.get(r.id).status,"PARTIALLY_RECONCILED");});

test("reconciliation never aliases total known cost to actual spend",()=>{const r=reconcile();assert.equal(r.metricComparisons.find(x=>x.metric==="totalKnownCost").actual.value,25000);assert.equal(r.budget.actualSpendMinor,null);assert.equal(r.budget.unusedAuthorizationMinor,null);});
