"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const E=require("../src/business-os/economics");
const ORG="org:portfolio",WORK="work:portfolio",AT="2037-02-01T00:00:00.000Z",PERIOD={start:"2037-01-01T00:00:00.000Z",end:AT};
const amounts={REVENUE:100000,REFUND:5000,DISCOUNT:0,ACQUISITION_COST:20000,PAYMENT_FEE:3000,FULFILLMENT_COST:30000,FIXED_COST:10000};
const coverage={requiredCostCategories:["ACQUISITION_COST","PAYMENT_FEE","FULFILLMENT_COST","FIXED_COST"],units:100,newCustomers:20};
function assessment(id,product,campaign=null,{unknown,estimated,revenue=100000}={}){const inputs=Object.keys(amounts).map(category=>E.EconomicInput({id:`${id}:${category}`,organizationId:ORG,productRef:product,campaignRef:campaign,currency:"USD",reportingPeriod:PERIOD,version:1,category,classification:category===unknown?"UNKNOWN":category===estimated?"ESTIMATED":"ACTUAL",amountMinor:category===unknown?null:category==="REVENUE"?revenue:amounts[category],assumptions:category===estimated?["Explicit expectation."]:[],evidenceRefs:category===unknown?[]:[`evidence:${id}:${category}`],source:{system:"TEST",recordRef:`record:${id}:${category}`,observedAt:AT}}));const a=E.calculateEconomicAssessment({id,version:2,workId:WORK,financialInputs:inputs,coverage},{clock:()=>AT});return {...a,provenance:{asOf:AT,inputs:a.financialInputs.map(x=>({inputId:x.id,accepted:true,trustState:"TRUSTED"}))}}}
const a=assessment("assessment:a","product:a"),b=assessment("assessment:b","product:b",null,{revenue:120000});
function member(id,value,patch={}){return{id,memberType:"PRODUCT",economicUnitId:`unit:${value.productRef}`,organizationId:ORG,workId:WORK,productRef:value.productRef,campaignRef:value.campaignRef,economicAssessmentRef:E.economicPortfolioAssessmentReference(value),engineVersion:E.ECONOMICS_ENGINE_VERSION,economicView:"ACTUAL",currency:"USD",reportingPeriod:PERIOD,scenarioRef:null,calibrationRef:null,...patch}}
function definition(members=[member("a",a)],patch={}){return{id:"portfolio:one",version:1,organizationId:ORG,workId:WORK,name:"Declared portfolio",economicView:"ACTUAL",currency:"USD",reportingPeriod:PERIOD,engineVersion:E.ECONOMICS_ENGINE_VERSION,policyVersion:E.PORTFOLIO_POLICY_VERSION,createdAt:AT,createdBy:"user:economist",members,limitations:[],...patch}}
const run=(members=[member("a",a)],options={})=>E.runEconomicPortfolioStudy({portfolio:definition(members,options.patch),economicAssessments:options.assessments||[a,b],scenarioResults:options.scenarios||[],calibrationProfiles:options.calibrations||[]});

test("valid one-member and multi-member portfolios aggregate authoritative additive metrics",()=>{const one=run(),many=run([member("a",a),member("b",b)]);assert.equal(one.metrics.contribution.knownResolvedValue,a.metrics.contribution.value);assert.equal(many.metrics.grossRevenue.knownResolvedValue,a.metrics.grossRevenue.value+b.metrics.grossRevenue.value);assert.equal(many.memberCount,2);assert.equal(many.metrics.grossRevenue.coverage.resolvedMemberCount,2)});
test("member ordering and deterministic replay do not alter identity or output",()=>{const x=run([member("b",b),member("a",a)]),y=run([member("a",a),member("b",b)]);assert.deepEqual(x,y);assert.deepEqual(x,run([member("b",b),member("a",a)]))});
test("empty portfolio is not represented as zero economics",()=>{const result=run([],{assessments:[]});assert.equal(result.memberCount,0);assert.equal(result.metrics.grossRevenue.status,"NOT_APPLICABLE");assert.equal(result.metrics.grossRevenue.knownResolvedValue,null);assert.equal(result.composition.status,"NOT_APPLICABLE")});
test("duplicate IDs, exact assessments, declared units, and duplicate product/campaign periods fail closed",()=>{assert.throws(()=>run([member("same",a),member("same",b)]),/duplicate_or_invalid_member_id/);assert.throws(()=>run([member("a",a),member("other",a,{economicUnitId:"different"})]),/duplicate_assessment/);assert.throws(()=>run([member("a",a),member("other",b,{economicUnitId:"unit:product:a",productRef:a.productRef,economicAssessmentRef:E.economicPortfolioAssessmentReference(b)})]),/overlapping_economic_unit/);assert.throws(()=>run([member("a",a),member("alias",b,{economicUnitId:"unit:alias",productRef:a.productRef,economicAssessmentRef:E.economicPortfolioAssessmentReference(b)})]),/overlapping_product_campaign_period/)});
test("nested or subtotal members are rejected by the leaf-first contract",()=>{assert.throws(()=>run([member("subtotal",a,{memberType:"PORTFOLIO"})]),/leaf_member_type/);assert.throws(()=>run([member("subtotal",a,{memberType:"SUBTOTAL"})]),/leaf_member_type/)});
test("assessment id, version, digest, engine, mutation, and every scope binding are exact",()=>{const base=member("a",a);for(const ref of [{...base.economicAssessmentRef,assessmentId:"wrong"},{...base.economicAssessmentRef,version:99},{...base.economicAssessmentRef,digest:"wrong"},{...base.economicAssessmentRef,engineVersion:"wrong"}])assert.throws(()=>run([{...base,economicAssessmentRef:ref}]),/assessment_binding/);for(const patch of [{organizationId:"other"},{workId:"other"},{productRef:"other"},{campaignRef:"other"}])assert.throws(()=>run([{...base,...patch}]),/scope|binding/);const changed=structuredClone(a);changed.metrics.grossRevenue.value++;assert.throws(()=>run([base],{assessments:[changed]}),/assessment_binding/)});
test("currency, reporting period, engine, and economic view compatibility fail closed",()=>{const base=member("a",a);for(const patch of [{currency:"EUR"},{reportingPeriod:{...PERIOD,end:"2037-03-01T00:00:00.000Z"}},{engineVersion:"old"},{economicView:"EXPECTED_BASELINE"}])assert.throws(()=>run([{...base,...patch}]),/compatibility|engine|view/);assert.throws(()=>run([base],{patch:{currency:"EUR"}}),/currency/);assert.throws(()=>run([base],{patch:{reportingPeriod:{...PERIOD,end:"2037-03-01T00:00:00.000Z"}}}),/compatibility/)});
test("ACTUAL must prove authoritative actual provenance and EXPECTED is not ACTUAL",()=>{const noProvenance={...a,provenance:undefined},actualMember={...member("a",noProvenance),economicAssessmentRef:E.economicPortfolioAssessmentReference(noProvenance)};assert.throws(()=>run([actualMember],{assessments:[noProvenance]}),/actual_provenance/);const expected=assessment("assessment:expected","product:expected",null,{estimated:"REVENUE"}),m=member("expected",expected,{economicView:"EXPECTED_BASELINE"}),result=run([m],{assessments:[expected],patch:{economicView:"EXPECTED_BASELINE"}});assert.equal(result.economicView,"EXPECTED_BASELINE");assert.throws(()=>run([member("a",a,{economicView:"EXPECTED_BASELINE"})],{patch:{economicView:"EXPECTED_BASELINE"}}),/expected_provenance/)});
test("UNKNOWN is not zero and known aggregate is visibly incomplete",()=>{const unknown=assessment("assessment:u","product:u",null,{unknown:"FULFILLMENT_COST"}),result=run([member("a",a),member("u",unknown)],{assessments:[a,unknown]}),metric=result.metrics.contribution;assert.equal(metric.status,"PARTIAL");assert.equal(metric.knownResolvedValue,a.metrics.contribution.value);assert.deepEqual(metric.coverage.unresolvedMemberIds,["u"]);assert.equal(metric.coverage.resolvedMemberCount,1);assert.equal(metric.coverage.unresolvedMemberCount,1)});
test("PARTIAL remains partial, INVALID remains invalid, and NOT_APPLICABLE is not zero",()=>{const partial=assessment("assessment:p","product:p",null,{estimated:"REVENUE"}),invalid=structuredClone(a),na=structuredClone(b);invalid.id="assessment:i";invalid.productRef="product:i";invalid.metrics.contribution={...invalid.metrics.contribution,status:"INVALID",value:null};na.id="assessment:n";na.productRef="product:n";na.metrics.contribution={...na.metrics.contribution,status:"NOT_APPLICABLE",value:null};for(const x of [invalid,na])x.provenance={...a.provenance};let result=run([member("p",partial,{economicView:"EXPECTED_BASELINE"})],{assessments:[partial],patch:{economicView:"EXPECTED_BASELINE"}});assert.equal(result.metrics.grossRevenue.status,"PARTIAL");result=run([member("i",invalid)],{assessments:[invalid]});assert.equal(result.metrics.contribution.status,"INVALID");result=run([member("n",na)],{assessments:[na]});assert.equal(result.metrics.contribution.status,"NOT_APPLICABLE");assert.equal(result.metrics.contribution.knownResolvedValue,null)});
test("checked BigInt aggregation rejects unsafe totals",()=>{const x=structuredClone(a),y=structuredClone(b);x.metrics.grossRevenue.value=Number.MAX_SAFE_INTEGER;y.metrics.grossRevenue.value=1;x.id="assessment:max";y.id="assessment:one";x.productRef="product:max";y.productRef="product:one";assert.throws(()=>run([member("max",x),member("one",y)],{assessments:[x,y]}),/aggregate_overflow/)});
test("composition uses known resolved gross revenue, deterministic half-up shares, and no ranking",()=>{const result=run([member("a",a),member("b",b)]),shares=result.composition.memberShares,json=JSON.stringify(result);assert.equal(result.composition.denominator,"KNOWN_RESOLVED_GROSS_REVENUE");assert.equal(shares.reduce((n,x)=>n+x.shareBasisPoints,0),10000);assert.deepEqual(shares.map(x=>x.memberId),["a","b"]);for(const forbidden of ["\"rank\":","bestProduct","recommendedMember","priorityScore","investmentScore"])assert.ok(!json.includes(forbidden))});
test("zero known revenue makes concentration not applicable",()=>{const zero=assessment("assessment:zero","product:zero",null,{revenue:0}),result=run([member("zero",zero)],{assessments:[zero]});assert.equal(result.composition.status,"NOT_APPLICABLE");assert.deepEqual(result.composition.memberShares,[])});
test("ratios and unit metrics are never summed or averaged",()=>{const result=run([member("a",a),member("b",b)]);for(const metric of ["roi","roas","cac","contributionMargin","unitRevenue","unitCost","unitContribution","breakEvenUnits"]){assert.ok(result.nonAggregatedMetrics.includes(metric));assert.equal(result.metrics[metric],undefined)}});
test("scenario members bind exact ECO-5A lineage and stay explicitly hypothetical",()=>{const expected=assessment("assessment:scenario-base","product:scenario",null,{estimated:"REVENUE"}),override=E.deriveScenarioOverride(expected.financialInputs.find(x=>x.category==="REVENUE"),{transformationType:"ABSOLUTE_REPLACEMENT",transformationAmount:140000,reason:"Declared hypothesis."}),scenario=E.createEconomicScenarioResult({scenario:{id:"scenario:one",version:1,organizationId:ORG,workId:WORK,productRef:expected.productRef,campaignRef:null,name:"Scenario",description:"Member hypothesis",createdBy:"user:economist",createdAt:AT,reportingPeriod:PERIOD,currency:"USD",engineVersion:E.ECONOMICS_ENGINE_VERSION,policyVersion:E.SCENARIO_POLICY_VERSION,baselineAssessmentRef:E.baselineReference(expected),type:"CUSTOM",status:"DEFINED",assumptions:["Member-specific only."],overrides:[override]},baselineAssessment:expected,coverage});const m=member("scenario",scenario.assessment,{economicView:"SCENARIO",scenarioRef:E.economicPortfolioScenarioReference(scenario)}),result=run([m],{assessments:[],scenarios:[scenario],patch:{economicView:"SCENARIO"}});assert.equal(result.scenarioContext[0].interpretation,"MEMBER_HYPOTHETICAL_ONLY");assert.throws(()=>run([{...m,scenarioRef:{...m.scenarioRef,digest:"wrong"}}],{scenarios:[scenario],patch:{economicView:"SCENARIO"}}),/scenario_binding/)});
test("calibration is exact descriptive context and never modifies member economics",()=>{const profile={kind:"EconomicCalibrationProfile",id:"profile:a",version:1,modelVersion:E.CALIBRATION_MODEL_VERSION,cohortDefinition:{organizationId:ORG,productRef:a.productRef,campaignRef:a.campaignRef,currency:"USD",engineVersion:E.ECONOMICS_ENGINE_VERSION},statistics:{meanAbsoluteError:{value:123,observationCount:2}}};profile.digest=E.economicCalibrationDigest(profile);const m=member("a",a,{calibrationRef:E.economicPortfolioCalibrationReference(profile)}),result=run([m],{calibrations:[profile]});assert.equal(result.calibrationContext[0].modifiesEconomics,false);assert.equal(result.metrics.contribution.knownResolvedValue,a.metrics.contribution.value);const changed=structuredClone(profile);changed.statistics.meanAbsoluteError.value=999;assert.throws(()=>run([m],{calibrations:[changed]}),/mutated_supplied_calibration/)});
test("shared costs are not allocated and analysis has no capital or governance authority",()=>{const sources=[a,b],before=structuredClone(sources),allocation=Object.freeze({kind:"CapitalAllocationResult",status:"FEASIBLE"}),governance=Object.freeze({kind:"GovernedDecision",result:"APPROVE"}),result=run([member("a",a),member("b",b)],{assessments:sources});assert.deepEqual(sources,before);assert.match(result.limitations.join(" "),/invents no allocation/);assert.deepEqual({authorization:result.authorization,reservation:result.reservation,spend:result.spend,execution:result.execution},{authorization:null,reservation:null,spend:null,execution:null});assert.deepEqual(allocation,{kind:"CapitalAllocationResult",status:"FEASIBLE"});assert.deepEqual(governance,{kind:"GovernedDecision",result:"APPROVE"});assert.throws(()=>{result.memberCount=99},TypeError)});

test("unresolved PARTIAL with missing inputs is not included in known aggregate",()=>{const x=structuredClone(b);x.id="assessment:unresolved";x.productRef="product:unresolved";x.metrics.grossRevenue={...x.metrics.grossRevenue,status:"PARTIAL",value:90000,missingInputs:["REVENUE"]};const result=run([member("a",a),member("unresolved",x)],{assessments:[a,x]});assert.equal(result.metrics.grossRevenue.status,"PARTIAL");assert.equal(result.metrics.grossRevenue.knownResolvedValue,a.metrics.grossRevenue.value);assert.deepEqual(result.metrics.grossRevenue.coverage.unresolvedMemberIds,["unresolved"]);assert.equal(result.metrics.grossRevenue.coverage.unresolvedMemberCount,1)});
test("NOT_APPLICABLE members cannot produce falsely complete totals",()=>{const x=structuredClone(b);x.id="assessment:na";x.productRef="product:na";x.metrics.grossRevenue={...x.metrics.grossRevenue,status:"NOT_APPLICABLE",value:null};const result=run([member("a",a),member("na",x)],{assessments:[a,x]});assert.equal(result.metrics.grossRevenue.status,"PARTIAL");assert.equal(result.metrics.grossRevenue.coverage.notApplicableMemberCount,1)});
test("negative known revenue cannot produce invented concentration shares",()=>{const x=structuredClone(a);x.id="assessment:negative";x.productRef="product:negative";x.metrics.grossRevenue={...x.metrics.grossRevenue,value:-100};assert.throws(()=>run([member("negative",x)],{assessments:[x]}),/composition_nonnegative_denominator/)});
