"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const W=require("../src/business-os/organization/economic-workflow"),C=require("../src/business-os/organization/contracts");
const ORG="org:a",WORK="work:1042",AT="2030-01-01T00:00:00.000Z";
function chain(patch={}){
 const opportunity=W.sealArtifact({id:"candidate:332",artifactType:"OpportunityCandidate",organizationId:ORG,workId:WORK,version:1,producingRoleId:"SMART_SCOUT",status:"ACCEPTED",createdAt:AT});
 const analyst=W.sealArtifact({id:"assessment:211",artifactType:"AnalystAssessment",organizationId:ORG,workId:WORK,version:1,producingRoleId:"SMART_ANALYST",status:"ACCEPTED",createdAt:AT,upstreamRefs:[W.reference(opportunity)]});
 const proposal=W.sealArtifact({id:"proposal:97",artifactType:"ExperimentProposal",organizationId:ORG,workId:WORK,version:1,producingRoleId:"EXPERIMENT_MANAGER",status:"PROPOSED",createdAt:AT,budgetMinor:30000,objective:"pilot",upstreamRefs:[W.reference(analyst)]});
 const economics=W.sealArtifact({id:"economic:55",artifactType:"EconomicAssessment",organizationId:ORG,workId:WORK,version:1,producingRoleId:"ECONOMICS",status:"ACCEPTED",createdAt:AT,disposition:"CONTINUE",provenanceStatus:"TRUSTED",upstreamRefs:[W.reference(proposal)]});
 const artifacts=[opportunity,analyst,proposal,economics].map(a=>patch[a.artifactType]?W.sealArtifact({...a,...patch[a.artifactType],digest:undefined}):a);
 const refs=artifacts.map(W.reference);
 const decision=W.createGovernedDecision({id:"decision:31",organizationId:ORG,workId:WORK,decisionType:"AUTHORIZE_EXPERIMENT",result:"APPROVE",economicAssessmentRef:refs[3],experimentProposalRef:refs[2],chainRefs:refs,decidedAt:AT,decisionMakerRef:"human:owner",authorityRef:"grant:owner",authorityType:"HUMAN",authorizationScope:"EXPERIMENT_EXECUTION",conditions:[],reason:"Reviewed exact chain",version:1});
 return {artifacts,decision};
}
const auth=(c=chain(),extra={})=>W.authorizeExecution({organizationId:ORG,workId:WORK,workflowState:"APPROVED",artifacts:c.artifacts,decisions:[c.decision],now:AT,...extra});
test("happy path is deterministic, order independent, replay serializable, and becomes READY_FOR_EXECUTION",()=>{const c=chain(),a=auth(c),b=auth({...c,artifacts:[...c.artifacts].reverse()});assert.equal(a.authorized,true);assert.equal(a.workflowState,"READY_FOR_EXECUTION");assert.deepEqual(a,b);assert.deepEqual(auth(JSON.parse(JSON.stringify(c))),a)});
test("state machine permits the governed path and rejects skips",()=>{let s="DISCOVERED";for(const n of ["UNDER_ANALYSIS","ANALYSIS_COMPLETE","EXPERIMENT_PROPOSED","ECONOMIC_REVIEW","DECISION_REQUIRED","APPROVED","READY_FOR_EXECUTION"]){assert.equal(W.transition(s,n).to,n);s=n}assert.throws(()=>W.transition("DISCOVERED","APPROVED"),/illegal_workflow_transition/);assert.throws(()=>W.transition("EXPERIMENT_PROPOSED","READY_FOR_EXECUTION"),/illegal_workflow_transition/)});
test("missing role artifacts and pre-approval requests fail closed",()=>{const c=chain();for(let i=0;i<4;i++){const r=auth({...c,artifacts:c.artifacts.filter((_,j)=>i!==j)});assert.match(r.code,/^MISSING_/)}assert.equal(auth(c,{workflowState:"ANALYSIS_COMPLETE"}).code,"WORKFLOW_NOT_APPROVED");assert.equal(auth({...c,decision:null},{decisions:[]}).code,"MISSING_GOVERNED_DECISION")});
test("Economics recommendations never authorize and unknown provenance blocks",()=>{for(const disposition of ["NEEDS_MORE_EVIDENCE","REVISE","REJECT","ESCALATE",undefined]){const c=chain({EconomicAssessment:{disposition}});assert.equal(auth(c).authorized,false)}const c=chain({EconomicAssessment:{provenanceStatus:"CONFLICTED"}});assert.equal(auth(c).code,"ECONOMIC_PROVENANCE_BLOCKED")});
test("proposal mutation, version change, assessment replacement, and replay against new artifacts invalidate approval",()=>{for(const change of [{budgetMinor:300000},{version:2},{objective:"different"}]){const c=chain(),p=W.sealArtifact({...c.artifacts[2],...change,digest:undefined});assert.equal(auth({...c,artifacts:[c.artifacts[0],c.artifacts[1],p,c.artifacts[3]]}).authorized,false)}const c=chain(),e=W.sealArtifact({...c.artifacts[3],version:2,digest:undefined});assert.equal(auth({...c,artifacts:[...c.artifacts.slice(0,3),e]}).authorized,false)});
test("digest mismatch, wrong ancestry, supersession, cancellation, and expiration fail",()=>{let c=chain();assert.equal(auth({...c,artifacts:[{...c.artifacts[0],digest:"bad"},...c.artifacts.slice(1)]}).code,"ARTIFACT_DIGEST_MISMATCH");c=chain({ExperimentProposal:{upstreamRefs:[]}});assert.equal(auth(c).code,"UPSTREAM_REFERENCE_MISMATCH");for(const [type,status] of [["ExperimentProposal","SUPERSEDED"],["EconomicAssessment","SUPERSEDED"],["ExperimentProposal","CANCELLED"]])assert.equal(auth(chain({[type]:{status}})).code,"ARTIFACT_BLOCKED");c=chain();assert.equal(auth({...c,decision:{...c.decision,expiresAt:"2029-01-01T00:00:00.000Z"}}).code,"DECISION_EXPIRED")});
test("organization, work, type, and producer isolation fail closed",()=>{for(const [type,change,code] of [["AnalystAssessment",{organizationId:"org:b"},"ORGANIZATION_MISMATCH"],["EconomicAssessment",{workId:"work:other"},"WORK_MISMATCH"],["EconomicAssessment",{producingRoleId:"EXPERIMENT_MANAGER"},"ROLE_SEPARATION_VIOLATION"]])assert.equal(auth(chain({[type]:change})).code,code);const c=chain(),bad=W.sealArtifact({...c.artifacts[0],artifactType:"Unknown",digest:undefined});assert.equal(auth({...c,artifacts:[bad,...c.artifacts.slice(1)]}).code,"WRONG_ARTIFACT_TYPE")});
test("decision must bind the exact economics/proposal chain and cannot conflict",()=>{const c=chain();assert.equal(auth(c,{decisions:[{...c.decision,organizationId:"org:b"}]}).code,"DECISION_ORGANIZATION_MISMATCH");assert.equal(auth(c,{decisions:[{...c.decision,workId:"work:b"}]}).code,"DECISION_WORK_MISMATCH");assert.equal(auth(c,{decisions:[c.decision,{...c.decision,id:"decision:32",result:"REJECT"}]}).code,"CONFLICTING_DECISIONS");assert.equal(auth(c,{decisions:[{...c.decision,economicAssessmentRef:c.decision.experimentProposalRef}]}).code,"DECISION_CHAIN_MISMATCH");assert.equal(auth(c,{decisions:[{...c.decision,result:"REVISE"}]}).code,"DECISION_DOES_NOT_AUTHORIZE")});
test("governance authority is explicitly human and Economics cannot self-authorize",()=>{const c=chain();assert.throws(()=>C.GovernedDecision({...c.decision,authorityType:"AI_AGENT"}),/requires_human_authority/);assert.throws(()=>C.GovernedDecision({...c.decision,decisionMakerRef:"ECONOMICS",authorityType:"AI_AGENT"}),/requires_human_authority/)});
