"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const E=require("../src/business-os/economics");
const ORG="org:sensitivity",WORK="work:sensitivity",PRODUCT="product:sensitivity",CAMPAIGN="campaign:sensitivity",AT="2035-03-01T00:00:00.000Z",PERIOD={start:"2035-02-01T00:00:00.000Z",end:AT};
const amounts={REVENUE:100000,REFUND:5000,DISCOUNT:0,ACQUISITION_COST:20000,PAYMENT_FEE:3000,FULFILLMENT_COST:30000,FIXED_COST:10000};
const coverage={requiredCostCategories:["ACQUISITION_COST","PAYMENT_FEE","FULFILLMENT_COST","FIXED_COST"],units:100,newCustomers:20};
function input(category,{amount=amounts[category],classification="ACTUAL"}={}){return E.EconomicInput({id:`input:${category}`,organizationId:ORG,productRef:PRODUCT,campaignRef:CAMPAIGN,currency:"USD",reportingPeriod:PERIOD,version:1,category,classification,amountMinor:classification==="UNKNOWN"?null:amount,assumptions:classification==="ESTIMATED"?["Estimated baseline."]:[],evidenceRefs:classification==="UNKNOWN"?[]:[`evidence:${category}`],source:{system:"TEST_LEDGER",recordRef:`record:${category}`,recordVersion:1,payloadHash:`hash:${category}`,observedAt:AT}})}
function baseline({unknown,estimated}={}){return E.calculateEconomicAssessment({id:"assessment:baseline",version:4,workId:WORK,financialInputs:Object.keys(amounts).map(category=>input(category,{classification:category===unknown?"UNKNOWN":category===estimated?"ESTIMATED":"ACTUAL"})),coverage},{clock:()=>AT})}
function definition(base,{id="study:one",metric="contribution",type="ONE_WAY",axes,thresholds=[{label:"break-even contribution",value:0}],patch={}}={}){return{id,version:1,organizationId:ORG,workId:WORK,productRef:PRODUCT,campaignRef:CAMPAIGN,name:"Bounded sensitivity",createdBy:"user:economist",createdAt:AT,reportingPeriod:PERIOD,currency:"USD",engineVersion:E.ECONOMICS_ENGINE_VERSION,scenarioModelVersion:E.SCENARIO_MODEL_VERSION,policyVersion:E.SENSITIVITY_POLICY_VERSION,baselineAssessmentRef:E.baselineReference(base),targetMetric:metric,type,axes:axes||[{targetInputId:"input:ACQUISITION_COST",category:"ACQUISITION_COST",transformationType:"ABSOLUTE_REPLACEMENT",points:[10000,20000,30000],uncertainty:{kind:"EXPLICIT_BOUNDED_RANGE",rationale:"Supplier quote range.",evidenceRefs:["evidence:quote"]}}],thresholds,limitations:[],...patch}}
const run=(base,options)=>E.runSensitivityStudy({study:definition(base,options),baselineAssessment:base,coverage});

test("one-way replacement orchestrates immutable ECO-5A scenarios and ECO-2 assessments",()=>{const base=baseline(),snapshot=structuredClone(base),result=run(base);assert.deepEqual(result.points.map(x=>x.value),[42000,32000,22000]);assert.deepEqual(result.points.map(x=>x.changeFromBaseline.absolute),[10000,0,-10000]);assert.deepEqual(result.analysis,{status:"PARTIAL",minimum:22000,maximum:42000,absoluteSpread:20000,relativeSpreadBasisPoints:6250});assert.ok(result.points.every(x=>x.scenarioResult.kind==="EconomicScenarioResult"&&x.scenarioResult.assessment.engineVersion===E.ECONOMICS_ENGINE_VERSION));assert.deepEqual(base,snapshot);assert.equal(result.authorization,null);assert.equal(result.probabilityModel,null);assert.match(result.limitations.join(" "),/not prediction.*causal effect.*authorization.*optimization/)});
test("absolute delta and percentage points are canonical, deterministic, and order independent",()=>{const base=baseline(),delta={targetInputId:"input:ACQUISITION_COST",category:"ACQUISITION_COST",transformationType:"ABSOLUTE_DELTA",points:[5000,-5000,0]},a=run(base,{axes:[delta]}),b=run(structuredClone(base),{axes:[{...delta,points:[0,5000,-5000]}]});assert.deepEqual(a,b);assert.deepEqual(a.study.axes[0].points,[-5000,0,5000]);const pct=run(base,{axes:[{...delta,transformationType:"PERCENTAGE_DELTA",points:[-3000,0,3000]}]});assert.deepEqual(pct.points.map(x=>x.value),[38000,32000,26000]);assert.notEqual(a.studyDigest,pct.studyDigest)});
test("duplicate and unsafe points, invalid negative results, and hidden extra axes fail closed",()=>{const base=baseline();for(const axes of [[{targetInputId:"input:ACQUISITION_COST",category:"ACQUISITION_COST",transformationType:"ABSOLUTE_REPLACEMENT",points:[1,1]}],[{targetInputId:"input:ACQUISITION_COST",category:"ACQUISITION_COST",transformationType:"ABSOLUTE_DELTA",points:[Number.MAX_SAFE_INTEGER]}],[{targetInputId:"input:ACQUISITION_COST",category:"ACQUISITION_COST",transformationType:"ABSOLUTE_DELTA",points:[-20001]}],[{targetInputId:"input:ACQUISITION_COST",category:"ACQUISITION_COST",transformationType:"ABSOLUTE_REPLACEMENT",points:[1]},{targetInputId:"input:REVENUE",category:"REVENUE",transformationType:"ABSOLUTE_REPLACEMENT",points:[1]}]])assert.throws(()=>run(base,{axes}),/invalid_economic_sensitivity/)});
test("UNKNOWN relative changes remain unresolved; replacement establishes only hypothetical estimated evidence",()=>{const base=baseline({unknown:"ACQUISITION_COST"}),relative=run(base,{axes:[{targetInputId:"input:ACQUISITION_COST",category:"ACQUISITION_COST",transformationType:"PERCENTAGE_DELTA",points:[1000]}]});assert.deepEqual([relative.points[0].status,relative.points[0].value,relative.points[0].changeFromBaseline.absolute],["UNKNOWN",null,null]);const replacement=run(base,{axes:[{targetInputId:"input:ACQUISITION_COST",category:"ACQUISITION_COST",transformationType:"ABSOLUTE_REPLACEMENT",points:[20000]}]});const changed=replacement.points[0].scenarioResult.scenarioInputs.find(x=>x.category==="ACQUISITION_COST");assert.equal(changed.classification,"ESTIMATED");assert.equal(changed.source.system,"SCENARIO_ASSUMPTION");assert.equal(replacement.points[0].status,"PARTIAL")});
test("PARTIAL and estimated status remain visible and unresolved dependencies are never interpolated",()=>{const estimated=run(baseline({estimated:"REVENUE"}));assert.ok(estimated.points.every(x=>x.status==="PARTIAL"));const unknown=run(baseline({unknown:"FULFILLMENT_COST"}));assert.ok(unknown.points.every(x=>x.status==="UNKNOWN"&&x.value===null));assert.equal(unknown.analysis.status,"UNKNOWN");assert.deepEqual(unknown.thresholdCrossings,[])});
test("exact baseline binding and every economic scope dimension fail closed",()=>{const base=baseline(),ref=E.baselineReference(base);for(const patch of [{organizationId:"other"},{workId:"other"},{productRef:"other"},{campaignRef:"other"},{currency:"EUR"},{reportingPeriod:{start:PERIOD.start,end:"2035-04-01T00:00:00.000Z"}},{baselineAssessmentRef:{...ref,assessmentId:"other"}},{baselineAssessmentRef:{...ref,version:99}},{baselineAssessmentRef:{...ref,digest:"bad"}}])assert.throws(()=>run(base,{patch}),/invalid_economic_sensitivity/);const mutated=structuredClone(base);mutated.metrics.contribution.value++;assert.throws(()=>E.runSensitivityStudy({study:definition(base),baselineAssessment:mutated,coverage}),/baseline_binding/)});
test("study identity changes with range and metric while replay is canonical",()=>{const base=baseline(),a=run(base),replay=run(structuredClone(base)),range=run(base,{axes:[{targetInputId:"input:ACQUISITION_COST",category:"ACQUISITION_COST",transformationType:"ABSOLUTE_REPLACEMENT",points:[10000,40000]}]}),metric=run(base,{metric:"roi"});assert.deepEqual(a,replay);assert.notEqual(a.studyDigest,range.studyDigest);assert.notEqual(a.studyDigest,metric.studyDigest);assert.throws(()=>run(base,{metric:"madeUpMetric"}),/unsupported_target_metric/)});
test("driver comparison is contextual, range-preserving, and compatible-only",()=>{const base=baseline(),cac=run(base),fee=run(base,{id:"study:fee",axes:[{targetInputId:"input:PAYMENT_FEE",category:"PAYMENT_FEE",transformationType:"ABSOLUTE_REPLACEMENT",points:[2000,4000]}]}),comparison=E.compareSensitivityDrivers([fee,cac]);assert.equal(comparison.drivers[0].targetInputId,"input:ACQUISITION_COST");assert.deepEqual(comparison.drivers[0].testedRange.points,[10000,20000,30000]);assert.match(comparison.interpretation,/explicitly supplied tested ranges.*not universal/);assert.throws(()=>E.compareSensitivityDrivers([cac,run(base,{metric:"roi"})]),/incompatible_comparison/)});
test("breakpoints report exact tested thresholds or bounded intervals without invented precision",()=>{const base=baseline(),axis={targetInputId:"input:ACQUISITION_COST",category:"ACQUISITION_COST",transformationType:"ABSOLUTE_REPLACEMENT",points:[30000,52000,60000]},result=run(base,{axes:[axis]});assert.deepEqual(result.thresholdCrossings.map(x=>x.type),["EXACT_TESTED_POINT"]);const between=run(base,{axes:[{...axis,points:[50000,60000]}]});assert.equal(between.thresholdCrossings[0].type,"BETWEEN_TESTED_POINTS");assert.equal(between.thresholdCrossings[0].exactCrossing,null)});
test("bounded uncertainty is explicit evidence context, never probability or observed fact",()=>{const result=run(baseline());assert.equal(result.uncertainty[0].definition.kind,"EXPLICIT_BOUNDED_RANGE");assert.equal(result.uncertainty[0].definition.probabilityModel,null);assert.deepEqual(result.uncertainty[0].definition.evidenceRefs,["evidence:quote"]);assert.ok(!JSON.stringify(result).includes('"probability":'))});
test("bounded two-way matrix uses two declared ECO-5A overrides with canonical order",()=>{const base=baseline(),axes=[{targetInputId:"input:REVENUE",category:"REVENUE",transformationType:"PERCENTAGE_DELTA",points:[1000,-1000]},{targetInputId:"input:ACQUISITION_COST",category:"ACQUISITION_COST",transformationType:"ABSOLUTE_REPLACEMENT",points:[30000,10000]}],a=run(base,{type:"TWO_WAY",axes}),b=run(base,{type:"TWO_WAY",axes:[...axes].reverse()});assert.equal(a.points.length,4);assert.deepEqual(a,b);assert.ok(a.points.every(x=>x.scenarioResult.scenario.overrides.length===2));assert.throws(()=>run(base,{type:"TWO_WAY",axes:[axes[0],{...axes[0],points:[0]}]}),/duplicate_axis_target/)});
test("sensitivity cannot mutate historical reconciliation, authorize, scale, Scout, or Learning",()=>{const history=Object.freeze([{kind:"EconomicReconciliation",id:"history"}]),scout=Object.freeze({status:"unchanged"}),learning=Object.freeze({lessons:[]}),result=run(baseline());assert.deepEqual(history,[{kind:"EconomicReconciliation",id:"history"}]);assert.deepEqual(scout,{status:"unchanged"});assert.deepEqual(learning,{lessons:[]});assert.equal(result.executionAuthorization,undefined);assert.equal(result.scalingDecision,undefined);assert.throws(()=>{result.points[0].value=0},TypeError)});
