"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const E=require("../src/business-os/economics");
const ORG="org:capital",AT="2036-02-01T00:00:00.000Z",PERIOD={start:"2036-01-01T00:00:00.000Z",end:AT};
const amounts={REVENUE:100000,REFUND:5000,DISCOUNT:0,ACQUISITION_COST:20000,PAYMENT_FEE:3000,FULFILLMENT_COST:30000,FIXED_COST:10000};
const coverage={requiredCostCategories:["ACQUISITION_COST","PAYMENT_FEE","FULFILLMENT_COST","FIXED_COST"],units:100,newCustomers:20};
function assessment(id,work,product,campaign,{unknown,estimated,revenue=100000}={}){const inputs=Object.keys(amounts).map(category=>E.EconomicInput({id:`${id}:input:${category}`,organizationId:ORG,productRef:product,campaignRef:campaign,currency:"USD",reportingPeriod:PERIOD,version:1,category,classification:category===unknown?"UNKNOWN":category===estimated?"ESTIMATED":"ACTUAL",amountMinor:category===unknown?null:category==="REVENUE"?revenue:amounts[category],assumptions:category===estimated?["Estimate."]:[],evidenceRefs:category===unknown?[]:[`${id}:evidence:${category}`],source:{system:"TEST",recordRef:`${id}:record:${category}`,observedAt:AT}}));return E.calculateEconomicAssessment({id,version:2,workId:work,financialInputs:inputs,coverage},{clock:()=>AT})}
const a=assessment("assessment:a","work:capital","product:a","campaign:a"),b=assessment("assessment:b","work:capital","product:b","campaign:b",{revenue:120000});
function candidate(id,base,capital,patch={}){return{id,organizationId:ORG,workId:base.workId,productRef:base.productRef,campaignRef:base.campaignRef,economicAssessmentRef:E.capitalAllocationAssessmentReference(base),requiredCapitalMinor:capital,fundingSemantics:"ALL_OR_NOTHING",economicsSource:"BASELINE",scenarioRef:null,sensitivityRef:null,...patch}}
function definition({candidates=[candidate("a",a,40000)],constraints=[{id:"total",type:"TOTAL_CAPITAL_LIMIT"}],capital=100000,patch={}}={}){return{id:"capital-study",version:1,organizationId:ORG,workId:"work:capital",name:"Capital study",allocationPeriod:PERIOD,currency:"USD",availableCapitalMinor:capital,candidates,constraints,policyVersion:E.CAPITAL_ALLOCATION_POLICY_VERSION,engineVersion:E.ECONOMICS_ENGINE_VERSION,createdAt:AT,createdBy:"user:economist",limitations:[],...patch}}
const run=(options={})=>E.runCapitalAllocationStudy({study:definition(options),economicAssessments:options.assessments||[a,b],scenarioResults:options.scenarios||[],sensitivityResults:options.sensitivities||[]});

test("single and multiple all-or-nothing alternatives report modeled capital exactly",()=>{const one=run();assert.equal(one.status,"FEASIBLE");assert.deepEqual(one.feasibleAlternatives.map(x=>x.modeledCapitalCommittedMinor),[0,40000]);const multiple=run({candidates:[candidate("a",a,40000),candidate("b",b,60000)]});const full=multiple.feasibleAlternatives.find(x=>x.includedCandidateIds.length===2);assert.equal(full.modeledCapitalRemainingMinor,0);assert.equal(full.modeledUtilizationBasisPoints,10000);assert.equal(full.economicProfile.metrics.contribution.value,a.metrics.contribution.value+b.metrics.contribution.value)});
test("capital remaining and candidate exceeding capital are factual, diagnosed outcomes",()=>{const result=run({candidates:[candidate("a",a,40001)],capital:40000});assert.equal(result.feasibleAlternatives.length,1);assert.equal(result.feasibleAlternatives[0].modeledCapitalRemainingMinor,40000);assert.deepEqual(result.rejectedAlternatives[0].failedConstraints,[{constraintId:"AVAILABLE_CAPITAL",reason:"TOTAL_CAPITAL_EXCEEDED"}])});
test("required candidates are never silently dropped and can make a study infeasible",()=>{const required={id:"required-a",type:"REQUIRED",candidateId:"a"},ok=run({constraints:[required]});assert.ok(ok.feasibleAlternatives.every(x=>x.includedCandidateIds.includes("a")));const impossible=run({capital:39999,constraints:[required]});assert.equal(impossible.status,"INFEASIBLE");assert.equal(impossible.feasibleAlternatives.length,0);assert.ok(impossible.rejectedAlternatives.every(x=>x.failedConstraints.length))});
test("mutual exclusion and dependency constraints accept only satisfying combinations",()=>{const candidates=[candidate("a",a,40000),candidate("b",b,50000)],exclusive=run({candidates,constraints:[{id:"exclusive",type:"MUTUALLY_EXCLUSIVE",candidateIds:["b","a"]}]});assert.ok(exclusive.feasibleAlternatives.every(x=>x.includedCandidateIds.length<2));const dependency=run({candidates,constraints:[{id:"dep",type:"DEPENDENCY",candidateId:"b",dependsOnCandidateId:"a"}]});assert.ok(dependency.feasibleAlternatives.some(x=>x.includedCandidateIds.join() === "a,b"));assert.ok(!dependency.feasibleAlternatives.some(x=>x.includedCandidateIds.join() === "b"));assert.match(JSON.stringify(dependency.rejectedAlternatives),/DEPENDENCY_MISSING/)});
test("unknown targets, self dependencies, cycles, duplicates and malformed graphs fail closed",()=>{for(const constraints of [[{id:"d",type:"DEPENDENCY",candidateId:"a",dependsOnCandidateId:"missing"}],[{id:"d",type:"DEPENDENCY",candidateId:"a",dependsOnCandidateId:"a"}],[{id:"d1",type:"DEPENDENCY",candidateId:"a",dependsOnCandidateId:"b"},{id:"d2",type:"DEPENDENCY",candidateId:"b",dependsOnCandidateId:"a"}]])assert.throws(()=>run({candidates:[candidate("a",a,1),candidate("b",b,1)],constraints}),/invalid_capital_allocation/);assert.throws(()=>run({candidates:[candidate("a",a,1),candidate("a",b,1)]}),/duplicate/);assert.throws(()=>run({constraints:[{id:"x",type:"REQUIRED",candidateId:"a"},{id:"x",type:"REQUIRED",candidateId:"a"}]}),/duplicate/)});
test("minimum and maximum commitments constrain fixed commitments without inventing partial funding",()=>{const constraints=[{id:"min",type:"MINIMUM_COMMITMENT",candidateId:"a",amountMinor:40000},{id:"max",type:"MAXIMUM_COMMITMENT",candidateId:"a",amountMinor:40000}];assert.equal(run({constraints}).feasibleAlternatives.length,2);assert.equal(run({constraints:[{...constraints[0],amountMinor:40001}]}).feasibleAlternatives.length,1);assert.equal(run({constraints:[{...constraints[1],amountMinor:39999}]}).feasibleAlternatives.length,1)});
test("assessment identity, version, digest, engine and every scope dimension bind exactly",()=>{const base=candidate("a",a,1);for(const ref of [{...base.economicAssessmentRef,assessmentId:"wrong"},{...base.economicAssessmentRef,version:99},{...base.economicAssessmentRef,digest:"wrong"},{...base.economicAssessmentRef,engineVersion:"wrong"}])assert.throws(()=>run({candidates:[{...base,economicAssessmentRef:ref}]}),/assessment/);for(const patch of [{organizationId:"other"},{workId:"other"},{productRef:"other"},{campaignRef:"other"}])assert.throws(()=>run({candidates:[{...base,...patch}]}),/scope|identity/);assert.throws(()=>run({patch:{currency:"EUR"}}),/currency/);assert.throws(()=>run({patch:{allocationPeriod:{start:PERIOD.start,end:"2036-03-01T00:00:00.000Z"}}}),/reporting_period/);const mutated=structuredClone(a);mutated.metrics.contribution.value++;assert.throws(()=>run({assessments:[mutated,b]}),/assessment_binding/)});
test("unsafe, negative, unknown and overflowing capital fail closed",()=>{for(const capital of [-1,Number.MAX_SAFE_INTEGER+1,null])assert.throws(()=>run({capital}),/available_capital/);for(const requiredCapitalMinor of [-1,Number.MAX_SAFE_INTEGER+1,null])assert.throws(()=>run({candidates:[{...candidate("a",a,1),requiredCapitalMinor}]}),/required_capital/);assert.throws(()=>run({capital:Number.MAX_SAFE_INTEGER,candidates:[candidate("a",a,Number.MAX_SAFE_INTEGER),candidate("b",b,1)]}),/capital_overflow/)});
test("ordering and replay are deterministic",()=>{const candidates=[candidate("a",a,40000),candidate("b",b,50000)],constraints=[{id:"z",type:"DEPENDENCY",candidateId:"b",dependsOnCandidateId:"a"},{id:"a",type:"TOTAL_CAPITAL_LIMIT"}],x=run({candidates,constraints}),y=run({candidates:[...candidates].reverse(),constraints:[...constraints].reverse()});assert.deepEqual(x,y);assert.deepEqual(x,run({candidates,constraints}))});
test("empty candidate set is technically feasible but not economically useful or zero economics",()=>{const result=run({candidates:[],assessments:[]});assert.equal(result.status,"FEASIBLE");assert.equal(result.economicUsefulness,"NO_CANDIDATES");assert.equal(result.feasibleAlternatives.length,1);assert.equal(result.feasibleAlternatives[0].economicProfile.metrics.contribution.status,"NOT_APPLICABLE");assert.equal(result.feasibleAlternatives[0].economicProfile.metrics.contribution.value,null)});
test("required and mutually exclusive conflict produces truthful no-feasible result",()=>{const candidates=[candidate("a",a,1),candidate("b",b,1)],constraints=[{id:"ra",type:"REQUIRED",candidateId:"a"},{id:"rb",type:"REQUIRED",candidateId:"b"},{id:"x",type:"MUTUALLY_EXCLUSIVE",candidateIds:["a","b"]}],result=run({candidates,constraints});assert.equal(result.status,"INFEASIBLE");assert.equal(result.feasibleAlternatives.length,0);assert.equal(result.diagnostics[0].code,"NO_FEASIBLE_ALTERNATIVES")});
test("search is exhaustively bounded at twelve candidates and fails one beyond",()=>{const candidates=Array.from({length:12},(_,i)=>candidate(`c${String(i).padStart(2,"0")}`,a,1));assert.equal(run({candidates,assessments:[a]}).feasibleAlternatives.length,4096);assert.throws(()=>run({candidates:[...candidates,candidate("c12",a,1)],assessments:[a]}),/candidate_limit/)});
test("compatible additive metrics retain PARTIAL and UNKNOWN; ratios are never aggregated",()=>{const partial=assessment("assessment:partial","work:capital","product:partial",null,{estimated:"REVENUE"}),unknown=assessment("assessment:unknown","work:capital","product:unknown",null,{unknown:"FULFILLMENT_COST"});const result=run({candidates:[candidate("p",partial,1),candidate("u",unknown,1)],assessments:[partial,unknown]});const full=result.feasibleAlternatives.find(x=>x.includedCandidateIds.length===2).economicProfile;assert.equal(full.metrics.grossRevenue.status,"PARTIAL");assert.equal(full.metrics.contribution.status,"UNKNOWN");assert.equal(full.metrics.contribution.value,null);assert.ok(full.nonAggregatedMetrics.includes("roi")&&full.nonAggregatedMetrics.includes("roas")&&full.nonAggregatedMetrics.includes("contributionMargin"));assert.equal(full.metrics.roi,undefined)});
test("explicit scenario economics remain hypothetical and exact-lineage bound",()=>{const override=E.deriveScenarioOverride(a.financialInputs.find(x=>x.category==="REVENUE"),{transformationType:"ABSOLUTE_REPLACEMENT",transformationAmount:150000,reason:"Explicit hypothetical."}),scenario=E.createEconomicScenarioResult({scenario:{id:"scenario:a",version:1,organizationId:ORG,workId:a.workId,productRef:a.productRef,campaignRef:a.campaignRef,name:"Upside",description:"Hypothesis",createdBy:"user:economist",createdAt:AT,reportingPeriod:PERIOD,currency:"USD",engineVersion:E.ECONOMICS_ENGINE_VERSION,policyVersion:E.SCENARIO_POLICY_VERSION,baselineAssessmentRef:E.baselineReference(a),type:"UPSIDE",status:"DEFINED",assumptions:["Explicit hypothetical."],overrides:[override]},baselineAssessment:a,coverage});const c=candidate("a",a,1,{economicsSource:"SCENARIO",scenarioRef:E.capitalAllocationScenarioReference(scenario)}),result=run({candidates:[c],scenarios:[scenario]});const context=result.feasibleAlternatives[1].economicProfile.candidateEconomics[0];assert.equal(context.source,"SCENARIO");assert.equal(context.assessmentId,scenario.assessment.id);assert.match(result.limitations.join(" "),/hypothetical scenarios.*not predictions/);assert.throws(()=>run({candidates:[{...c,scenarioRef:{...c.scenarioRef,digest:"wrong"}}],scenarios:[scenario]}),/scenario_binding/)});
test("sensitivity is preserved descriptively without probability, score, ranking or preference",()=>{const study={id:"sensitivity:a",version:1,organizationId:ORG,workId:a.workId,productRef:a.productRef,campaignRef:a.campaignRef,name:"Range",createdBy:"user:economist",createdAt:AT,reportingPeriod:PERIOD,currency:"USD",engineVersion:E.ECONOMICS_ENGINE_VERSION,scenarioModelVersion:E.SCENARIO_MODEL_VERSION,policyVersion:E.SENSITIVITY_POLICY_VERSION,baselineAssessmentRef:E.baselineReference(a),targetMetric:"contribution",type:"ONE_WAY",axes:[{targetInputId:"assessment:a:input:ACQUISITION_COST",category:"ACQUISITION_COST",transformationType:"ABSOLUTE_REPLACEMENT",points:[10000,30000],uncertainty:{kind:"EXPLICIT_BOUNDED_RANGE",rationale:"Quote range.",evidenceRefs:["quote"]}}],thresholds:[],limitations:[]},sensitivity=E.runSensitivityStudy({study,baselineAssessment:a,coverage}),c=candidate("a",a,1,{sensitivityRef:E.capitalAllocationSensitivityReference(sensitivity)}),result=run({candidates:[c],sensitivities:[sensitivity]});assert.equal(result.feasibleAlternatives[1].economicProfile.candidateEconomics[0].uncertaintyContext.analysis.absoluteSpread,20000);assert.throws(()=>run({candidates:[{...c,sensitivityRef:{...c.sensitivityRef,digest:"bad"}}],sensitivities:[sensitivity]}),/sensitivity_binding/);for(const forbidden of ["recommendedAlternative","bestAlternative","optimalPortfolio","capitalScore","investmentScore","priorityScore","probabilityModel"])assert.ok(!JSON.stringify(result).includes(forbidden))});
test("all supplied source artifacts and unrelated historical/governance state remain immutable",()=>{const assessments=[a,b],snapshot=structuredClone(assessments),reconciliation=Object.freeze({kind:"EconomicReconciliation",status:"RECONCILED"}),actuals=Object.freeze([{amountMinor:1}]),governance=Object.freeze({decision:"unchanged"}),result=run({candidates:[candidate("a",a,1),candidate("b",b,1)],assessments});assert.deepEqual(assessments,snapshot);assert.deepEqual(reconciliation,{kind:"EconomicReconciliation",status:"RECONCILED"});assert.deepEqual(actuals,[{amountMinor:1}]);assert.deepEqual(governance,{decision:"unchanged"});assert.deepEqual({authorization:result.authorization,reservation:result.reservation,spend:result.spend,execution:result.execution},{authorization:null,reservation:null,spend:null,execution:null});assert.throws(()=>{result.status="APPROVED"},TypeError)});


test("portfolio aggregation preserves INVALID instead of softening it to UNKNOWN",()=>{const invalid=structuredClone(a);invalid.id="assessment:invalid";invalid.productRef="product:invalid";invalid.metrics.contribution.status="INVALID";invalid.metrics.contribution.value=null;invalid.metrics.contribution.missingInputs=[];const c={...candidate("invalid",invalid,1),economicAssessmentRef:E.capitalAllocationAssessmentReference(invalid)};const result=run({candidates:[c],assessments:[invalid]});const profile=result.feasibleAlternatives.find(x=>x.includedCandidateIds.length===1).economicProfile;assert.equal(profile.metrics.contribution.status,"INVALID");assert.equal(profile.metrics.contribution.value,null);assert.equal(profile.status,"INVALID")});
