"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const S=require("../src/business-os/sales");
const need=()=>S.CustomerNeed({id:"need-1",organizationId:"org-1",workId:"work-1",statement:"Need a governed service",evidenceRefs:["ev-1"],unknowns:[],version:1});
test("SALES-1 contracts are immutable and deterministic",()=>{const n=need(),a=S.artifactRef(n),b=S.artifactRef(need());assert.deepEqual(a,b);assert(Object.isFrozen(n));assert(Object.isFrozen(a))});
test("commercial opportunity binds organization/work scoped source and needs",()=>{const n=need(),nr=S.artifactRef(n),src={artifactType:"AnalystAssessment",artifactId:"aa-1",version:1,digest:"d1",organizationId:"org-1",workId:"work-1"};const o=S.CommercialOpportunity({id:"opp-1",organizationId:"org-1",workId:"work-1",sourceType:"ANALYST",sourceRef:src,needRefs:[nr],evidenceRefs:["ev-1"],version:1});assert.equal(o.kind,"CommercialOpportunity");assert.throws(()=>S.CommercialOpportunity({...o,id:"opp-2",sourceRef:{...src,organizationId:"other"}}),/source_scope/)});
test("qualification input requires exact opportunity digest binding",()=>{const n=need(),src={artifactType:"AnalystAssessment",artifactId:"aa-1",version:1,digest:"d1",organizationId:"org-1",workId:"work-1"},o=S.CommercialOpportunity({id:"opp-1",organizationId:"org-1",workId:"work-1",sourceType:"ANALYST",sourceRef:src,needRefs:[S.artifactRef(n)],evidenceRefs:[],version:1}),r=S.artifactRef(o);assert.equal(S.QualificationInput({id:"qi-1",organizationId:"org-1",workId:"work-1",opportunityRef:r,opportunityDigest:r.digest,evidenceRefs:[],version:1}).kind,"QualificationInput");assert.throws(()=>S.QualificationInput({id:"qi-2",organizationId:"org-1",workId:"work-1",opportunityRef:r,opportunityDigest:"tampered",evidenceRefs:[],version:1}),/opportunity_digest/)});
test("proposal reference cannot claim acceptance payment or fulfillment",()=>{const base={id:"pr-1",organizationId:"org-1",workId:"work-1",proposalId:"p-1",proposalVersion:1,proposalDigest:"d",status:"PROPOSED",accepted:false,paymentVerified:false,fulfilled:false,version:1};assert.equal(S.ProposalReference(base).status,"PROPOSED");for(const k of ["accepted","paymentVerified","fulfilled"])assert.throws(()=>S.ProposalReference({...base,[k]:true}),/authority_flags/)});
test("artifact refs change when canonical artifact content changes",()=>{const a=S.artifactRef(need()),b=S.artifactRef(S.CustomerNeed({...need(),statement:"Changed need"}));assert.notEqual(a.digest,b.digest)});
