"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const Scout=require("../src/business-os/scout/contracts");
const Analyst=require("../src/business-os/analyst/assessment");
const EM=require("../src/business-os/experiment-manager");
const O=require("../src/business-os/organization/contracts");
const W=require("../src/business-os/organization/economic-workflow");
const E=require("../src/business-os/economics");

const ORG="org:eco6b",WORK="work:eco6b",PRODUCT="product:alpha",CAMPAIGN="campaign:alpha";
const EXPECTED_AT="2038-02-01T00:00:00.000Z",ACTUAL_AT="2038-03-02T00:00:00.000Z",RECONCILED_AT="2038-03-03T00:00:00.000Z";
const PERIOD={start:"2038-02-01T00:00:00.000Z",end:"2038-03-01T00:00:00.000Z"};
const categories=["REVENUE","REFUND","DISCOUNT","ACQUISITION_COST","FULFILLMENT_COST"];
const amounts={REVENUE:120000,REFUND:5000,DISCOUNT:0,ACQUISITION_COST:25000,FULFILLMENT_COST:30000};
function inputs(prefix,classification="ACTUAL",product=PRODUCT,values=amounts){return categories.map(category=>E.EconomicInput({id:`${prefix}:input:${category}`,organizationId:ORG,productRef:product,campaignRef:CAMPAIGN,currency:"USD",reportingPeriod:PERIOD,version:1,category,classification,amountMinor:values[category],assumptions:classification==="ESTIMATED"?["Pre-experiment estimate."]:[],evidenceRefs:[`${prefix}:evidence:${category}`],source:{system:"ECO6B_FIXTURE",recordRef:`${prefix}:record:${category}`,recordVersion:1,payloadHash:`${prefix}:hash:${category}`,observedAt:classification==="ACTUAL"?"2038-02-28T00:00:00.000Z":EXPECTED_AT}}))}
function evidence(prefix,product=PRODUCT,values=amounts){return categories.map(category=>E.EconomicEvidenceRecord({id:`${prefix}:evidence:${category}`,evidenceType:"OBSERVED_FACT",source:{type:"ACCOUNTING_SYSTEM",system:"ECO6B_FIXTURE",recordRef:`${prefix}:record:${category}`,availability:"AVAILABLE"},actorId:"books:controller",recordedAt:ACTUAL_AT,observedAt:"2038-02-28T00:00:00.000Z",version:1,scope:{organizationId:ORG,productRef:product,campaignRef:CAMPAIGN,currency:"USD",reportingPeriod:PERIOD},claim:{category,classification:"ACTUAL",amountMinor:values[category]},payloadHash:`${prefix}:hash:${category}`,supersededBy:null}))}
const coverage={requiredCostCategories:["ACQUISITION_COST","FULFILLMENT_COST"],units:100,newCustomers:20};
function actualAssessment(prefix="actual",product=PRODUCT,values=amounts){return E.calculateEvidenceBackedAssessment({id:`assessment:${prefix}`,workId:WORK,financialInputs:inputs(prefix,"ACTUAL",product,values),coverage},{clock:()=>ACTUAL_AT,asOf:ACTUAL_AT,evidenceRecords:evidence(prefix,product,values),freshnessPolicies:categories.map(category=>({id:`fresh:${category}`,category,sourceType:"ACCOUNTING_SYSTEM",mode:"HISTORICAL"}))})}
function expectedAssessment(){const a=E.calculateEconomicAssessment({id:"assessment:expected",workId:WORK,financialInputs:inputs("expected","ESTIMATED"),coverage},{clock:()=>EXPECTED_AT});return Object.freeze({...a,provenance:{asOf:EXPECTED_AT,inputs:a.financialInputs.map(x=>({inputId:x.id,accepted:true,trustState:"TRUSTED"}))}})}
function build(){
 const candidate=Scout.OpportunityCandidate({id:"candidate:eco6b",organizationId:ORG,audience:"fitness buyers",problem:"Need attributable acquisition economics",motivation:"Bound a test",customerLanguage:["show value"],productRefs:[PRODUCT],requiredCapabilityRefs:["capability:experiment"],productReadiness:"OPERATIONAL",evidenceRefs:["evidence:opportunity"],contradictions:[],unknowns:[],sourceDiversity:2,intentClassification:"EXPLICIT",geography:"US",recency:"CURRENT",confidence:.9,confidenceBasis:["evidence:opportunity"],historicalOutcomeSummaryRefs:[],recommendedAnalystQuestion:"Can a bounded experiment resolve value?",limitations:["Fixture evidence only."],status:"CANDIDATE",version:1});
 const analyst=Analyst.createAnalystAssessment({id:"analyst:eco6b",organizationId:ORG,candidateRef:candidate.id,inputArtifactRefs:[candidate.id],evidence:[{classification:"VERIFIED_OUTCOME",evidenceRefs:["evidence:opportunity"]}],problemEvidence:.9,productFit:.9,readiness:.9,outcomeStrength:.8,confidence:.8,productReadiness:"OPERATIONAL"});
 const opportunityArtifact=W.sealArtifact({id:candidate.id,artifactType:"OpportunityCandidate",organizationId:ORG,workId:WORK,version:1,producingRoleId:"SMART_SCOUT",status:"ACCEPTED",createdAt:EXPECTED_AT,candidate});
 const analystArtifact=W.sealArtifact({id:analyst.id,artifactType:"AnalystAssessment",organizationId:ORG,workId:WORK,version:1,producingRoleId:"SMART_ANALYST",status:"ACCEPTED",createdAt:EXPECTED_AT,assessment:analyst,upstreamRefs:[W.reference(opportunityArtifact)]});
 let current=EXPECTED_AT,decision;
 const authority={verify({proposal,budgetCeiling}){assert.equal(proposal.id,"proposal:eco6b");assert.equal(budgetCeiling,500);assert.ok(decision);return{actorType:"HUMAN",actorId:"human:owner",authorityRef:"grant:owner",scope:EM.APPROVAL_SCOPE,decisionRef:decision.id,evidenceRefs:["evidence:authenticated-human"]}},check(approval,proposal){return approval.actorType==="HUMAN"&&approval.decisionRef===decision.id&&approval.proposalDigest===EM.proposalDigest(proposal)&&decision.result==="APPROVE"}};
 const manager=EM.createExperimentManager({organizationId:ORG,clock:()=>new Date(current),approvalAuthority:authority});
 const proposal=manager.propose({id:"proposal:eco6b",workId:WORK,question:"Does the bounded offer generate qualified demand?",hypothesis:"The offer generates demand.",variable:"offer",successMetric:"qualified_interest",failureMetric:"rejection",costCeiling:500,minimumUsefulEvidence:1,riskCeiling:"LOW",boundary:"INTERNAL",motivatingEvidenceRefs:[analyst.id],requiredAuthorityRefs:["grant:owner"],stopConditions:["technical_failure"]});
 const proposalArtifact=W.sealArtifact({id:proposal.id,artifactType:"ExperimentProposal",organizationId:ORG,workId:WORK,version:proposal.version,producingRoleId:"EXPERIMENT_MANAGER",status:"PROPOSED",createdAt:proposal.createdAt,managerProposalDigest:EM.proposalDigest(proposal),upstreamRefs:[W.reference(analystArtifact)]});
 const expected=expectedAssessment();
 const expectedArtifact=W.sealArtifact({id:"economic:expected",artifactType:"EconomicAssessment",organizationId:ORG,workId:WORK,version:1,producingRoleId:"ECONOMICS",status:"ACCEPTED",createdAt:EXPECTED_AT,assessmentId:expected.id,assessmentDigest:E.economicArtifactDigest(expected),disposition:"CONTINUE",provenanceStatus:"TRUSTED",upstreamRefs:[W.reference(proposalArtifact)]});
 const artifacts=[opportunityArtifact,analystArtifact,proposalArtifact,expectedArtifact];
 decision=W.createGovernedDecision({id:"decision:eco6b",organizationId:ORG,workId:WORK,decisionType:"AUTHORIZE_EXPERIMENT",result:"APPROVE",economicAssessmentRef:W.reference(expectedArtifact),experimentProposalRef:W.reference(proposalArtifact),chainRefs:artifacts.map(W.reference),decidedAt:EXPECTED_AT,decisionMakerRef:"human:owner",authorityRef:"grant:owner",authorityType:"HUMAN",authorizationScope:"EXPERIMENT_EXECUTION",conditions:[],reason:"Human reviewed the exact chain.",version:1});
 const authorization=W.authorizeExecution({organizationId:ORG,workId:WORK,workflowState:"APPROVED",artifacts,decisions:[decision],now:EXPECTED_AT});
 const approval=manager.approve({proposalId:proposal.id,proposalVersion:proposal.version,budgetCeiling:500},Object.freeze({authenticated:true}));
 const started=manager.start({proposalId:proposal.id,proposalVersion:proposal.version,approvalRef:approval.id,budget:500,boundary:"INTERNAL",idempotencyKey:"eco6b-run"});
 manager.measure({runRef:started.id,metric:"qualified_interest",value:1,sampleRef:"sample:one",evidenceRefs:["evidence:experiment"],observedAt:EXPECTED_AT});
 const experimentResult=manager.complete({runRef:started.id,workId:WORK,evidenceRefs:["evidence:experiment"]});
 const run=manager.getRun(started.id);current=ACTUAL_AT;
 const actual=actualAssessment(),actualArtifact=W.sealArtifact({id:"economic:actual",artifactType:"EconomicAssessment",organizationId:ORG,workId:WORK,version:1,producingRoleId:"ECONOMICS",status:"ACCEPTED",createdAt:ACTUAL_AT,assessmentId:actual.id,assessmentDigest:E.economicArtifactDigest(actual),upstreamRefs:[{artifactType:"ExperimentResult",artifactId:experimentResult.id,version:1,digest:E.economicArtifactDigest(experimentResult),organizationId:ORG,workId:WORK}]});
 const reconciliation=E.createEconomicReconciliation({organizationId:ORG,workId:WORK,proposalArtifact,baselineArtifact:expectedArtifact,baselineAssessment:expected,decision,approval,run,experimentResult,actualArtifact,actualAssessment:actual,authorizedAmountMinor:50000,reservedAmountMinor:50000,asOf:ACTUAL_AT},{clock:()=>RECONCILED_AT,validateExperimentResult:manager.validateResult});
 const observation=E.createEconomicCalibrationObservation({metric:"grossRevenue",baselineArtifact:expectedArtifact,baselineAssessment:expected,decision,actualArtifact,actualAssessment:actual,reconciliation,reconciliationRef:{artifactId:reconciliation.id,version:reconciliation.version,digest:E.economicCalibrationDigest(reconciliation)}});
 return{candidate,analyst,artifacts,proposal,expected,expectedArtifact,decision,authorization,approval,run,experimentResult,manager,actual,actualArtifact,reconciliation,observation};
}

test("canonical governed workflow reaches authoritative actual reconciliation and descriptive calibration",()=>{const x=build();assert.equal(x.analyst.disposition,"ADVANCE_TO_EXPERIMENT");assert.equal(x.authorization.code,"AUTHORIZED");assert.equal(x.approval.decisionRef,x.decision.id);assert.equal(x.run.status,"COMPLETED");assert.equal(x.manager.validateResult(x.experimentResult).id,x.experimentResult.id);assert.equal(x.actual.actualValue.classification,"OBSERVED");assert.equal(x.reconciliation.experimentResultClass,"SUPPORTED");assert.equal(x.reconciliation.decisionDigest,E.economicCalibrationDigest(x.decision));assert.deepEqual([x.observation.comparisonStatus,x.observation.signedError.value,x.observation.direction], ["PARTIAL",null,"NOT_COMPARABLE"]);assert.equal(x.observation.authorization,undefined)});

test("economics, scenarios, and portfolios never manufacture governance or execution authority",()=>{const x=build();const rejected={...x.decision,result:"REJECT"};assert.equal(W.authorizeExecution({organizationId:ORG,workId:WORK,workflowState:"APPROVED",artifacts:x.artifacts,decisions:[rejected]}).authorized,false);assert.throws(()=>O.GovernedDecision({...x.decision,authorityType:"AI_AGENT"}),/human_authority/);assert.throws(()=>x.manager.start({proposalId:x.proposal.id,proposalVersion:1,approvalRef:"forged",budget:1,boundary:"INTERNAL",idempotencyKey:"unauthorized"}),/approved_matching_authority/);assert.equal(x.reconciliation.budget.actualSpendMinor,null)});

test("Experiment Manager authority rejects serialized, forged, mutated, cross-scope, and wrong-experiment results",()=>{const x=build();for(const changed of [{...x.experimentResult,id:"forged"},{...x.experimentResult,resultClass:"NOT_SUPPORTED"},{...x.experimentResult,organizationId:"org:other"},{...x.experimentResult,runRef:"run:other"},{...x.experimentResult,proposalRef:"proposal:other"}])assert.throws(()=>x.manager.validateResult(changed),/stored_experiment_result_required/);assert.throws(()=>E.createEconomicReconciliation({...baseReconciliation(x),experimentResult:{...x.experimentResult,id:"forged"}},{validateExperimentResult:x.manager.validateResult}),/not_authoritative/);assert.throws(()=>E.createEconomicReconciliation(baseReconciliation(x),{}),/validator_required/)});
function baseReconciliation(x){return{organizationId:ORG,workId:WORK,proposalArtifact:x.artifacts[2],baselineArtifact:x.expectedArtifact,baselineAssessment:x.expected,decision:x.decision,approval:x.approval,run:x.run,experimentResult:x.experimentResult,actualArtifact:x.actualArtifact,actualAssessment:x.actual,authorizedAmountMinor:50000,reservedAmountMinor:50000,asOf:ACTUAL_AT}}

test("cross-role substitutions and stale, conflicted, wrong-period, and wrong-currency actuals fail closed",()=>{const x=build(),base=baseReconciliation(x);for(const patch of [{approval:{...x.approval,decisionRef:"decision:other"}},{run:{...x.run,approvalRef:"approval:other"}},{actualAssessment:{...x.actual,organizationId:"org:other"}},{actualAssessment:{...x.actual,workId:"work:other"}},{actualAssessment:{...x.actual,currency:"EUR"}},{actualAssessment:{...x.actual,reportingPeriod:{...PERIOD,end:"2038-04-01T00:00:00.000Z"}}},{actualAssessment:{...x.actual,provenance:{...x.actual.provenance,inputs:x.actual.provenance.inputs.map((v,i)=>i? v:{...v,trustState:"STALE"})}}}])assert.throws(()=>E.createEconomicReconciliation({...base,...patch},{clock:()=>RECONCILED_AT,validateExperimentResult:x.manager.validateResult}),/invalid_economic_reconciliation/);const mutated={...x.reconciliation,status:"INVALID"};assert.throws(()=>E.createEconomicCalibrationObservation({metric:"grossRevenue",...base,reconciliation:mutated,reconciliationRef:{artifactId:x.reconciliation.id,version:1,digest:E.economicCalibrationDigest(x.reconciliation)}}),/reconciliation_binding/)});

test("EXPECTED, ACTUAL, UNKNOWN, PARTIAL, INVALID, and NOT_APPLICABLE remain distinct",()=>{const x=build();assert.ok(x.expected.financialInputs.every(v=>v.classification==="ESTIMATED"));assert.ok(x.actual.financialInputs.every(v=>v.classification==="ACTUAL"));assert.equal(x.expected.actualValue.classification,"UNKNOWN");const metric=(status,value=null,missingInputs=[])=>({status,value,unit:"MINOR_CURRENCY",missingInputs});assert.equal(E.compareEconomicMetric("grossRevenue",metric("UNKNOWN"),metric("CALCULATED",0)).comparisonStatus,"UNKNOWN");assert.equal(E.compareEconomicMetric("grossRevenue",metric("PARTIAL",1,["x"]),metric("CALCULATED",1)).comparisonStatus,"PARTIAL");assert.equal(E.compareEconomicMetric("grossRevenue",metric("INVALID"),metric("UNKNOWN")).comparisonStatus,"INVALID");assert.equal(E.compareEconomicMetric("grossRevenue",metric("NOT_APPLICABLE"),metric("CALCULATED",0)).comparisonStatus,"NOT_APPLICABLE")});

test("explicit actual portfolio binds two non-overlapping units, aggregates only additive values, and remains descriptive",()=>{const x=build(),betaValues={...amounts,REVENUE:80000},beta=actualAssessment("actual-beta","product:beta",betaValues);const member=(id,a)=>({id,memberType:"PRODUCT",economicUnitId:`unit:${a.productRef}`,organizationId:ORG,workId:WORK,productRef:a.productRef,campaignRef:a.campaignRef,economicAssessmentRef:E.economicPortfolioAssessmentReference(a),engineVersion:E.ECONOMICS_ENGINE_VERSION,economicView:"ACTUAL",currency:"USD",reportingPeriod:PERIOD,scenarioRef:null,calibrationRef:null});const members=[member("beta",beta),member("alpha",x.actual)],portfolio={id:"portfolio:eco6b",version:1,organizationId:ORG,workId:WORK,name:"ECO-6B explicit actual portfolio",economicView:"ACTUAL",currency:"USD",reportingPeriod:PERIOD,engineVersion:E.ECONOMICS_ENGINE_VERSION,policyVersion:E.PORTFOLIO_POLICY_VERSION,createdAt:RECONCILED_AT,createdBy:"human:economist",members,limitations:[]},result=E.runEconomicPortfolioStudy({portfolio,economicAssessments:[beta,x.actual]});assert.deepEqual(result.memberReferences.map(v=>v.memberId),["alpha","beta"]);assert.equal(result.metrics.grossRevenue.knownResolvedValue,x.actual.metrics.grossRevenue.value+beta.metrics.grossRevenue.value);assert.ok(result.nonAggregatedMetrics.includes("roi"));assert.deepEqual({authorization:result.authorization,reservation:result.reservation,spend:result.spend,execution:result.execution},{authorization:null,reservation:null,spend:null,execution:null});assert.throws(()=>E.runEconomicPortfolioStudy({portfolio:{...portfolio,members:[member("alpha",x.actual),member("duplicate",x.actual)]},economicAssessments:[x.actual]}),/duplicate_assessment/);const tampered=structuredClone(x.actual);tampered.metrics.grossRevenue.value++;assert.throws(()=>E.runEconomicPortfolioStudy({portfolio:{...portfolio,members:[member("alpha",x.actual)]},economicAssessments:[tampered]}),/assessment_binding/)});

test("canonical deterministic replay preserves economic identities, digests, and outputs",()=>{const a=build(),b=build();for(const key of ["expectedArtifact","decision","approval","run","experimentResult","actualArtifact","reconciliation","observation"])assert.deepEqual(a[key],b[key],key);assert.equal(a.expected.engineVersion,E.ECONOMICS_ENGINE_VERSION);assert.equal(a.actual.engineVersion,E.ECONOMICS_ENGINE_VERSION)});
