"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const C=require("../src/business-os/execution/contracts");
const {createRegistry}=require("../src/business-os/execution/registry");
const {createExecutionController}=require("../src/business-os/execution/controller");
const {createPlanner}=require("../src/business-os/execution/planner");
const {createSyntheticAdapter}=require("../src/business-os/execution/synthetic-tools");
const {deriveDiagnostics}=require("../src/business-os/execution/diagnostics");
const {phase4Readiness,REQUIREMENTS}=require("../src/business-os/execution/phase4-readiness");
const {createConstitutionalKernel}=require("../src/business-os/kernel/kernel");
const {createMemorySystem}=require("../src/business-os/memory/system");

const actor={id:"worker",organizationId:"org-a",permissionTags:["TEAM"]};
const tool=(id="primary",overrides={})=>({id,organizationId:"org-a",name:id,version:"1",description:"synthetic",inputSchema:{type:"object",required:["value"]},outputSchema:{type:"object",required:["accepted"]},risk:"LOW",cost:{currency:"USD",amount:1},timeoutMs:15,retryPolicy:{maxAttempts:2},idempotency:"KEY_REQUIRED",authorityRequirements:["grant"],policyRequirements:["policy"],sideEffect:"REVERSIBLE",reversibility:"SYNTHETIC",limitations:[],status:"AVAILABLE",requiredCredentialRefs:[],verificationRequirements:["independent"],reliability:{sampleSize:0,successRate:null},supportedCapabilityIds:["cap"],autonomyLevels:["EXECUTE_APPROVED","BOUNDED_AUTONOMOUS"],killSwitchApplicable:true,schemaVersion:1,permissionTags:["TEAM"],...overrides});
const capability=(overrides={})=>({id:"cap",organizationId:"org-a",name:"Synthetic operation",version:"1",description:"certification only",requiredInputs:["value"],producedOutputs:["accepted"],requiredToolIds:["primary"],optionalToolIds:["alternative"],procedureRefs:["procedure:synthetic"],qaContractRefs:["qa:independent"],validationStatus:"VALIDATED",reliabilityEvidenceRefs:[],limitations:[],risk:"LOW",estimatedCost:{currency:"USD",amount:1},estimatedDurationMs:10,capacity:{concurrency:1},autonomyLevel:"BOUNDED_AUTONOMOUS",humanRequiredSteps:[],authorityRequirements:["grant"],policyRequirements:["policy"],evidenceRefs:[],status:"AVAILABLE",schemaVersion:1,permissionTags:["TEAM"],...overrides});
const goal=(overrides={})=>C.Goal({id:"goal",organizationId:"org-a",objective:"produce verified synthetic output",requestedAutonomy:"EXECUTE_APPROVED",createdAt:"now",correlationId:"corr",...overrides});
const step=(overrides={})=>C.PlanStep({id:"step",objective:"execute",dependencyIds:[],capabilityId:"cap",toolId:"primary",inputs:{value:7},expectedOutput:{type:"object",required:["accepted"]},successCriteria:["independent verification"],verificationMethod:"independent",authorityRef:"grant",policyRef:"policy@1",estimatedCost:{currency:"USD",amount:1},risk:"LOW",timeoutMs:10,retryPolicy:{maxAttempts:2},idempotencyKey:"idem-1",failureBehavior:{allowSubstitution:false,onExhausted:"REPLAN"},humanApprovalRequired:false,status:"READY",...overrides});
const plan=(s=step(),overrides={})=>C.Plan({id:"plan",goalId:"goal",organizationId:"org-a",steps:[s],status:"READY",createdAt:"now",version:1,...overrides});
function fixture({behavior="SUCCESS",verdict="VERIFIED_SUCCESS",extraTools=[],capabilityOverrides={},memory=false}={}){let n=0;const registry=createRegistry();registry.registerCapability(capability(capabilityOverrides));registry.registerTool(tool());for(const t of extraTools)registry.registerTool(t);const kernel=createConstitutionalKernel({id:()=>`k-${++n}`});kernel.registerActor({id:"issuer",type:"HUMAN",status:"ACTIVE"});kernel.registerActor({id:"worker",type:"SERVICE",status:"ACTIVE"});kernel.registerActor({id:"human",type:"HUMAN",status:"ACTIVE"});kernel.issueGrant({id:"grant",subjectActorId:"worker",issuerActorId:"issuer",actionScopes:["tool.*"],resourceScopes:["organization:org-a"]});kernel.addPolicy({definitionId:"tools",id:"policy@1",version:1,rules:{"tool.primary":{outcome:"ALLOW"},"tool.alternative":{outcome:"ALLOW"},"tool.human":{outcome:"REQUIRE_HUMAN"}}});const adapters={primary:createSyntheticAdapter(behavior)};for(const t of extraTools)adapters[t.id]=createSyntheticAdapter("SUCCESS");const memorySystem=memory?createMemorySystem({id:()=>`m-${++n}`}):null;const controller=createExecutionController({registry,kernel,memorySystem,adapters,verifiers:{independent:async()=>({status:verdict,evidenceRefs:["verifier:evidence"]})},id:()=>`x-${++n}`});return {registry,kernel,controller,adapters,memorySystem}}

test("Phase 4 contracts are versioned, frozen, and distinguish capability from tool",()=>{const t=C.Tool(tool()),c=C.Capability(capability());assert.equal(t.contractVersion,C.CONTRACT_VERSION);assert.equal(c.contractVersion,C.CONTRACT_VERSION);assert.notEqual(t.kind,c.kind);assert.ok(Object.isFrozen(t)&&Object.isFrozen(c))});
test("registry resolves validated capability and supporting tools structurally",()=>{const {registry}=fixture();assert.deepEqual(registry.resolveCapabilities({actor,requiredInputs:["value"],autonomyLevel:"EXECUTE_APPROVED",maxCost:2,riskLevels:["LOW"]}).map(x=>x.id),["cap"]);assert.deepEqual(registry.toolsForCapability("cap",actor).map(x=>x.id),["primary"])});
test("unknown capability and unknown tool fail closed before invocation",async()=>{for(const s of [step({capabilityId:"ghost"}),step({toolId:"ghost"})]){const f=fixture();const result=await f.controller.execute({goal:goal(),plan:plan(s),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(result.ok,false);assert.match(result.code,/NOT_FOUND/);assert.equal(f.adapters.primary.calls,0)}});
test("organization boundary precedes permission and leaks no private registry record",()=>{const registry=createRegistry();registry.registerTool(tool("foreign",{organizationId:"org-b",permissionTags:["TEAM"],description:"tenant secret"}));registry.registerCapability(capability({id:"foreign-cap",organizationId:"org-b",permissionTags:["TEAM"],description:"tenant capability secret"}));assert.equal(registry.getTool("foreign",actor),null);assert.equal(registry.getCapability("foreign-cap",actor),null);assert.doesNotMatch(JSON.stringify(registry.listTools(actor)),/tenant secret/)});
test("missing inputs and capability-tool mismatch block execution",async()=>{for(const s of [step({inputs:{}}),step({toolId:"alternative"})]){const f=fixture({extraTools:s.toolId==="alternative"?[tool("alternative",{supportedCapabilityIds:["other"]})]:[]});const result=await f.controller.execute({goal:goal(),plan:plan(s),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(result.ok,false);assert.ok(["MISSING_REQUIRED_INPUT","CAPABILITY_TOOL_MISMATCH"].includes(result.code))}});
test("authority and policy denial prevent adapter use",async()=>{const cases=[];{const f=fixture();cases.push([f,step({authorityRef:"missing"}),"MISSING_AUTHORITY"])}{const f=fixture();cases.push([f,step({policyRef:"missing"}),"POLICY_NOT_FOUND"])}for(const [f,s,code] of cases){const r=await f.controller.execute({goal:goal(),plan:plan(s),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(r.code,code);assert.equal(f.adapters.primary.calls,0)}});
test("active kill switch prevents execution",async()=>{const f=fixture();f.kernel.registerActor({id:"governor",type:"HUMAN",status:"ACTIVE"});f.kernel.issueGrant({id:"switch",subjectActorId:"governor",issuerActorId:"issuer",actionScopes:["governance.kill-switch"],resourceScopes:["system"]});f.kernel.setKillSwitch({id:"halt",scopeType:"ACTION",scopeValue:"tool.*",active:true,issuerActorId:"governor",reason:"incident"});const r=await f.controller.execute({goal:goal(),plan:plan(),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(r.code,"KILL_SWITCH_ACTIVE");assert.equal(f.adapters.primary.calls,0)});
test("unknown cost, excessive cost, high risk, and missing human approval never execute",async()=>{const specimens=[[tool("primary",{cost:{amount:null}}),step(),"UNKNOWN_COST"],[tool("primary",{cost:{amount:9}}),step(),"COST_BOUNDARY_EXCEEDED"],[tool("primary",{risk:"HIGH"}),step({risk:"HIGH"}),"RISK_REQUIRES_ESCALATION"]];for(const [replacement,s,code] of specimens){const f=fixture();f.registry=createRegistry;const registry=createRegistry();registry.registerCapability(capability());registry.registerTool(replacement);const controller=createExecutionController({registry,kernel:f.kernel,adapters:{primary:f.adapters.primary},verifiers:{independent:async()=>({status:"VERIFIED_SUCCESS"})}});const r=await controller.execute({goal:goal(),plan:plan(s),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(r.code,code);assert.equal(f.adapters.primary.calls,0)}const f=fixture({capabilityOverrides:{humanRequiredSteps:["step"]}});const r=await f.controller.execute({goal:goal(),plan:plan(),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(r.nextAction,"ESCALATE");assert.equal(f.adapters.primary.calls,0)});
test("controlled success separates invocation, result, observation, verification, and evidence",async()=>{const f=fixture({memory:true});const r=await f.controller.execute({goal:goal(),plan:plan(),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(r.ok,true);assert.equal(r.verification.status,"VERIFIED_SUCCESS");assert.equal(r.nextAction,"COMPLETE");assert.equal(f.kernel.repository.data.evidence.size,2);assert.equal(f.memorySystem.listMemories()[0].content.verificationStatus,"VERIFIED_SUCCESS")});
test("failed tool, timeout, malformed output, failed/ambiguous/partial verification never become success",async()=>{for(const [behavior,verdict] of [["FAIL","VERIFIED_SUCCESS"],["TIMEOUT","VERIFIED_SUCCESS"],["MALFORMED","VERIFIED_SUCCESS"],["SUCCESS","VERIFIED_FAILURE"],["SUCCESS","AMBIGUOUS"],["PARTIAL","PARTIAL"]]){const f=fixture({behavior,verdict});const r=await f.controller.execute({goal:goal(),plan:plan(step({retryPolicy:{maxAttempts:1}})),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(r.ok,false);assert.notEqual(r.stepStatus,"COMPLETED")}});
test("retry is bounded and retry exhaustion replans",async()=>{const recovered=fixture({behavior:"RETRYABLE"});const ok=await recovered.controller.execute({goal:goal(),plan:plan(),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(ok.ok,true);assert.equal(recovered.adapters.primary.calls,2);const failed=fixture({behavior:"FAIL"});const no=await failed.controller.execute({goal:goal(),plan:plan(),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(no.nextAction,"REPLAN");assert.equal(failed.adapters.primary.calls,1)});
test("approved substitution records lineage, rechecks authority, verifies recovery, and completes",async()=>{const f=fixture({behavior:"FAIL",extraTools:[tool("alternative")]});const r=await f.controller.execute({goal:goal(),plan:plan(step({retryPolicy:{maxAttempts:1},failureBehavior:{allowSubstitution:true,onExhausted:"REPLAN"}})),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(r.ok,true);assert.equal(r.tool.id,"alternative");assert.equal(r.substitutionOf,"primary");assert.deepEqual(f.controller.getLedger().replans.map(x=>[x.fromToolId,x.toToolId]),[["primary","alternative"]])});
test("unauthorized substitution fails closed on the constitutional recheck",async()=>{const f=fixture({behavior:"FAIL",extraTools:[tool("alternative")]});f.kernel.repository.data.grants.set("grant",f.kernel.contracts.AuthorityGrant({...f.kernel.repository.data.grants.get("grant"),actionScopes:["tool.primary"]}));const r=await f.controller.execute({goal:goal(),plan:plan(step({retryPolicy:{maxAttempts:1},failureBehavior:{allowSubstitution:true,onExhausted:"REPLAN"}})),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(r.code,"WRONG_ACTION_SCOPE");assert.equal(f.adapters.alternative.calls,0)});
test("idempotent replay returns prior verified outcome without duplicate invocation",async()=>{const f=fixture();const args={goal:goal(),plan:plan(),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}};const first=await f.controller.execute(args),second=await f.controller.execute(args);assert.equal(first.ok,true);assert.equal(second.replayed,true);assert.equal(f.adapters.primary.calls,1)});
test("dependency failure blocks downstream execution truthfully",async()=>{const f=fixture(),s=step({dependencyIds:["prior"]}),p=plan(s,{steps:[C.PlanStep({...step(),id:"prior",status:"FAILED"}),s]});const r=await f.controller.execute({goal:goal(),plan:p,stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(r.stepStatus,"BLOCKED");assert.equal(r.nextAction,"STOP");assert.equal(f.adapters.primary.calls,0)});
test("model proposals remain advisory and cannot invent tools, capabilities, success, or prohibition overrides",async()=>{const f=fixture();for(const proposed of [step({toolId:"model-invented"}),step({capabilityId:"model-invented"})]){const r=await f.controller.execute({goal:goal(),plan:plan(proposed),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(r.ok,false)}const claimed=fixture({verdict:"VERIFIED_FAILURE"});const result=await claimed.controller.execute({goal:goal(),plan:plan(),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]},cognitiveProposal:{claimsSuccess:true}});assert.equal(result.ok,false)});
test("planner consumes the canonical Context Engine handoff and Cognitive Core while keeping its plan advisory",async()=>{let drafted=null;const contextPackage={kind:"ContextPackage",id:"ctx"};const planner=createPlanner({contextEngine:{build:request=>({ok:true,package:{...contextPackage,request}}),toCognitiveRequest:(pkg,request)=>({ok:true,request:{...request,inputRefs:[pkg.id]}})},cognitiveCore:{draftPlan:async request=>{drafted=request;return {ok:true,result:{content:{steps:[{toolId:"model-proposal"}]}}}}}});const result=await planner.propose({contextRequest:{organizationId:"org-a"},cognitiveRequest:{id:"cog"}});assert.deepEqual(drafted.inputRefs,["ctx"]);assert.equal(drafted.taskType,"PLAN_DRAFT");assert.equal(result.authoritative,false);assert.equal(result.requiresDeterministicValidation,true)});
test("FIRST FAILURE blocks dependent diagnostics",()=>{const d=deriveDiagnostics({GOAL:{status:"PASS"},CONTEXT:{status:"PASS"},PLAN_GENERATION:{status:"FAIL",reason:"bad plan"},PLAN_VALIDATION:{status:"FAIL",reason:"must not surface"}},"now");assert.equal(d.firstFailure.checkId,"PLAN_GENERATION");assert.equal(d.checks.find(x=>x.id==="PLAN_VALIDATION").status,"BLOCKED")});
test("Phase 4 readiness can only reach CONDITIONAL_GO without human acceptance",()=>{const automated=Object.fromEntries(REQUIREMENTS.map(x=>[x,"PASS"])),r=phase4Readiness({automated});assert.equal(r.gate,"CONDITIONAL_GO");assert.equal(r.humanAcceptance.status,"PENDING");assert.ok(r.exclusions.includes("PHASE_5_AGENT_RUNTIME"))});

test("controller diagnostics do not fabricate PASS for checks that never ran",async()=>{const f=fixture();const r=await f.controller.execute({goal:goal(),plan:plan(step({capabilityId:"ghost"})),stepId:"step",actor,budget:{maxCost:2,allowedRisks:["LOW"]}});assert.equal(r.ok,false);assert.equal(r.diagnostics.firstFailure.checkId,"CAPABILITY_RESOLUTION");const byId=Object.fromEntries(r.diagnostics.checks.map(x=>[x.id,x.status]));assert.notEqual(byId.CONTEXT,"PASS");assert.notEqual(byId.PLAN_GENERATION,"PASS");assert.notEqual(byId.PLAN_VALIDATION,"PASS");});
