"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const source=fs.readFileSync(path.join(__dirname,"../public/api-client.js"),"utf8");
function client(fetchImpl=async request=>new Response(JSON.stringify({ok:true}),{status:200,headers:{"content-type":"application/json"}})) { const window={location:{origin:"https://mufasafitsite.onrender.com",href:"https://mufasafitsite.onrender.com/dashboard.html"},RuntimeState:{getBackendOrigin:()=>"https://mufasa-fitness-node.onrender.com"},AuthStateRuntime:{getAuthToken:()=>"aaa.bbb.ccc"},fetch:fetchImpl};window.window=window;vm.runInNewContext(source,{window,globalThis:window,URL,Request,AbortController,setTimeout,clearTimeout,Object});return window.MaatApiClient; }
test("canonical client resolves production API and sends bearer cross-origin with Safari-compatible omitted credentials",async()=>{let request;const result=await client(async r=>(request=r,new Response("{}",{status:200,headers:{"content-type":"application/json"}}))).request("/api/auth/me");assert.equal(request.url,"https://mufasa-fitness-node.onrender.com/api/auth/me");assert.equal(request.headers.get("authorization"),"Bearer aaa.bbb.ccc");assert.equal(request.credentials,"omit");assert.equal(result.diagnostics.crossOrigin,true);assert.equal(result.diagnostics.preflightRequired,true);assert.equal(result.diagnostics.backendReached,true);});
test("history and admin diagnostics share canonical routing and distinguish HTTP auth",async()=>{const c=client(async()=>new Response(JSON.stringify({error:"denied"}),{status:403,headers:{"content-type":"application/json"}}));for(const route of ["/api/me/history","/api/admin/diagnostics/run-club/run"]){const result=await c.request(route,{method:route.includes("run-club")?"POST":"GET"});assert.equal(result.diagnostics.apiOrigin,"https://mufasa-fitness-node.onrender.com");assert.equal(result.diagnostics.failureClass,"authentication HTTP response");}});
test("opaque Safari fetch rejection is safely classified without claiming backend or CORS knowledge",async()=>{const result=await client(async()=>{throw new TypeError("Load failed")}).request("/api/auth/me");assert.equal(result.diagnostics.dispatched,true);assert.equal(result.diagnostics.backendReached,null);assert.equal(result.diagnostics.failureClass,"unknown network");});
const os=require("node:os");
test("production CORS preflight explicitly permits frontend Authorization and rejects another origin",async t=>{const previous=process.env.NODE_ENV,allowed=process.env.ALLOWED_ORIGINS;process.env.NODE_ENV="production";delete process.env.ALLOWED_ORIGINS;const {createApp}=require("../server"),app=createApp({dataDir:fs.mkdtempSync(path.join(os.tmpdir(),"api-cors-"))}),server=app.listen(0);t.after(()=>{server.close();previous===undefined?delete process.env.NODE_ENV:process.env.NODE_ENV=previous;allowed===undefined?delete process.env.ALLOWED_ORIGINS:process.env.ALLOWED_ORIGINS=allowed;});await new Promise(r=>server.once("listening",r));const base=`http://127.0.0.1:${server.address().port}`,headers={Origin:"https://mufasafitsite.onrender.com","Access-Control-Request-Method":"GET","Access-Control-Request-Headers":"authorization"};const ok=await fetch(base+"/api/auth/me",{method:"OPTIONS",headers});assert.equal(ok.status,200);assert.equal(ok.headers.get("access-control-allow-origin"),"https://mufasafitsite.onrender.com");assert.match(ok.headers.get("access-control-allow-headers"),/Authorization/i);const denied=await fetch(base+"/api/auth/me",{method:"OPTIONS",headers:{...headers,Origin:"https://evil.example"}});assert.equal(denied.headers.get("access-control-allow-origin"),null);});
