"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const source=fs.readFileSync(path.join(__dirname,"../public/auth-navigation.js"),"utf8");
function harness({result={ok:false,reason:"missing_token"},auth={isAuthenticated:false,token:null,user:null}}={}){
 const redirects=[];const location={origin:"https://app.example",pathname:"/workout.html",search:"?source=challenge",hash:"#camera",replace:v=>redirects.push(v),assign:v=>redirects.push(v)};
 const window={location,AuthStateRuntime:{whenReady:async()=>result,getCanonicalAuthState:()=>auth}};window.window=window;
 vm.runInNewContext(source,{window,globalThis:window,URL,URLSearchParams,Set});return{navigation:window.AuthNavigation,redirects};
}
test("returnTo normalization accepts same-origin application paths",()=>{const {navigation:n}=harness();for(const value of ["/workout.html","/challenge.html?slug=push-up","/greatness.html","/dashboard.html#section"])assert.equal(n.normalizeReturnTo(value),value)});
test("returnTo normalization rejects external, network, backslash, malformed, control and login-loop destinations",()=>{const {navigation:n}=harness();for(const value of ["https://evil.example/x","//evil.example/x","/\\evil","/%ZZ","/workout.html\u0000x","/login.html","/login.html?returnTo=/workout.html"])assert.equal(n.normalizeReturnTo(value),"/dashboard.html")});
test("authenticated readiness continues without redirect",async()=>{const h=harness({result:{ok:true},auth:{isAuthenticated:true,token:"token",user:{id:"member"}}});assert.equal((await h.navigation.requireUser()).ok,true);assert.deepEqual(h.redirects,[])});
test("definitive missing or invalid auth redirects once with full pathname query and hash",async()=>{for(const reason of ["missing_token","invalid_token","expired_token","invalid_session"]){const h=harness({result:{ok:false,reason}}),r=await h.navigation.requireUser();assert.equal(r.redirected,true);assert.equal(h.redirects.length,1);assert.match(h.redirects[0],/^\/login\.html\?returnTo=/);assert.equal(new URLSearchParams(h.redirects[0].split("?")[1]).get("returnTo"),"/workout.html?source=challenge#camera")}});
test("temporary auth unavailability neither redirects nor clears auth",async()=>{const h=harness({result:{ok:false,reason:"auth_unavailable"},auth:{isAuthenticated:false,token:null,user:null}}),r=await h.navigation.requireUser();assert.equal(r.retryable,true);assert.deepEqual(h.redirects,[]);assert.doesNotMatch(source,/clearCanonicalAuthState|removeItem/)});
test("AuthNavigation owns no credentials or browser storage",()=>{assert.doesNotMatch(source,/api\/auth\/login|password|localStorage|sessionStorage|maatAuthToken/)});
test("one validated canonical session crosses protected product surfaces without re-login",async()=>{const auth={isAuthenticated:true,token:"token",user:{id:"member",accessTier:"free_run_club"}},h=harness({result:{ok:true},auth});for(const returnTo of ["/dashboard.html","/workout.html","/challenge.html?slug=push-up","/greatness.html","/dashboard.html"]){const result=await h.navigation.requireUser({returnTo});assert.equal(result.ok,true)}assert.deepEqual(h.redirects,[])});
test("modified protected surfaces load and use the shared guard",()=>{for(const file of ["workout.html","dashboard.html","challenge.html","pocketpt-my-program.html","greatness.html"]){const html=fs.readFileSync(path.join(__dirname,"../public",file),"utf8");assert.match(html,/auth-navigation\.js/,file)}for(const file of ["workout.html","dashboard.js","challenge-page.js","pocketpt-youth-program.js","greatness-entry-auth.js"]){const body=fs.readFileSync(path.join(__dirname,"../public",file),"utf8");assert.match(body,/AuthNavigation\.requireUser/,file)}});
test("challenge and workout guards preserve pathname query and hash",()=>{for(const file of ["workout.html","challenge-page.js"]){const body=fs.readFileSync(path.join(__dirname,"../public",file),"utf8");assert.match(body,/(?:window\.)?location\.pathname\s*\+\s*(?:window\.)?location\.search\s*\+\s*(?:window\.)?location\.hash/,file)}});
test("Run Club remains free at the authentication layer",()=>{const server=fs.readFileSync(path.join(__dirname,"../server.js"),"utf8"),landing=fs.readFileSync(path.join(__dirname,"../public/stepping-into-greatness.html"),"utf8");assert.match(server,/requestedContext === "run_club" \? "free_run_club"/);assert.match(landing,/FREE DIGITAL RUN CLUB/);assert.doesNotMatch(source,/membership|trial|payment/i)});
