const test=require('node:test');
const assert=require('node:assert/strict');
const THREE=require('three');
const {AvatarPresentationStabilizer}=require('../public/motion/live-avatar-mirror');
const {AvaturnLivePoseSolver}=require('../public/motion/avaturn-live-pose-solver');

function frame(timestamp,angle=0){const direction={x:Math.cos(angle),y:Math.sin(angle),z:0};const joint=Object.freeze({x:.5,y:.5,z:null,confidence:.95});return Object.freeze({timestamp,joints:Object.freeze({left_shoulder:joint,right_shoulder:joint,left_hip:joint,right_hip:joint}),directions:Object.freeze({shoulderLine:direction,hipLine:direction})});}
function rig(){const avatar=new THREE.Group(),add=(name,parent,y=.2)=>{const bone=Object.assign(new THREE.Bone(),{name});bone.position.y=y;parent.add(bone);return bone;};const hips=add('Hips',avatar,0),spine=add('Spine',hips),chest=add('Spine1',spine),shoulder=add('RightShoulder',chest),arm=add('RightArm',shoulder),forearm=add('RightForeArm',arm),hand=add('RightHand',forearm);avatar.updateMatrixWorld(true);return{avatar,hips,spine,chest};}

test('avatar presentation smooths and interpolates without mutating authoritative input',()=>{const source=frame(100,0),next=frame(200,1),s=new AvatarPresentationStabilizer({smoothingAlpha:.5,coastMs:200});s.observe(source);s.observe(next);const sample=s.sample(150);assert.equal(source.directions.shoulderLine.y,0);assert.ok(sample.directions.shoulderLine.y>0&&sample.directions.shoulderLine.y<Math.sin(1));assert.equal(s.diagnostics(150).interpolatedAvatarFrames,1);});
test('avatar presentation coasts briefly, stops after the bound, and counts reacquisition',()=>{const s=new AvatarPresentationStabilizer({coastMs:100});s.observe(frame(0));assert.ok(s.sample(50));assert.equal(s.sample(101),null);s.observe(frame(250));assert.equal(s.diagnostics(250).reacquiredFrames,1);});
test('torso calibrates neutral, distributes delta without compounding, clamps, and returns upright',()=>{const r=rig(),solver=new AvaturnLivePoseSolver({THREE,avatar:r.avatar,calibrationMs:100,calibrationMinFrames:2,smoothingLambda:1000});solver.observe(frame(100,.12));solver.observe(frame(220,.12));assert.equal(solver.diagnostics().torsoCalibrationState,'CALIBRATED');solver.observe(frame(250,1.2));let d=solver.diagnostics();assert.equal(d.torsoClampApplied,'YES');assert.ok(Math.abs(d.appliedHipRotation)<=solver.options.hipRollClamp);assert.ok(Math.abs(d.appliedSpineRotation)<=solver.options.spineRollClamp);assert.ok(Math.abs(d.appliedChestRotation)<Math.abs(d.appliedSpineRotation));assert.ok(Math.abs(d.appliedSpineRotation+d.appliedChestRotation)<1.2);solver.observe(frame(280,.12));d=solver.diagnostics();assert.ok(Math.abs(d.appliedSpineRotation)<1e-9);assert.ok(Math.abs(d.appliedChestRotation)<1e-9);});
