"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

function element(id) {
  return { id, textContent:"", value:"", files:[], disabled:false, dataset:{}, style:{}, classList:{ values:new Set(id === "avatarModal" ? ["hidden"] : []), add(v){this.values.add(v);}, remove(v){this.values.delete(v);}, toggle(){} }, removeAttribute(){}, setAttribute(){} };
}
function harness({ open=()=>({}), runtime, profile }={}) {
  const ids=["connectBtn","avatarCreateBtn","avatarModal","avatarCreationStatus","closeAvatarModalBtn","launchAvaturnBtn","avatarFileInput","uploadAvatarBtn","saveAvatarBtn","clearAvatarBtn","avatarDiagControls","avatarDiagLaunch","avatarDiagFile","avatarDiagApiOrigin","avatarDiagContractUrl","avatarDiagContractVersion","avatarDiagContractStatus","avatarDiagBackendBuild","avatarDiagUploadRoute","avatarDiagUploadMethod","avatarDiagMultipartField","avatarDiagMaxUpload","avatarDiagUpload","avatarDiagHttp","avatarDiagServerCode","avatarDiagCompatibility","avatarDiagProfile","avatarDiagReload","avatarDiagRuntime","avatarDiagError"];
  const elements=Object.fromEntries(ids.map(id=>[id,element(id)]));
  const window={ document:{readyState:"complete",getElementById:id=>elements[id]||null}, open, AvatarRuntime:runtime, ProfileWriteRuntime:profile };
  window.window=window;
  vm.runInNewContext(fs.readFileSync(path.join(__dirname,"../public/workout-control-activation.js"),"utf8"),{window,Promise});
  return {window,elements};
}

test("modal opens and Close works without AvatarRuntime",()=>{ const h=harness(); h.elements.avatarCreateBtn.onclick(); assert.equal(h.elements.avatarModal.classList.values.has("hidden"),false); h.elements.closeAvatarModalBtn.onclick(); assert.equal(h.elements.avatarModal.classList.values.has("hidden"),true); assert.equal(h.elements.avatarDiagControls.textContent,"READY"); });
test("Avaturn is opened synchronously from the tap without AvatarRuntime",()=>{ let duringClick=false,called=false; const h=harness({open:url=>{called=duringClick; assert.equal(url,"https://www.avaturn.me/"); return {};}}); duringClick=true; h.elements.launchAvaturnBtn.onclick(); duringClick=false; assert.equal(called,true); assert.equal(h.elements.avatarDiagLaunch.textContent,"OPENED"); });
test("blocked Avaturn launch is visibly reported",()=>{ const h=harness({open:()=>null}); h.elements.launchAvaturnBtn.onclick(); assert.equal(h.elements.avatarDiagLaunch.textContent,"FAILED"); assert.match(h.elements.avatarDiagError.textContent,/could not open/i); });
test("file change displays filename, size, type, and permits blank MIME",()=>{ const h=harness(); h.elements.avatarFileInput.files=[{name:"model 2.glb",size:2048,type:""}]; h.elements.avatarFileInput.onchange(); assert.match(h.elements.avatarDiagFile.textContent,/FILE SELECTED \| name: model 2\.glb \| size: 2\.0 KB \| browser MIME: not provided/); assert.equal(h.elements.avatarDiagUpload.textContent,"IDLE"); });
test("non-GLB selection gives useful feedback",()=>{ const h=harness(); h.elements.avatarFileInput.files=[{name:"model.zip",size:2048,type:"application/zip"}]; h.elements.avatarFileInput.onchange(); assert.match(h.elements.avatarDiagFile.textContent,/INVALID FILE/); assert.equal(h.elements.avatarDiagError.textContent,"AVATAR_FILE_EXTENSION"); });
test("upload passes the exact click-time File object to transport",async()=>{ const selected={name:"model 2.glb",size:3500000,type:"model/gltf-binary"}; let received; const h=harness({profile:{uploadAvatarFile:async file=>{received=file;return {ok:true};}}}); h.elements.avatarFileInput.files=[selected]; assert.equal(await h.elements.uploadAvatarBtn.onclick(),true); assert.equal(received,selected); assert.equal(h.elements.avatarDiagUpload.textContent,"COMPLETE"); });
test("one upload runs while pending and success is visible",async()=>{ let calls=0,release; const pending=new Promise(resolve=>release=resolve); const h=harness({profile:{uploadAvatarFile:async()=>{calls++; await pending; return {ok:true};}}}); const first=h.elements.uploadAvatarBtn.onclick(),second=h.elements.uploadAvatarBtn.onclick(); assert.equal(calls,1); assert.equal(await second,false); release(); assert.equal(await first,true); assert.equal(h.elements.avatarDiagUpload.textContent,"COMPLETE"); assert.equal(h.elements.uploadAvatarBtn.disabled,false); });
test("server and network upload failures are visible",async()=>{ for(const reason of ["incompatible GLB: required humanoid skeleton missing","Network request failed"]){ const h=harness({profile:{uploadAvatarFile:async()=>{throw new Error(reason);}}}); assert.equal(await h.elements.uploadAvatarBtn.onclick(),false); assert.equal(h.elements.avatarDiagUpload.textContent,"FAILED"); assert.equal(h.elements.avatarDiagError.textContent,reason); } });
test("profile save and remove success/failure are visible",async()=>{ const success=harness({profile:{saveAvatarFromInputs:async()=>({ok:true}),clearAvatarMetadata:async()=>({ok:true})}}); await success.elements.saveAvatarBtn.onclick(); assert.equal(success.elements.avatarDiagProfile.textContent,"SUCCESS"); await success.elements.clearAvatarBtn.onclick(); assert.equal(success.elements.avatarDiagProfile.textContent,"SUCCESS"); const failure=harness({profile:{saveAvatarFromInputs:async()=>{throw new Error("profile save failure")},clearAvatarMetadata:async()=>({ok:false,reason:"owner rejected"})}}); await failure.elements.saveAvatarBtn.onclick(); assert.equal(failure.elements.avatarDiagProfile.textContent,"FAILED"); await failure.elements.clearAvatarBtn.onclick(); assert.match(failure.elements.avatarDiagError.textContent,/owner rejected/); });
test("optional runtime failure leaves handlers attached and rebinding does not duplicate",async()=>{ let uploads=0; const h=harness({runtime:{ensureThreeModules:async()=>{throw new Error("Three unavailable")}},profile:{uploadAvatarFile:async()=>{uploads++;return {ok:true}}}}); const close=h.elements.closeAvatarModalBtn.onclick,upload=h.elements.uploadAvatarBtn.onclick; h.elements.avatarCreateBtn.onclick(); await new Promise(resolve=>setImmediate(resolve)); assert.equal(h.elements.avatarDiagRuntime.textContent,"FAILED"); assert.equal(h.elements.closeAvatarModalBtn.onclick,close); h.window.WorkoutControlActivation.bind(); assert.equal(typeof h.elements.uploadAvatarBtn.onclick,"function"); await h.elements.uploadAvatarBtn.onclick(); assert.equal(uploads,1); });
test("runtime configuration does not claim modal button ownership",()=>{ const source=fs.readFileSync(path.join(__dirname,"../public/avatar-runtime.js"),"utf8"); const bind=source.slice(source.indexOf("function bindControls"),source.indexOf("function handlePosePacket")); assert.doesNotMatch(bind,/\.onclick\s*=/); });
test("upload contract remains authenticated, discoverable, owner-scoped, and auto-saves profile",()=>{ const client=fs.readFileSync(path.join(__dirname,"../public/profile-write-runtime.js"),"utf8"),server=fs.readFileSync(path.join(__dirname,"../server.js"),"utf8"),contract=require("../public/avatar-upload-contract"); assert.deepEqual(contract,{version:1,discoveryPath:"/api/avatar/upload-contract",path:"/api/avatar/upload",method:"POST",field:"avatar"}); assert.match(client,/authorization: `Bearer \$\{authToken\}`/); assert.match(client,/verifyUploadContract/); assert.match(server,/app\.get\("\/api\/avatar\/upload-contract"/); assert.match(server,/app\.post\("\/api\/avatar\/upload", requireAuth/); assert.match(server,/ownerUserId: req\.auth\.userId/); assert.match(server,/user\.profile\.avatar =/); });
test("avatar contract discovery and upload reuse the canonical API client origin",()=>{ const client=fs.readFileSync(path.join(__dirname,"../public/profile-write-runtime.js"),"utf8"); assert.match(client,/global\.MaatApiClient\?\.resolve/); assert.match(client,/const discoveryUrl = resolveCanonicalApiUrl\(contract\.discoveryPath\)/); assert.match(client,/const uploadUrl = resolveCanonicalApiUrl\(advertisedContract\.path\)/); assert.doesNotMatch(client,/String\(state\.endpoints\.nodeBaseUrl\).*contract\.discoveryPath/); });
test("workout exposes public-safe contract and deployment diagnostics",()=>{ const workout=fs.readFileSync(path.join(__dirname,"../public/workout.html"),"utf8"),client=fs.readFileSync(path.join(__dirname,"../public/profile-write-runtime.js"),"utf8"); for(const id of ["avatarDiagApiOrigin","avatarDiagContractUrl","avatarDiagContractVersion","avatarDiagContractStatus","avatarDiagBackendBuild","avatarDiagUploadRoute","avatarDiagUploadMethod","avatarDiagMultipartField","avatarDiagMaxUpload"]) assert.match(workout,new RegExp(`id="${id}"`)); assert.match(client,/UPLOAD_CONTRACT_VERSION_MISMATCH/); assert.match(client,/AVATAR_UPLOAD_DISABLED/); assert.ok(client.indexOf("await verifyUploadContract") < client.indexOf("fetch(uploadUrl")); });
test("Render frontend and backend deployments are pinned to the same branch",()=>{ const render=fs.readFileSync(path.join(__dirname,"../render.yaml"),"utf8"); assert.equal((render.match(/^    branch: main$/gm)||[]).length,2); assert.match(render,/name: mufasafitsite[\s\S]*?branch: main[\s\S]*?name: mufasa-fitness-node[\s\S]*?branch: main/); });
test("profile reload and avatar mounting are awaited only after server-confirmed profile save",()=>{ const source=fs.readFileSync(path.join(__dirname,"../public/profile-write-runtime.js"),"utf8"),flow=source.slice(source.indexOf("async function uploadAvatarFile"),source.indexOf("async function clearAvatarMetadata")),saved=flow.indexOf("payload.data.avatarModelUrl"),reload=flow.indexOf("await reloadProfile()"),mount=flow.indexOf('await refreshAvatarAsset("uploaded_file")'); assert.ok(saved < reload); assert.ok(reload < mount); assert.match(flow,/diagnostic\("avatarDiagRuntime", "MOUNTED"\)/); });

test("profile reload falls back to the canonical hydration runtime when shell injection is absent",()=>{ const source=fs.readFileSync(path.join(__dirname,"../public/profile-write-runtime.js"),"utf8"),resolver=source.slice(source.indexOf("function resolveProfileReload"),source.indexOf("async function verifyUploadContract")); assert.match(resolver,/state\.deps\.reloadProfile/); assert.match(resolver,/global\.AppHydrationRuntime\?\.hydrateProfileFromBackend/); assert.match(resolver,/global\.AppHydrationRuntime\.hydrateProfileFromBackend\(\)/); });

test("workout wires canonical profile reload into avatar transport",()=>{ const workout=fs.readFileSync(path.join(__dirname,"../public/workout.html"),"utf8"); assert.match(workout,/reloadProfile: \(\) => window\.AppHydrationRuntime\?\.hydrateProfileFromBackend\?\.\(\)/); assert.match(workout,/await window\.AuthNavigation\.requireUser/); });

test("production avatar chooser leaves native browsing permissive and validates after selection",()=>{
  const workout=fs.readFileSync(path.join(__dirname,"../public/workout.html"),"utf8");
  const input=workout.match(/<input\b[^>]*\bid="avatarFileInput"[^>]*>/g)||[];
  assert.equal(input.length,1,"one authoritative production avatar file input");
  assert.match(input[0],/\btype="file"/);
  assert.doesNotMatch(input[0],/\b(?:accept|capture|multiple|webkitdirectory|hidden|disabled|name|form)\b/i);
  for(const source of [workout,fs.readFileSync(path.join(__dirname,"../public/workout-control-activation.js"),"utf8")]) {
    assert.doesNotMatch(source,/(?:\.accept\s*=|setAttribute\(["']accept|removeAttribute\(["']accept)/);
  }
  assert.match(fs.readFileSync(path.join(__dirname,"../public/workout-control-activation.js"),"utf8"),/\/\\\.glb\$\/i\.test\(selected\.name/);
});
