"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),{createApp}=require("../server"),{glb,nodes}=require("./avatar-glb-validator.test");
async function fixture(t){const old={p:process.env.PILOT_LOGIN_PASSWORD,n:process.env.NODE_ENV,a:process.env.AUTH_TEST_LOGIN_FIXTURE_ENABLED};Object.assign(process.env,{PILOT_LOGIN_PASSWORD:"avatar-test",NODE_ENV:"test",AUTH_TEST_LOGIN_FIXTURE_ENABLED:"true"});t.after(()=>{old.p==null?delete process.env.PILOT_LOGIN_PASSWORD:process.env.PILOT_LOGIN_PASSWORD=old.p;old.n==null?delete process.env.NODE_ENV:process.env.NODE_ENV=old.n;old.a==null?delete process.env.AUTH_TEST_LOGIN_FIXTURE_ENABLED:process.env.AUTH_TEST_LOGIN_FIXTURE_ENABLED=old.a});const root=fs.mkdtempSync(path.join(os.tmpdir(),"avatar-transport-"));fs.mkdirSync(path.join(root,"public/exercise-db"),{recursive:true});fs.writeFileSync(path.join(root,"public/exercise-db/index.json"),"[]");const server=createApp({rootDir:root}).listen(0);await new Promise(r=>server.once("listening",r));t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}`,response=await fetch(`${base}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:"transport@example.test",password:"avatar-test",testUserId:"transport_member"})});return{base,token:(await response.json()).token}}
function multipart(buffer,field="avatar",name="model 2.glb"){const form=new FormData();if(buffer)form.append(field,new Blob([buffer],{type:"model/gltf-binary"}),name);return form}
test("real Blob traverses FormData, validation, persistence, and automatic profile save",async t=>{const{base,token}=await fixture(t),response=await fetch(`${base}/api/avatar/upload`,{method:"POST",headers:{authorization:`Bearer ${token}`},body:multipart(glb(nodes))}),payload=await response.json();assert.equal(response.status,201);assert.equal(payload.data.compatibility.profileId,"avaturn-native-v1");assert.equal(payload.data.profileSaved,true);assert.deepEqual(payload.data.uploadStages,["SERVER_RECEIVED_FILE","VALIDATING_GLB","PERSISTING_ASSET","SAVING_PROFILE"]);const profile=await fetch(`${base}/api/me/profile`,{headers:{authorization:`Bearer ${token}`}}).then(r=>r.json());assert.equal(profile.data.profile.avatar.avatarModelUrl,payload.data.avatarModelUrl)});
test("empty and wrong multipart fields report server file missing",async t=>{const{base,token}=await fixture(t);for(const form of[multipart(null),multipart(glb(nodes),"wrong")]){const response=await fetch(`${base}/api/avatar/upload`,{method:"POST",headers:{authorization:`Bearer ${token}`},body:form});assert.equal(response.status,400);assert.equal((await response.json()).error.code,"AVATAR_FILE_MISSING")}});
test("valid approximately 3.5 MB GLB reaches compatibility validation",async t=>{const{base,token}=await fixture(t),large=structuredClone(nodes);large[0].extras={transportPadding:"x".repeat(3500000)};const asset=glb(large);assert.ok(asset.length>=3500000&&asset.length<3600000);const response=await fetch(`${base}/api/avatar/upload`,{method:"POST",headers:{authorization:`Bearer ${token}`},body:multipart(asset,"avatar","large.glb")});assert.equal(response.status,201)});
test("incompatible GLB is not misreported as missing",async t=>{const{base,token}=await fixture(t),response=await fetch(`${base}/api/avatar/upload`,{method:"POST",headers:{authorization:`Bearer ${token}`},body:multipart(glb([{name:"Hips"}]))});assert.equal(response.status,422);assert.equal((await response.json()).error.code,"AVATAR_INCOMPATIBLE")});
test("unauthenticated multipart upload is rejected before parsing",async t=>{const{base}=await fixture(t),response=await fetch(`${base}/api/avatar/upload`,{method:"POST",body:multipart(glb(nodes))});assert.equal(response.status,401)});
