"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

function element(id) {
  return { id, textContent:"", value:"", files:[], disabled:false, dataset:{}, style:{}, classList:{ values:new Set(id === "avatarModal" ? ["hidden"] : []), add(v){this.values.add(v);}, remove(v){this.values.delete(v);}, toggle(){} }, removeAttribute(){}, setAttribute(){} };
}
function harness({ open=()=>({}), runtime, profile }={}) {
  const ids=["connectBtn","avatarCreateBtn","avatarModal","avatarCreationStatus","closeAvatarModalBtn","launchAvaturnBtn","avatarFileInput","uploadAvatarBtn","saveAvatarBtn","clearAvatarBtn","avatarDiagControls","avatarDiagLaunch","avatarDiagFile","avatarDiagUpload","avatarDiagProfile","avatarDiagRuntime","avatarDiagError"];
  const elements=Object.fromEntries(ids.map(id=>[id,element(id)]));
  const window={ document:{readyState:"complete",getElementById:id=>elements[id]||null}, open, AvatarRuntime:runtime, ProfileWriteRuntime:profile };
  window.window=window;
  vm.runInNewContext(fs.readFileSync(path.join(__dirname,"../public/workout-control-activation.js"),"utf8"),{window,Promise});
  return {window,elements};
}

test("modal opens and Close works without AvatarRuntime",()=>{ const h=harness(); h.elements.avatarCreateBtn.onclick(); assert.equal(h.elements.avatarModal.classList.values.has("hidden"),false); h.elements.closeAvatarModalBtn.onclick(); assert.equal(h.elements.avatarModal.classList.values.has("hidden"),true); assert.equal(h.elements.avatarDiagControls.textContent,"READY"); });
test("Avaturn is opened synchronously from the tap without AvatarRuntime",()=>{ let duringClick=false,called=false; const h=harness({open:url=>{called=duringClick; assert.equal(url,"https://www.avaturn.me/"); return {};}}); duringClick=true; h.elements.launchAvaturnBtn.onclick(); duringClick=false; assert.equal(called,true); assert.equal(h.elements.avatarDiagLaunch.textContent,"OPENED"); });
test("blocked Avaturn launch is visibly reported",()=>{ const h=harness({open:()=>null}); h.elements.launchAvaturnBtn.onclick(); assert.equal(h.elements.avatarDiagLaunch.textContent,"FAILED"); assert.match(h.elements.avatarDiagError.textContent,/could not open/i); });
test("file change displays filename, size, type, and READY",()=>{ const h=harness(); h.elements.avatarFileInput.files=[{name:"model 2.glb",size:2048,type:"model/gltf-binary"}]; h.elements.avatarFileInput.onchange(); assert.match(h.elements.avatarDiagFile.textContent,/model 2\.glb — 2\.0 KB — model\/gltf-binary/); assert.equal(h.elements.avatarDiagUpload.textContent,"READY"); });
test("one upload runs while pending and success is visible",async()=>{ let calls=0,release; const pending=new Promise(resolve=>release=resolve); const h=harness({profile:{uploadAvatarFile:async()=>{calls++; await pending; return {ok:true};}}}); const first=h.elements.uploadAvatarBtn.onclick(),second=h.elements.uploadAvatarBtn.onclick(); assert.equal(calls,1); assert.equal(await second,false); release(); assert.equal(await first,true); assert.equal(h.elements.avatarDiagUpload.textContent,"SUCCESS"); assert.equal(h.elements.uploadAvatarBtn.disabled,false); });
test("server and network upload failures are visible",async()=>{ for(const reason of ["incompatible GLB: required humanoid skeleton missing","Network request failed"]){ const h=harness({profile:{uploadAvatarFile:async()=>{throw new Error(reason);}}}); assert.equal(await h.elements.uploadAvatarBtn.onclick(),false); assert.equal(h.elements.avatarDiagUpload.textContent,"FAILED"); assert.equal(h.elements.avatarDiagError.textContent,reason); } });
test("profile save and remove success/failure are visible",async()=>{ const success=harness({profile:{saveAvatarFromInputs:async()=>({ok:true}),clearAvatarMetadata:async()=>({ok:true})}}); await success.elements.saveAvatarBtn.onclick(); assert.equal(success.elements.avatarDiagProfile.textContent,"SUCCESS"); await success.elements.clearAvatarBtn.onclick(); assert.equal(success.elements.avatarDiagProfile.textContent,"SUCCESS"); const failure=harness({profile:{saveAvatarFromInputs:async()=>{throw new Error("profile save failure")},clearAvatarMetadata:async()=>({ok:false,reason:"owner rejected"})}}); await failure.elements.saveAvatarBtn.onclick(); assert.equal(failure.elements.avatarDiagProfile.textContent,"FAILED"); await failure.elements.clearAvatarBtn.onclick(); assert.match(failure.elements.avatarDiagError.textContent,/owner rejected/); });
test("optional runtime failure leaves handlers attached and rebinding does not duplicate",async()=>{ let uploads=0; const h=harness({runtime:{ensureThreeModules:async()=>{throw new Error("Three unavailable")}},profile:{uploadAvatarFile:async()=>{uploads++;return {ok:true}}}}); const close=h.elements.closeAvatarModalBtn.onclick,upload=h.elements.uploadAvatarBtn.onclick; h.elements.avatarCreateBtn.onclick(); await new Promise(resolve=>setImmediate(resolve)); assert.equal(h.elements.avatarDiagRuntime.textContent,"FAILED"); assert.equal(h.elements.closeAvatarModalBtn.onclick,close); h.window.WorkoutControlActivation.bind(); assert.equal(typeof h.elements.uploadAvatarBtn.onclick,"function"); await h.elements.uploadAvatarBtn.onclick(); assert.equal(uploads,1); });
test("runtime configuration does not claim modal button ownership",()=>{ const source=fs.readFileSync(path.join(__dirname,"../public/avatar-runtime.js"),"utf8"); const bind=source.slice(source.indexOf("function bindControls"),source.indexOf("function handlePosePacket")); assert.doesNotMatch(bind,/\.onclick\s*=/); });
test("upload contract remains authenticated, owner-scoped, and auto-saves profile",()=>{ const client=fs.readFileSync(path.join(__dirname,"../public/profile-write-runtime.js"),"utf8"),server=fs.readFileSync(path.join(__dirname,"../server.js"),"utf8"); assert.match(client,/authorization: `Bearer \$\{authToken\}`/); assert.match(client,/saveProfileToNode\(\{ source: "avatar-upload", allowLegacyFallback: false/); assert.match(server,/app\.post\("\/api\/avatar\/upload", requireAuth/); assert.match(server,/ownerUserId: req\.auth\.userId/); });
test("rendering is attempted only after authenticated profile save",()=>{ const source=fs.readFileSync(path.join(__dirname,"../public/profile-write-runtime.js"),"utf8"),flow=source.slice(source.indexOf("async function uploadAvatarFile"),source.indexOf("async function clearAvatarMetadata")); assert.ok(flow.indexOf('saveProfileToNode({ source: "avatar-upload"') < flow.indexOf('refreshAvatarAsset("uploaded_file")')); });
