"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {createChallengeEngineService}=require("../src/services/challengeEngineService");
const {normalizeEnrollment,buildCommitmentSchedule}=require("../src/program-engine/challengeCommitmentScheduler");
const {createApp}=require("../server");
function store(state){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"challenge-reliability-")),file=path.join(dir,"runtime.json");if(state)fs.writeFileSync(file,JSON.stringify(state));return file;}
function enrollment(){return{workoutsPerWeek:3,preferredWeekdays:["friday","sunday","tuesday"],startDate:"2026-08-21"};}
async function withServer(run){const file=store(),app=createApp({rootDir:path.join(__dirname,".."),challengeEnginePath:file,allowInsecureTestRoutes:true}),server=app.listen(0);await new Promise(resolve=>server.once("listening",resolve));try{await run(`http://127.0.0.1:${server.address().port}`);}finally{await new Promise(resolve=>server.close(resolve));}}
async function request(base,route,{method="GET",token,body}={}){const response=await fetch(base+route,{method,headers:{...(token?{authorization:`Bearer ${token}`}:{}),...(body?{"content-type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});return{response,json:await response.json().catch(()=>null)};}
async function login(base,user){const result=await request(base,"/api/auth/login",{method:"POST",body:{email:"fixture@example.test",password:"top-secret",testUserId:user}});assert.equal(result.response.status,200);return result.json.token;}
test("static challenge library uses canonical backend client, public auth mode, static-safe links, and diagnostic errors",()=>{const html=fs.readFileSync(path.join(__dirname,"../public/challenges.html"),"utf8"),js=fs.readFileSync(path.join(__dirname,"../public/challenges.js"),"utf8");assert.match(html,/api-client\.js/);assert.match(html,/mufasa-fitness-node\.onrender\.com/);assert.match(js,/MaatApiClient\.request/);assert.match(js,/auth:false/);assert.match(js,/ChallengeRouteContract\.challengePageUrl/);assert.match(js,/console\.error\("Challenge library request failed"/);assert.match(js,/Challenges are temporarily unavailable/);});
test("weekday controls expose all labels, selection semantics, exact-count validation, deselection, and submit states",()=>{const js=fs.readFileSync(path.join(__dirname,"../public/challenge-page.js"),"utf8"),css=fs.readFileSync(path.join(__dirname,"../public/challenges.css"),"utf8");for(const day of ["sunday","monday","tuesday","wednesday","thursday","friday","saturday"])assert.match(js,new RegExp(`"${day}"`));assert.match(js,/type="checkbox"/);assert.match(js,/aria-label=/);assert.match(js,/check\.checked=false/);assert.match(js,/selected\.length!==commitment/);assert.match(js,/Building your schedule/);assert.match(js,/Submitting your commitment/);assert.match(css,/input:focus-visible\+span/);assert.match(css,/color:#111827/);assert.match(css,/min-height:52px/);});
test("date-only enrollment keeps Friday 2026-08-21 and selected weekdays without timezone shifts",()=>{const normalized=normalizeEnrollment(enrollment());assert.equal(normalized.startDate,"2026-08-21");const schedule=buildCommitmentSchedule(enrollment()).schedule;assert.equal(schedule[0].weekday,"friday");assert.equal(schedule[0].plannedDate,"2026-08-21");assert.deepEqual(schedule.filter(x=>x.weekNumber===1&&x.type==="workout").map(x=>x.weekday),["friday","sunday","tuesday"]);});
test("legacy kettlebell recovery preserves enrollment progress and is retry-safe",()=>{const file=store({schemaVersion:1,userChallenges:[{id:"legacy",userId:"owner",challengeId:"challenge_kettlebell_8_week",status:"active",currentDay:9,currentWeek:2,completionPercent:17,totalXpEarned:425,createdAt:"2026-08-01T00:00:00Z"}],dayLogs:[{id:"log",userChallengeId:"legacy",challengeDayId:"kb_day_1",status:"completed"}],activityLogs:[],personalRecords:[],assessments:[]}),service=createChallengeEngineService({filePath:file,clock:()=>new Date("2026-08-21T12:00:00Z")});const recovered=service.joinChallenge("owner","8-week-kettlebell-strength-power",enrollment()),again=service.joinChallenge("owner","8-week-kettlebell-strength-power",enrollment()),state=service._read();assert.equal(recovered.recovered,true);assert.equal(again.recovered,false);assert.equal(state.userChallenges.length,1);assert.equal(state.userChallenges[0].id,"legacy");assert.equal(state.userChallenges[0].currentDay,9);assert.equal(state.userChallenges[0].totalXpEarned,425);assert.equal(state.dayLogs.length,1);assert.equal(state.userChallenges[0].commitmentSchedule.length,56);});
test("authenticated Push-Up and Squat joins succeed and challenge-scoped current state does not collide",async t=>{const old={n:process.env.NODE_ENV,f:process.env.AUTH_TEST_LOGIN_FIXTURE_ENABLED,p:process.env.PILOT_LOGIN_PASSWORD};process.env.NODE_ENV="test";process.env.AUTH_TEST_LOGIN_FIXTURE_ENABLED="true";process.env.PILOT_LOGIN_PASSWORD="top-secret";t.after(()=>{old.n==null?delete process.env.NODE_ENV:process.env.NODE_ENV=old.n;old.f==null?delete process.env.AUTH_TEST_LOGIN_FIXTURE_ENABLED:process.env.AUTH_TEST_LOGIN_FIXTURE_ENABLED=old.f;old.p==null?delete process.env.PILOT_LOGIN_PASSWORD:process.env.PILOT_LOGIN_PASSWORD=old.p;});await withServer(async base=>{const token=await login(base,"generic-owner");for(const slug of ["push-up-21","squat-21"]){const joined=await request(base,`/api/me/challenges/${slug}/join`,{method:"POST",token,body:{}});assert.equal(joined.response.status,201);const current=await request(base,`/api/me/challenges/${slug}/current`,{token});assert.equal(current.response.status,200);assert.equal(current.json.data.challenge.slug,slug);}const unauth=await request(base,"/api/me/challenges/push-up-21/current");assert.equal(unauth.response.status,401);});});
test("legacy route recovery is authenticated, owner scoped, and idempotent",async t=>{const old={n:process.env.NODE_ENV,f:process.env.AUTH_TEST_LOGIN_FIXTURE_ENABLED,p:process.env.PILOT_LOGIN_PASSWORD};process.env.NODE_ENV="test";process.env.AUTH_TEST_LOGIN_FIXTURE_ENABLED="true";process.env.PILOT_LOGIN_PASSWORD="top-secret";t.after(()=>{old.n==null?delete process.env.NODE_ENV:process.env.NODE_ENV=old.n;old.f==null?delete process.env.AUTH_TEST_LOGIN_FIXTURE_ENABLED:process.env.AUTH_TEST_LOGIN_FIXTURE_ENABLED=old.f;old.p==null?delete process.env.PILOT_LOGIN_PASSWORD:process.env.PILOT_LOGIN_PASSWORD=old.p;});await withServer(async base=>{const owner=await login(base,"legacy-owner"),attacker=await login(base,"legacy-attacker"),first=await request(base,"/api/me/challenges/8-week-kettlebell-strength-power/join",{method:"POST",token:owner,body:enrollment()}),repeat=await request(base,"/api/me/challenges/8-week-kettlebell-strength-power/join",{method:"POST",token:owner,body:enrollment()});assert.equal(first.response.status,201);assert.equal(repeat.response.status,200);assert.equal(first.json.data.participation.id,repeat.json.data.participation.id);const denied=await request(base,`/api/me/challenges/${first.json.data.participation.id}/commitment-sessions/commitment_w1_s1/reschedule`,{method:"PATCH",token:attacker,body:{targetDate:"2026-08-22"}});assert.equal(denied.response.status,404);});});
