"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {createChallengeEngineService,calculateChallengeProgress,calculateChallengeAdherence,calculateStreak,calculateChallengeScore,trainingVolume}=require("../src/services/challengeEngineService");
const {challengeDefinitions}=require("../data/challenges/seeds");
const kettlebellEnrollment={workoutsPerWeek:3,preferredWeekdays:["tuesday","thursday","saturday"],startDate:"2026-08-18"};
function harness(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"challenge-engine-"));const events=[];return{events,service:createChallengeEngineService({filePath:path.join(dir,"runtime.json"),clock:()=>new Date("2026-08-20T12:00:00Z"),onWorkoutCompleted:fact=>events.push(fact)})}}
test("joining is user-owned and idempotent",()=>{const {service}=harness(),first=service.joinChallenge("a","8-week-kettlebell-strength-power",kettlebellEnrollment),again=service.joinChallenge("a","8-week-kettlebell-strength-power",kettlebellEnrollment),other=service.joinChallenge("b","8-week-kettlebell-strength-power",kettlebellEnrollment);assert.equal(first.created,true);assert.equal(again.created,false);assert.equal(first.participation.id,again.participation.id);assert.notEqual(other.participation.id,first.participation.id)});
test("kettlebell enrollment persists commitment and recovery schedule",()=>{const {service}=harness(),joined=service.joinChallenge("a","8-week-kettlebell-strength-power",kettlebellEnrollment).participation,reloaded=service.active("a");assert.equal(joined.commitment.promisedWorkouts,24);assert.equal(reloaded.participation.commitmentSchedule.length,56);assert.equal(reloaded.participation.commitmentSchedule.filter(x=>x.weekNumber===1&&x.type==="workout").length,3);assert.equal(reloaded.participation.commitmentSchedule.filter(x=>x.weekNumber===1&&x.type==="recovery").length,4);assert.equal(reloaded.commitmentSummary.promisedWorkouts,24)});
test("owner rescheduling persists while unsafe spacing is rejected",()=>{const {service}=harness(),joined=service.joinChallenge("a","8-week-kettlebell-strength-power",kettlebellEnrollment).participation,active=service.active("a"),missed=active.participation.commitmentSchedule.find(x=>x.state==="makeup_available");assert.throws(()=>service.rescheduleCommitment("b",joined.id,missed.scheduleSessionId,{targetDate:"2026-08-23"}),/not found/);assert.throws(()=>service.rescheduleCommitment("a",joined.id,missed.scheduleSessionId,{targetDate:"2026-08-21"}),/three consecutive/);service.rescheduleCommitment("a",joined.id,missed.scheduleSessionId,{targetDate:"2026-08-23"});const saved=service.active("a").participation.commitmentSchedule.find(x=>x.scheduleSessionId===missed.scheduleSessionId);assert.equal(saved.state,"rescheduled");assert.equal(saved.originalPlannedDate,"2026-08-18");assert.equal(saved.plannedDate,"2026-08-23")});
test("kettlebell enrollment rejects absent or excessive commitment",()=>{const {service}=harness();assert.throws(()=>service.joinChallenge("a","8-week-kettlebell-strength-power"),/workoutsPerWeek/);assert.throws(()=>service.joinChallenge("a","8-week-kettlebell-strength-power",{workoutsPerWeek:5,preferredWeekdays:["monday"],startDate:"2026-08-18"}),/1 to 4/)});
test("completion awards server XP once and advances progress",()=>{const {service,events}=harness(),joined=service.joinChallenge("a","8-week-kettlebell-strength-power",kettlebellEnrollment).participation,active=service.active("a"),first=service.completeDay("a",joined.id,active.todaysMission.id,{sessionRpe:7}),duplicate=service.completeDay("a",joined.id,active.todaysMission.id,{sessionRpe:7});assert.equal(first.xpAwarded,100);assert.ok(first.progress>0);assert.equal(duplicate.xpAwarded,0);assert.equal(events.length,1)});
test("progress, adherence and recovery-day streak use required workout days",()=>{const challenge=challengeDefinitions[0],logs=[{challengeDayId:"kb_day_1",status:"completed"},{challengeDayId:"kb_day_3",status:"completed_late"}];assert.equal(calculateChallengeProgress(challenge,logs),8);assert.equal(calculateChallengeAdherence(challenge,logs,3),100);assert.deepEqual(calculateStreak(challenge,logs),{currentStreak:2,longestStreak:2})});
test("a skipped required workout breaks a streak but a recovery day does not",()=>{const challenge=challengeDefinitions[0],logs=[{challengeDayId:"kb_day_1",status:"completed"},{challengeDayId:"kb_day_3",status:"skipped"},{challengeDayId:"kb_day_5",status:"completed"}];assert.deepEqual(calculateStreak(challenge,logs),{currentStreak:1,longestStreak:1})});
test("score normalizes missing dimensions and volume supports set detail",()=>{assert.equal(calculateChallengeScore({consistency:100,technique:50}),86);assert.equal(trainingVolume({sets:[{reps:10,weight:12},{reps:8,weight:12}]}),216)});
test("activity validation and authorization protect member progress",()=>{const {service}=harness(),joined=service.joinChallenge("a","8-week-kettlebell-strength-power",kettlebellEnrollment).participation,activity=service.active("a").todaysMission.activities[0];assert.throws(()=>service.logActivity("b",joined.id,activity.id,{repsCompleted:5}),/Active challenge not found/);assert.throws(()=>service.logActivity("a",joined.id,activity.id,{weightUsed:-1}),/non-negative/);const result=service.logActivity("a",joined.id,activity.id,{completed:true,repsCompleted:10,weightUsed:12,rpe:7});assert.equal(result.activityLog.userId,"a")});
test("personal records are detected server-side",()=>{const {service}=harness(),joined=service.joinChallenge("a","push-up-21").participation,activity=service.active("a").todaysMission.activities[0],first=service.logActivity("a",joined.id,activity.id,{completed:true,repsCompleted:10}),lower=service.logActivity("a",joined.id,activity.id,{completed:true,repsCompleted:8}),higher=service.logActivity("a",joined.id,activity.id,{completed:true,repsCompleted:12});assert.equal(first.personalRecord.value,10);assert.equal(lower.personalRecord,null);assert.equal(higher.personalRecord.value,12)});
