"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const {rankRoutes,candidate}=require("../src/services/walkingRouteService");
test("challenge-aware ranking prefers verified, feasible, low-error routes",()=>{const options=[{routeSource:"place_only"},{routeSource:"google_walking_route",withinTolerance:true,distanceErrorPercent:1},{routeSource:"verified_geometry",withinTolerance:true,distanceErrorPercent:2}];assert.equal(rankRoutes(options)[0].routeSource,"verified_geometry");});
test("deterministic generation supports loop-like and out-and-back shapes",()=>{const point={latitude:32.9,longitude:-96.8};assert.equal(candidate({place:point,start:point,target:3218,routeType:"loop",attempt:0,maxRadius:5000}).waypoints.length,2);const out=candidate({place:point,start:point,target:1609,routeType:"out_and_back",attempt:0,maxRadius:5000});assert.equal(out.waypoints.length,1);assert.ok(out.turnaroundPoint);});
test("route UI clears stale routes, renders warnings, mobile controls and route association",()=>{const js=fs.readFileSync(path.join(__dirname,"../public/greatness.js"),"utf8"),html=fs.readFileSync(path.join(__dirname,"../public/greatness.html"),"utf8"),css=fs.readFileSync(path.join(__dirname,"../public/greatness.css"),"utf8");for(const text of ["clearPlannedRoute","Google walking route","Use this route","Try another route","Change starting point","Start activity","Halfway point reached","One loop completed","Nearby related places","selectedRoute"])assert.match(js,new RegExp(text));assert.match(html,/challengeRouteSuggestions/);assert.match(css,/@media\(max-width:650px\)/);});
test("authorization contract contains every new route",()=>{const server=fs.readFileSync(path.join(__dirname,"../server.js"),"utf8");for(const route of ["goal-routes","goal-routes/alternatives","route-suggestions","activities/start-with-route"])assert.match(server,new RegExp(route.replaceAll("/","\\/")));assert.match(server,/start-with-route", requireAuth/);});
test("authorization contract classifies all goal routes as authenticated private endpoints",()=>{const contract=require("../config/route-authorization-contract");const expected=["/api/me/greatness/activities/start-with-route","/api/me/greatness/challenges/:challengeId/route-suggestions","/api/me/greatness/trails/:trailId/goal-routes","/api/me/greatness/trails/:trailId/goal-routes/alternatives"];for(const routePath of expected){const entry=contract.find(item=>item.method==="POST"&&item.path===routePath);assert.ok(entry,routePath);assert.equal(entry.authentication,"required");assert.ok(["sensitive-private","generated-route-options"].includes(entry.publicOutput));}});
test("invalid route-planning environment values fall back to bounded integer defaults",()=>{const {DEFAULTS,loadRoutePlanningConfig}=require("../src/config/routePlanningConfig");const config=loadRoutePlanningConfig({TRAIL_ROUTE_MAX_CANDIDATES:"2.5",TRAIL_ROUTE_MAX_GRAPH_NODES:"Infinity",GOOGLE_WALKING_ROUTE_TIMEOUT_MS:"999999",TRAIL_ROUTE_MAX_OFF_TRAIL_PERCENT:"0"});assert.equal(config.TRAIL_ROUTE_MAX_CANDIDATES,DEFAULTS.TRAIL_ROUTE_MAX_CANDIDATES);assert.equal(config.TRAIL_ROUTE_MAX_GRAPH_NODES,DEFAULTS.TRAIL_ROUTE_MAX_GRAPH_NODES);assert.equal(config.GOOGLE_WALKING_ROUTE_TIMEOUT_MS,DEFAULTS.GOOGLE_WALKING_ROUTE_TIMEOUT_MS);assert.equal(config.TRAIL_ROUTE_MAX_OFF_TRAIL_PERCENT,0);});
