"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("fs"),os=require("os"),path=require("path");
const {createUserStore}=require("../src/repositories/userStore");
const {createClientMessagingStore}=require("../src/repositories/clientMessagingStore");
const {createClientCrmService}=require("../src/services/clientCrmService");
const {createAuthorizationResolver}=require("../src/lib/authorization");

function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"crm-")),users=createUserStore({userDir:path.join(dir,"users")});for(let i=1;i<=3;i++)users.saveUser({userId:`member${i}`,createdAt:Date.now()-i*86400000,updatedAt:i===1?Date.now():Date.now()-40*86400000,profile:{displayName:`Member ${i}`,email:`m${i}@test.local`},membership:{status:i===1?"active":"inactive"},journeyProfile:i===1?{submittedAt:new Date().toISOString(),primaryGoal:"strength"}:{},assessments:i===1?[{id:"a1",status:"completed",completedAt:new Date().toISOString()}]:[],sessions:i===1?{s1:{id:"s1",status:"completed",completedAt:new Date().toISOString()}}:{},ohsa:[],events:[]});const assigned=new Set(["member1"]),workspace={hasActiveAccess:(a,c)=>a==="coach"&&assigned.has(c)},messages=createClientMessagingStore({filePath:path.join(dir,"messages.json")}),authz=createAuthorizationResolver({adminEmails:[],bootstrap:{superAdminUserIds:[],superAdminSubjects:[]},roleAssignments:{adminUserIds:[],adminSubjects:[],trainerUserIds:[],trainerSubjects:[]}}),service=createClientCrmService({userStore:users,authCredentialStore:{listIdentities:()=>[]},membershipService:{getMembership:id=>users.loadUser(id).membership||{}},trainerWorkspaceStore:workspace,messagingStore:messages,authorizationResolver:authz});return{service,messages};}
test("admin directory uses authoritative totals, filters, search, and pagination",()=>{const{service}=fixture(),actor={userId:"admin",role:"admin"};const first=service.directory(actor,{pageSize:2,page:1});assert.equal(first.metrics.totalMembers,3);assert.equal(first.members.length,2);assert.equal(first.pagination.totalPages,2);assert.equal(service.directory(actor,{pageSize:2,page:2}).members.length,1);assert.equal(service.directory(actor,{filter:"paid"}).pagination.total,1);assert.equal(service.directory(actor,{filter:"inactive"}).pagination.total,2);assert.equal(service.directory(actor,{search:"m3@test"}).members[0].userId,"member3");});
test("trainer scope and sensitive projections deny unassigned clients",()=>{const{service}=fixture(),coach={userId:"coach",role:"trainer"};assert.deepEqual(service.directory(coach).members.map(x=>x.userId),["member1"]);assert.throws(()=>service.intake(coach,"member2"),/not permitted/);assert.equal(service.intake(coach,"member1").intake.primaryGoal,"strength");assert.equal(service.assessments(coach,"member1").assessments.length,1);});
test("participant-only messaging validates content, unread and spoof-resistant sender",()=>{const{service}=fixture(),admin={userId:"admin",role:"admin"},member={userId:"member1",role:"user"},attacker={userId:"member2",role:"user"};const c=service.conversation(admin,"member1",true),sent=service.send(admin,c.id,"<script>alert(1)</script>");assert.equal(sent.senderUserId,"admin");assert.equal(service.directory(admin,{filter:"unread"}).members.length,0);assert.throws(()=>service.viewMessages(attacker,c.id),/not found/);assert.throws(()=>service.send(member,c.id," "),/1-4000/);assert.throws(()=>service.send(member,c.id,"x".repeat(4001)),/1-4000/);service.send(member,c.id,"reply");assert.equal(service.directory(admin,{filter:"unread"}).members[0].unreadMessages,1);const view=service.viewMessages(admin,c.id);assert.equal(view.messages[0].body,"<script>alert(1)</script>");assert.ok(view.messages.every(m=>m.createdAt));assert.ok(view.messages.find(m=>m.senderUserId==="member1").readAt);});
