"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
const {createControlledLiveService}=require("../src/business-os/real-world/controlled-live");
const {createCommandCenterService}=require("../src/business-os/command/service");
const ORDER=["CLARKE","BEN_JOCHANNAN","MALCOLM_X","GARVEY","PAYTON","ALI","THOTH","MAAT"];
function councilBrain(claimFactory){return {available:true,async understand(){return {ok:true,intent:{intent:"full council",informationNeeds:["architecture","financial sustainability","community outcomes"],toolNames:["get_diagnostics","get_evidence"],contextReferences:[],actionRequested:false,limitations:[]},contextPackage:{items:[]}}},async reason({evidence}){return {ok:true,content:{answer:"unsafe raw answer",facts:[],inferences:[],unknowns:[],recommendations:[],authorityRequirements:[],assumptions:[],limitations:[],materialGaps:[],claims:ORDER.map((seat,index)=>claimFactory(seat,index,evidence))},gateway:{result:{metacognitiveState:"SUFFICIENT_EVIDENCE"},invocations:[]}}},remember(){return {ok:true}}}}
function service(brain){return createCommandCenterService({controlledLiveService:createControlledLiveService(),brain,architectureReader:()=>[{source:"canonical.md",content:"The kernel denies action without authority.",evidenceKind:"ARCHITECTURE"}]})}
test("Full Council downgrades unsupported factual findings and reports material gaps despite ten sources",async()=>{const brain=councilBrain(seat=>({seat,findingType:"RISK",statement:"The business has a single revenue stream and discriminatory outcomes.",classification:"OBSERVED_FACT",evidenceRefs:["command-evidence:get_command_summary:1"],evidenceQuotes:["not present"]}));const r=await service(brain).converse({actor:{userId:"owner"},question:"Give me the full council assessment",conversationId:"ground"});assert.equal(r.evidence.length,10);assert.ok(r.claims.every(c=>c.classification==="UNKNOWN"));assert.ok(r.materialGaps.length);assert.match(r.answer,/MATERIAL GAPS/);assert.doesNotMatch(r.answer,/\[OBSERVED_FACT\].*single revenue stream/)});
test("Full Council retains claim provenance and architecture/runtime evidence distinction",async()=>{const brain=councilBrain((seat,index,evidence)=>({seat,findingType:"STRENGTH",statement:index?"Further review is recommended.":"The kernel denies action without authority.",classification:index?"RECOMMENDATION":"OBSERVED_FACT",evidenceRefs:index?[]:[evidence.find(e=>e.evidenceKind==="ARCHITECTURE").id],evidenceQuotes:index?[]:["The kernel denies action without authority."]}));const r=await service(brain).converse({actor:{userId:"owner"},question:"Ask every Council perspective",conversationId:"provenance"});assert.ok(r.evidence.some(e=>e.evidenceKind==="ARCHITECTURE"));assert.ok(r.evidence.some(e=>e.evidenceKind==="RUNTIME_OPERATIONAL"));assert.equal(r.claims[0].classification,"OBSERVED_FACT");assert.deepEqual(r.claims[0].evidenceRefs,[r.evidence.find(e=>e.evidenceKind==="ARCHITECTURE").id]);assert.deepEqual(r.claims.map(c=>c.seat),ORDER)});
test("Full Council fails closed when an ordered seat is absent",async()=>{const brain=councilBrain((seat,index)=>({seat:index===7?null:seat,findingType:"GENERAL",statement:"Review.",classification:"RECOMMENDATION",evidenceRefs:[],evidenceQuotes:[]}));await assert.rejects(()=>service(brain).converse({actor:{userId:"owner"},question:"full council please",conversationId:"closed"}),/COUNCIL_CLAIM_GROUNDING_FAILURE/)});
function voiceHarness(request){const events=[],audio={paused:true,src:"",currentTime:0,removeAttribute(){this.src=""},pause(){this.paused=true},play(){this.paused=false;return Promise.resolve()}};const scope={URL:{createObjectURL:()=>"blob:voice",revokeObjectURL(){}},document:{createElement:()=>audio},setImmediate};scope.globalThis=scope;vm.runInNewContext(fs.readFileSync(path.join(__dirname,"../public/command-voice-runtime.js"),"utf8"),scope);return {runtime:scope.CommandVoiceRuntime.create({audio,request,onStatus:e=>events.push(e)}),audio,events,api:scope.CommandVoiceRuntime}}
test("AI voice lifecycle uses authenticated backend abstraction, strips diagnostics, and supports pause resume stop",async()=>{let spoken="";const h=voiceHarness(async(_url,o)=>{spoken=o.body.text;return {ok:true,response:{blob:async()=>({})}}});const pending=h.runtime.play("Answer for owner. (command-evidence:get_x:0)\nBRAIN CONNECTED · LATENCY 2ms");await new Promise(r=>setImmediate(r));assert.equal(h.runtime.pause(),true);assert.equal(h.runtime.resume(),true);h.runtime.stop();assert.doesNotMatch(spoken,/command-evidence|LATENCY/);assert.ok(h.events.some(e=>e.state==="SPEAKING"));assert.equal((await pending).cancelled,true)});
test("AI voice exposes authentication and playback FIRST FAILURE without changing text",async()=>{const auth=voiceHarness(async()=>({ok:false,response:{status:401}}));const result=await auth.runtime.play("Canonical text remains available.");assert.equal(result.code,"VOICE_AUTHENTICATION_FAILURE");assert.equal(auth.events.at(-1).firstFailure.code,"VOICE_AUTHENTICATION_FAILURE");const playback=voiceHarness(async()=>({ok:true,response:{blob:async()=>({})}}));playback.audio.play=()=>Promise.reject(Error("blocked"));const failed=await playback.runtime.play("Still readable");assert.equal(failed.code,"VOICE_PLAYBACK_FAILURE")});
