"use strict";
const test = require("node:test"), assert = require("node:assert/strict");
const { classifyBuilds, aiStatic, buildLaunchHealth } = require("../src/diagnostics/launchHealthService");
test("build compatibility requires exact available identifiers", () => { assert.equal(classifyBuilds({ frontendBuild: "2026-07-31-launch-readiness", backendBuild: "2026-07-31-launch-readiness" }).compatible, true); assert.equal(classifyBuilds({ frontendBuild: "2026-07-31-a", backendBuild: "2026-07-31-b" }).compatible, false); assert.equal(classifyBuilds({ frontendBuild: "", backendBuild: "x" }).compatible, null); });
test("AI Coach and summarizer readiness are independent and secret-free", () => { const env = { AI_COACH_ENABLED: "true", AI_COACH_MODEL: "coach-model", AI_COACH_PROVIDER: "openai", OPENAI_API_KEY: "secret", DIAGNOSTIC_SUMMARIZER_ENABLED: "true" }; assert.equal(aiStatic(env, "AI_COACH").staticReadiness, "READY"); assert.equal(aiStatic(env, "DIAGNOSTIC_SUMMARIZER").staticReadiness, "CONFIGURATION_MISSING"); assert.doesNotMatch(JSON.stringify(aiStatic(env, "AI_COACH")), /secret/); });

test("external results remain capability-specific", () => { const env={AI_COACH_ENABLED:"true",AI_COACH_MODEL:"coach",OPENAI_API_KEY:"secret",DIAGNOSTIC_SUMMARIZER_ENABLED:"true",DIAGNOSTIC_SUMMARIZER_MODEL:"summary"}; assert.equal(aiStatic(env,"AI_COACH",{status:"READY",checkedAt:"2026-08-01T00:00:00.000Z",latencyMs:12}).liveReachability,"READY"); assert.equal(aiStatic(env,"DIAGNOSTIC_SUMMARIZER",{status:"RATE_LIMITED",checkedAt:"2026-08-01T00:00:00.000Z",latencyMs:9}).failureClassification,"RATE_LIMITED"); });
test("disabled Avatar presentation suppresses stale repair classifications",()=>{const fs=require("node:fs"),path=require("node:path"),dashboard=fs.readFileSync(path.join(__dirname,"../public/dashboard.js"),"utf8"),landing=fs.readFileSync(path.join(__dirname,"../public/landing-diagnostics.js"),"utf8");assert.match(dashboard,/DISABLED_INTENTIONALLY/);assert.match(dashboard,/capability not requested on this page/);assert.match(dashboard,/filter\(line => launchHealth\?\.avatar\?\.enabled !== false/);assert.match(landing,/filter\(line => avatarEnabled/);});

test("cache-token mismatch blocks compatibility while deployed freshness stays unclaimed",()=>{const report=buildLaunchHealth({env:{},rootDir:process.cwd(),dataDir:process.cwd(),frontendBuild:"2026-07-31-launch-readiness",backendBuild:"2026-07-31-launch-readiness",assetCacheToken:"stale",expectedAssetCacheToken:"current"});assert.equal(report.builds.compatibilityResult,"BLOCKED");assert.equal(report.builds.staticCacheTokenAligned,false);assert.equal(report.builds.deployedCacheFreshness,"UNKNOWN_UNTIL_CLIENT_EVIDENCE");});
