"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const runtime = require("../public/motion/disposable-motion-session");
const loaderModule = require("../public/motion/shared3d-loader");

function target(extra = {}) { const events = new Map(); return Object.assign({ addEventListener(type, fn) { events.set(type, fn); }, removeEventListener(type, fn) { if (events.get(type) === fn) events.delete(type); }, dispatch(type, event = {}) { events.get(type)?.(event); }, eventCount: () => events.size }, extra); }
function harness() {
  let rafId = 0; const rafs = new Map();
  const document = target({ hidden: false, createElement: () => ({ getContext: () => ({}) }) });
  const env = target({ document, AbortController, devicePixelRatio: 3, requestAnimationFrame(fn) { const id = ++rafId; rafs.set(id, fn); return id; }, cancelAnimationFrame(id) { rafs.delete(id); }, setTimeout, clearTimeout });
  const container = { clientWidth: 2000, clientHeight: 1000, children: [], appendChild(node) { node.parentNode = this; this.children.push(node); }, removeChild(node) { this.children.splice(this.children.indexOf(node), 1); node.parentNode = null; } };
  class Disposable { dispose() { this.disposed = true; } }
  class Quaternion { constructor(x=0,y=0,z=0,w=1){this.x=x;this.y=y;this.z=z;this.w=w;} clone(){return new Quaternion(this.x,this.y,this.z,this.w);} multiply(){return this;} setFromEuler(){return this;} toArray(){return[this.x,this.y,this.z,this.w];} }
  class Euler { constructor(x,y,z,order){this.x=x;this.y=y;this.z=z;this.order=order;} }
  class Object3D { constructor() { this.children = [];this.position=new Vector3();this.quaternion=new Quaternion();this.name=""; } add(value) { this.children.push(value); } remove(value) { this.children=this.children.filter(child=>child!==value); } traverse(fn) { fn(this); this.children.forEach(child=>child.traverse?child.traverse(fn):fn(child)); } updateMatrixWorld(){} }
  class Scene extends Object3D {}
  class Vector3 { constructor(x=0,y=0,z=0){this.x=x;this.y=y;this.z=z;} set(x,y,z){this.x=x;this.y=y;this.z=z;} clone(){return new Vector3(this.x,this.y,this.z);} }
  class PerspectiveCamera { constructor(fov,aspect,near,far) { this.fov=fov;this.aspect=aspect;this.near=near;this.far=far;this.position = new Vector3(); } updateProjectionMatrix() {} lookAt(x,y,z){this.target={x,y,z};} }
  class Color { constructor(value){this.value=value;} }
  class Light extends Object3D { constructor(color,intensity){super();this.color=color;this.intensity=intensity;this.position=new Vector3();} }
  class HemisphereLight extends Light { constructor(sky,ground,intensity){super(sky,intensity);this.ground=ground;} }
  class DirectionalLight extends Light {}
  class Box3 { setFromObject(root){this.root=root;return this;} getSize(out){return Object.assign(out,this.root.testSize||{x:1,y:2,z:.5});} getCenter(out){return Object.assign(out,this.root.testCenter||{x:0,y:1,z:0});} }
  class BoxGeometry extends Disposable {}
  class MeshBasicMaterial extends Disposable { constructor() { super(); } }
  class Mesh { constructor(geometry, material) { this.geometry = geometry; this.material = material; this.rotation = { y: 0 }; this.visible=true; } }
  class Clock { getDelta(){return 0.016;} }
  class AnimationMixer { constructor(root){this.root=root;} clipAction(clip){const action={clip,paused:false,play(){this.played=true;return this;},stop(){this.stopped=true;},reset(){this.resetCalled=true;return this;},setLoop(mode,count){this.loop=[mode,count];}};return action;} update(delta){this.delta=delta;} stopAllAction(){this.stopped=true;} }
  class QuaternionKeyframeTrack {constructor(name,times,values){this.name=name;this.times=times;this.values=values;}}
  class VectorKeyframeTrack extends QuaternionKeyframeTrack {}
  class AnimationClip {constructor(name,duration,tracks){this.name=name;this.duration=duration;this.tracks=tracks;}}
  const renderers = [];
  class WebGLRenderer extends Disposable { constructor() { super(); this.domElement = target(); this.renderLists = new Disposable(); renderers.push(this); } setPixelRatio(v) { this.dpr = v; } setSize(w, h) { this.size = [w, h]; } render() {} forceContextLoss() { this.lost = true; } }
  const THREE = { Scene, PerspectiveCamera, Color, HemisphereLight, DirectionalLight, Box3, Vector3, Quaternion, Euler, BoxGeometry, MeshBasicMaterial, Mesh, WebGLRenderer, AnimationMixer, AnimationClip, QuaternionKeyframeTrack, VectorKeyframeTrack, MathUtils:{degToRad:value=>value*Math.PI/180}, InterpolateLinear:"linear", InterpolateSmooth:"smooth", Clock, LoopRepeat:"repeat", LoopOnce:"once" };
  const loader = { probeCapability: () => ({ supported: true, webgl: true }), loadThree: async ({ signal }) => { if (signal.aborted) throw Object.assign(new Error(), { code: "session_aborted" }); return THREE; } };
  return { env, container, loader, renderers, rafs, THREE };
}

test("capability probe returns structured unsupported results", () => {
  assert.deepEqual(loaderModule.probeCapability({}), { supported: false, webgl: false, reason: "required_api_unavailable" });
  const env = { document: { createElement: () => ({ getContext: () => null }) }, AbortController, requestAnimationFrame() {} };
  assert.deepEqual(loaderModule.probeCapability(env), { supported: false, webgl: false, reason: "webgl_unavailable" });
});

test("dependency and renderer failures normalize and dispose partial ownership", async () => {
  const one = harness(); const dependency = runtime.createMotionSession({ environment: one.env, loader: { ...one.loader, loadThree: async () => { throw Object.assign(new Error("no"), { code: "dependency_load_failed" }); } } });
  assert.equal((await dependency.start(one.container)).code, "dependency_load_failed"); assert.equal(dependency.state, "disposed");
  const two = harness(); const renderer = runtime.createMotionSession({ environment: two.env, loader: two.loader, injectFailure: "renderer_init" });
  assert.equal((await renderer.start(two.container)).code, "renderer_init_failed"); assert.equal(renderer.state, "disposed");
  assert.deepEqual(runtime.diagnostics(), { activeSessions: 0, activeRafs: 0, listeners: 0, timers: 0, canvases: 0 });
});

test("dispose during initialization aborts and ignores stale completion", async () => {
  const h = harness(); let release; h.loader.loadThree = () => new Promise(resolve => { release = resolve; });
  const session = runtime.createMotionSession({ environment: h.env, loader: h.loader }); const starting = session.start(h.container); session.dispose(); release({});
  assert.equal((await starting).code, "session_aborted"); session.dispose();
  assert.deepEqual(runtime.diagnostics(), { activeSessions: 0, activeRafs: 0, listeners: 0, timers: 0, canvases: 0 });
});

test("runtime throw and context loss stop the sole RAF and report safe failures", async () => {
  const h = harness(); let code; const session = runtime.createMotionSession({ environment: h.env, loader: h.loader, injectFailure: "runtime", onError: error => { code = error.code; } });
  await session.start(h.container); h.rafs.values().next().value(); assert.equal(code, "runtime_failed");
  const h2 = harness(); const context = runtime.createMotionSession({ environment: h2.env, loader: h2.loader, onError: error => { code = error.code; } });
  await context.start(h2.container); context.canvas.dispatch("webglcontextlost", { preventDefault() {} }); assert.equal(code, "context_lost");
  assert.deepEqual(runtime.diagnostics(), { activeSessions: 0, activeRafs: 0, listeners: 0, timers: 0, canvases: 0 });
});

test("40 complete start/dispose cycles leave no owned resources", async () => {
  for (let index = 0; index < 40; index++) { const h = harness(); const session = runtime.createMotionSession({ environment: h.env, loader: h.loader }); assert.equal((await session.start(h.container)).status, "ready"); assert.equal(h.renderers[0].dpr, 1.5); assert.deepEqual(h.renderers[0].size, [1280, 720]); session.dispose(); session.dispose(); assert.equal(h.container.children.length, 0); }
  assert.deepEqual(runtime.diagnostics(), { activeSessions: 0, activeRafs: 0, listeners: 0, timers: 0, canvases: 0 });
});

test("canonical avatar and independent clip are mixer-owned and bounded",async()=>{const h=harness(),bone={name:"mixamorig:Hips",isBone:true},skin={name:"Body",isSkinnedMesh:true},avatar=new h.THREE.Scene();avatar.add(bone);avatar.add(skin);const clip={name:"fixture",duration:2,tracks:[{name:"mixamorig:Hips.quaternion"}]};let requested=[];class GLTFLoader{async loadAsync(url){requested.push(url);return url.includes("avatar")?{scene:avatar,animations:[]}:{scene:new h.THREE.Scene(),animations:[clip]};}}h.loader.loadGLTFLoader=async()=>GLTFLoader;const session=runtime.createMotionSession({environment:h.env,loader:h.loader});await session.start(h.container);const loaded=await session.loadAvatar("avatar.glb");assert.deepEqual(loaded.diagnostics.boneNames,["mixamorig:Hips"]);const animation=await session.loadAnimation("fixture.glb");assert.equal(animation.diagnostics.unboundTrackCount,0);assert.equal(session.play().status,"playing");assert.equal(session.pause().status,"paused");assert.equal(session.resume().status,"playing");assert.equal(session.setLoop(false).loop,false);session.stop();assert.equal(session.restart().status,"playing");session.dispose();assert.deepEqual(requested,["avatar.glb","fixture.glb"]);assert.deepEqual(runtime.diagnostics(),{activeSessions:0,activeRafs:0,listeners:0,timers:0,canvases:0});});

test("50 complete push-up spec lifecycles leave avatar, clip, action, mixer, scene, and owned counters empty",async()=>{const contract=require("../public/motion/push-up-motion-spec"),compiler=require("../public/motion/motion-spec-clip");for(let index=0;index<50;index++){const h=harness(),avatar=new h.THREE.Scene();for(const name of contract.CANONICAL_BONES){const bone=new h.THREE.Scene();bone.name=name;bone.isBone=true;avatar.add(bone);}const skin=new h.THREE.Scene();skin.name="Body";skin.isSkinnedMesh=true;avatar.add(skin);class GLTFLoader{async loadAsync(){return{scene:avatar,animations:[]};}}h.loader.loadGLTFLoader=async()=>GLTFLoader;const session=runtime.createMotionSession({environment:h.env,loader:h.loader});assert.equal((await session.start(h.container)).status,"ready");assert.equal((await session.loadAvatar("avatar.glb")).status,"ready");const motion=session.loadMotionSpec(contract.spec,compiler);assert.equal(motion.status,"ready");assert.equal(motion.diagnostics.unboundTargetCount,0);session.play();session.stop();session.unloadMotion();assert.equal(session.action,null);assert.equal(session.motionSpec,null);session.unloadAvatar();assert.equal(session.avatar,null);assert.equal(session.mixer,null);assert.equal(session.scene.children.includes(avatar),false);session.dispose();assert.equal(session.animationFixture,null);assert.equal(session.clock,null);assert.equal(h.container.children.length,0);}assert.deepEqual(runtime.diagnostics(),{activeSessions:0,activeRafs:0,listeners:0,timers:0,canvases:0});});

test("50 personalized profile cycles keep one avatar root, preserve native clips without actions, and release owned resources",async()=>{const profile=require("../public/motion/avatar-profiles").profiles.personalized;for(let index=0;index<50;index++){const h=harness(),avatar=new h.THREE.Scene(),bone=new h.THREE.Scene(),skin=new h.THREE.Scene(),geometry={dispose(){this.disposed=true;}},texture={isTexture:true,dispose(){this.disposed=true;}},material={map:texture,dispose(){this.disposed=true;}};bone.name="Hips";bone.isBone=true;skin.name="Body_Mesh";skin.isMesh=true;skin.isSkinnedMesh=true;skin.geometry=geometry;skin.material=material;avatar.add(bone);avatar.add(skin);const clip={name:"avaturn_animation",duration:8.083333015441895,tracks:[{name:"Hips.position"},{name:"Hips.quaternion"},{name:"Eye_Mesh.morphTargetInfluences"}]};class GLTFLoader{async loadAsync(url){assert.equal(url,profile.assetUrl);return{scene:avatar,animations:[clip],parser:{json:{nodes:[{name:"Hips"},{name:"Body_Mesh"}],skins:[{joints:[0]}]}}};}}h.loader.loadGLTFLoader=async()=>GLTFLoader;const session=runtime.createMotionSession({environment:h.env,loader:h.loader});await session.start(h.container);const loaded=await session.loadAvatar(profile);assert.equal(loaded.status,"ready");assert.equal(loaded.diagnostics.avatarProfileId,profile.avatarId);assert.equal(loaded.diagnostics.animationCount,1);assert.deepEqual(loaded.diagnostics.animations[0],{name:"avaturn_animation",duration:8.083333015441895,trackCount:3,skeletalTrackCount:2,morphTrackCount:1});assert.equal(session.action,null);assert.equal(session.scene.children.filter(child=>child===avatar).length,1);session.unloadAvatar();assert.equal(geometry.disposed,true);assert.equal(material.disposed,true);assert.equal(texture.disposed,true);assert.equal(session.avatar,null);assert.equal(session.avatarAsset,null);assert.equal(session.mixer,null);session.dispose();assert.equal(h.container.children.length,0);}assert.deepEqual(runtime.diagnostics(),{activeSessions:0,activeRafs:0,listeners:0,timers:0,canvases:0});});

test("50 complete native Avaturn playback lifecycles bind embedded tracks and release every retained reference",async()=>{const profile=require("../public/motion/avatar-profiles").profiles.personalized;for(let index=0;index<50;index++){const h=harness(),avatar=new h.THREE.Scene();for(const name of ["Hips","Eye_Mesh"]){const node=new h.THREE.Scene();node.name=name;node.isBone=name==="Hips";node.isMesh=name==="Eye_Mesh";node.isSkinnedMesh=name==="Eye_Mesh";avatar.add(node);}const tracks=[{name:"Hips.position"},{name:"Hips.quaternion"},{name:"Eye_Mesh.morphTargetInfluences"}],clip={name:"avaturn_animation",duration:8.083333015441895,tracks,clone(){return{name:this.name,duration:this.duration,tracks:this.tracks.slice(),trim(){this.trimmed=true;}};}};class GLTFLoader{async loadAsync(){return{scene:avatar,animations:[clip]};}}h.loader.loadGLTFLoader=async()=>GLTFLoader;const session=runtime.createMotionSession({environment:h.env,loader:h.loader});assert.equal((await session.start(h.container)).status,"ready");assert.equal((await session.loadAvatar(profile)).status,"ready");assert.equal(session.action,null,"native animation must not autoplay or create an action during avatar load");const native=session.loadNativeAnimation("body-window");assert.equal(native.status,"ready");assert.equal(native.diagnostics.bindingMode,"NATIVE");assert.equal(native.diagnostics.sourceDuration,8.083333015441895);assert.deepEqual(native.diagnostics.activePlaybackRange,{start:0,end:1.533333,mode:"BODY-MOTION WINDOW"});assert.equal(native.diagnostics.trackCount,3);assert.equal(native.diagnostics.skeletalTrackCount,2);assert.equal(native.diagnostics.morphTrackCount,1);assert.equal(native.diagnostics.boundTrackCount,3);assert.deepEqual(native.diagnostics.unboundTracks,[]);assert.equal(session.play().status,"playing");assert.equal(session.pause().status,"paused");assert.equal(session.resume().status,"playing");assert.equal(session.stop().status,"stopped");assert.equal(session.restart().status,"playing");assert.equal(session.setLoop(false).loop,false);assert.equal(session.setLoop(true).loop,true);session.unloadMotion();session.unloadAvatar();assert.deepEqual(session.ownershipDiagnostics(),{actions:0,mixers:0,avatarRoots:0,gltfAssetReferences:0,clipsOwnedBySession:0,sceneAvatarObjects:0,pendingRequests:0});session.dispose();assert.equal(h.container.children.length,0);}assert.deepEqual(runtime.diagnostics(),{activeSessions:0,activeRafs:0,listeners:0,timers:0,canvases:0});});

test("50 extracted-fixture control lifecycles release actions, mixers, roots, clips, and GLTF references",async()=>{const profile=require("../public/motion/avatar-profiles").profiles.personalized,fixture=require("../public/motion/avaturn-push-up-fixture").fixture;for(let index=0;index<50;index++){const h=harness(),avatar=new h.THREE.Scene(),bone=new h.THREE.Scene(),skin=new h.THREE.Scene(),fixtureRoot=new h.THREE.Scene();bone.name="Hips";bone.isBone=true;skin.name="Body";skin.isSkinnedMesh=true;avatar.add(bone);avatar.add(skin);const clip={name:fixture.clipName,duration:1.5333333015441895,tracks:[{name:"Hips.position"},{name:"Hips.quaternion"}]};class GLTFLoader{async loadAsync(url){return url===profile.assetUrl?{scene:avatar,animations:[]}:{scene:fixtureRoot,animations:[clip]};}}h.loader.loadGLTFLoader=async()=>GLTFLoader;const session=runtime.createMotionSession({environment:h.env,loader:h.loader});assert.equal((await session.start(h.container)).status,"ready");assert.equal((await session.loadAvatar(profile)).status,"ready");const loaded=await session.loadExtractedAnimation(fixture);assert.equal(loaded.status,"ready");assert.equal(loaded.diagnostics.unboundTrackCount,0);assert.equal(session.scene.children.includes(fixtureRoot),false);session.play();session.pause();session.resume();session.stop();session.restart();session.setLoop(false);session.setLoop(true);session.unloadMotion();session.unloadAvatar();assert.deepEqual(session.ownershipDiagnostics(),{actions:0,mixers:0,avatarRoots:0,gltfAssetReferences:0,clipsOwnedBySession:0,sceneAvatarObjects:0,pendingRequests:0});session.dispose();}assert.deepEqual(runtime.diagnostics(),{activeSessions:0,activeRafs:0,listeners:0,timers:0,canvases:0});});

test("native and Phase E animation sources reject incompatible avatar profiles",async()=>{const h=harness(),avatar=new h.THREE.Scene(),bone=new h.THREE.Scene(),skin=new h.THREE.Scene();bone.name="Hips";bone.isBone=true;skin.name="Body";skin.isSkinnedMesh=true;avatar.add(bone);avatar.add(skin);class GLTFLoader{async loadAsync(){return{scene:avatar,animations:[{name:"avaturn_animation",duration:1,tracks:[]}]};}}h.loader.loadGLTFLoader=async()=>GLTFLoader;const session=runtime.createMotionSession({environment:h.env,loader:h.loader});await session.start(h.container);await session.loadAvatar({...require("../public/motion/avatar-profiles").profiles.reference,assetUrl:"reference.glb"});assert.equal(session.loadNativeAnimation().code,"native_animation_incompatible_profile");session.dispose();});

test("missing optional GLB is a contained asset_missing result",async()=>{const h=harness();class GLTFLoader{async loadAsync(){throw{target:{status:404}};}}h.loader.loadGLTFLoader=async()=>GLTFLoader;const session=runtime.createMotionSession({environment:h.env,loader:h.loader});await session.start(h.container);assert.equal((await session.loadAvatar("missing.glb")).code,"asset_missing");assert.equal(session.state,"running");session.dispose();});

test("camera fit centers a complete avatar with padding and honors narrow viewports",()=>{
  const landscape=runtime.calculateCameraFit({x:1,y:2,z:.5},{x:.2,y:1,z:-.1},2,50,1.2);
  const portrait=runtime.calculateCameraFit({x:1,y:2,z:.5},{x:.2,y:1,z:-.1},.25,50,1.2);
  assert.deepEqual(landscape.center,{x:.2,y:1,z:-.1}); assert.ok(landscape.distance>2.5); assert.ok(portrait.distance>landscape.distance);
  assert.ok(landscape.near>0); assert.ok(landscape.far>landscape.distance);
});
