"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const {GOAL_PRESETS,normalizeGoal,goalProgress}=require("../src/stepping/distanceGoals");
const {validateSearch,normalizeElement,createNearbyTrailService}=require("../src/services/nearbyTrailService");
const {createSteppingIntoGreatnessService}=require("../src/services/steppingIntoGreatnessService");
const expected={half_mile:804.672,one_mile:1609.344,two_miles:3218.688,five_k:5000,ten_k:10000,half_marathon:21097.5,marathon:42195};
test("every distance goal preset uses exact canonical meters",()=>{for(const [key,meters] of Object.entries(expected))assert.equal(GOAL_PRESETS[key].meters,meters);assert.equal(GOAL_PRESETS.open.meters,null);});
test("custom miles and kilometers convert once to canonical meters",()=>{assert.equal(normalizeGoal({type:"custom",customValue:"1.5",customUnit:"miles"}).distanceMeters,2414.016);assert.equal(normalizeGoal({type:"custom",customValue:"1.5",customUnit:"kilometers"}).distanceMeters,1500);});
test("custom validation rejects malformed, negative, non-finite, tiny, and excessive values",()=>{for(const value of ["1 mile","-1","Infinity","NaN","0",".01","201"])assert.throws(()=>normalizeGoal({type:"custom",customValue:value,customUnit:"kilometers"}));});
test("goal crossing fires once and auto finish defaults off",()=>{const goal=normalizeGoal({type:"five_k"});assert.equal(goal.autoFinish,false);const before=goalProgress(goal,4999),crossed=goalProgress(goal,5001,before),again=goalProgress(goal,6000,crossed);assert.equal(crossed.justCompleted,true);assert.equal(again.justCompleted,false);assert.equal(crossed.remainingMeters,0);});
test("rejected and paused movement cannot update accepted goal progress",()=>{const goal=normalizeGoal({type:"five_k"});assert.equal(goalProgress(goal,4999).completed,false);assert.equal(goalProgress(goal,4999).completed,false);});
test("trail inputs validate coordinates, supported radii, and limits",()=>{assert.deepEqual(validateSearch({latitude:1,longitude:2,radiusMeters:16093.44,limit:10}),{latitude:1,longitude:2,radiusMeters:16093.44,limit:10});for(const input of [{latitude:91,longitude:0,radiusMeters:16093.44},{latitude:0,longitude:181,radiusMeters:16093.44},{latitude:0,longitude:0,radiusMeters:1},{latitude:0,longitude:0,radiusMeters:16093.44,limit:26}])assert.throws(()=>validateSearch(input));});
test("provider data is normalized without fabricating optional values",()=>{const value=normalizeElement({type:"node",id:7,lat:1,lon:2,tags:{name:"Trailhead",highway:"trailhead"}},{latitude:1,longitude:2});assert.equal(value.name,"Trailhead");assert.equal(value.lengthMeters,undefined);assert.equal(value.difficulty,undefined);assert.equal(value.provider,"OpenStreetMap");assert.equal(normalizeElement({bad:true},{latitude:0,longitude:0}),null);});
test("trail service returns provider results and never persists coordinates",async()=>{let seen;const service=createNearbyTrailService({provider:{searchNearbyTrails:async input=>(seen=input,[{id:"a"}])}});const result=await service.search("member",{latitude:1,longitude:2,radiusMeters:8046.72,limit:1});assert.equal(seen.latitude,1);assert.deepEqual(result.trails,[{id:"a"}]);assert.equal(result.locationStored,false);assert.equal(JSON.stringify(result).includes('"latitude":1'),false);});
test("missing activityType idempotent retry repairs legacy record without duplicate effects",()=>{const users={maya:{userId:"maya",steppingIntoGreatness:{activities:[{activityId:"old",clientSessionId:"same",distanceMeters:5000,status:"completed",endedAt:"2026-01-02T00:00:00Z",validation:{state:"valid"},verificationLevel:"verified_gps",route:{points:[]},privacy:{activityVisibleToCommunity:false},personalRecordsEarned:[],achievementIds:[],challengeContributionIds:[]}],achievements:[],personalBests:{},memberships:[],feedEvents:[],contributions:[],enrollments:[],operationalEvents:[]}}};const store={loadUser:id=>users[id]||{userId:id},listUsers:()=>Object.values(users),updateUser:(id,fn)=>{users[id]=fn(users[id]);}};const service=createSteppingIntoGreatnessService({userStore:store,clock:()=>Date.parse("2026-01-03")});const result=service.complete("maya",{clientSessionId:"same",activityType:"walk"});assert.equal(result.activityType,"walk");assert.equal(result.duplicateCompletion,true);assert.equal(users.maya.steppingIntoGreatness.activities.length,1);assert.equal(users.maya.steppingIntoGreatness.feedEvents.length,0);assert.equal(users.maya.steppingIntoGreatness.contributions.length,0);});
test("mobile UI retains destinations, associated pace units, distinct labels, safe errors, and trail privacy",()=>{const html=fs.readFileSync(path.join(__dirname,"../public/greatness.html"),"utf8"),css=fs.readFileSync(path.join(__dirname,"../public/greatness.css"),"utf8"),js=fs.readFileSync(path.join(__dirname,"../public/greatness.js"),"utf8");const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size);for(const label of ["Move","Challenges","The Greatness Movement","Your Journey","Connections"])assert.ok(html.includes(`>${label}<`));assert.match(css,/overflow-x:auto/);assert.match(css,/white-space:nowrap/);assert.match(html,/Activity status:/);assert.match(html,/Sync status:/);assert.doesNotMatch(js,/Save failed: \$\{error\.message\}/);assert.match(js,/safeActivityType/);assert.match(html,/will not be posted/);assert.doesNotMatch(js,/operationalEvent\([^)]*latitude/);});

test("iPhone trail search has privacy-safe staged diagnostics and fresh-request safeguards",()=>{
  const js=fs.readFileSync(path.join(__dirname,"../public/greatness.js"),"utf8");
  for(const stage of ["search_button_pressed","secure_context_detected","navigator_geolocation_available","geolocation_request_started","geolocation_success","geolocation_error","backend_request_started","backend_http_status","backend_stable_error_code","response_parsing_success","response_parsing_failure","trail_count_rendered"])assert.match(js,new RegExp(stage));
  assert.match(js,/getCurrentPosition\(async position/);
  assert.match(js,/timeout:30000/);
  assert.match(js,/credentialsMode:"omit"/);
  assert.doesNotMatch(js,/\bfetch\s*\(/);
  assert.match(js,/const sequence=\+\+trailSearchSequence/);
  assert.match(js,/trailController=new AbortController\(\)/);
  assert.match(js,/event\.persisted&&trailSearchLoading/);
  assert.doesNotMatch(js,/trailDiagnostic\([^\n]*(?:latitude|longitude|Authorization|Bearer)/);
});

test("trail search distinguishes location, authentication, transport, provider, parsing, and cancellation errors",()=>{
  const js=fs.readFileSync(path.join(__dirname,"../public/greatness.js"),"utf8");
  for(const text of ["Location permission was denied","current location is unavailable","location request timed out","session has expired","network request failed","provider is temporarily unavailable","malformed response","Trail search cancelled"])assert.match(js,new RegExp(text,"i"));
});
