"use strict";
const test=require("node:test");const assert=require("node:assert/strict");
const {exerciseService}=require("../src/exercise-intelligence");const {validatePlatform}=require("../src/exercise-intelligence/exerciseValidation");
test("legacy catalog becomes uniquely identified, versioned canonical knowledge",()=>{const all=exerciseService.list();assert.ok(all.length>=873);assert.equal(new Set(all.map(x=>x.exerciseId)).size,all.length);assert.ok(all.every(x=>x.schemaVersion===1&&x.contentVersion));assert.deepEqual(validatePlatform(all,exerciseService.relationships()),{valid:true,errors:[]});});
test("search and composable filters are deterministic",()=>{assert.equal(exerciseService.search("pushup")[0].exerciseId,"push_up");const results=exerciseService.search("",{movementPatterns:["squat"],equipment:["bodyweight"],difficulties:["beginner"]});assert.ok(results.some(x=>x.exerciseId==="bodyweight_squat"));assert.ok(results.every(x=>x.classification.movementPattern==="squat"));});
test("substitution preserves movement intent and respects constraints",()=>{const result=exerciseService.substitutions("bench_press",{equipment:["bodyweight"],experienceLevel:"intermediate",programGoal:"strength"});assert.ok(result.length);assert.ok(result.every(x=>x.exercise.classification.movementPattern==="horizontal_push"));assert.ok(result.every(x=>x.preserved.includes("training_intent")));});
test("progressions require measured competency and movement quality",()=>{assert.deepEqual(exerciseService.progressions("bodyweight_squat",{competency:.79,movementQuality:["controlled_range","stable_alignment"]}),[]);assert.equal(exerciseService.progressions("bodyweight_squat",{competency:.8,movementQuality:["controlled_range","stable_alignment"]})[0].exerciseId,"goblet_squat");});
test("movement and AI integrations expose deterministic reference metadata",()=>{assert.equal(exerciseService.movementSupport("push_up").supportedDetector,"movenet");const context=exerciseService.coachContext("push_up");assert.equal(context.policy,"explain_only");assert.equal(context.exerciseId,"push_up");});
test("catalog returns snapshots and does not expose an edit path",()=>{const first=exerciseService.list();first.pop();assert.ok(exerciseService.list().length>first.length);assert.equal(exerciseService.update,undefined);});
