'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const metadata=require('../public/exercise-metadata.js'),generator=require('../scripts/lib/exercise-profile-generator');
const canonical=generator.generateProfile(generator.loadSource('push_up')).profile,runtime=metadata.profiles.find(x=>x.exerciseId==='push_up'),adapter=generator.runtimeAdapter(canonical);
const fields={setup:['instruction','setupCues'],movement:['instruction','movementCues'],safety:['instruction','safetyCues'],cadence:['cadence'],phrases:['phrases'],camera:['cameraGuidance'],limitations:['limitations'],measurements:['poseAnalysis','rules'],thresholds:['poseAnalysis'],confidence:['poseAnalysis'],workflow:['approval'],versions:['schemaVersion','sourceVersion','profileVersion','generatorVersion','rulesVersion','capabilityRegistryVersion'],fingerprint:['metadataFingerprint']};
for(const[name,path]of Object.entries(fields))test(`canonical-to-runtime parity: ${name}`,()=>{let a=runtime,b=adapter;if(name==='versions'){a=Object.fromEntries(path.map(key=>[key,a[key]]));b=Object.fromEntries(path.map(key=>[key,b[key]]));}else for(const key of path){a=a[key];b=b[key];}if(name==='thresholds'||name==='confidence'){a={minimumUsableFramePercentage:a.minimumUsableFramePercentage,minimumOverallConfidence:a.minimumOverallConfidence,rules:a.rules};b={minimumUsableFramePercentage:b.minimumUsableFramePercentage,minimumOverallConfidence:b.minimumOverallConfidence,rules:b.rules};}assert.deepEqual(a,b)});
test('documented runtime adapter is the only shape transformation',()=>assert.deepEqual(runtime,adapter));
test('Push-Up has one human-maintained authority and runtime is marked generated',()=>{assert.match(fs.readFileSync(require.resolve('../public/exercise-metadata.js'),'utf8'),/^\/\* GENERATED FILE/);assert.doesNotMatch(fs.readFileSync(require.resolve('../scripts/templates/exercise-metadata.js'),'utf8'),/profile\('push_up'/);assert.equal(fs.existsSync(require.resolve('../exercise-generation/sources/push_up.json')),true)});
test('challenge foundation exposes normalized pose trace compatibility without implementing challenge behavior',()=>assert.deepEqual(runtime.runtimeContract,{poseTraceCompatible:true,sessionRecorderCompatible:true,comparisonInput:'normalized_pose_trace'}));
