'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const metadata=require('../public/exercise-metadata.js');const review=require('../scripts/export-exercise-metadata-review.js');const generator=require('../scripts/generate-exercise-review-workspace.js');const validator=require('../scripts/validate-fitness-bot-review.js');
const required=['profile.json','review.md','fitness-bot-review.md','fitness-bot-input.json','trainer-decision.md','translation-source.json','translations/README.md'];
function temp(){return fs.mkdtempSync(path.join(os.tmpdir(),'exercise-review-'));}
test('workspace covers canonical profiles and snapshots exact review export',()=>{const out=temp();generator.generate(out);const exported=review.buildReviewExport().profiles;assert.deepEqual(fs.readdirSync(path.join(out,'exercises')),exported.map(x=>x.exerciseId).sort());for(const p of exported){const dir=path.join(out,'exercises',p.exerciseId);required.forEach(f=>assert.ok(fs.existsSync(path.join(dir,f)),`${p.exerciseId}/${f}`));const snap=JSON.parse(fs.readFileSync(path.join(dir,'profile.json')));assert.deepEqual(snap,generator.snapshot(p));assert.equal(snap.metadataFingerprint,p.metadataFingerprint);assert.equal(snap.schemaVersion,p.schemaVersion);assert.equal(snap.profileVersion,p.profileVersion);const before=JSON.stringify(metadata.profiles);snap.instructions.setupCues.push('detached');assert.equal(JSON.stringify(metadata.profiles),before);const summary=fs.readFileSync(path.join(out,'SUMMARY.md'),'utf8');assert.match(summary,new RegExp(p.displayName));}assert.equal((fs.readFileSync(path.join(out,'SUMMARY.md'),'utf8').match(/Pending/g)||[]).length,exported.length*4);});
test('handoffs deny approval and decisions are blank',()=>{const out=temp();generator.generate(out);const all=JSON.parse(fs.readFileSync(path.join(out,'fitness-bot-handoff.json')));assert.equal(all.packages.length,7);for(const pkg of all.packages){assert.equal(pkg.authority.fitnessBotMayApprove,false);assert.equal(pkg.requiredResponseSchema.approval.mayChangeProductionStatus,false);const dir=path.join(out,'exercises',pkg.exercise.exerciseId);const prompt=fs.readFileSync(path.join(dir,'fitness-bot-review.md'),'utf8');assert.match(prompt,/Do not claim approval/);const decision=fs.readFileSync(path.join(dir,'trainer-decision.md'),'utf8');assert.doesNotMatch(decision,/- \[x\]/i);assert.match(decision,/Trainer name:\nTrainer role or credential:\n/);const t=JSON.parse(fs.readFileSync(path.join(dir,'translation-source.json')));assert.deepEqual(Object.keys(t.sourceContent.phrases),Object.keys(pkg.exercise.phrases));assert.ok(!JSON.stringify(t.sourceContent).includes('threshold'));assert.ok(!JSON.stringify(t.sourceContent).includes('landmark'));assert.ok(!JSON.stringify(t.sourceContent).includes('approvalStatus'));assert.equal(t.protectedMeaning.placeholdersMustBePreserved,true);}});
test('generation is byte deterministic and has no prohibited dependencies',()=>{const a=temp(),b=temp();generator.generate(a);generator.generate(b);function files(root){return fs.readdirSync(root,{recursive:true,withFileTypes:true}).filter(x=>x.isFile()).map(x=>path.join(x.parentPath||x.path,x.name).slice(root.length+1)).sort();}assert.deepEqual(files(a),files(b));for(const f of files(a))assert.deepEqual(fs.readFileSync(path.join(a,f)),fs.readFileSync(path.join(b,f)));const source=fs.readFileSync(require.resolve('../scripts/generate-exercise-review-workspace.js'),'utf8');for(const term of ['puppeteer','tensorflow','node:http','node:https','node:net'])assert.doesNotMatch(source,new RegExp(`require\\(['\"]${term}`,'i'));assert.doesNotMatch(source,/\bfetch\s*\(/);});
test('invalid metadata blocks generation',()=>{const bad=structuredClone(metadata.profiles);bad[0].schemaVersion=99;assert.throws(()=>generator.generate(temp(),bad),/Metadata validation failed/);});
test('validator detects stale and approval claims without mutation',()=>{const p=review.buildReviewExport().profiles[0];const value=generator.responseSchema(p);value.recommendation='accept_as_written';const before=JSON.stringify(metadata.profiles);assert.equal(validator.validate(value).valid,true);for(const [field,bad] of [['profileVersion',99],['metadataFingerprint','sha256:stale']]){const v=structuredClone(value);v[field]=bad;assert.equal(validator.validate(v).valid,false);}const claim=structuredClone(value);claim.approval.status='approved';assert.equal(validator.validate(claim).valid,false);assert.equal(JSON.stringify(metadata.profiles),before);});
