const test=require('node:test');
const assert=require('node:assert/strict');
const THREE=require('three');
const normalized=require('../public/motion/normalized-pose');
const {AvaturnLivePoseSolver,FULL_BODY_BONES}=require('../public/motion/avaturn-live-pose-solver');
function rig(missing){const avatar=new THREE.Group(),nodes=new Map(),add=(name,parent,p=[0,.2,0])=>{if(name===missing)return parent;const b=Object.assign(new THREE.Bone(),{name});b.position.set(...p);parent.add(b);nodes.set(name,b);return b};const hips=add('Hips',avatar,[0,0,0]),spine=add('Spine',hips),spine1=add('Spine1',spine),spine2=add('Spine2',spine1),neck=add('Neck',spine2),head=add('Head',neck);for(const side of ['Left','Right']){const shoulder=add(side+'Shoulder',spine2),arm=add(side+'Arm',shoulder),fore=add(side+'ForeArm',arm);add(side+'Hand',fore);const thigh=add(side+'UpLeg',hips),leg=add(side+'Leg',thigh);add(side+'Foot',leg);}avatar.updateMatrixWorld(true);return{avatar,nodes};}
const base={nose:[50,12],left_eye:[47,10],right_eye:[53,10],left_ear:[44,12],right_ear:[56,12],left_shoulder:[40,25],right_shoulder:[60,25],left_elbow:[34,43],right_elbow:[66,43],left_wrist:[30,60],right_wrist:[70,60],left_hip:[44,52],right_hip:[56,52],left_knee:[43,72],right_knee:[57,72],left_ankle:[42,94],right_ankle:[58,94]};
function frame(at,change={},score=.95){const points=Object.entries({...base,...change}).map(([name,[x,y]])=>({name,x,y,score}));return normalized.fromMoveNetPosePacket({at,video:{width:100,height:100},keypoints:points,pose:{keypoints:points}});}
function calibrated(){const r=rig(),s=new AvaturnLivePoseSolver({THREE,avatar:r.avatar,calibrationMs:100,calibrationMinFrames:2,smoothingLambda:1000});s.observe(frame(100));s.observe(frame(220));return{r,s};}
test('reports exact complete Avaturn full-body ownership and missing bones',()=>{const complete=new AvaturnLivePoseSolver({THREE,avatar:rig().avatar}).diagnostics();assert.deepEqual(complete.expectedFullBodyBones,FULL_BODY_BONES);assert.equal(complete.expectedFullBodyBones.length,20);assert.equal(complete.mappedFullBodyBones.length,20);assert.deepEqual(complete.missingFullBodyBones,[]);assert.equal(complete.fullBodySkeletonMapped,'YES');const partial=new AvaturnLivePoseSolver({THREE,avatar:rig('Head').avatar}).diagnostics();assert.deepEqual(partial.missingFullBodyBones,['Head']);assert.equal(partial.fullBodySkeletonMapped,'NO');});
test('calibrates full body, lowers squat root, rises bilaterally for jump, and has no drift',()=>{const {r,s}=calibrated();assert.equal(s.diagnostics().fullBodyCalibrationState,'ACTIVE');assert.equal(s.diagnostics().fullBodyCalibrationFrames,2);s.observe(frame(300,{left_hip:[44,65],right_hip:[56,65],left_knee:[38,78],right_knee:[62,78]}));s.update(.1,300);assert.ok(s.diagnostics().rootTranslationY<0);assert.ok(r.avatar.position.y<0);s.observe(frame(400,{left_shoulder:[40,15],right_shoulder:[60,15],left_hip:[44,42],right_hip:[56,42],left_knee:[43,62],right_knee:[57,62],left_ankle:[42,84],right_ankle:[58,84]}));assert.equal(s.diagnostics().jumpCandidate,true);assert.ok(s.diagnostics().appliedRootRise>0);s.observe(frame(500));s.update(.1,500);assert.ok(Math.abs(r.avatar.position.y)<1e-6);assert.ok(Math.abs(s.diagnostics().rootTranslationNormalized)<1e-9);});
test('applies bounded floor orientation with hysteresis while limbs and head remain driven',()=>{const {r,s}=calibrated();const horizontal={left_shoulder:[25,45],right_shoulder:[25,55],left_hip:[55,45],right_hip:[55,55],left_knee:[72,45],right_knee:[72,55],left_ankle:[92,45],right_ankle:[92,55],left_eye:[18,46],right_eye:[18,52],nose:[20,48]};s.observe(frame(300,horizontal));s.update(.1,300);let d=s.diagnostics();assert.equal(d.floorOrientationState,'FLOOR');assert.ok(Math.abs(d.globalBodyOrientationApplied)>1);assert.equal(d.headTrackingState,'TRACKING_2D');assert.ok(d.changedBones.includes('MODEL_ROOT'));assert.ok(d.changedBones.includes('LeftForeArm'));s.observe(frame(320,{left_shoulder:[19,25],right_shoulder:[29,25]}));assert.equal(s.diagnostics().floorOrientationState,'FLOOR');s.observe(frame(400));assert.equal(s.diagnostics().floorOrientationState,'UPRIGHT');assert.ok(Math.abs(d.headRoll)<=s.options.headRollClamp);assert.ok(r.nodes.get('Neck'));});
test('rejects incomplete low-confidence calibration and resets after subject loss',()=>{const r=rig(),s=new AvaturnLivePoseSolver({THREE,avatar:r.avatar,calibrationMs:0,calibrationMinFrames:2,holdMs:10,subjectLossResetMs:20});s.observe(frame(10,{},.2));assert.equal(s.diagnostics().fullBodyCalibrationFrames,0);s.observe(frame(20));s.observe(frame(21));assert.equal(s.diagnostics().fullBodyCalibrationState,'ACTIVE');s.updateTrackingState(50);assert.equal(s.diagnostics().fullBodyCalibrationState,'WAITING');});
