"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {createUserStore}=require("../src/repositories/userStore");
const {createUserDataService}=require("../src/services/userDataService");
const {createGeneratedWorkoutService}=require("../src/services/generatedWorkoutService");
function setup(restricted=false){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"generated-delivery-")),store=createUserStore({userDir:dir}),tracking=createUserDataService({userStore:store}),service=createGeneratedWorkoutService({userStore:store,userDataService:tracking});store.updateUser("member",u=>{u.programRecommendation={recommendedProgram:{id:"starter",title:restricted?"Review starter":"Strength starter"}};u.generatedWorkoutPlan={generatorVersion:1,generatedAt:"2026-07-19T00:00:00.000Z",recommendationOnly:true,plan:{version:1,week:1,status:restricted?"health_review_restricted":"recommended",pathway:"general_fitness",sessions:[{week:1,session:restricted?"Restricted Starter Session":"Day One",focus:"strength",durationMinutes:20,notes:restricted?"No progression is permitted.":"Persisted note",exercises:[{exerciseId:restricted?"breathing_reset":"bodyweight_squat",displayName:restricted?"Breathing Reset":"Bodyweight Squat",sets:2,reps:"8",restSeconds:60,notes:"Controlled."}]}]}};return u});return{store,service};}
test("returns stable safe empty state and keeps member ownership isolated",()=>{const{store,service}=setup();assert.deepEqual(service.readModel("other"),{available:false,plan:null,activeProgramSource:"legacy_fallback"});assert.equal(service.readModel("member").plan.recommendedProgram.title,"Strength starter");assert.equal(store.loadUser("other").generatedWorkoutPlan,undefined)});
test("enforces assigned then selected then generated then legacy precedence",()=>{const{store,service}=setup();assert.equal(service.readModel("member").activeProgramSource,"generated_recommendation");store.updateUser("member",u=>{u.selectedProgram={id:"selected"};return u});assert.equal(service.readModel("member").activeProgramSource,"member_selected");store.updateUser("member",u=>{u.program={programId:"coach",title:"Coach plan"};return u});const read=service.readModel("member");assert.equal(read.activeProgramSource,"coach_assigned");assert.equal(read.assignedProgram.title,"Coach plan");assert.equal(read.available,true)});
test("starts, resumes, updates and completes without mutating the plan",()=>{const{store,service}=setup(),before=structuredClone(store.loadUser("member").generatedWorkoutPlan);const sid=service.readModel("member").plan.sessions[0].sessionId;const first=service.start("member",sid).execution,again=service.start("member",sid).execution;assert.equal(again.executionId,first.executionId);service.update("member",first.executionId,{exerciseId:"bodyweight_squat",completedSets:2,actualReps:"8, 8",completed:true,notes:"Felt good"});const done=service.complete("member",first.executionId);assert.equal(done.execution.status,"completed");assert.equal(service.complete("member",first.executionId).alreadyCompleted,true);const saved=store.loadUser("member");assert.deepEqual(saved.generatedWorkoutPlan,before);assert.equal(saved.workoutTracking.length,1);assert.equal(service.readModel("member").plan.sessions[0].status,"completed")});
test("rejects foreign executions, invalid progress, and completed mutations",()=>{const{service}=setup();const sid=service.readModel("member").plan.sessions[0].sessionId,id=service.start("member",sid).execution.executionId;assert.throws(()=>service.update("other",id,{exerciseId:"bodyweight_squat",completedSets:1}),/not found/);assert.throws(()=>service.update("member",id,{exerciseId:"bodyweight_squat",completedSets:99}),/integer/);service.complete("member",id);assert.throws(()=>service.update("member",id,{exerciseId:"bodyweight_squat",completedSets:1}),/cannot be changed/)});
test("health review exposes and executes only a restricted non-clearance plan",()=>{const{service}=setup(true),read=service.readModel("member");assert.equal(read.plan.sessions.length,1);assert.match(read.plan.healthReviewRestriction,/does not provide medical clearance/);assert.match(read.plan.sessions[0].exercises[0].progressionGuidance,/No progression/);assert.equal(service.start("member",read.plan.sessions[0].sessionId).execution.status,"in_progress")});
test("workout UI renders weekly cards, details, persisted execution controls, and no localStorage authority",()=>{const html=fs.readFileSync(path.join(__dirname,"../public/workout.html"),"utf8"),js=fs.readFileSync(path.join(__dirname,"../public/generated-workout-runtime.js"),"utf8");assert.match(html,/generatedWorkoutPlan/);assert.match(html,/generatedSessionDialog/);assert.match(js,/Recommendation only/);assert.match(js,/Completed sets for/);assert.match(js,/aria-live|announce/);assert.doesNotMatch(js,/localStorage|sessionStorage/)});
