"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {createUserStore}=require("../src/repositories/userStore");
const {createGeneratedWorkoutProgressionService,evaluateSummary,nextPlan,OUTCOMES}=require("../src/services/generatedWorkoutProgressionService");
const thresholds=require("../src/config/generatedWorkoutProgression");

function basePlan(overrides={}){return{planId:"gwp-old",planVersion:1,generatorVersion:1,sourceJourneyProfileVersion:1,programRecommendationVersion:1,weekNumber:1,status:"active",createdAt:"2026-07-01T00:00:00.000Z",activatedAt:"2026-07-01T00:00:00.000Z",completedAt:null,supersededAt:null,recommendationOnly:true,healthReviewRestricted:false,previousPlanVersion:null,progressionReason:"INITIAL_GENERATION",pathway:"general_fitness",sessions:[{week:1,session:"Day 1",durationMinutes:45,exercises:[{exerciseId:"bodyweight_squat",displayName:"Bodyweight Squat",sets:2,reps:"8-12",restSeconds:60}]}],...overrides};}
function summary(overrides={}){return{prescribedSessionCount:3,completedSessionCount:3,sessionAdherencePercent:100,prescribedSets:6,actualCompletedSets:6,exerciseCompletionPercent:100,completionTimestamps:[],checkIn:{painFlag:false,soreness:3,energy:7,sleep:8,adherence:90},healthReviewRequired:false,assignedProgramActive:false,...overrides};}
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"progression-")),store=createUserStore({userDir:dir}),service=createGeneratedWorkoutProgressionService({userStore:store});store.updateUser("member",u=>{u.journeyProfile={version:1,healthReviewRequired:false,equipmentAvailability:{equipment:[],gymAccess:"no"},trainingAvailability:{sessionsPerWeek:3,sessionLengthMinutes:45}};u.generatedWorkoutPlan={generatorVersion:1,generatedAt:"2026-07-01T00:00:00.000Z",journeyProfileVersion:1,recommendationOnly:true,plan:{version:1,week:1,status:"recommended",pathway:"general_fitness",sessions:basePlan().sessions}};u.generatedWorkoutExecutions=[{planVersion:1,sessionId:"week_1_session_1",status:"completed",completedAt:"2026-07-02T00:00:00.000Z",exerciseProgress:[{prescribedSets:2,completedSets:2,completed:true}]}];u.checkIns=[{painFlag:false,soreness:3,energy:7,sleep:8,adherence:90}];return u});return{store,service};}

test("centralized deterministic outcome thresholds cover every outcome",()=>{assert.equal(thresholds.progressSessionAdherencePercent,80);assert.equal(evaluateSummary(summary()).outcome,OUTCOMES.PROGRESS);assert.equal(evaluateSummary(summary({sessionAdherencePercent:70})).outcome,OUTCOMES.MAINTAIN);assert.equal(evaluateSummary(summary({checkIn:{painFlag:false,soreness:8,energy:7,sleep:8,adherence:90}})).outcome,OUTCOMES.DELOAD);assert.equal(evaluateSummary(summary({sessionAdherencePercent:20})).outcome,OUTCOMES.INCOMPLETE_WEEK);assert.equal(evaluateSummary(summary({healthReviewRequired:true})).outcome,OUTCOMES.HEALTH_REVIEW_BLOCKED);assert.equal(evaluateSummary(summary({assignedProgramActive:true})).outcome,OUTCOMES.ASSIGNED_PROGRAM_ACTIVE);});
test("next plans use bounded one-variable progression and preserve the prior plan",()=>{const prior=basePlan(),snapshot=structuredClone(prior),next=nextPlan(prior,OUTCOMES.PROGRESS,{equipmentAvailability:{equipment:[]},trainingAvailability:{sessionsPerWeek:1,sessionLengthMinutes:30}});assert.deepEqual(prior,snapshot);assert.equal(next.sessions[0].exercises[0].reps,"9-13");assert.equal(next.sessions[0].exercises[0].sets,2);assert.equal(next.sessions[0].durationMinutes,30);assert.equal(next.sessions.length,1);});
test("set and rep progression and deload stay inside hard boundaries",()=>{const capped=basePlan({sessions:[{week:1,durationMinutes:45,exercises:[{exerciseId:"dead_bug",sets:4,reps:"20"}]}]}),progressed=nextPlan(capped,OUTCOMES.PROGRESS,{equipmentAvailability:{equipment:[]},trainingAvailability:{sessionsPerWeek:1,sessionLengthMinutes:45}});assert.equal(progressed.sessions[0].exercises[0].sets,5);assert.equal(progressed.sessions[0].exercises[0].reps,"20");const deload=nextPlan(basePlan(),OUTCOMES.DELOAD,{equipmentAvailability:{equipment:[]},trainingAvailability:{sessionsPerWeek:1}});assert.equal(deload.sessions[0].exercises[0].sets,1);});
test("equipment, duration, frequency, and normalized-catalog protections are enforced",()=>{const prior=basePlan({sessions:Array.from({length:7},()=>({durationMinutes:200,exercises:[{exerciseId:"barbell_squat",sets:2,reps:"8"},{exerciseId:"bodyweight_squat",sets:2,reps:"8"},{exerciseId:"unknown",sets:2,reps:"8"}]}))}),next=nextPlan(prior,OUTCOMES.MAINTAIN,{equipmentAvailability:{equipment:[],gymAccess:"no"},trainingAvailability:{sessionsPerWeek:7,sessionLengthMinutes:200}});assert.equal(next.sessions.length,thresholds.boundaries.maxWeeklyFrequency);assert.equal(next.sessions[0].durationMinutes,thresholds.boundaries.maxSessionMinutes);assert.deepEqual(next.sessions[0].exercises.map(x=>x.exerciseId),["bodyweight_squat"]);});
test("legacy lifecycle migration, evaluation, acceptance, persistence and history are idempotent",()=>{const{store,service}=setup(),before=structuredClone(store.loadUser("member").generatedWorkoutPlan.plan),first=service.evaluate("member"),again=service.evaluate("member");assert.equal(first.evaluation.progressionId,again.evaluation.progressionId);let user=store.loadUser("member");assert.equal(user.generatedWorkoutPlans.length,2);assert.equal(user.generatedWorkoutProgressions.length,1);assert.deepEqual(user.generatedWorkoutPlans[0].sessions,before.sessions);const accepted=service.accept("member"),acceptedAgain=service.accept("member");assert.equal(accepted.evaluation.progressionId,acceptedAgain.evaluation.progressionId);user=store.loadUser("member");assert.equal(user.generatedWorkoutPlans.length,2);assert.equal(user.generatedWorkoutPlans[0].status,"completed");assert.equal(user.generatedWorkoutPlans[1].status,"active");assert.equal(service.state("member").currentPlan.planVersion,2);assert.equal(createGeneratedWorkoutProgressionService({userStore:store}).state("member").latestCompletedWeek,1);});
test("ownership, assigned-program, and health-review protections block activation",()=>{const{store,service}=setup();assert.equal(service.state("other").available,false);store.updateUser("member",u=>{u.program={programId:"coach"};return u});const assigned=service.evaluate("member");assert.equal(assigned.evaluation.outcome,OUTCOMES.ASSIGNED_PROGRAM_ACTIVE);assert.equal(assigned.evaluation.toPlanVersion,null);assert.throws(()=>service.accept("member"),/eligible/);const second=setup();second.store.updateUser("member",u=>{u.journeyProfile.healthReviewRequired=true;return u});const restricted=second.service.evaluate("member");assert.equal(restricted.evaluation.outcome,OUTCOMES.HEALTH_REVIEW_BLOCKED);assert.equal(second.store.loadUser("member").generatedWorkoutPlans.length,1);});
test("member UI renders readable progression without browser storage authority",()=>{const html=fs.readFileSync(path.join(__dirname,"../public/workout.html"),"utf8"),js=fs.readFileSync(path.join(__dirname,"../public/generated-workout-runtime.js"),"utf8");assert.match(html,/generatedWorkoutProgression/);assert.match(js,/Weekly progress/);assert.match(js,/Accept next week/);assert.match(js,/e\.explanation/);assert.doesNotMatch(js,/reasonCodes/);assert.doesNotMatch(js,/localStorage|sessionStorage/);});
test("authenticated member progression routes are registered",()=>{const source=fs.readFileSync(path.join(__dirname,"../server.js"),"utf8");assert.match(source,/get\("\/api\/me\/generated-workout-progression", requireAuth/);assert.match(source,/post\("\/api\/me\/generated-workout-progression\/evaluate", requireAuth/);assert.match(source,/post\("\/api\/me\/generated-workout-progression\/accept", requireAuth/);});
