'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const GESE=require('../public/generic-exercise-sequence-engine'),D=require('../public/exercise-sequence-definitions');
const landmark=(x,y)=>({x,y,confidence:.95});
function squat(angle,t){const rad=(180-angle)*Math.PI/180;return{timestamp:t,trackingState:'LOCKED',analysisUsable:true,sequenceLandmarks:{hip:landmark(0,0),knee:landmark(.5,0),ankle:landmark(.5+.5*Math.cos(rad),.5*Math.sin(rad))}};}
test('schemas explicitly reject unknown evaluators and conditions',()=>{assert.throws(()=>new GESE.ExerciseSequenceEngine({...D.squatFixture,measurements:[{id:'x',type:'magic'}]}),/Unsupported measurement/);const d=structuredClone(D.squatFixture);d.phases[0].condition={type:'maybe'};assert.throws(()=>new GESE.ExerciseSequenceEngine(d),/Unsupported condition/);});
test('fingerprints are canonical, complete, and exercise-specific',()=>{const reordered=Object.fromEntries(Object.entries(D.pushUp).reverse());assert.equal(GESE.fingerprint(D.pushUp),GESE.fingerprint(reordered));assert.notEqual(GESE.fingerprint(D.pushUp),GESE.fingerprint(D.squatFixture));const changed=structuredClone(D.pushUp);changed.phases[0].condition.value++;assert.notEqual(GESE.fingerprint(D.pushUp),GESE.fingerprint(changed));});
test('Squat fixture completes ordered repetition without modifying GESE',()=>{const e=new GESE.ExerciseSequenceEngine(D.squatFixture);[170,170,150,110,110,130,160,160].forEach((a,i)=>e.observe(squat(a,i)));assert.equal(e.repetitions,1);assert.deepEqual(e.repetitionEvents[0].evidence.map(x=>x.phaseId),D.squatFixture.repetitionPath);});
test('Squat fixture rejects wrong order',()=>{const e=new GESE.ExerciseSequenceEngine(D.squatFixture);[110,110,170,170,110,110].forEach((a,i)=>e.observe(squat(a,i)));assert.equal(e.repetitions,0);});
test('explainability comes from observed evaluator evidence',()=>{const e=new GESE.ExerciseSequenceEngine(D.squatFixture),out=e.observe(squat(170,1));assert.equal(out.evidence.measurements[0].measurement,'knee_angle');assert.equal(typeof out.evidence.measurements[0].value,'number');assert.equal(out.evidence.condition.comparison,'greater_than');assert.equal(out.evidence.condition.pass,true);});
