"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const {createGoogleWalkingRouteProvider,createWalkingRouteService,decodePolyline,WALKING_WARNING}=require("../src/services/walkingRouteService");

const place={id:"google:p1",providerId:"p1",latitude:32.9,longitude:-96.8};
test("Google walking provider sends a server-side WALK request and normalizes encoded geometry",async()=>{let request;const provider=createGoogleWalkingRouteProvider({apiKey:"server-secret",fetchImpl:async(url,options)=>(request={url,options},{ok:true,status:200,json:async()=>({routes:[{distanceMeters:804,polyline:{encodedPolyline:"_p~iF~ps|U_ulLnnqC_mqNvxq`@"}}]})})});const route=await provider.route({startPoint:place,endPoint:place,waypoints:[]});assert.equal(JSON.parse(request.options.body).travelMode,"WALK");assert.equal(request.options.headers["x-goog-api-key"],"server-secret");assert.equal(route.distanceMeters,804);assert.deepEqual(decodePolyline("_p~iF~ps|U_ulLnnqC_mqNvxq`@"),[{latitude:38.5,longitude:-120.2},{latitude:40.7,longitude:-120.95},{latitude:43.252,longitude:-126.453}]);});
test("verified geometry remains preferred without calling Google",async()=>{let calls=0;const routeStore={get:()=>({verificationStatus:"admin_verified",routeType:"point_to_point",geometry:[place,{latitude:32.91,longitude:-96.8}]})};const service=createWalkingRouteService({provider:{name:"fake",route:async()=>{calls++;}},routeStore});const result=await service.generate({trailId:"verified",place,targetDistanceMeters:1609});assert.equal(result.options[0].routeSource,"verified_geometry");assert.equal(calls,0);});
test("walking fallback supports half-mile, one-mile, two-mile and 5K goals",async()=>{for(const target of [804.672,1609.344,3218.688,5000]){const service=createWalkingRouteService({provider:{name:"fake",route:async()=>({distanceMeters:target*.99,polyline:[place,{latitude:32.901,longitude:-96.8}]})},maxAttempts:2,now:()=>Date.parse("2026-07-29")});const result=await service.generate({trailId:`p-${target}`,place,targetDistanceMeters:target});assert.equal(result.options[0].routeSource,"google_walking_route");assert.equal(result.options[0].withinTolerance,true);assert.ok(result.options[0].warnings.includes(WALKING_WARNING));}});
test("candidate attempts are bounded and provider failure falls back honestly",async()=>{let calls=0;const service=createWalkingRouteService({provider:{name:"fake",route:async()=>{calls++;throw Object.assign(new Error("no route"),{code:"NO_ROUTE"});}},maxAttempts:3});const result=await service.generate({trailId:"none",place,targetDistanceMeters:1609});assert.equal(calls,3);assert.equal(result.options[0].routeSource,"place_only");assert.equal(result.fallbackReason,"NO_ROUTE");});
test("identical requests are coalesced and then served from short-lived cache",async()=>{let calls=0,release;const provider={name:"fake",route:()=>new Promise(resolve=>{calls++;release=()=>resolve({distanceMeters:1600,polyline:[place,{latitude:32.901,longitude:-96.8}]});})},service=createWalkingRouteService({provider,maxAttempts:1});const input={trailId:"same",place,targetDistanceMeters:1609},a=service.generate(input),b=service.generate(input);await new Promise(resolve=>setImmediate(resolve));release();const results=await Promise.all([a,b]);assert.equal(calls,1);assert.equal(results[1].coalesced,true);assert.equal((await service.generate(input)).cacheHit,true);});
test("timeout and quota errors are normalized",async()=>{for(const [status,code] of [[429,"WALKING_ROUTE_QUOTA_EXCEEDED"],[403,"WALKING_ROUTE_PROVIDER_AUTH_FAILED"]]){const provider=createGoogleWalkingRouteProvider({apiKey:"secret",fetchImpl:async()=>({ok:false,status,json:async()=>({error:{}})})});await assert.rejects(provider.route({startPoint:place,endPoint:place}),error=>error.code===code);}});
