"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const source=fs.readFileSync(path.join(__dirname,"../public/greatness-entry-auth.js"),"utf8");
function harness({result={ok:true},auth={isAuthenticated:true,token:"redacted",user:{id:"member-1"}},transition=true}={}){let resolve,ready=result instanceof Promise?result:new Promise(r=>{resolve=r});if(!(result instanceof Promise))queueMicrotask(()=>resolve(result));const redirects=[],nodes={greatnessEntryAuthDiagnostics:{textContent:""},greatnessSessionRestore:{hidden:false,querySelector:()=>({textContent:""})}};const sessionStorage={value:transition?JSON.stringify({loginSuccess:true,tokenPersisted:true}):null,getItem(){return this.value},removeItem(){this.value=null}};const window={sessionStorage,document:{getElementById:id=>nodes[id]},location:{pathname:"/greatness.html",search:"",hash:"",replace:value=>redirects.push(value)},AuthStateRuntime:{whenReady:()=>ready,getCanonicalAuthState:()=>auth,getAuthToken:()=>auth.token},MaatApiClient:{request(){}},console};window.window=window;vm.runInNewContext(source,{window,globalThis:window,console,Set,Object,JSON,encodeURIComponent});return{guard:window.GreatnessEntryAuth.guard,nodes,redirects,resolve};}
test("fresh login persists, restores identity, and allows Greatness",async()=>{const h=harness();const state=await h.guard();assert.equal(state.loginSuccess,true);assert.equal(state.tokenPersisted,true);assert.equal(state.meStatus,"200");assert.equal(state.identityResolved,true);assert.equal(state.decision,"ALLOW");assert.deepEqual(h.redirects,[]);});
test("restoration delay remains WAIT with no premature redirect, then allows",async()=>{let finish;const pending=new Promise(r=>finish=r),h=harness({result:pending});const guard=h.guard();await new Promise(setImmediate);assert.equal(h.nodes.greatnessSessionRestore.hidden,false);assert.deepEqual(h.redirects,[]);finish({ok:true});assert.equal((await guard).decision,"ALLOW");assert.deepEqual(h.redirects,[]);});
test("pending auth me remains restoring until 200",async()=>{let finish;const pending=new Promise(r=>finish=r),h=harness({result:pending});const guard=h.guard();await new Promise(setImmediate);assert.match(h.nodes.greatnessEntryAuthDiagnostics.textContent,/\/api\/auth\/me: pending/);assert.deepEqual(h.redirects,[]);finish({ok:true});assert.equal((await guard).decision,"ALLOW");});
test("transient network failure keeps canonical auth and shows retry state",async()=>{const auth={isAuthenticated:true,token:"redacted",user:{id:"member-1"}},h=harness({result:{ok:false,reason:"auth_unavailable"},auth});const state=await h.guard();assert.equal(state.decision,"WAIT");assert.equal(state.meStatus,"network error");assert.equal(auth.token,"redacted");assert.deepEqual(h.redirects,[]);});
test("confirmed 401 invalid session redirects exactly once",async()=>{const h=harness({result:{ok:false,reason:"invalid_session"},auth:{isAuthenticated:false,token:null,user:null}});const state=await h.guard();assert.equal(state.decision,"REDIRECT");assert.equal(state.redirectReason,"invalid_session");assert.equal(h.redirects.length,1);assert.match(h.redirects[0],/^\/run-club-login\.html/);});
test("signed-out entry redirects while logout remains canonical",async()=>{const h=harness({result:{ok:false,reason:"missing_token"},auth:{isAuthenticated:false,token:null,user:null},transition:false});assert.equal((await h.guard()).decision,"REDIRECT");const greatness=fs.readFileSync(path.join(__dirname,"../public/greatness.js"),"utf8");assert.match(greatness,/authRuntime\.logout\(\{redirectTo:"\/run-club-login\.html"\}\)/);assert.equal(h.redirects.length,1);});
test("guard owns the sole Greatness redirect and never reads storage for auth",()=>{const greatness=fs.readFileSync(path.join(__dirname,"../public/greatness.js"),"utf8"),login=fs.readFileSync(path.join(__dirname,"../public/run-club-login.js"),"utf8"),html=fs.readFileSync(path.join(__dirname,"../public/greatness.html"),"utf8");assert.doesNotMatch(greatness,/location\.replace\(`\/run-club-login/);assert.doesNotMatch(login,/location\.replace\([^)]*greatness/);assert.doesNotMatch(html,/location\.replace\([^)]*run-club-login/);assert.doesNotMatch(source,/localStorage/);assert.match(source,/runtime\.whenReady\(\)/);assert.match(html,/Greatness Entry Auth/);});
