"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const greatness=fs.readFileSync(path.join(__dirname,"../public/greatness.js"),"utf8");
const html=fs.readFileSync(path.join(__dirname,"../public/greatness.html"),"utf8");
const clientSource=fs.readFileSync(path.join(__dirname,"../public/api-client.js"),"utf8");
function client({fetchImpl,token="canonical.jwt.token"}={}){const window={location:{origin:"https://mufasafitsite.onrender.com",href:"https://mufasafitsite.onrender.com/greatness.html"},RuntimeState:{getBackendOrigin:()=>"https://mufasa-fitness-node.onrender.com"},AuthStateRuntime:{getAuthToken:()=>token},fetch:fetchImpl||(async()=>new Response(JSON.stringify({ok:true,data:{trails:[]}}),{status:200,headers:{"content-type":"application/json"}}))};window.window=window;vm.runInNewContext(clientSource,{window,globalThis:window,URL,Request,AbortController,setTimeout,clearTimeout,Object});return window.MaatApiClient;}
test("manual and nearby trail search use the canonical authenticated API path",()=>{assert.match(greatness,/api\("\/api\/me\/greatness\/trails\/text-search"/);assert.match(greatness,/canonicalRequest\(path,\{method:"POST"/);assert.match(greatness,/await runtime\.whenReady\(\)/);assert.match(greatness,/runtime\.getCanonicalAuthState\(\)/);assert.doesNotMatch(greatness,/\bfetch\s*\(/);assert.doesNotMatch(greatness,/localStorage\.getItem\([^)]*(?:token|auth)/i);});
test("trail detail, route retrieval, goal routes and alternatives all pass through api",()=>{for(const route of [/api\(`\/api\/me\/greatness\/trails\/\$\{encodeURIComponent\(trail\.trailRouteId\)\}`\)/,/api\(`\/api\/me\/greatness\/activities\/\$\{id\}\/route`\)/,/goal-routes\$\{endpoint\}/,/alternative\?"\/alternatives"/])assert.match(greatness,route);assert.doesNotMatch(greatness,/new URL\([^\n]+\/api\/me\/greatness/);});
test("canonical client dispatches authenticated trail requests to the production backend",async()=>{const requests=[],c=client({fetchImpl:async request=>{requests.push(request);return new Response(JSON.stringify({ok:true,data:{trails:[]}}),{status:200,headers:{"content-type":"application/json"}});}});for(const route of ["/api/me/greatness/trails/text-search","/api/me/greatness/nearby-trails/search"]){const result=await c.request(route,{method:"POST",body:{limit:15}});assert.equal(result.ok,true);}assert.equal(requests.length,2);for(const request of requests){assert.equal(new URL(request.url).origin,"https://mufasa-fitness-node.onrender.com");assert.equal(request.headers.get("authorization"),"Bearer canonical.jwt.token");assert.equal(request.credentials,"omit");}});
test("401 and Mobile Safari network failure remain distinct",async()=>{const unauthorized=await client({fetchImpl:async()=>new Response("{}",{status:401})}).request("/api/me/greatness/trails/text-search");assert.equal(unauthorized.diagnostics.failureClass,"authentication HTTP response");assert.equal(unauthorized.diagnostics.backendReached,true);const network=await client({fetchImpl:async()=>{throw new TypeError("Load failed");}}).request("/api/me/greatness/nearby-trails/search");assert.equal(network.diagnostics.failureClass,"unknown network");assert.equal(network.diagnostics.backendReached,null);});
test("restoration and redacted production diagnostics copy are wired before Greatness module",()=>{assert.ok(html.indexOf("auth-state-runtime.js")<html.indexOf("api-client.js"));assert.ok(html.indexOf("api-client.js")<html.indexOf("greatness.js"));assert.match(greatness,/Restoring your session…/);assert.match(greatness,/Your session has expired\. Please sign in again\./);assert.match(html,/trailRequestDiagnostics/);assert.match(html,/Resolved API origin/);assert.doesNotMatch(`${html}\n${greatness}`,/raw token/i);});
test("Greatness guard, free sign out, and consistency diagnostics share canonical auth",()=>{assert.match(greatness,/await window\.GreatnessEntryAuth\.guard/);assert.match(fs.readFileSync(path.join(__dirname,"../public/greatness-entry-auth.js"),"utf8"),/await runtime\.whenReady\(\)/);assert.match(greatness,/routeGuardAuthenticated/);assert.match(greatness,/authRuntime\.logout\(\{redirectTo:"\/run-club-login\.html"\}\)/);assert.match(html,/id="greatnessSignOut"/);assert.match(html,/Greatness Auth Consistency/);assert.match(greatness,/Route guard\/API agreement/);assert.doesNotMatch(`${html}\n${greatness}`,/Authorization header|Bearer \$\{.*greatnessAuthConsistency/);});

test("Run Club bypass waits for validated canonical identity and has no storage auth read",()=>{const entry=fs.readFileSync(path.join(__dirname,"../public/run-club-login.js"),"utf8");assert.match(entry,/await runtime\.whenReady\(\)/);assert.match(entry,/state\.user\?\.id/);assert.doesNotMatch(entry,/localStorage\.getItem\([^)]*(?:token|auth)/i);assert.doesNotMatch(entry,/fetch\(`\$\{backendOrigin\(\)\}\/api\/auth\/me/);});
