"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const source=fs.readFileSync(path.join(__dirname,"../public/greatness-entry-auth.js"),"utf8");
const VERSION="20260813-authorization-header-canonicalization-v1";
function harness({result={ok:true,diagnostics:{url:"https://api.example/api/auth/me",dispatched:true,backendReached:true,status:200}},auth={isAuthenticated:true,token:"redacted",user:{id:"member-1"}},versions=true}={}){
 const redirects=[],store=new Map(),nodes={greatnessEntryAuthDiagnostics:{textContent:""},greatnessSessionRestore:{hidden:false,querySelector:()=>({textContent:""})}};
 const diagnostics=()=>({credentialPresent:Boolean(auth.token),tokenFormatValid:Boolean(auth.token),expiryState:auth.token?"valid":"unavailable"});
 const window={__MAAT_ASSET_VERSIONS__:Object.fromEntries(["auth-state-runtime.js","api-client.js","greatness.js"].map(n=>[n,versions?VERSION:"stale"])),sessionStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},document:{getElementById:id=>nodes[id]},location:{origin:"https://web.example",pathname:"/greatness.html",search:"",hash:"",replace:v=>redirects.push(v)},AuthStateRuntime:{whenReady:async()=>result,getCanonicalAuthState:()=>auth,getAuthToken:()=>auth.token,getSafeDiagnostics:diagnostics,ensureDebugState:()=>({})},MaatApiClient:{request(){},origin:()=>"https://api.example",resolve:p=>`https://api.example${p}`},console};window.window=window;
 vm.runInNewContext(source,{window,globalThis:window,console,Set,Object,JSON,encodeURIComponent,Date});return{window,redirects,store,nodes,guard:window.GreatnessEntryAuth.guard};
}
test("successful fresh login records a complete allowing trace",async()=>{const h=harness(),t=await h.guard();assert.equal(t.decision,"ALLOW");assert.equal(t.meResponseClass,"200");assert.equal(t.assetVersionMatch,true);assert.equal(h.redirects.length,0);assert.ok(h.store.get(h.window.GreatnessEntryAuth.TRACE_KEY));});
test("correct backend-origin auth URL is captured",async()=>{const t=await harness().guard();assert.equal(t.meUrl,"https://api.example/api/auth/me");assert.equal(t.apiOrigin,"https://api.example");});
test("wrong frontend-origin 404 remains WAIT and persists token",async()=>{const auth={isAuthenticated:true,token:"redacted",user:{id:"member-1"}},h=harness({auth,result:{ok:false,reason:"auth_unavailable",diagnostics:{url:"https://web.example/api/auth/me",dispatched:true,backendReached:true,status:404}}}),t=await h.guard();assert.equal(t.decision,"WAIT");assert.equal(t.meResponseClass,"other HTTP");assert.equal(t.meHttpStatus,404);assert.equal(auth.token,"redacted");assert.equal(h.redirects.length,0);});
for(const status of [405,500])test(`${status} response does not redirect or clear auth`,async()=>{const auth={isAuthenticated:true,token:"redacted",user:{id:"member-1"}},h=harness({auth,result:{ok:false,reason:"auth_unavailable",diagnostics:{url:"https://api.example/api/auth/me",dispatched:true,backendReached:true,status}}}),t=await h.guard();assert.equal(t.decision,"WAIT");assert.equal(auth.token,"redacted");assert.equal(h.redirects.length,0);});
test("network failure remains WAIT",async()=>{const h=harness({result:{ok:false,reason:"auth_unavailable",diagnostics:{url:"https://api.example/api/auth/me",dispatched:true,backendReached:null,status:null}}}),t=await h.guard();assert.equal(t.meResponseClass,"network");assert.equal(t.decision,"WAIT");});
test("confirmed 401 redirects once with exact owner and persistent trace",async()=>{const h=harness({auth:{isAuthenticated:false,token:null,user:null},result:{ok:false,reason:"invalid_session",diagnostics:{url:"https://api.example/api/auth/me",dispatched:true,backendReached:true,status:401}}}),t=await h.guard();assert.equal(t.decision,"REDIRECT");assert.equal(t.meResponseClass,"401");assert.equal(t.redirectOwner,"public/greatness-entry-auth.js/GreatnessEntryAuth.guard");assert.equal(h.redirects.length,1);assert.equal(JSON.parse(h.store.get(h.window.GreatnessEntryAuth.TRACE_KEY)).decision,"REDIRECT");});
test("stale asset mismatch is visible",async()=>{const t=await harness({versions:false}).guard();assert.equal(t.assetVersionMatch,false);assert.match(t.assetVersions["greatness.js"],/stale/);});
test("there is exactly one automatic Greatness auth redirect owner",()=>{const files=["greatness.html","greatness.js","greatness-entry-auth.js","run-club-login.js","auth-state-runtime.js"],matches=[];for(const file of files){const text=fs.readFileSync(path.join(__dirname,"../public",file),"utf8");if(/location\.replace\(target\)/.test(text)&&file==="greatness-entry-auth.js")matches.push(file);}assert.deepEqual(matches,["greatness-entry-auth.js"]);});
test("legacy Run Club login redirects to the canonical login without a form",()=>{const html=fs.readFileSync(path.join(__dirname,"../public/run-club-login.html"),"utf8");assert.match(html,/location\.replace/);assert.match(html,/\/login\.html/);assert.doesNotMatch(html,/<form|type="password"/);assert.match(source,/Greatness request Authorization attached/);assert.doesNotMatch(source,/Bearer \$\{|session secret/i);});
