"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const source=fs.readFileSync(path.join(__dirname,"../public/trail-map.js"),"utf8");
const greatness=fs.readFileSync(path.join(__dirname,"../public/greatness.js"),"utf8");

test("established frontend browser key delivery is primary and backend runtime is fallback",()=>{assert.match(source,/frontend_same_origin/);assert.match(source,/frontend_injected/);assert.match(source,/browser_config_fallback/);assert.match(source,/backendUrl\("\/api\/browser-config"\)/);assert.ok(source.indexOf("frontend_same_origin")<source.indexOf("backend_fallback"));assert.match(source,/googleMapsBrowserApiKey/);assert.doesNotMatch(source,/process\.env\.GOOGLE_MAPS_API_KEY/);assert.match(source,/BROWSER_MAP_KEY_MISSING/);});
test("frontend key compatibility names precede runtime config fetch",()=>{for(const name of ["__MAAT_RUNTIME_CONFIG__","VITE_GOOGLE_MAPS_BROWSER_API_KEY","GOOGLE_MAPS_BROWSER_API_KEY"])assert.match(source,new RegExp(name));assert.ok(source.indexOf("injectedBrowserMapKey()")<source.indexOf('backendUrl("/api/browser-config")'));});
test("loader has encoded URL, one promise, callback, timeout, auth hook and required library",()=>{assert.match(source,/new URLSearchParams/);assert.match(source,/loaderPromise/);assert.match(source,/gm_authFailure/);assert.match(source,/LOAD_TIMEOUT_MS/);assert.match(source,/libraries:"geometry"/);assert.match(source,/script\.async = true/);assert.match(source,/script\.defer = true/);});
test("map classifications cover configuration, provider, container, library and coordinates",()=>{for(const code of ["BROWSER_MAP_KEY_MISSING","BROWSER_CONFIG_UNAVAILABLE","MAPS_SCRIPT_BLOCKED","MAPS_AUTHENTICATION_FAILED","MAPS_REFERRER_NOT_ALLOWED","MAPS_API_NOT_ACTIVATED","MAP_CONTAINER_ZERO_SIZE","MAP_CONTAINER_NOT_VISIBLE","MAP_INITIALIZATION_FAILED","ROUTE_COORDINATES_INVALID","MAPS_LIBRARY_UNAVAILABLE","UNKNOWN_MAP_RENDER_FAILURE"])assert.match(source,new RegExp(code));});
test("mobile lifecycle waits for reveal, resizes, fits bounds and refreshes carousel routes",()=>{assert.match(source,/await waitUntilVisible\(container\)/);assert.match(source,/orientationchange/);assert.match(source,/trigger\?\.\(map,"resize"\)/);assert.match(source,/map\.fitBounds\(bounds,48\)/);assert.match(greatness,/queueMicrotask\(\(\)=>preview/);assert.match(greatness,/Route options remain available/);});
test("route validation and client evidence are sanitized classifications only",()=>{assert.match(source,/finiteGeometry/);assert.match(greatness,/classifyMapError/);assert.match(greatness,/ClientCapabilityEvidence/);assert.doesNotMatch(greatness,/ClientCapabilityEvidence[^\n]+polyline/);});
test("script URL uses only the resolved browser key and never the Places key",()=>{assert.match(source,/googleMapsScriptUrl\(browserKey,callback\)/);assert.doesNotMatch(source,/googleMapsScriptUrl\([^\n]*GOOGLE_MAPS_API_KEY/);});
test("safe evidence includes every live configuration and loader fact",()=>{for(const field of ["frontendInjectedConfigFound","frontendSameOriginConfigRequested","frontendSameOriginConfigStatus","frontendSameOriginConfigContentType","frontendSameOriginConfigSchemaValid","backendFallbackConfigRequested","backendFallbackConfigStatus","backendFallbackConfigContentType","backendFallbackConfigSchemaValid","browserKeyResolved","browserKeySource","browserKeyPlaceholderDetected","loaderAttempted","loaderScriptCount","loaderCallbackReached","googleMapsGlobalAvailable","geometryLibraryAvailable","mapContainerVisible","mapContainerWidth","mapContainerHeight","providerFailureClassification","finalMapStatus","checkedAt"])assert.match(source,new RegExp(field));assert.match(source,/__MAAT_MAP_DIAGNOSTICS__/);assert.doesNotMatch(source,/slice\([^\n]+browserKey/);});
