"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {createUserStore}=require("../src/repositories/userStore");
const {createGuidedExperienceService,determineNextGuidance,projectJourneyState,PROMPT_COOLDOWN_MS}=require("../src/services/guidedExperienceService");
const base={authenticated:true,intakeComplete:false,intakeStarted:false,programExists:false,firstWorkoutComplete:false,workoutsCompleted:0,nutritionUsed:false};
test("journey decision engine follows canonical milestones",()=>{
  assert.equal(determineNextGuidance(base,{}).key,"intake-incomplete");
  assert.equal(determineNextGuidance({...base,intakeComplete:true},{}).key,"program-missing");
  assert.equal(determineNextGuidance({...base,intakeComplete:true,programExists:true},{}).key,"first-workout");
  assert.equal(determineNextGuidance({...base,intakeComplete:true,programExists:true,firstWorkoutComplete:true,workoutsCompleted:1},{}).key,"nutrition-discovery");
  assert.match(determineNextGuidance({...base,intakeComplete:true,programExists:true,firstWorkoutComplete:true,workoutsCompleted:4,nutritionUsed:true,returningMember:true,nextAction:{type:"start_workout",title:"Train today",route:"/workout.html"}},{}).key,/returning-start-workout/);
});
test("projection reads member-home state without copying sensitive intake",()=>{const state=projectJourneyState({journey:{complete:true,started:true},healthReview:{required:false},activeProgram:{source:"Generated program"},progressSummary:{workoutsCompleted:2},nutritionMission:{active:true},primaryAction:{type:"start_workout"}});assert.equal(state.firstWorkoutComplete,true);assert.equal(state.returningMember,true);assert.equal("intake" in state,false)});
test("anti-nagging honors disable, dismissal, cooldown and milestone changes",()=>{const now=Date.now(),guide={lastPromptKey:"intake-incomplete",lastPromptAt:new Date(now-1000).toISOString(),dismissedPromptKeys:[]};assert.equal(determineNextGuidance(base,guide,{now}),null);assert.ok(determineNextGuidance({...base,intakeComplete:true},guide,{now}));assert.equal(determineNextGuidance(base,{proactiveDisabled:true},{now}),null);assert.equal(determineNextGuidance(base,{dismissedPromptKeys:["intake-incomplete"]},{now}),null);assert.ok(determineNextGuidance(base,{...guide,lastPromptAt:new Date(now-PROMPT_COOLDOWN_MS-1).toISOString()},{now}));assert.ok(determineNextGuidance(base,{proactiveDisabled:true},{now,manual:true}))});
test("presentation state persists dismiss, prompt memory, disable and manual replay",()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"guide-")),store=createUserStore({userDir:dir});let clock=1000000000;let service=createGuidedExperienceService({userStore:store,clock:()=>clock});service.update("member",{promptKey:"first-workout",action:"prompt"});service.update("member",{promptKey:"first-workout",action:"dismiss-prompt"});service.update("member",{tourId:"training",action:"dismiss"});service.update("member",{proactiveDisabled:true});const state=service.get("member");assert.equal(state.lastPromptKey,"first-workout");assert.deepEqual(state.dismissedPromptKeys,["first-workout"]);assert.equal(service.eligible(state,"training"),false);assert.equal(service.eligible(state,"training",{manual:true}),true)});
test("guided state rejects unknown tour identifiers",()=>{const store=createUserStore({userDir:fs.mkdtempSync(path.join(os.tmpdir(),"guide-"))});assert.throws(()=>createGuidedExperienceService({userStore:store}).update("member",{tourId:"fake",action:"complete"}),/unknown_tour/)});
test("browser lifecycle includes delayed targets, auth ordering, escape, focus trap and restore",()=>{const source=fs.readFileSync(path.join(__dirname,"../public/guided-experience.js"),"utf8");assert.match(source,/waitForTarget/);assert.match(source,/whenReady/);assert.match(source,/event\.key==="Escape"/);assert.match(source,/event\.key==="Tab"/);assert.match(source,/previousFocus/);assert.match(source,/manual:true/);assert.match(source,/dialog\[open\]/)});
