"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("fs");const os=require("os");const path=require("path");
const {createUserStore}=require("../src/repositories/userStore");const {createJourneyIntakeService}=require("../src/services/journeyIntakeService");
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"journey-"));const store=createUserStore({userDir:dir});return{dir,store,service:createJourneyIntakeService({userStore:store})};}
const universal={pathwaySelection:{selected:["general_fitness","yoga_wellness"],primary:"general_fitness"},identity:{fullName:"Alex Adult",phone:"555-0100",cityState:"Austin, TX",preferredCommunication:"text",emergencyContactName:"Sam",emergencyContactPhone:"555-0101"},profile:{dateOfBirth:"1990-02-03",heightCm:175,weightKg:70},goals:{primaryGoal:"Improve health",successDefinition:"Train consistently"},healthSafety:{receivingTreatmentOrRehab:false,believesExerciseIsSafe:"yes",medicalDisclaimerConsent:true},trainingContext:{activeDaysPerWeek:"3",selfRatedFitnessLevel:"beginner"},schedule:{availableDays:["monday"],availableTimes:["morning"],realisticSessionsPerWeek:"3"},generalFitness:{weightChangeGoal:"general_health",desiredWeightChange:0},yogaWellness:{experienceLevel:"beginner",primaryIntentions:["mobility"]}};
test("initializes once, migrates placeholders safely, and preserves legacy",()=>{const{store,service}=setup();store.updateUser("a",u=>{u.clientIntake={name:"N/A",goals:["N/A"],equipment:["bodyweight"]};u.goalsBaseline={goal:"strength"};return u});const a=service.get("a"),b=service.get("a");assert.equal(a.intake.schemaVersion,1);assert.equal(a.intake.identity.fullName,null);assert.deepEqual(a.intake.trainingContext.availableEquipment,[]);assert.equal(a.intake.createdAt,b.intake.createdAt);const legacy=store.loadUser("a");assert.equal(legacy.clientIntake.name,"N/A");assert.equal(legacy.goalsBaseline.goal,"strength");assert.equal(a.intake.migration.migratedFromLegacy,true)});
test("draft resumes and deeply merges without overwriting hidden fields",()=>{const{service}=setup();service.patch("a",{identity:{fullName:"Alex",preferredName:"Al"},currentStep:"goals"});service.patch("a",{identity:{phone:"555"}});const r=service.get("a").intake;assert.equal(r.identity.fullName,"Alex");assert.equal(r.identity.preferredName,"Al");assert.equal(r.identity.phone,"555");assert.equal(r.currentStep,"goals")});
test("preserves valid zero values",()=>{const{service}=setup();service.patch("a",{generalFitness:{desiredWeightChange:0}});assert.equal(service.get("a").intake.generalFitness.desiredWeightChange,0)});
test("rejects too many, duplicate, invalid, and invalid-primary pathways",()=>{const{service}=setup();for(const selection of [{selected:["general_fitness","yoga_wellness","athlete_performance"],primary:"general_fitness"},{selected:["general_fitness","general_fitness"],primary:"general_fitness"},{selected:["mystery"],primary:"mystery"},{selected:["general_fitness"],primary:"yoga_wellness"}])assert.throws(()=>service.patch("a",{pathwaySelection:selection}),/pathway/) });
test("supports General Fitness plus Yoga and server-derived completion",()=>{const{service}=setup();service.patch("a",universal);const p=service.progress("a");assert.equal(p.sectionStatuses.pathway_details,"complete");assert.equal(p.sectionStatuses.health_safety,"complete");assert.equal(p.completedCount,7)});
test("supports Athlete Performance plus Yoga without rugby requirements",()=>{const{service}=setup();const x=structuredClone(universal);x.pathwaySelection={selected:["athlete_performance","yoga_wellness"],primary:"athlete_performance"};delete x.generalFitness;x.athletePerformance={sport:"Soccer",currentLevel:"club",performancePriorities:["speed"]};service.patch("a",x);assert.equal(service.progress("a").sectionStatuses.pathway_details,"complete");assert.equal(service.get("a").intake.rugbySupplement.enabled,false)});
test("enables and conditionally requires Rugby supplement",()=>{const{service}=setup();const x=structuredClone(universal);x.pathwaySelection={selected:["athlete_performance"],primary:"athlete_performance"};delete x.generalFitness;delete x.yogaWellness;x.athletePerformance={sport:"Rugby",currentLevel:"club",performancePriorities:["power"]};service.patch("a",x);assert.equal(service.get("a").intake.rugbySupplement.enabled,true);assert.equal(service.progress("a").sectionStatuses.pathway_details,"not_started");service.patch("a",{rugbySupplement:{experienceYears:"4",formats:["sevens"],primaryPosition:"wing"}});assert.equal(service.progress("a").sectionStatuses.pathway_details,"complete")});
test("derives flags, needs_review, successful submission, and account isolation",()=>{const{service}=setup();service.patch("a",universal);let out=service.submit("a");assert.equal(out.intake.status,"submitted");const flagged=structuredClone(universal);flagged.healthSafety.currentPainOrInjury="knee pain";service.patch("b",flagged);out=service.submit("b");assert.equal(out.intake.status,"needs_review");assert.ok(out.intake.healthSafety.healthFlags.includes("CURRENT_PAIN_OR_INJURY"));assert.equal(service.get("a").intake.healthSafety.currentPainOrInjury,null)});
test("rejects incomplete submission with field details",()=>{const{service}=setup();assert.throws(()=>service.submit("a"),/incomplete/)});
test("new mobile wizard uses structured controls and no comma-separated intake",()=>{const html=fs.readFileSync(path.join(__dirname,"../public/retention-flow.js"),"utf8");assert.match(html,/What brings you to the academy/);assert.match(html,/Save and exit/);assert.match(html,/data-journey-array/);assert.doesNotMatch(html,/journey[^\n]{0,80}comma-separated/i)});
