"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {createChallengeEngineService}=require("../src/services/challengeEngineService");
const {createSessionService}=require("../src/services/sessionService");
const {createUserStore}=require("../src/repositories/userStore");
const {createEventService}=require("../src/gamification/eventService");
const {createGamificationEventStore}=require("../src/repositories/gamificationEventStore");
function harness(now="2026-08-17T10:00:00Z") {const dir=fs.mkdtempSync(path.join(os.tmpdir(),"kb-runtime-")),clock=()=>new Date(now),challenges=createChallengeEngineService({filePath:path.join(dir,"challenges.json"),clock}),users=createUserStore({userDir:path.join(dir,"users")}),events=createGamificationEventStore({filePath:path.join(dir,"events.ndjson")}),gamification=createEventService({eventStore:events,clock}),workouts=[];const sessions=createSessionService({userStore:users,workoutCompletedAdapter:fact=>{workouts.push(fact);return gamification.recordWorkoutCompleted(fact);},clock:()=>new Date(now).getTime(),onSessionCompleted:fact=>{const completion=challenges.completeCommitmentWorkout(fact);if(completion?.comeback)gamification.recordComebackCompleted({userId:fact.userId,session:completion.session});return completion;}});return{challenges,sessions,events,workouts,setNow:value=>now=value};}
function enroll(h,user="owner",count=1,days=["monday"]){return h.challenges.joinChallenge(user,"8-week-kettlebell-strength-power",{workoutsPerWeek:count,preferredWeekdays:days,startDate:"2026-08-17"}).participation;}
function start(h,user,enrollment,commitment){const resolved=h.challenges.resolveCommitmentWorkout(user,enrollment.id,commitment.scheduleSessionId),sessionId=`kb_${enrollment.id}_${commitment.scheduleSessionId}`;h.sessions.startSession({userId:user,sessionId,programId:resolved.challenge.id,payload:{sourceMetadata:resolved.source,canonicalWorkout:resolved.canonical}});h.challenges.markCommitmentStarted(user,enrollment.id,commitment.scheduleSessionId,sessionId);return{resolved,sessionId};}
test("server resolves canonical prescription and normal completion preserves exact source identity",()=>{const h=harness(),enrollment=enroll(h),commitment=enrollment.commitmentSchedule.find(x=>x.type==="workout"),{resolved,sessionId}=start(h,"owner",enrollment,commitment);assert.equal(resolved.canonical.id,"week1-essential");assert.ok(resolved.canonical.activities.every(x=>x.exerciseId));assert.equal(resolved.source.commitmentSessionId,commitment.scheduleSessionId);const result=h.sessions.completeSession({userId:"owner",sessionId});const completed=result.sourceCompletion.session;assert.equal(completed.state,"completed");assert.equal(completed.originalPlannedDate,"2026-08-17");assert.equal(completed.actualCompletionDate,"2026-08-17");assert.equal(completed.completedOnPlannedDay,true);assert.equal(completed.workoutSessionId,sessionId);});
test("missed workout completed in makeup window is comeback and duplicate callback awards once",()=>{const h=harness(),enrollment=enroll(h),commitment=enrollment.commitmentSchedule.find(x=>x.type==="workout");h.setNow("2026-08-18T10:00:00Z");h.challenges.active("owner");const refreshed=h.challenges._read().userChallenges[0],missed=refreshed.commitmentSchedule.find(x=>x.scheduleSessionId===commitment.scheduleSessionId);assert.equal(missed.state,"makeup_available");h.challenges.rescheduleCommitment("owner",enrollment.id,missed.scheduleSessionId,{targetDate:"2026-08-18"});const {sessionId}=start(h,"owner",enrollment,missed);const first=h.sessions.completeSession({userId:"owner",sessionId}),second=h.sessions.completeSession({userId:"owner",sessionId});assert.equal(first.sourceCompletion.session.state,"comeback_completed");assert.equal(first.sourceCompletion.session.originalPlannedDate,"2026-08-17");assert.equal(first.sourceCompletion.session.actualCompletionDate,"2026-08-18");assert.equal(first.sourceCompletion.session.recoveredMissedCommitment,true);assert.equal(second.duplicate,true);assert.equal(second.sourceCompletion.duplicate,true);const types=h.events.readAfter().map(x=>x.event.eventType);assert.equal(types.filter(x=>x==="workout.completed").length,1);assert.equal(types.filter(x=>x==="commitment.comeback.completed").length,1);assert.equal(h.workouts.length,1);});
test("reschedule validation, completion guard, ownership, weekly adherence and fourth-day technique",()=>{const h=harness(),enrollment=enroll(h,"owner",3,["monday","wednesday","friday"]),monday=enrollment.commitmentSchedule.find(x=>x.weekNumber===1&&x.weekday==="monday");assert.throws(()=>h.challenges.rescheduleCommitment("owner",enrollment.id,monday.scheduleSessionId,{targetDate:"2026-08-19"}),/recovery day/);assert.throws(()=>h.challenges.rescheduleCommitment("attacker",enrollment.id,monday.scheduleSessionId,{targetDate:"2026-08-18"}),/not found/i);const {sessionId}=start(h,"owner",enrollment,monday);h.sessions.completeSession({userId:"owner",sessionId});assert.throws(()=>h.challenges.rescheduleCommitment("owner",enrollment.id,monday.scheduleSessionId,{targetDate:"2026-08-18"}),/eligible/);const active=h.challenges.active("owner");assert.equal(active.commitmentSummary.weeks[0].completed,1);assert.equal(active.participation.commitmentSchedule.filter(x=>x.type==="recovery").every(x=>x.state==="recovery"),true);const four=enroll(h,"four",4,["monday","tuesday","wednesday","thursday"]),fourth=four.commitmentSchedule.filter(x=>x.weekNumber===1&&x.type==="workout")[3],resolved=h.challenges.resolveCommitmentWorkout("four",four.id,fourth.scheduleSessionId);assert.equal(resolved.canonical.id,"week1-technique");assert.equal(resolved.canonical.technique,true);assert.notEqual(resolved.canonical.id,"week1-c");});
