"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {createChallengeEngineService}=require("../src/services/challengeEngineService");
const {createSessionService}=require("../src/services/sessionService");
const {createUserStore}=require("../src/repositories/userStore");
const {resetKettlebellTestSession}=require("../scripts/reset-kettlebell-test-session");

test("exact owned unfinished test session reset is idempotent and preserves commitment",()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"kb-reset-")),challengeFile=path.join(dir,"challenges.json"),users=createUserStore({userDir:path.join(dir,"users")}),service=createChallengeEngineService({filePath:challengeFile,clock:()=>new Date("2026-08-17T10:00:00Z")}),sessions=createSessionService({userStore:users,clock:()=>Date.parse("2026-08-17T10:00:00Z")});const enrollment=service.joinChallenge("owner","8-week-kettlebell-strength-power",{workoutsPerWeek:3,preferredWeekdays:["monday","wednesday","friday"],startDate:"2026-08-17"}).participation,commitment=enrollment.commitmentSchedule.find(item=>item.type==="workout"),resolved=service.resolveCommitmentWorkout("owner",enrollment.id,commitment.scheduleSessionId),runtimeId=`kb_${enrollment.id}_${commitment.scheduleSessionId}`;sessions.startSession({userId:"owner",sessionId:runtimeId,payload:{sourceMetadata:resolved.source,canonicalWorkout:resolved.canonical}});service.markCommitmentStarted("owner",enrollment.id,commitment.scheduleSessionId,runtimeId);const input={challengeFile,userFile:users.userPath("owner"),userId:"owner",enrollmentId:enrollment.id,commitmentSessionId:commitment.scheduleSessionId};resetKettlebellTestSession(input);resetKettlebellTestSession(input);const clean=createChallengeEngineService({filePath:challengeFile,clock:()=>new Date("2026-08-17T10:00:00Z")}).current("owner","8-week-kettlebell-strength-power"),user=users.loadUser("owner");assert.equal(clean.participation.commitment.workoutsPerWeek,3);assert.deepEqual(clean.participation.commitment.preferredWeekdays,["monday","wednesday","friday"]);assert.equal(clean.currentSession.schedule.state,"due_today");assert.equal(clean.currentSession.schedule.workoutSessionId,undefined);assert.equal(clean.commitmentSummary.completedWorkouts,0);assert.equal(clean.commitmentSummary.commitmentStreak,0);assert.equal(user.sessions[runtimeId],undefined);assert.equal(user.events.some(event=>event.command==="fitness.startSession"),false);assert.equal(clean.currentSession.workout.id,resolved.canonical.id);assert.equal(clean.currentSession.workout.activities[0].exerciseId,"exercise_kettlebell_deadlift");assert.equal(service.resolveCommitmentWorkout("owner",enrollment.id,commitment.scheduleSessionId).source.enrollmentId,enrollment.id);});

test("reset refuses cross-user and completed workout state",()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"kb-reset-guard-")),challengeFile=path.join(dir,"challenges.json"),userFile=path.join(dir,"owner.json"),service=createChallengeEngineService({filePath:challengeFile,clock:()=>new Date("2026-08-17")}),enrollment=service.joinChallenge("owner","8-week-kettlebell-strength-power",{workoutsPerWeek:1,preferredWeekdays:["monday"],startDate:"2026-08-17"}).participation,commitment=enrollment.commitmentSchedule.find(item=>item.type==="workout");fs.writeFileSync(userFile,JSON.stringify({userId:"owner",sessions:{},events:[]}));const input={challengeFile,userFile,userId:"attacker",enrollmentId:enrollment.id,commitmentSessionId:commitment.scheduleSessionId};assert.throws(()=>resetKettlebellTestSession(input),/owned/);});
