"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const {buildCommitmentSchedule,refreshCommitmentStates,rescheduleCommitmentSession,completeCommitmentSession,commitmentSummary}=require("../src/program-engine/challengeCommitmentScheduler");

const days=["monday","wednesday","friday","sunday"];
function build(count=3){return buildCommitmentSchedule({workoutsPerWeek:count,preferredWeekdays:days.slice(0,count),startDate:"2026-08-17"});}
for(const count of [1,2,3,4])test(`${count}-day commitment creates exact weekly workouts and visible recovery`,()=>{const {enrollment,schedule}=build(count);assert.equal(enrollment.promisedWorkouts,count*8);for(let week=1;week<=8;week++){const rows=schedule.filter(x=>x.weekNumber===week);assert.equal(rows.filter(x=>x.type==="workout").length,count);assert.equal(rows.filter(x=>x.type==="recovery").length,7-count);assert.ok(rows.filter(x=>x.type==="recovery").every(x=>x.state==="recovery"&&x.recoveryTip));}});
test("more than four training days and mismatched weekdays are rejected",()=>{assert.throws(()=>buildCommitmentSchedule({workoutsPerWeek:5,preferredWeekdays:days,startDate:"2026-08-17"}),/1 to 4/);assert.throws(()=>buildCommitmentSchedule({workoutsPerWeek:3,preferredWeekdays:["monday"],startDate:"2026-08-17"}),/one unique weekday/);});
test("a missed date remains recoverable inside its week and preserves original date",()=>{const {schedule}=build(3),refreshed=refreshCommitmentStates(schedule,new Date("2026-08-19T12:00:00Z")),missed=refreshed.find(x=>x.originalPlannedDate==="2026-08-17");assert.equal(missed.state,"makeup_available");assert.equal(missed.originalPlannedDate,"2026-08-17");assert.ok(missed.missedAt);});
test("safe makeup records planned and actual dates and is idempotent",()=>{const {enrollment,schedule}=build(2),refreshed=refreshCommitmentStates(schedule,new Date("2026-08-18T12:00:00Z")),session=refreshed.find(x=>x.state==="makeup_available"),rescheduled=rescheduleCommitmentSession(refreshed,session.scheduleSessionId,"2026-08-18",new Date("2026-08-18T12:00:00Z")),first=completeCommitmentSession(rescheduled,session.scheduleSessionId,new Date("2026-08-18T18:00:00Z")),again=completeCommitmentSession(first.schedule,session.scheduleSessionId,new Date("2026-08-18T18:10:00Z")),done=first.schedule.find(x=>x.scheduleSessionId===session.scheduleSessionId);assert.equal(new Set(rescheduled.filter(x=>x.weekNumber===1).map(x=>x.plannedDate)).size,7);assert.equal(done.originalPlannedDate,"2026-08-17");assert.equal(done.actualCompletionDate,"2026-08-18");assert.equal(done.state,"comeback_completed");assert.equal(first.duplicate,false);assert.equal(again.duplicate,true);const summary=commitmentSummary(first.schedule,enrollment);assert.equal(summary.comebackCount,1);});
test("makeup cannot stack on a workout day or create three consecutive training days",()=>{const {schedule}=build(3),refreshed=refreshCommitmentStates(schedule,new Date("2026-08-18T12:00:00Z")),session=refreshed.find(x=>x.state==="makeup_available");assert.throws(()=>rescheduleCommitmentSession(refreshed,session.scheduleSessionId,"2026-08-19",new Date("2026-08-18T12:00:00Z")),/recovery day/);assert.throws(()=>rescheduleCommitmentSession(refreshed,session.scheduleSessionId,"2026-08-20",new Date("2026-08-18T12:00:00Z")),/three consecutive/);});
test("planned recovery never breaks a weekly commitment streak",()=>{const {enrollment,schedule}=build(1),weekOne=schedule.find(x=>x.weekNumber===1&&x.type==="workout"),weekTwo=schedule.find(x=>x.weekNumber===2&&x.type==="workout"),one=completeCommitmentSession(schedule,weekOne.scheduleSessionId,new Date(`${weekOne.plannedDate}T18:00:00Z`)).schedule,two=completeCommitmentSession(one,weekTwo.scheduleSessionId,new Date(`${weekTwo.plannedDate}T18:00:00Z`)).schedule,summary=commitmentSummary(two,enrollment);assert.equal(summary.commitmentStreak,2);assert.equal(summary.weeks[0].status,"weekly_commitment_kept");assert.equal(summary.weeks[1].status,"weekly_commitment_kept");});
