const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('public/workout.html'),hub=read('public/kettlebell-workout-runtime.js'),challenge=read('public/challenge-page.js'),server=read('server.js');
test('Safari load order installs the one canonical API client before the challenge adapter',()=>{const api=html.indexOf('/api-client.js'),adapter=html.indexOf('/kettlebell-workout-runtime.js');assert.ok(api>0);assert.ok(adapter>api);assert.match(hub,/client\?\.request/);assert.doesNotMatch(hub,/window\.MaatApiClient\.request/)});
test('challenge handoff targets Pocket PT with authoritative correlation only',()=>{assert.match(challenge,/source","kettlebell-challenge/);assert.match(challenge,/commitmentSessionId/);assert.match(server,/runtimeUrl:`\/workout\.html\?sessionId=/);assert.doesNotMatch(challenge,/canonicalWorkout\s*:/)});
test('owned challenge is selected and projects Today workout, schedule, media and education',()=>{for(const token of ['workoutSelect','8-Week Kettlebell Strength & Power Challenge','workoutPlanView','commitmentSchedule','type==="workout"','education?.media','Movement Intelligence','MaatApiClient.resolve'])assert.match(hub,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(hub,/\.jpg|\.jpeg/i)});
test('hub start resumes first incomplete exercise and uses existing coach and camera controls',()=>{assert.match(hub,/runtimeProgress\?\.exerciseIndex/);assert.match(hub,/WorkoutCoachRuntime\?\.prepareSet/);assert.match(hub,/WorkoutCoachRuntime\?\.workStarted/);assert.match(hub,/document\.getElementById\("startBtn"\)/);assert.match(hub,/Connect Camera/);assert.doesNotMatch(hub,/getUserMedia|poseDetection/i)});
test('authoritative current activity selects the advisory checkpoint and candidate contracts',()=>{assert.match(html,/kettlebell-checkpoints\.js/);assert.match(html,/qualified-rep-runtime\.js/);assert.match(hub,/runtime\?\.canonicalWorkout\?\.activities\?\.\[currentIndex\]/);assert.match(hub,/exerciseId:exercise\.exerciseId/);assert.match(hub,/pose-runtime:frame/);assert.match(hub,/QualifiedRepRuntime\.CandidateStateMachine/);assert.match(hub,/advisory only/);assert.doesNotMatch(hub,/global\.RepRuntime|persistRepUpdate|completeCheckpoint/)});
test('friendly error hides raw implementation exception while diagnostics retain context',()=>{assert.match(hub,/couldn\\'t load this workout/);assert.match(hub,/\[KETTLEBELL_HUB_BOOT\]/);assert.doesNotMatch(hub,/safe\(error\.message\)/)});
