"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),os=require("node:os");
const {createChallengeEngineService}=require("../src/services/challengeEngineService");
const {MEDIA,getEducation}=require("../data/challenges/kettlebellExerciseEducation");
const {createApp}=require("../server");
async function withServer(run){const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),"kb-education-routes-")),app=createApp({rootDir:ROOT,challengeEnginePath:path.join(dataDir,"runtime.json"),allowInsecureTestRoutes:true}),server=app.listen(0);await new Promise((resolve,reject)=>{server.once("listening",resolve);server.once("error",reject);});try{return await run(`http://127.0.0.1:${server.address().port}`);}finally{await new Promise(resolve=>server.close(resolve));}}
const ROOT=path.resolve(__dirname,"..");
test("current challenge projection selects the actionable canonical session with structured cards",()=>{const service=createChallengeEngineService({filePath:path.join(fs.mkdtempSync(path.join(os.tmpdir(),"kb-education-")),"state.json"),clock:()=>new Date("2026-08-17T12:00:00Z")});service.joinChallenge("member","8-week-kettlebell-strength-power",{workoutsPerWeek:1,preferredWeekdays:["monday"],startDate:"2026-08-17"});const current=service.current("member","8-week-kettlebell-strength-power").currentSession;assert.equal(current.workout.id,"week1-essential");assert.equal(current.schedule.plannedDate,"2026-08-17");assert.ok(current.workout.activities.every(item=>item.exerciseId&&item.education?.movementStages.length));assert.equal(current.workout.activities.find(item=>item.exerciseId==="exercise_suitcase_carry").education.movementType,"carry");});
test("education registry uses only the four existing proof-of-concept files",()=>{assert.deepEqual(Object.keys(MEDIA).sort(),["exercise_bent_over_row","exercise_goblet_squat","exercise_kettlebell_halo","exercise_suitcase_carry"]);for(const media of Object.values(MEDIA)){assert.match(media.sourcePath,/^exercise-generation\/kettlebellchallenge\/[^/]+\.jpg$/);assert.ok(fs.existsSync(path.join(ROOT,media.sourcePath)));}assert.equal(getEducation({exerciseId:"exercise_two_hand_kettlebell_swing",name:"Swing",exerciseType:"ballistic"}).educationStatus,"canonical_fallback");});
test("allowlisted education API and existing-file media route are browser accessible",()=>withServer(async base=>{const education=await fetch(`${base}/api/challenge-exercises/exercise_goblet_squat`),media=await fetch(`${base}${MEDIA.exercise_goblet_squat.url}`),blocked=await fetch(`${base}/exercise-media/kettlebell/not-allowed`);assert.equal(education.status,200);assert.equal((await education.json()).data.movementType,"traditional_lift");assert.equal(media.status,200);assert.equal(media.headers.get("content-type"),"image/jpeg");assert.equal(Number(media.headers.get("content-length")),fs.statSync(path.join(ROOT,MEDIA.exercise_goblet_squat.sourcePath)).size);assert.equal(blocked.status,404);}));
test("challenge UI prioritizes current exercise cards and preserves explicit states",()=>{const js=fs.readFileSync(path.join(ROOT,"public/challenge-page.js"),"utf8"),css=fs.readFileSync(path.join(ROOT,"public/challenges.css"),"utf8");for(const text of ["Today's Workout","Resume Workout","Makeup Workout","Not Started","Completed","View Exercise","currentSession"])assert.match(js,new RegExp(text.replace(/[']/g,".")));assert.match(css,/\.exercise-grid/);assert.match(css,/\.state-current/);});
