"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),os=require("node:os");
const {createChallengeEngineService}=require("../src/services/challengeEngineService");
const {MEDIA,getEducation}=require("../data/challenges/kettlebellExerciseEducation");
const {createApp}=require("../server");
async function withServer(run){const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),"kb-education-routes-")),app=createApp({rootDir:ROOT,challengeEnginePath:path.join(dataDir,"runtime.json"),allowInsecureTestRoutes:true}),server=app.listen(0);await new Promise((resolve,reject)=>{server.once("listening",resolve);server.once("error",reject);});try{return await run(`http://127.0.0.1:${server.address().port}`);}finally{await new Promise(resolve=>server.close(resolve));}}
const ROOT=path.resolve(__dirname,"..");
const EXPECTED_MEDIA=Object.freeze({
  exercise_kettlebell_deadlift:"Kettlebell Deadlift.jpg",exercise_goblet_squat:"gobletsquat.jpg",exercise_bent_over_row:"bentoverrow.jpg",exercise_suitcase_carry:"suitcasecarry.jpg",exercise_kettlebell_halo:"kettelbellhalo.jpg",exercise_reverse_lunge:"ReverseLunge.jpg",exercise_kettlebell_floor_press:"Kettlebell Floor Press.jpg",exercise_two_hand_kettlebell_swing:"Two-HandKettlebellSwing.jpg",exercise_overhead_press:"Overhead Press.jpg",exercise_farmer_carry:"Farmer Carry.jpg",exercise_kettlebell_clean:"KettlebellClean.jpg",exercise_push_press:"PushPress.jpg",exercise_high_pull:"Kettlebell Clean.jpg",exercise_front_rack_carry:"Front-Rack Carry.jpg",exercise_clean_to_press:"Clean to Press.jpg",exercise_kettlebell_snatch:"Kettlebell Snatch.jpg"
});
test("current challenge projection selects the actionable canonical session with structured cards",()=>{const service=createChallengeEngineService({filePath:path.join(fs.mkdtempSync(path.join(os.tmpdir(),"kb-education-")),"state.json"),clock:()=>new Date("2026-08-17T12:00:00Z")});service.joinChallenge("member","8-week-kettlebell-strength-power",{workoutsPerWeek:1,preferredWeekdays:["monday"],startDate:"2026-08-17"});const current=service.current("member","8-week-kettlebell-strength-power").currentSession;assert.equal(current.workout.id,"week1-essential");assert.equal(current.schedule.plannedDate,"2026-08-17");assert.ok(current.workout.activities.every(item=>item.exerciseId&&item.education?.movementStages.length));assert.equal(current.workout.activities.find(item=>item.exerciseId==="exercise_suitcase_carry").education.movementType,"carry");});
test("canonical registry deliberately maps every challenge exercise to its exact existing JPG",()=>{assert.deepEqual(Object.keys(MEDIA).sort(),Object.keys(EXPECTED_MEDIA).sort());for(const [id,filename] of Object.entries(EXPECTED_MEDIA)){const media=MEDIA[id];assert.equal(media.sourcePath,`exercise-generation/kettlebellchallenge/${filename}`,id);assert.equal(media.url,`/exercise-media/kettlebell/${id}`,id);assert.ok(media.alt.length>10,id);assert.ok(fs.existsSync(path.join(ROOT,media.sourcePath)),id);}assert.equal(MEDIA.exercise_kettlebell_clean.sourcePath.endsWith("KettlebellClean.jpg"),true);assert.equal(MEDIA.exercise_high_pull.sourcePath.endsWith("Kettlebell Clean.jpg"),true);assert.equal(getEducation({exerciseId:"exercise_unknown",name:"Unknown",exerciseType:"strength"}).media,null);});
test("allowlisted education API and all registered media routes are browser accessible",()=>withServer(async base=>{const education=await fetch(`${base}/api/challenge-exercises/exercise_goblet_squat`);assert.equal(education.status,200);assert.equal((await education.json()).data.movementType,"traditional_lift");for(const [id,descriptor] of Object.entries(MEDIA)){const response=await fetch(`${base}${descriptor.url}`);assert.equal(response.status,200,id);assert.equal(response.headers.get("content-type"),"image/jpeg",id);assert.equal(Number(response.headers.get("content-length")),fs.statSync(path.join(ROOT,descriptor.sourcePath)).size,id);}for(const unsafe of ["exercise_unknown","..%2F..%2Fserver.js","%2e%2e%2fserver.js","exercise_goblet_squat%2F..%2Fserver.js"]){const blocked=await fetch(`${base}/exercise-media/kettlebell/${unsafe}`);assert.equal(blocked.status,404,unsafe);}}));
test("cards and Movement Intelligence share backend-owned media and graceful image-error fallback",()=>{const js=fs.readFileSync(path.join(ROOT,"public/challenge-page.js"),"utf8"),css=fs.readFileSync(path.join(ROOT,"public/challenges.css"),"utf8");for(const text of ["Today's Workout","Resume Workout","Makeup Workout","Not Started","Completed","View Exercise","currentSession","Exercise visual unavailable","installImageFallbacks"])assert.match(js,new RegExp(text.replace(/[']/g,".")));assert.match(js,/MaatApiClient\.resolve\(media\.url\)/);assert.match(js,/mediaMarkup\(exercise\.education\.media\)/);assert.match(js,/mediaMarkup\(d\.media,"education"\)/);assert.match(css,/\.exercise-grid/);assert.match(css,/\.state-current/);assert.match(css,/\.media-error \.media-fallback\{display:grid\}/);});
