"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const source=fs.readFileSync(path.join(__dirname,"../public/leaderboards.js"),"utf8");
function contract(){const listeners={};const win={location:{origin:"https://app.example"},MAAT_BACKEND_ORIGIN:"https://api.example/",addEventListener:(name,fn)=>listeners[name]=fn};const context={window:win,document:{},console,Set,encodeURIComponent};vm.runInNewContext(source,context);return win.LeaderboardBrowserContract;}
test("Safari-safe endpoint construction avoids URLPattern and dynamic regular expressions",()=>{const api=contract();assert.equal(api.endpoint("/api/me/leaderboards/xp_weekly?limit=25"),"https://api.example/api/me/leaderboards/xp_weekly?limit=25");assert.doesNotMatch(source,/URLPattern|new RegExp/);});
test("lifetime, weekly and monthly identifiers are the only client periods",()=>{const api=contract();assert.deepEqual([...api.periods],["xp_weekly","xp_monthly","xp_lifetime"]);});
test("zero XP, empty, private and not-ranked responses remain valid server projections",()=>{const api=contract();for(const entries of [[],[{rank:1,displayName:"Member Falcon",xp:0,isSelf:false}]])assert.equal(api.validBoard({leaderboardId:"xp_weekly",entries,nextCursor:null,selfPosition:null},"xp_weekly").entries.length,entries.length);});
test("invalid cursor, period, response and browser exceptions map to safe contracts",()=>{const api=contract();assert.throws(()=>api.validBoard({leaderboardId:"xp_weekly",entries:[],nextCursor:3},"xp_weekly"),/LEADERBOARD_CURSOR_INVALID/);assert.throws(()=>api.validBoard({leaderboardId:"xp_monthly",entries:[]},"xp_weekly"),/LEADERBOARD_RESPONSE_INVALID/);assert.equal(api.classify(Object.assign(new Error("The string did not match the expected pattern."),{name:"TypeError"})),"LEADERBOARD_BROWSER_COMPATIBILITY_ERROR");});
test("UI separates loading, empty, populated and error/retry while keeping Push-Up separate",()=>{for(const state of ["loading","empty","populated","error"])assert.match(source,new RegExp(`data(?:set)?[.\"]+${state}|${state}`));assert.match(source,/textContent="Retry"/);assert.match(source,/Push-Up Challenge scores remain separate/);assert.match(source,/LEADERBOARD_PRIVACY_UPDATE_FAILED/);assert.doesNotMatch(source,/board\.textContent\s*=\s*error\.message/);});
