"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{pathToFileURL}=require("node:url");
async function stateModule(){const source=fs.readFileSync(path.join(__dirname,"../public/goal-route-state.js"),"utf8"),file=`/tmp/goal-route-state-${process.pid}.mjs`;fs.writeFileSync(file,source);return import(pathToFileURL(file));}
test("preset conversions remain exact",async()=>{const {METERS_PER_MILE}=await stateModule();assert.equal(METERS_PER_MILE,1609.344);assert.equal(2*METERS_PER_MILE,3218.688);assert.equal(5*1000,5000);});
test("5K response is invalidated after switching to one mile",async()=>{const {createGoalRouteState}=await stateModule();let goal={distanceMeters:5000,label:"5K"};const state=createGoalRouteState(()=>goal),old=state.begin();goal={distanceMeters:1609.344,label:"1 mile"};state.changed();assert.equal(state.accepts({goalRevision:0,requestedTargetDistanceMeters:5000},old),false);});
test("two-mile alternative cannot overwrite one-mile route",async()=>{const {createGoalRouteState}=await stateModule();let goal={distanceMeters:3218.688,label:"2 miles"};const state=createGoalRouteState(()=>goal),old=state.begin();goal={distanceMeters:1609.344,label:"1 mile"};state.changed();assert.equal(state.accepts({goalRevision:0,requestedTargetDistanceMeters:3218.688},old),false);});
test("current matching request is accepted and stale generation is rejected",async()=>{const {createGoalRouteState}=await stateModule();const state=createGoalRouteState(()=>({distanceMeters:1609.344,label:"1 mile"})),old=state.begin(),current=state.begin(),response={goalRevision:0,requestedTargetDistanceMeters:1609.344};assert.equal(state.accepts(response,old),false);assert.equal(state.accepts(response,current),true);});
test("mobile route implementation sends loop preference/current goal and reuses map",()=>{const ui=fs.readFileSync(path.join(__dirname,"../public/greatness.js"),"utf8"),map=fs.readFileSync(path.join(__dirname,"../public/trail-map.js"),"utf8");assert.match(ui,/targetDistanceMeters:goal\.targetDistanceMeters/);assert.match(ui,/routeType:"loop"/);assert.match(ui,/goalRevision:goal\.goalRevision/);assert.match(ui,/currentRouteFingerprint/);assert.match(map,/mapStates\.get\(container\)/);assert.match(map,/event\?\.trigger\?\.\(map,"resize"\)/);assert.match(map,/INVALID_ROUTE_GEOMETRY/);});
test("Map Debug restores the proven admin or production debug authorization",()=>{const source=fs.readFileSync(path.join(__dirname,"../public/map-diagnostics.js"),"utf8");assert.doesNotMatch(source,/explicitlyRequested|userEnabled|diagnosticsEnabled/);assert.match(source,/authorized=ADMIN_ROLES\.has\(role\)\|\|config\.debugMapEnabled===true/);});
