'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const policy=require('../public/motion/lower-body-spatial-policy');
const Generator=require('../public/motion/motion-description-to-spec-generator');
const descriptions=require('../public/motion/yoga/beginner-flow-motion-descriptions.v1.json');
const plans=require('../public/motion/yoga/beginner-flow-generation-plans.v1.json');
const classification=descriptions.descriptions.find(x=>x.exerciseId==='warrior-ii').movementClassification;
function fixture(scale=1,leadLeg='left'){
  return policy.resolve({classification:{...classification,leadLeg},groundY:0,center:{x:0,z:0},left:{hip:{x:-.1*scale,y:1*scale,z:0},upperLength:.5*scale,lowerLength:.5*scale},right:{hip:{x:.1*scale,y:1*scale,z:0},upperLength:.5*scale,lowerLength:.5*scale}});
}
test('classification selects asymmetric wide-lunge, never symmetric straddle',()=>{const request={requestType:'motion-description-to-draft',exerciseId:'warrior-ii',displayName:'Warrior II',description:descriptions.descriptions.find(x=>x.exerciseId==='warrior-ii')};const out=Generator.generate(request,plans.plans.find(x=>x.exerciseId==='warrior-ii'));assert.equal(out.status,'ready');assert.equal(out.spec.generationMetadata.movementClassification.movementFamily,'standing-asymmetric-wide-lunge');assert.ok(out.spec.generationMetadata.selectedMovementOperators.some(x=>x.id==='lower-body:standing-asymmetric-wide-lunge-v1'));assert.ok(!out.spec.generationMetadata.selectedMovementOperators.some(x=>/straddle/.test(x.id)));assert.equal(out.spec.lowerBodySpatialPolicy.scaleReference,'effective-leg-length');assert.deepEqual(out.spec.lowerBodySpatialPolicy.activePhaseIds,['target','hold']);assert.deepEqual(out.spec.phases.find(x=>x.id==='target').contacts,['left_foot','right_foot']);assert.deepEqual(out.spec.phases.find(x=>x.id==='hold').contacts,['left_foot','right_foot']);});
test('stance width scales across avatar proportions while knee geometry remains targeted',()=>{const short=fixture(1),tall=fixture(1.4);assert.equal(short.status,'ready');assert.equal(tall.status,'ready');assert.ok(Math.abs(short.resolvedStanceWidth-1.35)<1e-9);assert.ok(Math.abs(tall.resolvedStanceWidth-1.89)<1e-9);for(const x of [short,tall]){assert.ok(x.leadKneeAngleMeasuredDegrees>=80&&x.leadKneeAngleMeasuredDegrees<=105);assert.ok(x.leadKneeToAnkleHorizontalError<=.02*x.effectiveLegLength);assert.ok(x.trailingKneeAngleDegrees>=170);assert.equal(x.leftFootContact,true);assert.equal(x.rightFootContact,true);}});
test('mirroring swaps lead/trail anchors without changing stance depth',()=>{const left=fixture(1,'left'),right=fixture(1,'right');assert.equal(left.leadLeg,'left');assert.equal(right.leadLeg,'right');assert.equal(left.resolvedStanceWidth,right.resolvedStanceWidth);assert.equal(left.leadAnchor.x,-right.leadAnchor.x);assert.equal(left.trailAnchor.x,-right.trailAnchor.x);});
test('non-wide-lunge poses remain free of the spatial operator',()=>{for(const id of ['mountain','chair','downward-dog','cobra','bridge']){const description=descriptions.descriptions.find(x=>x.exerciseId===id),plan=plans.plans.find(x=>x.exerciseId===id),out=Generator.generate({requestType:'motion-description-to-draft',exerciseId:id,displayName:description.displayName,description},plan);assert.equal(out.status,'ready');assert.equal(out.spec.lowerBodySpatialPolicy,undefined,id);}});
