'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
function fresh(){const p=require.resolve('../public/mirror-motion-acceptance');delete require.cache[p];return require(p);}
function clear(){for(let n=2;n<=18;n++)delete global[`PocketPTMirrorMotionPhase${n}`];delete global.AvatarRuntime;delete global.__avatarRuntime;delete global.PocketPTMotionLabRuntime;delete global.__avatarRuntimeStatus;delete global.__mirrorMotionFoundationStatus;delete global.PocketPTMirrorMotionCameraReview;delete global.PocketPTMirrorMotionCameraActivation;}
function healthyPhases(){for(let n=2;n<=18;n++)global[`PocketPTMirrorMotionPhase${n}`]={diagnostics:()=>({firstFailingBoundary:'NONE',processErrors:0,lastIssue:'OK'})};}
function healthyClosures(){global.PocketPTMirrorMotionCameraReview={diagnostics:()=>({firstFailingBoundary:'NONE',processErrors:0,lastIssue:'OK'})};global.PocketPTMirrorMotionCameraActivation={diagnostics:()=>({firstFailingBoundary:'NONE',processErrors:0,lastIssue:'OK'})};}

test('acceptance waits at the earliest missing stage instead of claiming ready',()=>{clear();global.PocketPTMirrorMotionPhase2={diagnostics:()=>({firstFailingBoundary:'NONE',processErrors:0})};const p=fresh();const d=p.evaluate();assert.equal(d.status,'WAITING');assert.equal(d.firstWaitingBoundary,'PHASE3_NOT_LOADED');assert.equal(global.__mirrorMotionFoundationStatus.status,'WAITING');clear();});

test('acceptance reports the earliest actual phase failure before downstream symptoms',()=>{clear();healthyPhases();healthyClosures();global.PocketPTMirrorMotionPhase5={diagnostics:()=>({firstFailingBoundary:'PHASE5_IK_FAILURE',processErrors:1,lastIssue:'IK'})};global.PocketPTMirrorMotionPhase11={diagnostics:()=>({firstFailingBoundary:'PHASE11_DOWNSTREAM_FAILURE',processErrors:1})};global.AvatarRuntime={boneRestPose:{hips:{}},getStatus:()=>({mappedBoneCount:1})};const p=fresh();const d=p.evaluate();assert.equal(d.status,'FAIL');assert.equal(d.firstFailingBoundary,'PHASE5_IK_FAILURE');assert.equal(global.__mirrorMotionFoundationStatus.firstFailingBoundary,'PHASE5_IK_FAILURE');clear();});

test('acceptance does not call the stack ready until avatar runtime and rest pose are observable',()=>{clear();healthyPhases();healthyClosures();const p=fresh();let d=p.evaluate();assert.equal(d.status,'WAITING');assert.equal(d.firstWaitingBoundary,'AVATAR_RUNTIME_NOT_AVAILABLE');global.AvatarRuntime={};d=p.evaluate();assert.equal(d.firstWaitingBoundary,'REST_POSE_NOT_OBSERVABLE');clear();});

test('acceptance rejects a partial rest snapshot against the mapped rig',()=>{clear();healthyPhases();healthyClosures();const status={mappedBoneCount:4};global.AvatarRuntime={boneRestPose:{hips:{},spine:{}},getStatus:()=>status};const p=fresh();const d=p.evaluate();assert.equal(d.status,'WAITING');assert.equal(d.firstWaitingBoundary,'REST_POSE_INCOMPLETE');assert.equal(d.restPoseStatus,'PARTIAL');assert.equal(d.restPoseBoneCount,2);assert.equal(d.restPoseExpectedBones,4);assert.equal(status.mirrorMotionFoundationStatus,'WAITING');clear();});

test('acceptance waits when camera closure layers are not loaded',()=>{clear();healthyPhases();const status={mappedBoneCount:1};global.AvatarRuntime={boneRestPose:{hips:{}},getStatus:()=>status};const p=fresh();let d=p.evaluate();assert.equal(d.status,'WAITING');assert.equal(d.firstWaitingBoundary,'CAMERA_MOTION_REVIEW_NOT_LOADED');global.PocketPTMirrorMotionCameraReview={diagnostics:()=>({firstFailingBoundary:'NONE',processErrors:0})};d=p.evaluate();assert.equal(d.firstWaitingBoundary,'CAMERA_MOTION_ACTIVATION_NOT_LOADED');clear();});

test('acceptance fails on camera closure runtime failure',()=>{clear();healthyPhases();healthyClosures();const status={mappedBoneCount:1};global.AvatarRuntime={boneRestPose:{hips:{}},getStatus:()=>status};global.PocketPTMirrorMotionCameraActivation={diagnostics:()=>({firstFailingBoundary:'CAMERA_MOTION_ACTIVATION_PROCESS_ERROR',processErrors:1})};const p=fresh();const d=p.evaluate();assert.equal(d.status,'FAIL');assert.equal(d.firstFailingBoundary,'CAMERA_MOTION_ACTIVATION_PROCESS_ERROR');clear();});

test('acceptance reports READY only with healthy phases, complete rest evidence, and healthy closure layers',()=>{clear();healthyPhases();healthyClosures();const status={mappedBoneCount:2};global.AvatarRuntime={boneRestPose:{hips:{},spine:{}},getStatus:()=>status};const p=fresh();const d=p.evaluate();assert.equal(d.status,'READY');assert.equal(d.firstFailingBoundary,'NONE');assert.equal(d.firstWaitingBoundary,'NONE');assert.equal(d.restPoseStatus,'CAPTURED');assert.equal(d.restPoseBoneCount,2);assert.equal(d.restPoseExpectedBones,2);assert.equal(d.closureStatus,'HEALTHY');assert.equal(global.__mirrorMotionFoundationStatus.cameraReviewLoaded,true);assert.equal(global.__mirrorMotionFoundationStatus.cameraActivationLoaded,true);clear();});

test('canonical foundation status overrides stale legacy phase number as build truth',()=>{clear();healthyPhases();healthyClosures();const status={mirrorMotionPhase:3,mappedBoneCount:1};global.__avatarRuntimeStatus=status;global.AvatarRuntime={boneRestPose:{hips:{}},getStatus:()=>status};const p=fresh();p.evaluate();assert.equal(status.mirrorMotionPhase,3);assert.equal(status.mirrorMotionFoundationStatus,'READY');assert.equal(status.mirrorMotionFoundationRange,'2-18');assert.equal(status.mirrorMotionFoundationStagesLoaded,17);assert.equal(status.mirrorMotionClosureStatus,'HEALTHY');assert.equal(status.mirrorMotionLegacyPhaseDiagnostic,true);assert.match(p.diagnosticsText(),/Legacy mirrorMotionPhase: diagnostic only/);clear();});

test('Phase 12 loads the final acceptance diagnostics after Phase 18 and before camera closure modules',()=>{const fs=require('node:fs'),path=require('node:path');const src=fs.readFileSync(path.join(__dirname,'../public/mirror-motion-phase12.js'),'utf8');const p18=src.indexOf('/mirror-motion-phase18.js'),accept=src.indexOf('/mirror-motion-acceptance.js'),review=src.indexOf('/mirror-motion-camera-review.js'),activation=src.indexOf('/mirror-motion-camera-activation.js');assert.ok(p18>=0&&accept>p18&&review>accept&&activation>review);assert.match(src,/MIRROR_MOTION_ACCEPTANCE_LOAD_FAILED/);assert.match(src,/MIRROR_MOTION_CAMERA_REVIEW_LOAD_FAILED/);assert.match(src,/MIRROR_MOTION_CAMERA_ACTIVATION_LOAD_FAILED/);});