'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const phase9=require('../public/mirror-motion-phase9.js');
const p=(name,x,y,c=.95,extra={})=>({name,x,y,confidence:c,score:c,...extra});
function packet(state='FRONT',scale=1,cameraScale=1){return{orientationIntent:{state,confidence:.95,measuredDepth:false},keypoints:[p('left_shoulder',20*cameraScale,20*cameraScale),p('left_elbow',(20+40*scale)*cameraScale,20*cameraScale),p('left_wrist',(20+70*scale)*cameraScale,20*cameraScale),p('right_shoulder',80*cameraScale,20*cameraScale),p('right_elbow',(80-40*scale)*cameraScale,20*cameraScale),p('right_wrist',(80-70*scale)*cameraScale,20*cameraScale),p('left_hip',30*cameraScale,70*cameraScale),p('left_knee',30*cameraScale,(70+40*scale)*cameraScale),p('left_ankle',30*cameraScale,(70+75*scale)*cameraScale),p('right_hip',70*cameraScale,70*cameraScale),p('right_knee',70*cameraScale,(70+40*scale)*cameraScale),p('right_ankle',70*cameraScale,(70+75*scale)*cameraScale)]};}
function calibrate(e,count=5){for(let i=0;i<count;i++)e.process(packet('FRONT',1));}
test('requires multiple trusted FRONT samples before a segment baseline gains authority',()=>{const e=phase9.createForeshorteningEngine({minCalibrationSamples:3,frontLearnAlpha:1});e.process(packet('FRONT',1));assert.equal(e.diagnostics().baselineSegments,0);e.process(packet('FRONT',1));assert.equal(e.diagnostics().baselineSegments,0);e.process(packet('FRONT',1));assert.ok(e.diagnostics().baselineSegments>=8);});
test('guards suspicious SIDE foreshortening instead of fabricating depth',()=>{const e=phase9.createForeshorteningEngine({minCalibrationSamples:1,frontLearnAlpha:1,sideCollapseRatio:.4});calibrate(e,1);const out=e.process(packet('SIDE',.25));assert.equal(out.foreshortening.measuredDepth,false);assert.ok(out.foreshortening.guardedSegments.length>0);assert.ok(out.keypoints.some(x=>x.foreshorteningState==='guarded'&&x.confidence===0));});
test('camera distance scaling alone does not look like limb collapse',()=>{const e=phase9.createForeshorteningEngine({minCalibrationSamples:1,frontLearnAlpha:1,sideCollapseRatio:.4});calibrate(e,1);const out=e.process(packet('SIDE',1,.55));assert.equal(out.foreshortening.guardedSegments.length,0);});
test('SIDE threshold tolerates more natural projected shortening than QUARTER threshold',()=>{assert.ok(phase9.DEFAULTS.sideCollapseRatio<phase9.DEFAULTS.quarterCollapseRatio);});
test('coasted joints cannot calibrate or trigger foreshortening authority',()=>{const e=phase9.createForeshorteningEngine({minCalibrationSamples:1});const q=packet('FRONT',1);q.keypoints.find(x=>x.name==='left_elbow').stabilityState='coasted';e.process(q);assert.equal(e.diagnostics().baseline.left_upper_arm,undefined);});
test('untrusted orientation cannot create foreshortening authority',()=>{const e=phase9.createForeshorteningEngine({minCalibrationSamples:1,frontLearnAlpha:1});calibrate(e,1);const q=packet('SIDE',.2);q.orientationIntent.confidence=.2;const out=e.process(q);assert.equal(out.foreshortening.guardedSegments.length,0);});
test('diagnostics expose no measured-depth authority',()=>{assert.match(phase9.diagnosticsText(),/Measured depth authority: NO/);});