'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
function fresh(){const p=require.resolve('../public/mirror-motion-camera-activation');delete require.cache[p];return require(p);}

test('trusted scene motion subtracts accumulated camera offset from absolute lateral intent',()=>{const p=fresh();const e=p.createActivationEngine();let out=e.process({timestamp:1,lateralIntent:{ready:true,cameraSpaceNormalized:.20,measuredDepth:false},cameraMotionIntent:{source:'scene',ambiguous:false,detected:true,confidence:.9,globalDxNormalized:.10,measuredDepth:false}});assert.equal(out.lateralIntent.rawCameraSpaceNormalized,.20);assert.equal(out.lateralIntent.cameraSpaceNormalized,.10);assert.equal(out.lateralIntent.cameraOffsetNormalized,.10);});

test('pose-only ambiguity never suppresses deliberate subject motion',()=>{const p=fresh();const e=p.createActivationEngine();const out=e.process({timestamp:1,lateralIntent:{ready:true,cameraSpaceNormalized:.20,measuredDepth:false},cameraMotionIntent:{source:'pose_coherence',ambiguous:true,detected:false,confidence:.4,globalDxNormalized:.20,measuredDepth:false}});assert.equal(out.lateralIntent.cameraSpaceNormalized,.20);assert.equal(out.lateralIntent.cameraOffsetNormalized,0);});

test('previously observed trusted camera offset remains applied when later evidence is unavailable',()=>{const p=fresh();const e=p.createActivationEngine();e.process({timestamp:1,lateralIntent:{ready:true,cameraSpaceNormalized:.10,measuredDepth:false},cameraMotionIntent:{source:'scene',ambiguous:false,detected:true,confidence:.9,globalDxNormalized:.10,measuredDepth:false}});const out=e.process({timestamp:2,lateralIntent:{ready:true,cameraSpaceNormalized:.25,measuredDepth:false},cameraMotionIntent:{source:'unavailable',ambiguous:true,detected:false,confidence:0,globalDxNormalized:0,measuredDepth:false}});assert.equal(out.lateralIntent.cameraSpaceNormalized,.15);});

test('low-confidence or non-detected scene evidence cannot change camera offset',()=>{const p=fresh();const e=p.createActivationEngine();const out=e.process({timestamp:1,lateralIntent:{ready:true,cameraSpaceNormalized:.18,measuredDepth:false},cameraMotionIntent:{source:'scene',ambiguous:false,detected:true,confidence:.4,globalDxNormalized:.12,measuredDepth:false}});assert.equal(out.lateralIntent.cameraSpaceNormalized,.18);assert.equal(out.lateralIntent.cameraOffsetNormalized,0);});

test('the same trusted scene delta is accumulated at most once per source frame',()=>{const p=fresh();const e=p.createActivationEngine();const packet={timestamp:100,lateralIntent:{ready:true,cameraSpaceNormalized:.30,measuredDepth:false},cameraMotionIntent:{source:'scene',ambiguous:false,detected:true,confidence:.9,globalDxNormalized:.10,measuredDepth:false}};let out=e.process(packet);assert.equal(out.lateralIntent.cameraOffsetNormalized,.10);out=e.process(packet);assert.equal(out.lateralIntent.cameraOffsetNormalized,.10);assert.equal(e.diagnostics().corrections,1);assert.equal(e.diagnostics().duplicateSceneFrames,1);assert.equal(e.diagnostics().lastIssue,'DUPLICATE_SCENE_DELTA_IGNORED');});

test('trusted scene evidence without source-frame identity cannot mutate camera offset',()=>{const p=fresh();const e=p.createActivationEngine();const out=e.process({lateralIntent:{ready:true,cameraSpaceNormalized:.2,measuredDepth:false},cameraMotionIntent:{source:'scene',ambiguous:false,detected:true,confidence:.9,globalDxNormalized:.1,measuredDepth:false}});assert.equal(out.lateralIntent.cameraOffsetNormalized,0);assert.equal(out.lateralIntent.cameraSpaceNormalized,.2);assert.equal(e.diagnostics().lastIssue,'SCENE_FRAME_ID_UNAVAILABLE');});

test('reset clears accumulated camera offset and consumed frame identity',()=>{const p=fresh();const e=p.createActivationEngine();e.process({timestamp:1,lateralIntent:{ready:true,cameraSpaceNormalized:.2,measuredDepth:false},cameraMotionIntent:{source:'scene',ambiguous:false,detected:true,confidence:.9,globalDxNormalized:.1,measuredDepth:false}});e.reset('TRACKER');const out=e.process({timestamp:1,lateralIntent:{ready:true,cameraSpaceNormalized:.2,measuredDepth:false},cameraMotionIntent:{source:'scene',ambiguous:false,detected:true,confidence:.9,globalDxNormalized:.1,measuredDepth:false}});assert.equal(out.lateralIntent.cameraSpaceNormalized,.1);assert.equal(out.lateralIntent.cameraOffsetNormalized,.1);});

test('activation diagnostics preserve no root and no measured-depth authority',()=>{const p=fresh();const d=p.diagnostics();assert.equal(d.avatarRootAuthority,false);assert.equal(d.measuredDepthAuthority,false);});

test('Phase 12 loads camera activation after camera review',()=>{const fs=require('node:fs'),path=require('node:path');const src=fs.readFileSync(path.join(__dirname,'../public/mirror-motion-phase12.js'),'utf8');const review=src.indexOf('/mirror-motion-camera-review.js'),activation=src.indexOf('/mirror-motion-camera-activation.js');assert.ok(review>=0&&activation>review);assert.match(src,/MIRROR_MOTION_CAMERA_ACTIVATION_LOAD_FAILED/);});