'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const phase11=require('../public/mirror-motion-phase11.js');
const p=(name,x,y,c=.95,extra={})=>({name,x,y,confidence:c,score:c,...extra});
function packet({facing='SIDE',leftKneeX=48,rightKneeX=52,leftKneeC=.95,rightKneeC=.55,leftExtra={},rightExtra={}}={}){return{orientationIntent:{state:facing,confidence:.95,measuredDepth:false},keypoints:[p('left_shoulder',40,20),p('right_shoulder',60,20),p('left_hip',45,70),p('right_hip',55,70),p('left_elbow',48,40,.95),p('right_elbow',52,40,.6),p('left_wrist',48,55,.95),p('right_wrist',52,55,.6),p('left_knee',leftKneeX,105,leftKneeC,leftExtra),p('right_knee',rightKneeX,105,rightKneeC,rightExtra),p('left_ankle',48,140,.95),p('right_ankle',52,140,.6)]};}
test('requires consecutive overlap evidence before suppressing the weaker paired joint',()=>{const e=phase11.createOcclusionEngine({enterFrames:2,overlapRatio:.2,confidenceMargin:.2});let out=e.process(packet());assert.equal(out.occlusion.suppressedPairs.length,0);out=e.process(packet());assert.ok(out.occlusion.suppressedPairs.some(x=>x==='knee:right'));assert.equal(out.keypoints.find(x=>x.name==='right_knee').confidence,0);});
test('ambiguous confidence does not create new near/far authority',()=>{const e=phase11.createOcclusionEngine({enterFrames:1,confidenceMargin:.2});const out=e.process(packet({leftKneeC:.8,rightKneeC:.72}));assert.equal(out.occlusion.suppressedPairs.length,0);});
test('active authority releases after bounded ambiguous overlap instead of suppressing forever',()=>{const e=phase11.createOcclusionEngine({enterFrames:1,confidenceMargin:.2,maxAmbiguousHoldFrames:1});e.process(packet());let out=e.process(packet({leftKneeC:.8,rightKneeC:.72}));assert.ok(out.occlusion.suppressedPairs.some(x=>x==='knee:right'));out=e.process(packet({leftKneeC:.8,rightKneeC:.72}));assert.equal(out.occlusion.suppressedPairs.some(x=>x==='knee:right'),false);assert.equal(e.diagnostics().ambiguityReleases>0,true);});
test('authority can switch sides after consecutive opposite evidence',()=>{const e=phase11.createOcclusionEngine({enterFrames:1,switchFrames:2,confidenceMargin:.2});let out=e.process(packet({leftKneeC:.95,rightKneeC:.55}));assert.ok(out.occlusion.suppressedPairs.includes('knee:right'));out=e.process(packet({leftKneeC:.55,rightKneeC:.95}));assert.equal(out.occlusion.suppressedPairs.includes('knee:left'),false);assert.equal(out.occlusion.suppressedPairs.includes('knee:right'),false);out=e.process(packet({leftKneeC:.55,rightKneeC:.95}));assert.ok(out.occlusion.suppressedPairs.includes('knee:left'));assert.equal(e.diagnostics().authoritySwitches,1);});
test('active hold persists through separation release hysteresis before clearing',()=>{const e=phase11.createOcclusionEngine({enterFrames:1,releaseFrames:2,overlapRatio:.2,confidenceMargin:.2});e.process(packet());let out=e.process(packet({rightKneeX:80}));assert.ok(out.occlusion.suppressedPairs.some(x=>x==='knee:right'));out=e.process(packet({rightKneeX:80}));assert.equal(out.occlusion.suppressedPairs.some(x=>x==='knee:right'),false);});
test('IK-solved or planted upstream joints are never suppressed',()=>{const e=phase11.createOcclusionEngine({enterFrames:1,confidenceMargin:.2});let out=e.process(packet({rightExtra:{ikState:'solved'}}));assert.equal(out.occlusion.suppressedPairs.some(x=>x==='knee:right'),false);out=e.process(packet({rightExtra:{exerciseConstraintState:'contact_anchor_right_knee'}}));assert.equal(out.occlusion.suppressedPairs.some(x=>x==='knee:right'),false);});
test('FRONT and untrusted orientation clear transient overlap authority',()=>{const e=phase11.createOcclusionEngine({enterFrames:1});e.process(packet());assert.ok(e.diagnostics().activePairs>0);e.process(packet({facing:'FRONT'}));assert.equal(e.diagnostics().activePairs,0);});
test('diagnostics expose authority switches ambiguity releases and no measured-depth authority',()=>{const text=phase11.diagnosticsText();assert.match(text,/Authority switches:/);assert.match(text,/Ambiguity releases:/);assert.match(text,/Measured depth authority: NO/);});
