'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
function fresh(){const p=require.resolve('../public/mirror-motion-phase18');delete require.cache[p];return require(p);}

test('Phase 18 does not assist stable endpoints',()=>{const p=fresh();const solver={rootRestPosition:{y:0},rootTargetPosition:{y:-.2}};assert.equal(p.applyToSolver(solver,{active:true,phase:'PLANK_STABLE',direction:'DOWN',progress01:1,confidence:.95,livePoseAuthority:true,measuredDepth:false}),true);assert.equal(solver.rootTargetPosition.y,-.2);});

test('Phase 18 rejects low-confidence, measured-depth, and missing live-pose authority',()=>{const p=fresh();const a={rootRestPosition:{y:0},rootTargetPosition:{y:-.05}};p.applyToSolver(a,{active:true,phase:'CROUCH',direction:'DOWN',progress01:.6,confidence:.2,livePoseAuthority:true,measuredDepth:false});assert.equal(a.rootTargetPosition.y,-.05);const b={rootRestPosition:{y:0},rootTargetPosition:{y:-.05}};p.applyToSolver(b,{active:true,phase:'CROUCH',direction:'DOWN',progress01:.6,confidence:.95,livePoseAuthority:true,measuredDepth:true});assert.equal(b.rootTargetPosition.y,-.05);const c={rootRestPosition:{y:0},rootTargetPosition:{y:-.05}};p.applyToSolver(c,{active:true,phase:'CROUCH',direction:'DOWN',progress01:.6,confidence:.95,measuredDepth:false});assert.equal(c.rootTargetPosition.y,-.05);});

test('Phase 18 applies bounded downward assistance during descent',()=>{const p=fresh();const solver={rootRestPosition:{y:0},rootTargetPosition:{y:-.05}};p.applyToSolver(solver,{active:true,phase:'CROUCH',direction:'DOWN',progress01:.7,confidence:.95,livePoseAuthority:true,measuredDepth:false});assert.ok(solver.rootTargetPosition.y<-.05);assert.ok(Math.abs(solver.floorTransitionAssistAppliedY)<=p.DEFAULTS.maxAssistY+1e-12);});

test('Phase 18 never exceeds max assist even when guide is far away',()=>{const p=fresh();const solver={rootRestPosition:{y:0},rootTargetPosition:{y:.3}};p.applyToSolver(solver,{active:true,phase:'HANDS_DOWN',direction:'DOWN',progress01:1,confidence:.99,livePoseAuthority:true,measuredDepth:false});assert.equal(Math.abs(solver.floorTransitionAssistAppliedY),p.DEFAULTS.maxAssistY);});

test('Phase 18 never pushes downward while direction is UP',()=>{const p=fresh();const solver={rootRestPosition:{y:0},rootTargetPosition:{y:-.10}};p.applyToSolver(solver,{active:true,phase:'HANDS_DOWN',direction:'UP',progress01:.75,confidence:.95,livePoseAuthority:true,measuredDepth:false});assert.equal(solver.rootTargetPosition.y,-.10);assert.equal(solver.floorTransitionAssistAppliedY,0);assert.equal(p.diagnostics().lastIssue,'LIVE_POSE_ALREADY_AT_OR_ABOVE_GUIDE');});

test('Phase 18 may assist upward only when the live root is still below the UP guide',()=>{const p=fresh();const solver={rootRestPosition:{y:0},rootTargetPosition:{y:-.30}};p.applyToSolver(solver,{active:true,phase:'HANDS_DOWN',direction:'UP',progress01:.75,confidence:.95,livePoseAuthority:true,measuredDepth:false});assert.ok(solver.rootTargetPosition.y>-.30);assert.ok(solver.floorTransitionAssistAppliedY>0);});

test('Phase 18 clears stale solver assist metadata on bypass',()=>{const p=fresh();const solver={rootRestPosition:{y:0},rootTargetPosition:{y:-.05},floorTransitionAssistAppliedY:-.08,floorTransitionGuideY:-.2};p.applyToSolver(solver,{active:false,phase:'STANDING',direction:'NONE',progress01:0,confidence:.95,livePoseAuthority:true,measuredDepth:false});assert.equal(solver.floorTransitionAssistAppliedY,0);assert.equal(solver.floorTransitionGuideY,null);});

test('Phase 18 diagnostics preserve live pose authority and no measured depth',()=>{const p=fresh();const d=p.diagnostics();assert.equal(d.livePoseAuthority,true);assert.equal(d.measuredDepthAuthority,false);assert.equal(d.avatarRootAuthority,true);assert.match(p.diagnosticsText(),/bounded transition assist only/);});