"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const assets=require("../public/motion/phase-e-assets"),loader=require("../public/motion/shared3d-loader");
const avatars=require("../public/motion/avatar-profiles");

test("manifest is the single stable optional asset contract",()=>{assert.equal(assets.paths.avatar,"/motion/assets/phase-e/canonical-avatar.glb");assert.equal(assets.paths.animation,"/motion/assets/phase-e/animation-fixture.glb");assert.equal(assets.manifest.canonicalAvatar.requires.animations,0);assert.equal(assets.manifest.animationFixture.requires.mesh,false);assert.equal(assets.manifest.licenseStatus,"development-test-only");});

test("development avatar registry preserves the reference while adding one isolated candidate",()=>{assert.equal(avatars.profiles.reference.assetUrl,assets.paths.avatar);assert.equal(avatars.profiles.reference.status,"reference-fallback");assert.equal(avatars.profiles.personalized.assetUrl,"/dev/motion-lab-avatar-assets/avaturn-push-up-source.glb");assert.equal(avatars.profiles.personalized.developmentOnly,true);assert.equal(avatars.get("avaturn-personalized-candidate"),avatars.profiles.personalized);assert.equal(avatars.get("unknown"),null);});

test("Three node-name normalization removes the canonical colon at runtime",()=>{const {PropertyBinding}=require(path.resolve(__dirname,"../node_modules/three/build/three.cjs"));assert.equal(PropertyBinding.sanitizeNodeName("mixamorig:Hips"),"mixamorigHips");assert.equal(PropertyBinding.sanitizeNodeName("Left Arm"),"Left_Arm");const browserBuild=fs.readFileSync(path.resolve(__dirname,"../public/vendor/three/build/three.module.js"),"utf8");assert.match(browserBuild,/Characters \[\]\.:\/ are reserved/);assert.match(browserBuild,/replace\( _reservedRe, '' \)/);});

test("personalized source GLB retains meshes, skin, materials, textures, and native animation",()=>{const file=path.resolve(__dirname,"../exercise-generation/source-assets/avaturn/avaturn-push-up-source.glb"),data=fs.readFileSync(file),jsonLength=data.readUInt32LE(12),gltf=JSON.parse(data.toString("utf8",20,20+jsonLength).trim()),animation=gltf.animations[0],targets=animation.channels.map(channel=>channel.target.path),skeletalChannels=animation.channels.filter(channel=>channel.target.path!=="weights");assert.equal(data.toString("ascii",0,4),"glTF");assert.equal(gltf.asset.generator,"Avaturn.me | Blender");assert.equal(gltf.nodes.length,65);assert.equal(gltf.meshes.length,10);assert.equal(gltf.skins.length,1);assert.equal(gltf.skins[0].joints.length,54);assert.equal(gltf.materials.length,10);assert.ok(gltf.textures.length>0);assert.ok(gltf.images.length>0);assert.equal(gltf.animations.length,1);assert.equal(animation.name,"avaturn_animation");assert.equal(animation.channels.length,46);assert.equal(skeletalChannels.length,40);assert.equal(new Set(skeletalChannels.map(channel=>channel.target.node)).size,39);assert.equal(targets.filter(value=>value==="weights").length,6);});

test("the 195-track failure is exactly the canonical Phase E fixture, not the Avaturn source",()=>{function animation(relative){const data=fs.readFileSync(path.resolve(__dirname,"..",relative)),jsonLength=data.readUInt32LE(12),gltf=JSON.parse(data.toString("utf8",20,20+jsonLength).trim());return gltf.animations[0];}const phaseE=animation("public/motion/assets/phase-e/animation-fixture.glb"),native=animation("exercise-generation/source-assets/avaturn/avaturn-push-up-source.glb");assert.equal(phaseE.name,"Armature|mixamo.com|Layer0");assert.equal(phaseE.channels.length,195);assert.equal(native.name,"avaturn_animation");assert.equal(native.channels.length,46);});

test("GLTF loader uses the local vendored module and normalizes failures",async()=>{let url;class GLTFLoader{};assert.equal(await loader.loadGLTFLoader({importModule:async value=>(url=value,{GLTFLoader})}),GLTFLoader);assert.equal(url,"/vendor/three/examples/jsm/loaders/GLTFLoader.js");await assert.rejects(loader.loadGLTFLoader({importModule:async()=>{throw new Error("no")}}),error=>error.code==="gltf_loader_failed");});

test("browser GLTF module graph resolves one vendored Three module without bare specifiers",()=>{const root=path.resolve(__dirname,"../public"),entry="/vendor/three/examples/jsm/loaders/GLTFLoader.js",threeUrl=loader.THREE_MODULE_URL,visited=new Set();function inspect(url){if(visited.has(url))return;visited.add(url);const filename=path.join(root,url.slice(1)),source=fs.readFileSync(filename,"utf8"),specifiers=[...source.matchAll(/(?:import|export)\s+(?:[\s\S]*?\s+from\s+)?["']([^"']+)["']/g)].map(match=>match[1]);for(const specifier of specifiers){assert.match(specifier,/^(?:\.|\/)/,`${url} has browser-unresolvable bare import ${specifier}`);if(specifier===threeUrl)continue;const resolved=specifier.startsWith("/")?specifier:path.posix.resolve(path.posix.dirname(url),specifier);if(resolved.startsWith("/vendor/three/examples/jsm/"))inspect(resolved);}}inspect(entry);assert.deepEqual([...visited].sort(),[entry,"/vendor/three/examples/jsm/utils/BufferGeometryUtils.js"].sort());for(const url of visited){const source=fs.readFileSync(path.join(root,url.slice(1)),"utf8");for(const match of source.matchAll(/from\s+["'](\/vendor\/three\/build\/three\.module\.js)["']/g))assert.equal(match[1],threeUrl);}});

test("published binaries remain core/member dependency isolated",()=>{const root=path.resolve(__dirname,"..");for(const binary of ["canonical-avatar.glb","animation-fixture.glb"])assert.equal(fs.existsSync(path.join(root,"public/motion/assets/phase-e",binary)),true);for(const relative of ["public/app-runtime.js","public/boot-core.js","public/auth-core.js","public/dashboard-runtime.js","public/workout-runtime.js","public/exercise-library.js"]){const source=fs.readFileSync(path.join(root,relative),"utf8");assert.doesNotMatch(source,/phase-e-assets|avatar-profiles|avaturn-push-up-source|canonical-avatar\.glb|animation-fixture\.glb|GLTFLoader|AnimationMixer/,relative);}});

test("conversion and validation contracts prohibit duplicate fixture meshes",()=>{const converter=fs.readFileSync(path.resolve(__dirname,"../scripts/motion/convert-phase-e.py"),"utf8"),validator=fs.readFileSync(path.resolve(__dirname,"../scripts/motion/validate-phase-e-glb.js"),"utf8");assert.match(converter,/obj\.type not in \{'ARMATURE','EMPTY'\}/);assert.match(validator,/animation fixture must not duplicate mesh/);assert.match(validator,/canonical avatar must contain no clips/);});
