"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),os=require("node:os");
const {createApp}=require("../server"),{createAuthTokenLib}=require("../src/lib/authToken");
async function server(t,env,options={}){const prior={...process.env};Object.assign(process.env,env);const app=createApp({dataDir:fs.mkdtempSync(path.join(os.tmpdir(),"motion-lab-")),...options}),s=app.listen(0);await new Promise(r=>s.once("listening",r));t.after(()=>{s.close();for(const k of Object.keys(process.env))if(!(k in prior))delete process.env[k];Object.assign(process.env,prior);});return`http://127.0.0.1:${s.address().port}`;}
const bearer=token=>({authorization:`Bearer ${token}`});
test("Motion Lab flag fails closed with 404",async t=>{const base=await server(t,{ENABLE_MOTION_LAB:"false",NODE_ENV:"production",POCKET_PT_DATA_DIR:fs.mkdtempSync(path.join(os.tmpdir(),"pt-data-"))});assert.equal((await fetch(base+"/api/dev/motion-lab/session",{method:"POST"})).status,404);assert.equal((await fetch(base+"/dev/motion-lab")).status,404);assert.equal((await fetch(base+"/dev/motion-lab-runtime.js")).status,404);});
test("launch bridge rejects anonymous and ordinary members",async t=>{const base=await server(t,{ENABLE_MOTION_LAB:"true",NODE_ENV:"test",AUTHZ_BOOTSTRAP_SUPER_ADMIN_USER_IDS:"lab_admin"}),auth=createAuthTokenLib({secret:process.env.AUTH_TOKEN_SECRET||"dev-only-secret-change-me"}),member=auth.issueUserToken({userId:"member"}).token;assert.equal((await fetch(base+"/api/dev/motion-lab/session",{method:"POST"})).status,401);assert.equal((await fetch(base+"/api/dev/motion-lab/session",{method:"POST",headers:bearer(member)})).status,403);});
test("authorized launch creates an opaque, short-lived session for the complete module graph",async t=>{const base=await server(t,{ENABLE_MOTION_LAB:"true",NODE_ENV:"test",AUTHZ_BOOTSTRAP_SUPER_ADMIN_USER_IDS:"lab_admin"}),auth=createAuthTokenLib({secret:process.env.AUTH_TOKEN_SECRET||"dev-only-secret-change-me"}),admin=auth.issueUserToken({userId:"lab_admin"}).token;const launch=await fetch(base+"/api/dev/motion-lab/session",{method:"POST",headers:bearer(admin)}),body=await launch.json(),setCookie=launch.headers.get("set-cookie"),cookie=setCookie.split(";")[0];assert.equal(launch.status,201);assert.equal(body.data.navigateTo,"/dev/motion-lab");assert.match(setCookie,/HttpOnly/i);assert.match(setCookie,/SameSite=Lax/i);assert.match(setCookie,/Path=\//i);assert.doesNotMatch(setCookie,new RegExp(admin.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(JSON.stringify(body),/Bearer|token/i);assert.equal(launch.headers.get("location"),null);for(const route of ["/dev/motion-lab","/dev/motion-lab.css","/dev/motion-lab-bootstrap.js","/dev/motion-lab-runtime.js","/dev/motion-lab-assets/phase-e-assets.js","/dev/motion-lab-assets/avatar-profiles.js","/dev/motion-lab-assets/push-up-motion-spec.js","/dev/motion-lab-assets/motion-spec-clip.js","/vendor/three/build/three.module.js","/vendor/three/examples/jsm/loaders/GLTFLoader.js","/vendor/three/examples/jsm/utils/BufferGeometryUtils.js","/motion/assets/phase-e/canonical-avatar.glb","/dev/motion-lab-avatar-assets/avaturn-push-up-source.glb"]){const response=await fetch(base+route,{headers:{cookie}});assert.equal(response.status,200,route);if(route.endsWith(".js"))assert.match(response.headers.get("content-type")||"",/javascript/,route);await response.arrayBuffer();}assert.equal((await fetch(base+"/dev/motion-lab-assets/push-up-motion-spec.js")).status,401);assert.equal((await fetch(base+"/motion/assets/phase-e/canonical-avatar.glb")).status,401);assert.equal((await fetch(base+"/dev/motion-lab-avatar-assets/avaturn-push-up-source.glb")).status,401);});
test("expired and invalid Motion Lab sessions are rejected",async t=>{const base=await server(t,{ENABLE_MOTION_LAB:"true",NODE_ENV:"test",AUTHZ_BOOTSTRAP_SUPER_ADMIN_USER_IDS:"lab_admin"},{motionLabSessionTtlMs:10}),auth=createAuthTokenLib({secret:process.env.AUTH_TOKEN_SECRET||"dev-only-secret-change-me"}),admin=auth.issueUserToken({userId:"lab_admin"}).token,launch=await fetch(base+"/api/dev/motion-lab/session",{method:"POST",headers:bearer(admin)}),cookie=launch.headers.get("set-cookie").split(";")[0];assert.equal((await fetch(base+"/dev/motion-lab",{headers:{cookie:"PocketPTMotionLabSession=invalid-session-value-that-is-long-enough"}})).status,401);await new Promise(resolve=>setTimeout(resolve,20));assert.equal((await fetch(base+"/dev/motion-lab",{headers:{cookie}})).status,401);});
test("logout revokes issued Motion Lab sessions",async t=>{const base=await server(t,{ENABLE_MOTION_LAB:"true",NODE_ENV:"test",AUTHZ_BOOTSTRAP_SUPER_ADMIN_USER_IDS:"lab_admin"}),auth=createAuthTokenLib({secret:process.env.AUTH_TOKEN_SECRET||"dev-only-secret-change-me"}),admin=auth.issueUserToken({userId:"lab_admin"}).token,launch=await fetch(base+"/api/dev/motion-lab/session",{method:"POST",headers:bearer(admin)}),cookie=launch.headers.get("set-cookie").split(";")[0];await fetch(base+"/api/auth/logout",{method:"POST",headers:{...bearer(admin),cookie}});assert.equal((await fetch(base+"/dev/motion-lab",{headers:{cookie}})).status,401);});
test("admin dashboard launches Motion Lab with canonical authenticated POST without changing member navigation",()=>{const html=fs.readFileSync(path.join(__dirname,"../public/dashboard.html"),"utf8"),js=fs.readFileSync(path.join(__dirname,"../public/dashboard.js"),"utf8");assert.match(html,/id="motionLabNav"[^>]+href="\/dev\/motion-lab"[^>]+hidden>Motion Lab<\/a>/);assert.match(js,/fetch\(backendUrl\("\/api\/dev\/motion-lab\/session"\)/);assert.match(js,/Authorization: `Bearer \$\{token\}`/);assert.match(js,/credentials: "include"/);assert.match(js,/window\.location\.assign\(backendUrl\(body\.data\.navigateTo\)\)/);assert.equal((html.match(/href="\/dev\/motion-lab"/g)||[]).length,1);assert.match(html,/href="\/dashboard\.html">Home<\/a>/);});
test("static shell does not load Three or create a renderer",()=>{const html=fs.readFileSync(path.join(__dirname,"../motion-lab/index.html"),"utf8");assert.match(html,/Initialize Runtime/);assert.doesNotMatch(html,/three\.module|disposable-motion-session|WebGLRenderer/);assert.match(html,/Avatar|Skeleton|Animation|Anatomy|Muscle Metadata/i);});
test("lab is one-way isolated and has controlled failures only",()=>{const core=["public/index.html","public/dashboard.js","public/exercise-library.js"].map(f=>fs.readFileSync(path.join(__dirname,"..",f),"utf8")).join("\n");assert.doesNotMatch(core,/MotionLabRuntime|motion-lab-bootstrap|motion-lab-runtime|phase-e-assets/);const runtime=fs.readFileSync(path.join(__dirname,"../motion-lab/motion-lab-runtime.js"),"utf8");for(const hook of ["dependency","webgl","renderer_init","runtime","context_loss","timeout","abort"])assert.match(runtime,new RegExp(hook));assert.doesNotMatch(runtime,/FBXLoader|Ch18|Silly Dancing/i);assert.match(runtime,/loadAvatar/);assert.match(runtime,/loadAnimation/);});
test("diagnostic contract has bounded safe statuses",()=>{const lab=require("../motion-lab/motion-lab-runtime");assert.deepEqual(Object.keys(lab.STATUS),["not_run","running","pass","fail","unavailable","aborted"]);assert.deepEqual(lab.result("avatar_asset","fail",4,"Bearer secret"),{stage:"avatar_asset",status:"fail",elapsedMs:4,code:"Bearer [redacted]"});});
