"use strict";
const test = require("node:test"), assert = require("node:assert/strict"), fs = require("node:fs"), os = require("node:os"), path = require("node:path");
const { parseGlb, encodeGlb } = require("../scripts/motion/glb-utils");
const { loadManifest, validateManifest, MANIFEST } = require("../scripts/motion/lib/motion-manifest");
const { build, validate, inventory, checkRegistry } = require("../scripts/motion/lib/motion-fixture");
const legacyExtractor = require("../scripts/motion/extract-avaturn-push-up"), legacyValidator = require("../scripts/motion/validate-avaturn-push-up");
const fixture = path.resolve("public/motion/assets/exercises/push-up/avaturn-push-up-animation.glb");
const expectedSha = "046034dd86350c4962ede767c2483e6c68d87b8115ccda5a9e26d4483615205f";
function clone(value) { return JSON.parse(JSON.stringify(value)); }
function temporaryManifest(edit) { const value = clone(loadManifest(MANIFEST).manifest); edit(value); const dir = fs.mkdtempSync(path.join(os.tmpdir(), "motion-manifest-")), file = path.join(dir, "manifest.json"); fs.writeFileSync(file, JSON.stringify(value)); return file; }

test("manifest contract and JSON schema describe all build stages", () => { const { manifest } = loadManifest(MANIFEST); assert.equal(validateManifest(manifest), manifest); const schema = JSON.parse(fs.readFileSync("schemas/motion/motion-source-manifest.schema.json")); assert.equal(schema.$schema, "https://json-schema.org/draft/2020-12/schema"); assert.ok(schema.required.includes("structuralExpectations")); });
test("generic builder produces the approved fixture byte-for-byte without touching production", () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), "motion-build-")), output = path.join(dir, "fixture.glb"), before = fs.readFileSync(fixture); const result = build(MANIFEST, { outputPath: output, writeProvenance: false }); assert.equal(result.sha256, expectedSha); assert.equal(result.bytes, 52232); assert.deepEqual(fs.readFileSync(output), before); assert.deepEqual(fs.readFileSync(fixture), before); });
test("generic builder rejects an invalid immutable source hash", () => { const file = temporaryManifest(m => { m.source.sha256 = "0".repeat(64); }); assert.throws(() => build(file, { outputPath: path.join(os.tmpdir(), "never.glb"), writeProvenance: false }), /source SHA-256/); });
test("generic builder rejects a missing declared animation", () => { const file = temporaryManifest(m => { m.animationSelection.sourceClipName = "missing"; }); assert.throws(() => build(file, { outputPath: path.join(os.tmpdir(), "never.glb"), writeProvenance: false }), /missing declared source animation/); });
test("skeletal channel filtering removes weights and retains target ancestors", () => { const result = inventory(fixture), parsed = parseGlb(fixture).json; assert.equal(result.morphTracks, 0); assert.equal(result.tracks, 40); assert.equal(result.nodes, 40); const children = new Set(parsed.nodes.flatMap(n => n.children || [])); assert.ok(parsed.scenes[0].nodes.some(index => !children.has(index))); });
test("generic validator passes fixture and registry cross-check", () => { const result = validate(MANIFEST, fixture); assert.equal(result.sha256, expectedSha); assert.equal(result.size, 52232); assert.equal(result.clip, "avaturn_push_up_native_v1"); assert.equal(result.duration, 1.5333333015441895); assert.doesNotThrow(() => checkRegistry(loadManifest(MANIFEST).manifest)); });
test("validator rejects wrong hash and structurally altered content", () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), "motion-invalid-")), cases = [{ label: "wrong clip", edit: j => { j.animations[0].name = "wrong"; } }, { label: "wrong duration", edit: j => { j.accessors[j.animations[0].samplers[0].input].max = [9]; } }, { label: "wrong track count", edit: j => { j.animations[0].channels.pop(); } }, { label: "unexpected mesh", edit: j => { j.meshes = [{}]; } }, { label: "unexpected morph track", edit: j => { j.animations[0].channels[0].target.path = "weights"; } }]; for (const item of cases) { const parsed = parseGlb(fs.readFileSync(fixture)), file = path.join(dir, item.label.replaceAll(" ", "-") + ".glb"); item.edit(parsed.json); fs.writeFileSync(file, encodeGlb(parsed.json, parsed.binary)); assert.throws(() => validate(MANIFEST, file), /output SHA-256/, item.label); } });
test("registry disagreement fails closed", () => { const manifest = loadManifest(MANIFEST).manifest, records = { fixtures: JSON.parse(fs.readFileSync("public/motion/registry/fixtures.json")), motions: JSON.parse(fs.readFileSync("public/motion/registry/motions.json")), avatars: JSON.parse(fs.readFileSync("public/motion/registry/avatar-profiles.json")), skeletons: JSON.parse(fs.readFileSync("public/motion/registry/skeleton-profiles.json")) }; records.fixtures.records[0].motionId = "wrong"; assert.throws(() => checkRegistry(manifest, records), /registry motion relationship/); });
for (const [policy, value, message] of [["rootMotionPolicy", "remove", "unsupported root"], ["clipPolicy", "trim", "unsupported clip"], ["reductionPolicy", "keyframe", "unsupported reduction"], ["compressionPolicy", "meshopt", "unsupported compression"]]) test(`${message} policy fails closed`, () => { const file = temporaryManifest(m => { m[policy].mode = value; }); assert.throws(() => loadManifest(file), new RegExp(message)); });
test("legacy extractor and validator remain generic compatibility wrappers", () => { const before = fs.readFileSync(fixture), result = legacyExtractor.extract(); assert.deepEqual(result, { bytes: 52232, sha256: expectedSha }); assert.deepEqual(fs.readFileSync(fixture), before); assert.equal(legacyValidator.validate().sha256, expectedSha); });
