"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),os=require("node:os");
const {createApp}=require("../server"),{createAuthTokenLib}=require("../src/lib/authToken");
async function server(t,env){const prior={...process.env};Object.assign(process.env,env);const app=createApp({dataDir:fs.mkdtempSync(path.join(os.tmpdir(),"motion-lab-"))}),s=app.listen(0);await new Promise(r=>s.once("listening",r));t.after(()=>{s.close();for(const k of Object.keys(process.env))if(!(k in prior))delete process.env[k];Object.assign(process.env,prior);});return`http://127.0.0.1:${s.address().port}`;}
test("Motion Lab flag fails closed with 404",async t=>{const base=await server(t,{ENABLE_MOTION_LAB:"false",NODE_ENV:"production",POCKET_PT_DATA_DIR:fs.mkdtempSync(path.join(os.tmpdir(),"pt-data-"))});assert.equal((await fetch(base+"/dev/motion-lab")).status,404);assert.equal((await fetch(base+"/dev/motion-lab-runtime.js")).status,404);});
test("enabled lab requires admin and gates its complete module graph",async t=>{const base=await server(t,{ENABLE_MOTION_LAB:"true",NODE_ENV:"test",AUTHZ_BOOTSTRAP_SUPER_ADMIN_USER_IDS:"lab_admin"}),auth=createAuthTokenLib({secret:process.env.AUTH_TOKEN_SECRET||"dev-only-secret-change-me"}),member=auth.issueUserToken({userId:"member"}).token,admin=auth.issueUserToken({userId:"lab_admin"}).token;assert.equal((await fetch(base+"/dev/motion-lab")).status,401);assert.equal((await fetch(base+"/dev/motion-lab",{headers:{authorization:`Bearer ${member}`}})).status,403);for(const file of ["motion-lab","motion-lab.css","motion-lab-bootstrap.js","motion-lab-runtime.js"]){const r=await fetch(base+"/dev/"+file,{headers:{authorization:`Bearer ${admin}`}});assert.equal(r.status,200,file);}});
test("admin dashboard exposes Motion Lab only through its existing observability capability",()=>{const html=fs.readFileSync(path.join(__dirname,"../public/dashboard.html"),"utf8"),js=fs.readFileSync(path.join(__dirname,"../public/dashboard.js"),"utf8");assert.match(html,/id="motionLabNav"[^>]+href="\/dev\/motion-lab"[^>]+hidden>Motion Lab<\/a>/);assert.match(js,/const hasObservabilityAccess = roles\.some\(\(role\) => role === "admin" \|\| role === "super_admin"\)/);assert.match(js,/motionLabNav\.hidden = !hasObservabilityAccess/);assert.match(js,/if \(motionLabNav\) motionLabNav\.hidden = true/);assert.equal((html.match(/href="\/dev\/motion-lab"/g)||[]).length,1);});
test("static shell does not load Three or create a renderer",()=>{const html=fs.readFileSync(path.join(__dirname,"../motion-lab/index.html"),"utf8");assert.match(html,/Initialize Runtime/);assert.doesNotMatch(html,/three\.module|disposable-motion-session|WebGLRenderer/);assert.match(html,/Avatar|Skeleton|Animation|Anatomy|Muscle Metadata/i);});
test("lab is one-way isolated and has controlled failures only",()=>{const core=["public/index.html","public/dashboard.js","public/exercise-library.js"].map(f=>fs.readFileSync(path.join(__dirname,"..",f),"utf8")).join("\n");assert.doesNotMatch(core,/MotionLabRuntime|motion-lab-bootstrap|motion-lab-runtime|phase-e-assets/);const runtime=fs.readFileSync(path.join(__dirname,"../motion-lab/motion-lab-runtime.js"),"utf8");for(const hook of ["dependency","webgl","renderer_init","runtime","context_loss","timeout","abort"])assert.match(runtime,new RegExp(hook));assert.doesNotMatch(runtime,/FBXLoader|Ch18|Silly Dancing/i);assert.match(runtime,/loadAvatar/);assert.match(runtime,/loadAnimation/);});
test("diagnostic contract has bounded safe statuses",()=>{const lab=require("../motion-lab/motion-lab-runtime");assert.deepEqual(Object.keys(lab.STATUS),["not_run","running","pass","fail","unavailable","aborted"]);assert.deepEqual(lab.result("avatar_asset","fail",4,"Bearer secret"),{stage:"avatar_asset",status:"fail",elapsedMs:4,code:"Bearer [redacted]"});});
