"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const {createOverpassTrailProvider,createNearbyTrailService,parseEndpoints,coarseKey,buildQuery}=require("../src/services/nearbyTrailService");
const input={latitude:1.001,longitude:2.001,radiusMeters:8046.72,limit:3};
const response=(status=200,body={elements:[{type:"node",id:1,lat:1,lon:2,tags:{name:"A",highway:"trailhead"}}]},type="application/json")=>new Response(typeof body==="string"?body:JSON.stringify(body),{status,headers:{"content-type":type}});
test("fallback endpoint succeeds after retryable statuses and failures",async()=>{for(const first of [429,502,503,504,"connection"]){let calls=0;const fetchImpl=async()=>{calls++;if(calls===1){if(first==="connection")throw new TypeError("fetch failed");return response(first,{})}return response()};const p=createOverpassTrailProvider({fetchImpl,endpoints:["https://a.example/api/interpreter","https://b.example/api/interpreter"]});assert.equal((await p.searchNearbyTrails(input)).length,1);assert.ok(calls>=2&&calls<=3);}});
test("bad provider bodies are rejected without retry",async()=>{for(const r of [response(200,"nope"),response(200,"<html>bad</html>","text/html"),response(200,"x".repeat(2000))]){const p=createOverpassTrailProvider({fetchImpl:async()=>r,endpoints:["https://a.example/api/interpreter"],maxResponseBytes:1000});await assert.rejects(p.searchNearbyTrails(input),e=>e.code==="TRAIL_PROVIDER_BAD_RESPONSE");}});
test("timeout aborts provider request",async()=>{let aborted=false;const p=createOverpassTrailProvider({fetchImpl:(_u,o)=>new Promise((_r,reject)=>o.signal.addEventListener("abort",()=>{aborted=true;reject(Object.assign(new Error(),{name:"AbortError"}));})),endpoints:["https://a.example/api/interpreter"],timeoutMs:20,connectTimeoutMs:10});await assert.rejects(p.searchNearbyTrails(input),e=>e.code==="TRAIL_PROVIDER_TIMEOUT");assert.equal(aborted,true);});
test("configuration and query are constrained",()=>{assert.throws(()=>parseEndpoints({OVERPASS_API_URL:"http://bad/api/interpreter"},{useDefaults:false}),e=>e.code==="TRAIL_PROVIDER_CONFIGURATION_ERROR");assert.deepEqual(parseEndpoints({},{useDefaults:false}),[]);assert.match(buildQuery(input),/out center tags 25/);assert.doesNotMatch(buildQuery(input),/out geom/);});
test("cache is coarse, identity-free, and provides stale fallback",async()=>{let now=0,calls=0;const service=createNearbyTrailService({provider:{searchNearbyTrails:async()=>{calls++;if(calls>1)throw Object.assign(new Error(),{code:"TRAIL_PROVIDER_UNAVAILABLE"});return[{id:"a"}]}},ttlMs:10,maxEntries:2,now:()=>now});await service.search("user-secret",input);const hit=await service.search("other",{...input,latitude:1.002});assert.equal(hit.cached,true);assert.equal(calls,1);assert.doesNotMatch(JSON.stringify([...service._cache]),/user-secret|1\.001/);now=11;const stale=await service.search("other",input);assert.equal(stale.stale,true);assert.equal(coarseKey(input),coarseKey({...input,latitude:1.002}));});
test("invalid input never reaches provider",async()=>{let calls=0;const service=createNearbyTrailService({provider:{searchNearbyTrails:async()=>calls++}});await assert.rejects(service.search("u",{...input,latitude:100}),e=>e.code==="TRAIL_SEARCH_INVALID_INPUT");assert.equal(calls,0);});

test("500 is unavailable and is not retried",async()=>{let calls=0;const p=createOverpassTrailProvider({fetchImpl:async()=>{calls++;return response(500,{})},endpoints:["https://a.example/api/interpreter","https://b.example/api/interpreter"]});await assert.rejects(p.searchNearbyTrails(input),e=>e.code==="TRAIL_PROVIDER_UNAVAILABLE");assert.equal(calls,1);});
