"use strict";
const test = require("node:test"), assert = require("node:assert/strict"), fs = require("node:fs"), os = require("node:os"), path = require("node:path");
const { createNotificationService } = require("../src/notifications/notificationService");
function service() { const dir = fs.mkdtempSync(path.join(os.tmpdir(), "notifications-")); return createNotificationService({ filePath: path.join(dir, "items.json"), clock: () => new Date("2026-07-31T12:00:00Z"), maxPerMember: 2 }); }
test("authoritative event creates one durable, safe notification and suppresses duplicates", () => { const svc = service(), event = { eventId: "evt_1", eventType: "workout.completed", subjectUserId: "member-a" }; assert.equal(svc.ingestEvents([event])[0].status, "created"); assert.equal(svc.ingestEvents([event])[0].status, "duplicate"); assert.equal(svc.unreadCount("member-a"), 1); assert.equal(svc.list("member-a", {}).notifications[0].actionRoute, "/dashboard.html"); assert.deepEqual(svc._events().map(x => x.operation), ["created"]); assert.equal(svc.health().appendOnlyAudit, true); });
test("read, read-all, dismiss, isolation, pagination and bounded history", () => { const svc = service(); for (let i = 0; i < 3; i++) svc.create({ memberId: "member-a", type: "workout.completed", sourceEventId: `evt_${i}` }); svc.create({ memberId: "member-b", type: "workout.completed", sourceEventId: "evt_b" }); assert.equal(svc.list("member-a", { limit: 1 }).hasMore, true); assert.equal(svc.list("member-a", {}).notifications.length, 2); assert.equal(svc.list("member-b", {}).notifications.length, 1); const id = svc.list("member-a", {}).notifications[0].notificationId; svc.markRead("member-a", id); assert.equal(svc.unreadCount("member-a"), 1); assert.equal(svc.readAll("member-a").updated, 1); svc.dismiss("member-a", id); assert.equal(svc.list("member-a", {}).notifications.length, 1); assert.equal(svc.markRead("member-b", id), null); });

test("achievement and badge facts create separate award-linked durable history", () => { const svc=service(), facts=[{memberId:"member-a",type:"achievement.awarded",sourceEventId:"evt_award",sourceAwardId:"awd_1"},{memberId:"member-a",type:"badge.awarded",sourceEventId:"evt_award",sourceAwardId:"awd_1"}]; assert.deepEqual(svc.ingestFacts(facts).map(x=>x.status),["created","created"]); assert.deepEqual(svc.list("member-a",{}).notifications.map(x=>x.type).sort(),["ACHIEVEMENT_AWARDED","BADGE_AWARDED"]); });
test("dashboard notification UI exposes bell, live unread count, owner actions, and safe rendering",()=>{const html=fs.readFileSync(path.join(__dirname,"../public/dashboard.html"),"utf8"),js=fs.readFileSync(path.join(__dirname,"../public/notifications.js"),"utf8");assert.match(html,/id="notificationExperience"[^>]+aria-label="Notifications"/);assert.match(js,/aria-expanded="false"/);assert.match(js,/aria-live="polite"/);assert.match(js,/Mark read/);assert.match(js,/textContent = item\.body/);assert.match(js,/safeRoute\(item\.actionRoute\)/);});
