"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { createApp } = require("../server");
const { createAuthTokenLib } = require("../src/lib/authToken");
const contract = require("../config/route-authorization-contract");
const sinks = require("../config/intentional-html-sinks");
const { safeUrl, setText } = require("../public/safe-rendering");
const SECRET = "phase12b-authorization-secret-32-chars";
function makeRoot() { const root = fs.mkdtempSync(path.join(os.tmpdir(), "phase12b-")); fs.mkdirSync(path.join(root,"public","exercise-db"),{recursive:true}); fs.writeFileSync(path.join(root,"public","exercise-db","index.json"),"[]"); return root; }
async function start(t, extra={}) { const previous={}; const env={AUTH_TOKEN_SECRET:SECRET,NODE_ENV:"test",AUTH_TOKEN_CLOCK_SKEW_MS:"0",...extra}; for(const[k,v] of Object.entries(env)){previous[k]=process.env[k];process.env[k]=v;} t.after(()=>{for(const[k,v]of Object.entries(previous))v==null?delete process.env[k]:process.env[k]=v;}); const app=createApp({rootDir:makeRoot(),fetch:async()=>new Response("RAW_PROVIDER_SECRET",{status:503})}); const server=app.listen(0); await new Promise(r=>server.once("listening",r)); t.after(()=>server.close()); return `http://127.0.0.1:${server.address().port}`; }
function auth(userId="matrix_owner", opts={}) { return createAuthTokenLib({secret:SECRET,clockSkewMs:0}).issueUserToken({userId,providerVerified:true,...opts}); }
function concrete(route){return route.replace(/:executionId|:entryId|:mealId|:planId|:itemId|:missionId|:id|:slug|:barcode|:fdcId/g,"unknown-resource");}
async function call(base, entry, token, body={}) { const headers={}; if(token)headers.authorization=`Bearer ${token}`; if(entry.method!=="GET")headers["content-type"]="application/json"; return fetch(base+concrete(entry.path),{method:entry.method,headers,body:entry.method==="GET"?undefined:JSON.stringify(body),redirect:"manual"}); }

test("complete route contract rejects anonymous, malformed, and expired credentials", async t=>{ const base=await start(t); const required=contract.filter(x=>x.authentication==="required"); assert.ok(required.length>80); const expired=auth("expired",{ttlMs:1}).token; await new Promise(r=>setTimeout(r,5)); for(const route of required){ for(const [scenario,credential] of [["anonymous",null],["malformed","not.a.valid-token"],["expired",expired]]){const response=await call(base,route,credential); assert.equal(response.status,401,`${scenario}: ${route.method} ${route.path} returned ${response.status}`);} } });

test("owner, role, permission, membership, feature, resource, and server identity matrix",async t=>{const base=await start(t,{MEMBERSHIP_GATE_TEST_ENFORCED:"true",ENABLE_AVATAR_FEATURE:"false"}),owner=auth().token; for(const route of contract.filter(x=>x.authentication==="required")){const response=await call(base,route,owner);assert.notEqual(response.status,401,`owner credential rejected by ${route.method} ${route.path}`);} for(const route of contract.filter(x=>x.requiredPermissions.length||x.ownership==="privileged")){assert.equal((await call(base,route,owner)).status,403,`missing permission/wrong role: ${route.path}`);} for(const route of contract.filter(x=>x.membership==="required")){assert.equal((await call(base,route,owner)).status,402,`missing membership: ${route.path}`);} for(const route of contract.filter(x=>x.featureFlag)){assert.ok([404,503].includes((await call(base,route,owner)).status),`disabled feature: ${route.path}`);} const cross=await fetch(base+"/api/programs",{method:"POST",headers:{authorization:`Bearer ${owner}`,"content-type":"application/json"},body:JSON.stringify({clientId:"different-user",goal:"strength",durationWeeks:4,daysPerWeek:3})});assert.equal(cross.status,403); const spoof=await fetch(base+"/api/challenges/pushup/results",{method:"POST",headers:{authorization:`Bearer ${owner}`,"content-type":"application/json"},body:JSON.stringify({userId:"different-user",submissionId:"server-identity-1",displayName:"Athlete",consent:true,variant:"standard_pushup",validRepCount:3})});assert.equal(spoof.status,201);const duplicate=await fetch(base+"/api/challenges/pushup/results",{method:"POST",headers:{authorization:`Bearer ${owner}`,"content-type":"application/json"},body:JSON.stringify({userId:"another-user",submissionId:"server-identity-1",displayName:"Athlete",consent:true,variant:"standard_pushup",validRepCount:3})});assert.equal(duplicate.status,409);});

test("revoked credential is rejected black-box",async t=>{const base=await start(t,{AUTHZ_ADMIN_USER_IDS:"matrix_admin"});const admin=auth("matrix_admin"),revoked=auth("revoked_member");const revoke=await fetch(base+"/api/ops/auth/token-revocations",{method:"POST",headers:{authorization:`Bearer ${admin.token}`,"content-type":"application/json"},body:JSON.stringify({jti:revoked.jti,expiresAt:revoked.expiresAt,reason:"assurance-test"})});assert.equal(revoke.status,201);assert.equal((await fetch(base+"/api/me",{headers:{authorization:`Bearer ${revoked.token}`}})).status,401);});

test("captured logs exclude personal, credential, provider, and body values across security operations",async t=>{const secretValues=["Sensitive Person","private@example.test","INJURY_PRIVATE_雪","waist=91cm","private notes","Bearer_PRIVATE_TOKEN","cookie_private","provider-secret-value","RAW_PROVIDER_SECRET"];const captured=[];const original={};for(const level of ["log","info","warn","error"]){original[level]=console[level];console[level]=(...args)=>captured.push(args.map(x=>typeof x==="string"?x:JSON.stringify(x)).join(" "));}t.after(()=>Object.assign(console,original));const base=await start(t,{SKILL_WORLD_TTS_TOKEN:"provider-secret-value",AIVOICE_URL:"http://127.0.0.1:1"}),token=auth().token;const requests=[
["PUT","/api/me/profile",{name:secretValues[0],email:secretValues[1],notes:secretValues[4],heightCm:181,weightKg:82}],
["PUT","/api/me/profile",{name:secretValues[2]}],["PATCH","/api/me/retention/intake",{notes:secretValues[4],injuries:[secretValues[2]]}],["POST","/api/me/retention/intake/submit",{notes:secretValues[4]}],["POST","/api/ohsa",{summary:{injury:secretValues[2],measurements:secretValues[3]}}],["POST","/api/me/nutrition/entries",{foodName:secretValues[0],notes:secretValues[4]}],["POST","/api/me/generated-workout-executions",{sessionId:secretValues[4]}],["POST","/api/me/generated-workout-executions/unknown/complete",{notes:secretValues[4]}],["POST","/api/challenges/pushup/results",{displayName:secretValues[0],email:secretValues[1],consent:true,variant:"standard_pushup",validRepCount:3}],["POST","/api/speak",{text:secretValues[2]}]];
for(const [method,url,body] of requests)await fetch(base+url,{method,headers:{authorization:`Bearer ${token}`,cookie:`session=${secretValues[6]}`,"content-type":"application/json"},body:JSON.stringify(body)});await fetch(base+"/api/me",{headers:{authorization:"Bearer_PRIVATE_TOKEN"}});const output=captured.join("\n");for(const value of secretValues)assert.equal(output.includes(value),false,`log leaked ${value}`);});

test("browser-safe rendering neutralizes active markup, schemes, Unicode controls, and prototype keys",()=>{const attacks=["<script>alert(1)</script>","<img src=x onerror=alert(1)>","<svg onload=alert(1)>","&lt;script&gt;","‮<script>","__proto__","constructor","prototype"];for(const attack of attacks){const node={textContent:""};setText(node,attack);assert.equal(node.textContent,attack);}for(const url of ["javascript:alert(1)"," java\nscript:alert(1)","java\u0000script:alert(1)","data:text/html,<svg onload=1>","\u0000JaVaScRiPt:1"])assert.throws(()=>safeUrl(url),/Unsafe URL/);assert.throws(()=>safeUrl("data:image/svg+xml,<svg onload=1>",{allowDataImage:true}),/Unsafe URL/);assert.equal(safeUrl("data:image/png;base64,iVBORw0KGgo=",{allowDataImage:true}),"data:image/png;base64,iVBORw0KGgo=");for(const review of Object.values(sinks))assert.match(review.safety,/encode|esc\(|constant|createElement|Clears|fixed/i);});
