"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {createApp}=require("../server");const {createAuthTokenLib}=require("../src/lib/authToken");const contract=require("../config/route-authorization-contract");const sinks=require("../config/intentional-html-sinks");const {safeUrl,setText}=require("../public/safe-rendering");
const SECRET="phase12a-test-secret-at-least-32-characters";
function token(userId="phase12-member"){return createAuthTokenLib({secret:SECRET}).issueUserToken({userId,providerVerified:true}).token}
async function server(t,env={}){const old={};for(const[k,v]of Object.entries({AUTH_TOKEN_SECRET:SECRET,...env})){old[k]=process.env[k];process.env[k]=String(v)}t.after(()=>{for(const[k,v]of Object.entries(old))v==null?delete process.env[k]:process.env[k]=v});const root=fs.mkdtempSync(path.join(os.tmpdir(),"phase12a-"));fs.mkdirSync(path.join(root,"public","exercise-db"),{recursive:true});fs.writeFileSync(path.join(root,"public","exercise-db","index.json"),"[]");const s=createApp({rootDir:root}).listen(0);await new Promise(r=>s.once("listening",r));t.after(()=>s.close());return `http://127.0.0.1:${s.address().port}`}
async function post(base,route,body,auth){const r=await fetch(base+route,{method:"POST",headers:{"content-type":"application/json",...(auth?{authorization:`Bearer ${auth}`}:{})},body:JSON.stringify(body)});return{r,j:await r.json().catch(()=>({}))}}
test("route authorization contract exactly inventories declarations and has complete policies",()=>{const source=fs.readFileSync(path.join(__dirname,"..","server.js"),"utf8"),actual=[];for(const m of source.matchAll(/app\.(get|post|put|patch|delete)\(\s*["'`]([^"'`]+)["'`]/g))actual.push(`${m[1].toUpperCase()} ${m[2]}`);const declared=contract.map(x=>`${x.method} ${x.path}`);assert.deepEqual([...new Set(declared)].sort(),[...new Set(actual)].sort());for(const x of contract){assert.ok(x.publicOutput);if(x.authentication==="required")assert.ok(x.ownership||x.requiredPermissions.length);if(x.method!=="GET"&&x.authentication==="public")assert.ok(x.publicWrite)}});
test("dangerous HTML sinks are inventoried and safe rendering rejects active URLs",()=>{const files=fs.readdirSync(path.join(__dirname,"..","public")).filter(x=>/\.(js|html)$/.test(x));for(const file of files){const source=fs.readFileSync(path.join(__dirname,"..","public",file),"utf8");if(/\.(?:innerHTML|outerHTML)\s*=|insertAdjacentHTML\s*\(|document\.write\s*\(/.test(source))assert.ok(sinks[`public/${file}`],`unallowlisted sink: ${file}`)}const node={textContent:""};setText(node,'<img src=x onerror=alert(1)> & "雪"');assert.equal(node.textContent,'<img src=x onerror=alert(1)> & "雪"');for(const value of ["javascript:alert(1)"," JaVaScRiPt:alert(1)","data:text/html,<script>x</script>"])assert.throws(()=>safeUrl(value),/Unsafe URL/);assert.equal(safeUrl("https://example.test/a?q=%26"),"https://example.test/a?q=%26")});
test("critical write routes reject anonymous requests and telemetry rejects arbitrary payloads",async t=>{const base=await server(t);for(const [route,body]of [["/command",{domain:"fitness",command:"fitness.endSession",userId:"victim",payload:{}}],["/api/speak",{text:"private words"}],["/api/challenges/pushup/results",{displayName:"A",consent:true,submissionId:"submission-1"}],["/api/pilot/events",{event:"workout_started",payload:{}}]])assert.equal((await post(base,route,body)).r.status,401);const auth=token();assert.equal((await post(base,"/api/pilot/events",{event:"not_allowed",payload:{}},auth)).r.status,400);assert.equal((await post(base,"/api/pilot/events",{event:"workout_started",payload:{userId:"victim"}},auth)).r.status,400);assert.equal((await post(base,"/api/pilot/events",{event:"workout_started",payload:{label:"ok"}},auth)).r.status,202)});
test("speech limiter preserves ordinary use, emits stable 429 and Retry-After without logging text",async t=>{const logs=[],old=console.info;console.info=(...x)=>logs.push(JSON.stringify(x));t.after(()=>console.info=old);const base=await server(t,{TTS_RATE_LIMIT:1,SKILL_WORLD_TTS_TOKEN:"configured",AIVOICE_URL:"http://127.0.0.1:1"});const auth=token(),secret="OHSA-INJURY-PRIVATE-雪";await post(base,"/api/speak",{text:secret},auth);const limited=await post(base,"/api/speak",{text:secret},auth);assert.equal(limited.r.status,429);assert.ok(limited.r.headers.get("retry-after"));assert.equal(JSON.stringify(logs).includes(secret),false)});
