"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("fs"),os=require("os"),path=require("path");
const {generateProgram,prescribe,substitute,createProgramPersistence,createProgramService}=require("../src/program-engine");
const {createUserStore}=require("../src/repositories/userStore");
function harness(now=Date.parse("2026-08-03T12:00:00Z")){const store=createUserStore({userDir:fs.mkdtempSync(path.join(os.tmpdir(),"program-engine-"))}),persistence=createProgramPersistence({userStore:store}),service=createProgramService({persistence,clock:()=>now});return{store,service};}
test("generation is deterministic, versioned, periodized, and schedules unified recovery",()=>{const input={goal:"strength",experienceLevel:"intermediate",trainingDays:3,durationWeeks:8,equipment:["dumbbell"],startDate:"2026-08-03"},a=generateProgram(input),b=generateProgram(input);assert.deepEqual(a,b);assert.equal(a.schemaVersion,1);assert.deepEqual(a.mesocycles.map(x=>x.phase),["foundation","realization"]);assert.deepEqual(a.microcycles.filter(w=>w.deload).map(w=>w.week),[4,8]);assert.ok(a.microcycles.flatMap(w=>w.sessions).some(s=>s.type==="yoga"));assert.ok(a.microcycles.flatMap(w=>w.sessions).some(s=>s.type==="rest"));});
test("constraints deterministically select compatible exercises",()=>{const p=generateProgram({goal:"general_fitness",experienceLevel:"beginner",trainingDays:2,durationWeeks:4,equipment:[],availableDays:[1,4],startDate:"2026-08-03"});const exercises=p.microcycles[0].sessions.find(s=>s.type==="workout").exercises;assert.ok(exercises.every(x=>x.equipment==="bodyweight"));assert.equal(p.weeklySchedule.trainingDays,2);});
test("progress is earned from authoritative history and deload overrides it",()=>{const base={id:"squat",sets:3,reps:8,intensity:6};assert.equal(prescribe(base,{week:3,deload:false},[]).progression,"preserved");assert.equal(prescribe(base,{week:3,deload:false},[{exerciseId:"squat",status:"completed",completionPercent:100,completedAt:1}]).progression,"earned");assert.equal(prescribe(base,{week:4,deload:true},[]).progression,"scheduled_deload");});
test("substitution preserves movement intent and respects equipment",()=>{const result=substitute({id:"back_squat",equipment:"barbell",difficulty:3,movementPattern:"squat",trainingIntent:"primary",muscleEmphasis:"squat"},{equipment:["dumbbell"],reason:"travel"});assert.equal(result.id,"goblet_squat");assert.equal(result.substitution.reason,"travel");assert.ok(result.substitution.preserved.includes("movement_pattern"));});
test("service persists minimal authoritative state and derives member-isolated views",()=>{const {store,service}=harness(),view=service.assign("member-a",{goal:"mobility",trainingDays:3,durationWeeks:4,startDate:"2026-08-03"});assert.equal(view.available,true);assert.equal(view.today.type,"workout");const updated=service.updateSession("member-a",view.today.sessionId,{status:"completed"});assert.equal(updated.analytics.completedSessions,1);assert.equal(service.view("member-b").available,false);const saved=store.loadUser("member-a").programAssignment;assert.equal(saved.userId,"member-a");assert.equal(saved.analytics,undefined);});
