"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const contract=require("../public/motion/push-up-motion-spec");

test("push-up Motion Spec is valid, ordered, normalized, canonical, and explicitly development-only",()=>{const {spec}=contract,check=contract.validate(spec);assert.deepEqual(check,{valid:true,errors:[]});assert.equal(spec.status,"development-test-only");assert.deepEqual(spec.phaseOrder,["start","descent","bottom","ascent","finish"]);assert.deepEqual(spec.phases.map(p=>p.normalizedTime),[0,.25,.5,.75,1]);assert.equal(spec.authoringBoundary.recognitionValuesUsedAsAnimationRotations,false);for(const phase of spec.phases)for(const target of phase.boneTargets)assert.ok(contract.CANONICAL_BONES.includes(target.bone));});

test("Motion Spec validation rejects bad ordering, time, and unknown bones",()=>{const clone=JSON.parse(JSON.stringify(contract.spec));clone.phases[1].normalizedTime=2;clone.phases[2].boneTargets[0].bone="unknown:Bone";clone.phaseOrder[0]="finish";const check=contract.validate(clone);assert.equal(check.valid,false);assert.match(check.errors.join("\n"),/phaseOrder/);assert.match(check.errors.join("\n"),/normalized time/);assert.match(check.errors.join("\n"),/unknown bone/);});

test("push-up motion remains protected Motion Lab-only and absent from member-facing/core paths",()=>{const root=path.join(__dirname,".."),core=["public/index.html","public/workout.html","public/dashboard.js","public/exercise-library.js","public/avatar-runtime.js"].map(file=>fs.readFileSync(path.join(root,file),"utf8")).join("\n");assert.doesNotMatch(core,/push-up-motion-spec|PocketPTPushUpMotionSpec|push_up_engineering_reference_v1/);const bootstrap=fs.readFileSync(path.join(root,"motion-lab/motion-lab-bootstrap.js"),"utf8"),lab=fs.readFileSync(path.join(root,"motion-lab/index.html"),"utf8");assert.match(bootstrap,/\/dev\/motion-lab-assets\/push-up-motion-spec\.js/);assert.match(lab,/Load Push-Up Motion/);});
