'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../public/push-up-challenge'),metadata=require('../public/exercise-metadata');
const ROOT=path.join(__dirname,'..'),profile=C.getPushUpProfile(metadata),rule=profile.poseAnalysis.rules[0];
const memory=()=>{const data=new Map();return{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)}};
const kp=(hipY=50,score=.9)=>['shoulder','hip','ankle'].flatMap((name,i)=>['left','right'].map(side=>({name:`${side}_${name}`,x:10+i*40,y:name==='hip'?hipY:50,score:side==='left'?score:.1})));
const version=()=>C.sessionVersionMetadata(profile);
function validSession(overrides={}){const frames=[0,1,2].map(i=>({timestamp:1000+i*100,side:'left',landmarks:{shoulder:{x:.1,y:.5,confidence:.9},hip:{x:.5,y:.5,confidence:.9},ankle:{x:.9,y:.5,confidence:.9}},frameConfidence:.9,usable:true}));return{schemaVersion:1,sessionId:'s',userId:'local-user',mode:'challenge',versionMetadata:version(),sessionStartedAt:new Date(0).toISOString(),sessionEndedAt:new Date(1000).toISOString(),requiredViewEstablished:true,normalizedLandmarkFrames:frames,repetitionEvents:[{index:1,timestamp:1200,type:'repetition_completed',complete:true}],supportedAlignmentFindings:[],summary:{valid:true,validRepetitions:1,completionTimeMs:1000},invalidationReason:null,...overrides};}

test('dedicated static route and dashboard navigation are present',()=>{const server=fs.readFileSync(path.join(ROOT,'server.js'),'utf8'),dashboard=fs.readFileSync(path.join(ROOT,'public/dashboard.html'),'utf8'),page=fs.readFileSync(path.join(ROOT,'public/push-up-challenge.html'),'utf8');assert.match(server,/app\.use\(express\.static\(PUBLIC_DIR/);assert.match(dashboard,/id="pushUpChallengeLink"[^>]+href="\/push-up-challenge\.html"/);assert.match(page,/Practice[\s\S]+Challenge[\s\S]+Me vs\. Me/)});
test('Practice and Challenge mode state transitions are reusable',()=>{const recorder=new C.PerformanceRecorder({profile}),engine=new C.ExerciseSessionEngine({profile,recorder,repetitions:new C.RepetitionEventEngine()});assert.equal(engine.state,'idle');engine.start('practice',{requiredViewEstablished:true});assert.equal(engine.state,'active');engine.finish();assert.equal(engine.state,'summary');engine.reset();engine.start('challenge',{requiredViewEstablished:true});assert.equal(engine.mode,'challenge')});
test('landmarks normalize to frame dimensions and select confident side',()=>{const result=C.normalizeLandmarks(kp(),100,100);assert.equal(result.side,'left');assert.deepEqual(result.landmarks.hip,{x:.5,y:.5,confidence:.9});assert.throws(()=>C.normalizeLandmarks(kp(),0,100))});
test('session serialization contains complete version metadata',()=>{const recorder=new C.PerformanceRecorder({profile,userId:'u'});recorder.start({mode:'challenge',requiredViewEstablished:true});const parsed=JSON.parse(recorder.serialize());assert.equal(parsed.userId,'u');assert.deepEqual(parsed.versionMetadata,version());for(const key of ['exerciseId','canonicalProfileFingerprint','profileVersion','generatorVersion','capabilityRegistryVersion','thresholdVersion','poseModel','poseModelVersion'])assert.ok(parsed.versionMetadata[key]!==undefined)});
test('valid and invalid sessions classify against authoritative gates',()=>{assert.equal(C.classifySession(validSession(),profile).valid,true);for(const [change,reason] of [[{requiredViewEstablished:false},'required_side_view_not_established'],[{normalizedLandmarkFrames:[]},'overall_confidence_below_threshold'],[{versionMetadata:{...version(),thresholdVersion:'wrong'}},'exercise_version_incompatible'],[{repetitionEvents:[]},'repetition_data_incomplete']])assert.ok(C.classifySession(validSession(change),profile).invalidationReasons.includes(reason))});
test('personal best uses repetitions then completion time and excludes invalid sessions',()=>{const store=new C.PersonalBestStore(memory());store.save(validSession({sessionId:'a',summary:{valid:true,validRepetitions:4,completionTimeMs:9000}}));store.save(validSession({sessionId:'b',summary:{valid:true,validRepetitions:5,completionTimeMs:12000}}));store.save(validSession({sessionId:'c',summary:{valid:false,validRepetitions:20,completionTimeMs:1}}));assert.equal(store.best().sessionId,'b')});
test('Me vs. Me requires valid version-compatible sessions',()=>{const engine=new C.ComparisonEngine(),a=validSession(),b=validSession({sessionId:'b'});assert.equal(engine.compatible(a,b).compatible,true);b.versionMetadata={...b.versionMetadata,canonicalProfileFingerprint:'other'};assert.match(engine.compatible(a,b).reason,/canonicalProfileFingerprint/);assert.equal(engine.compatible({...a,summary:{...a.summary,valid:false}},validSession()).compatible,false)});
test('ghost replay timing selects timeline frames without video',()=>{const ghost=new C.GhostRenderer(null),session=validSession();assert.equal(ghost.frameAt(session,0).timestamp,1000);assert.equal(ghost.frameAt(session,190).timestamp,1200);assert.equal(ghost.frameAt(session,205).timestamp,1000)});
test('session persistence contains no raw video by default',()=>{const json=JSON.stringify(validSession());for(const forbidden of ['rawVideo','videoBlob','videoData','mediaStream'])assert.doesNotMatch(json,new RegExp(forbidden,'i'))});
test('Push-Up thresholds remain unchanged and unsupported assessment is not introduced',()=>{assert.deepEqual({requiredView:profile.poseAnalysis.requiredView,landmarks:rule.landmarks,measurement:rule.measurement,maximumDeviationDegrees:rule.thresholds.maximumDeviationDegrees,minimumLandmarkConfidence:rule.minimumLandmarkConfidence,minimumAffectedFramePercentage:rule.minimumAffectedFramePercentage,minimumConsecutiveDurationMs:rule.minimumConsecutiveDurationMs,minimumUsableFramePercentage:profile.poseAnalysis.minimumUsableFramePercentage,minimumOverallConfidence:profile.poseAnalysis.minimumOverallConfidence},{requiredView:'side',landmarks:['shoulder','hip','ankle'],measurement:'alignment_deviation',maximumDeviationDegrees:18,minimumLandmarkConfidence:.75,minimumAffectedFramePercentage:35,minimumConsecutiveDurationMs:500,minimumUsableFramePercentage:60,minimumOverallConfidence:.75});const source=fs.readFileSync(path.join(ROOT,'public/push-up-challenge.js'),'utf8');for(const forbidden of ['elbow-angle','elbow-flare','wrist-position','wrist-comfort','depth assessment','pain assessment','scapular','neck-position','head-position','three-dimensional alignment'])assert.doesNotMatch(source,new RegExp(forbidden,'i'))});
test('challenge consumes runtime-authoritative profile rather than copied constants',()=>{assert.equal(profile,metadata.getDefaultRegistry().resolve('push_up'));assert.equal(version().canonicalProfileFingerprint,profile.metadataFingerprint);assert.match(fs.readFileSync(path.join(ROOT,'public/push-up-challenge-page.js'),'utf8'),/getPushUpProfile\(\)/)});

test('challenge scripts initialize runtime state before the deferred pose stack',()=>{const html=fs.readFileSync(path.join(ROOT,'public/push-up-challenge.html'),'utf8');const runtimePosition=html.indexOf('src="/runtime-state.js"'),initPosition=html.indexOf('RuntimeState?.initHeadRuntime?.()'),diagnosticPosition=html.indexOf('console.log("__ensurePoseRuntime =", window.__ensurePoseRuntime)'),deferredScripts=['pose-runtime.js','exercise-metadata.js','challenge-controller.js','push-up-challenge.js','push-up-challenge-page.js'],deferredPositions=deferredScripts.map(name=>html.indexOf(`defer src="/${name}"`));assert.ok(runtimePosition>=0);assert.ok(initPosition>runtimePosition);assert.ok(diagnosticPosition>initPosition);assert.ok(deferredPositions.every(position=>position>diagnosticPosition));assert.deepEqual([...deferredPositions].sort((a,b)=>a-b),deferredPositions);assert.doesNotMatch(html,/@tensorflow\/tfjs|@tensorflow-models\/pose-detection/);assert.match(html,/id="practiceBtn" disabled/);assert.match(html,/id="challengeBtn"[^>]+disabled/)});

test('PoseCaptureEngine reuses a bootstrapped detector rather than creating a second stack',async()=>{const detector={estimatePoses:async()=>[]};let created=0,received;const runtime={initMoveNetDetector:async()=>{created++;return{}},startPoseLoop:options=>{received=options.detector;return{stop(){}}}};const capture=new C.PoseCaptureEngine({profile,poseRuntime:runtime});await capture.start({videoWidth:10,videoHeight:10},{detector});assert.equal(created,0);assert.equal(received,detector)});

test('browser bootstrap waits for dependencies and detector before enabling camera',async()=>{const source=fs.readFileSync(path.join(ROOT,'public/push-up-challenge-page.js'),'utf8');assert.match(source,/await global\.__ensurePoseRuntime\(\)[\s\S]+await global\.tf\.ready\(\)[\s\S]+global\.poseDetection[\s\S]+await global\.PoseRuntime\.initMoveNetDetector/);assert.match(source,/if\(!engineReady\|\|!detector\|\|!cameraActive\|\|!sideConfirmed\.checked\)/);assert.match(source,/NotAllowedError[\s\S]+NotFoundError[\s\S]+does not support camera capture/);assert.match(source,/INSECURE_CONTEXT/);assert.match(source,/retryBtn\.onclick=initializePoseEngine/)});

test('shared dependency loader clears failed promises so Retry can load again',()=>{const source=fs.readFileSync(path.join(ROOT,'public/runtime-state.js'),'utf8');assert.match(source,/task\.catch\(\(\) => lazyScriptCache\.delete\(src\)\)/);assert.match(source,/poseRuntimePromise = null;[\s\S]+throw error/)});

test('camera controller prefers saved exact camera, enumerates, mirrors front, and stops old tracks on switch',async()=>{
  const calls=[],stopped=[];const devices=[{kind:'videoinput',deviceId:'front',label:'Front Camera'},{kind:'videoinput',deviceId:'rear',label:'Back Camera'}];
  const mediaDevices={enumerateDevices:async()=>devices,getUserMedia:async constraints=>{calls.push(constraints);const selected=constraints.video.deviceId?.exact||'front';return{getTracks:()=>[{stop:()=>stopped.push(selected)}],getVideoTracks:()=>[{getSettings:()=>({deviceId:selected,facingMode:selected==='rear'?'environment':'user'})}]};}};
  const video={readyState:1,srcObject:null,play:async()=>{}};const storage={getItem:()=> 'front',setItem(){}};const camera=new C.CameraController({mediaDevices,video,storage});
  await camera.initial();assert.equal(calls[0].video.deviceId.exact,'front');assert.equal(camera.devices.length,2);assert.equal(camera.isMirrored,true);await camera.switchTo('rear');assert.equal(calls[1].video.deviceId.exact,'rear');assert.ok(stopped.includes('front'));assert.equal(camera.isMirrored,false);assert.equal(camera.selectedCameraLabel,'Back Camera');camera.stop();
});

test('camera controller initial request prefers front camera without a saved device and supplies fallback labels',async()=>{let constraints;const stream={getTracks:()=>[],getVideoTracks:()=>[{getSettings:()=>({deviceId:'one',facingMode:'user'})}]};const camera=new C.CameraController({storage:{getItem:()=>''},video:{readyState:1,play:async()=>{}},mediaDevices:{getUserMedia:async value=>(constraints=value,stream),enumerateDevices:async()=>[{kind:'videoinput',deviceId:'one',label:''}]}});await camera.initial();assert.equal(constraints.video.facingMode.ideal,'user');assert.equal(constraints.video.width.ideal,640);assert.equal(camera.devices[0].friendlyLabel,'Camera 1');});

test('shared video transform maps cover crops, mirroring, portrait, landscape, and DPR deterministically',()=>{const landscape=C.createVideoScreenTransform({sourceWidth:1920,sourceHeight:1080,containerWidth:400,containerHeight:400,objectFit:'cover',isMirrored:false,devicePixelRatio:2});assert.equal(landscape.scale,400/1080);assert.ok(landscape.offsetX<0);assert.deepEqual(landscape.map({x:.5,y:.5}).screenX,200);assert.equal(landscape.devicePixelRatio,2);const mirrored=C.createVideoScreenTransform({sourceWidth:640,sourceHeight:480,containerWidth:300,containerHeight:600,objectFit:'cover',isMirrored:true});const point=mirrored.map({x:.25,y:.5});assert.equal(point.screenX,300-(.25*640*mirrored.scale+mirrored.offsetX));const contain=C.createVideoScreenTransform({sourceWidth:480,sourceHeight:640,containerWidth:600,containerHeight:300,objectFit:'contain'});assert.ok(contain.offsetX>0);});

test('pose readiness and side selection use temporal hysteresis',()=>{const gate=new C.PoseStabilityGate({readyFrames:3,lostFrames:2});assert.deepEqual([gate.update(true),gate.update(true),gate.update(true)],[false,false,true]);assert.equal(gate.update(false),true);assert.equal(gate.update(false),false);const points=(left,right)=>['left','right'].flatMap(side=>['shoulder','hip','ankle'].map((name,i)=>({name:`${side}_${name}`,x:i,y:i,score:side==='left'?left:right})));const tracker=new C.SideTracker({initialSideRequiredFrames:2,sideSwitchRequiredFrames:2,sideSwitchConfidenceMargin:.1});tracker.select(points(.9,.8),.75);tracker.select(points(.9,.8),.75);assert.equal(tracker.activeSide,'left');tracker.select(points(.8,.95),.75);assert.equal(tracker.activeSide,'left');tracker.select(points(.8,.95),.75);assert.equal(tracker.activeSide,'right');});

test('low-confidence frames stay unusable and cannot advance repetitions or findings',()=>{const engine=new C.PoseCaptureEngine({profile});const keypoints=['left','right'].flatMap(side=>['shoulder','hip','ankle'].map((name,i)=>({name:`${side}_${name}`,x:20+i*10,y:20+i*10,score:.5})));const frame=engine.transform({keypoints},{width:100,height:100});assert.equal(frame.usable,false);assert.equal(frame.poseReady,false);assert.ok(Object.values(frame.landmarks).every(point=>point===null||point.confidence<.75));const repetition=new C.RepetitionEventEngine();assert.equal(repetition.observe(frame),null);assert.equal(repetition.count,0);});
