'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { PUSH_UP_SEQUENCE_DEFINITION, normalizeSequencePose, PushUpSequenceMatcher } = require('../public/push-up-sequence-engine');

function pose(elbowDegrees, shift=0, { scale=1, mirror=false, offsetX=0, offsetY=0 }={}) {
  const rad=(180-elbowDegrees)*Math.PI/180;
  const raw={shoulder:{x:0,y:shift},elbow:{x:.5,y:shift},wrist:{x:.5+.5*Math.cos(rad),y:shift+.5*Math.sin(rad)},hip:{x:1,y:shift},ankle:{x:2,y:shift}};
  return Object.fromEntries(Object.entries(raw).map(([name,p])=>[name,{x:(mirror?-p.x:p.x)*scale+offsetX,y:p.y*scale+offsetY,confidence:.95}]));
}
const frame=(angle,shift,timestamp,extra={})=>({timestamp,trackingState:'LOCKED',analysisUsable:true,sequenceLandmarks:pose(angle,shift),...extra});
function valid(m=new PushUpSequenceMatcher()) { let t=0; for(const [a,y] of [[170,0],[170,0],[170,0],[164,.01],[158,.02],[130,.09],[130,.09],[130,.09],[140,.07],[150,.05],[165,.02],[165,.02],[165,.02]]) m.observe(frame(a,y,++t)); return m; }

test('versioned proposal preserves exact ordered phase model',()=>{assert.deepEqual(PUSH_UP_SEQUENCE_DEFINITION.phases.map(p=>p.phaseId),['top','lowering','bottom','rising','top_complete']);assert.equal(PUSH_UP_SEQUENCE_DEFINITION.reviewState,'trainer_review_required');});
test('valid Top Lowering Bottom Rising Top completes exactly once',()=>assert.equal(valid().repetitions,1));
test('every completed repetition carries ordered explainability evidence',()=>{const diagnostics=valid().diagnostics();assert.deepEqual(diagnostics.repetitionExplanations,[{repetition:1,timestamp:13,evidence:['top','lowering','bottom','rising','top_complete']}]);});

test('100 consecutive synthetic push-ups preserve order without duplicates',()=>{const matcher=new PushUpSequenceMatcher();for(let repetition=0;repetition<100;repetition++)valid(matcher);const diagnostics=matcher.diagnostics();assert.equal(matcher.repetitions,100);assert.equal(diagnostics.repetitionExplanations.length,100);assert.equal(diagnostics.phaseEvents.length,300);assert.equal(diagnostics.transitionEvents.length,200);assert.ok(diagnostics.repetitionExplanations.every((item,index)=>item.repetition===index+1));});
test('bottom first, Top to Top, and random order do not count',()=>{for(const frames of [[[120,.1],[120,.1],[120,.1]],[[170,0],[170,0],[170,0],[170,0],[170,0]],[[170,0],[170,0],[170,0],[130,.1],[130,.1],[170,0]]]){const m=new PushUpSequenceMatcher();frames.forEach(([a,y],i)=>m.observe(frame(a,y,i)));assert.equal(m.repetitions,0);}});
test('missing lowering and missing rising are rejected',()=>{const noLower=new PushUpSequenceMatcher();[[170,0],[170,0],[170,0],[130,.1],[130,.1],[130,.1]].forEach(([a,y],i)=>noLower.observe(frame(a,y,i)));assert.equal(noLower.expected(),'LOWERING');const noRise=new PushUpSequenceMatcher();[[170,0],[170,0],[170,0],[164,.01],[158,.02],[130,.09],[130,.09],[130,.09],[170,0],[170,0],[170,0]].forEach(([a,y],i)=>noRise.observe(frame(a,y,i)));assert.equal(noRise.repetitions,0);});
test('positions require persistence',()=>{const m=new PushUpSequenceMatcher();m.observe(frame(170,0,1));assert.equal(m.expected(),'TOP');m.observe(frame(170,0,2));m.observe(frame(170,0,3));assert.equal(m.expected(),'LOWERING');m.observe(frame(164,.01,4));m.observe(frame(158,.02,5));m.observe(frame(130,.09,6));assert.equal(m.expected(),'BOTTOM');m.observe(frame(130,.09,7));m.observe(frame(130,.09,8));assert.equal(m.expected(),'RISING');});
test('transition direction is required and missing frames interrupt it',()=>{const m=new PushUpSequenceMatcher();[1,2,3].forEach(i=>m.observe(frame(170,0,i)));m.observe(frame(160,-.01,4));assert.equal(m.expected(),'LOWERING');m.observe(frame(160,.01,5));m.observe({...frame(150,.02,6),analysisUsable:false,trackingState:'DEGRADED'});m.observe(frame(140,.03,7));assert.equal(m.expected(),'LOWERING');});
test('tracking degradation, recovery and display points cannot create a repetition',()=>{const m=valid();const completed=m.repetitions;m.observe({...frame(170,0,20),trackingState:'LOST',analysisUsable:false});assert.equal(m.repetitions,completed);const r=m.observe({...frame(170,0,21),recoveredThisFrame:true});assert.equal(r.phaseMatched,false);const cached=pose(170,0);cached.elbow.displayOnly=true;assert.equal(m.observe({...frame(170,0,22),sequenceLandmarks:cached}).phaseMatched,false);assert.equal(m.repetitions,completed);});
test('normalization is body-size, translation, mirror, and layout independent',()=>{const base=normalizeSequencePose(pose(150,.03));for(const options of [{scale:4},{mirror:true},{offsetX:8,offsetY:4},{scale:.4,mirror:true,offsetX:2,offsetY:3}]){const n=normalizeSequencePose(pose(150,.03,options));assert.ok(Math.abs(n.elbowAngle-base.elbowAngle)<1e-9);assert.ok(Math.abs(n.points.wrist.x-base.points.wrist.x)<1e-9);}});
test('similarity is explainable and form scoring remains separate',()=>{const m=new PushUpSequenceMatcher();const out=m.observe(frame(170,0,1));assert.deepEqual(Object.keys(out.similarity.featureScores),['bodyAlignment','elbowAngle','relativePosition','movementDirection']);assert.deepEqual(out.formFindings,[]);assert.equal(out.formScore,null);});
test('proposed elbow capability does not mutate approved alignment landmarks or claims',()=>{const C=require('../public/push-up-challenge');assert.deepEqual(C.LANDMARK_NAMES,['shoulder','hip','ankle']);assert.deepEqual(C.SEQUENCE_LANDMARK_NAMES,['shoulder','elbow','wrist','hip','ankle']);const source=require('node:fs').readFileSync(require('node:path').join(__dirname,'../public/push-up-sequence-engine.js'),'utf8');assert.doesNotMatch(source,/chest reached|perfect lockout|Perfect Push-Up|90-degree/);});
test('session diagnostics persist fingerprint and events without raw video or display points',()=>{const C=require('../public/push-up-challenge');const profile={exerciseId:'push_up',metadataFingerprint:'x',profileVersion:1,generatorVersion:'1',capabilityRegistryVersion:'1',rulesVersion:'1',poseAnalysis:{rules:[{thresholds:{maximumDeviationDegrees:18},minimumAffectedFramePercentage:35,minimumConsecutiveDurationMs:500}]}};const recorder=new C.PerformanceRecorder({profile});recorder.start({mode:'practice',requiredViewEstablished:true});const m=valid();recorder.sequence(m.diagnostics(),'sequenceOnly');const value=recorder.session;assert.ok(value.phaseEvents.length);assert.equal(value.templateFingerprint,PUSH_UP_SEQUENCE_DEFINITION.templateFingerprint);assert.equal('rawVideo' in value,false);assert.doesNotMatch(JSON.stringify(value),/displayOnly|predicted/);});
