"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path"),cp=require("node:child_process");
const {createLaunchReadinessService,deriveStatus,validateDependencies,boardPointers,seed,IDS,SCHEMA_VERSION}=require("../src/services/launchReadinessService");
const matrixPath=path.join(__dirname,"../data/launch/feature-readiness-matrix.v1.json");
const service=()=>createLaunchReadinessService({filePath:path.join(fs.mkdtempSync(path.join(os.tmpdir(),"readiness-os-")),"state.json"),canonicalMatrixPath:matrixPath});
test("canonical contract and update mechanism exist",()=>{assert.match(fs.readFileSync(path.join(__dirname,"../AGENTS.md"),"utf8"),/must never self-approve/i);assert.ok(fs.existsSync(path.join(__dirname,"../scripts/readiness-update.js")))});
test("status engine separates technical and human authority",()=>{const base={workStarted:true,codeComplete:false,automated:"NOT_RUN",humanRequired:false,humanVerified:false,blocker:""};assert.equal(deriveStatus(base),"IN_PROGRESS");assert.equal(deriveStatus({...base,codeComplete:true,automated:"PASS",humanRequired:true}),"HUMAN_TEST_REQUIRED");assert.equal(deriveStatus({...base,codeComplete:true,automated:"PASS",humanRequired:true,humanVerified:true}),"DONE");assert.equal(deriveStatus({...base,blocker:"dependency unavailable"}),"BLOCKED");assert.equal(deriveStatus({...base,workflowStatus:"POST_LAUNCH"}),"POST_LAUNCH")});
test("dependencies reject missing, self, duplicate, and cycles",()=>{assert.equal(validateDependencies([{id:"a",dependsOn:[]},{id:"b",dependsOn:["a"]}]),true);assert.throws(()=>validateDependencies([{id:"a",dependsOn:["x"]}]),/missing/);assert.throws(()=>validateDependencies([{id:"a",dependsOn:["a"]}]),/self/);assert.throws(()=>validateDependencies([{id:"a",dependsOn:["b"]},{id:"b",dependsOn:["a"]}]),/cycle/);assert.throws(()=>validateDependencies([{id:"a",dependsOn:[]},{id:"b",dependsOn:["a","a"]}]),/duplicate/)});
test("next is deterministic, dependency-aware, blocker-aware, and priority ordered",()=>{const done={workStarted:true,codeComplete:true,automated:"PASS",humanRequired:false,humanVerified:false,blocker:""},cards=[{id:"done",order:0,priority:"NORMAL",dependsOn:[],...done},{id:"blocked",order:1,priority:"CRITICAL",dependsOn:[],...done,blocker:"x"},{id:"waiting",order:2,priority:"CRITICAL",dependsOn:["blocked"],workStarted:false,codeComplete:false,automated:"NOT_RUN",humanRequired:false,blocker:""},{id:"high",order:4,priority:"HIGH",dependsOn:[],workStarted:false,codeComplete:false,automated:"NOT_RUN",humanRequired:false,blocker:""},{id:"normal",order:3,priority:"NORMAL",dependsOn:[],workStarted:false,codeComplete:false,automated:"NOT_RUN",humanRequired:false,blocker:""}];assert.equal(boardPointers(cards,null).nextCard.id,"high")});
test("updates append evidence, transition, and authorized human history while machine signoff fails",()=>{const s=service(),card=s.snapshot().boards.avatar.find(c=>c.title==="Physical-device acceptance");assert.throws(()=>s.update("avatar",card.id,{humanVerified:true,actorType:"machine"}),/authorized_human/);s.update("avatar",card.id,{action:"evidence",note:"repository proof",files:["test/example.js"]});let next=s.snapshot().boards.avatar.find(c=>c.id===card.id);assert.ok(next.history.some(e=>e.type==="evidence_attached"));s.update("avatar",card.id,{action:"human-verify",actorType:"human",note:"Authorized device acceptance"});next=s.snapshot().boards.avatar.find(c=>c.id===card.id);assert.ok(next.history.some(e=>e.type==="human_verification"))});
test("old JSON migrates defaults and preserves history/evidence",()=>{const s=service(),file=s.snapshot;const dir=fs.mkdtempSync(path.join(os.tmpdir(),"old-ready-")),state=path.join(dir,"state.json"),seeded=seed(require(matrixPath)),card=seeded.boards.avatar[0];fs.writeFileSync(state,JSON.stringify({version:4,boards:{launch:[],avatar:[{id:card.id,evidence:"old proof",history:[{type:"old"}]}]}}));const migrated=createLaunchReadinessService({filePath:state,canonicalMatrixPath:matrixPath}).snapshot(),got=migrated.boards.avatar[0];assert.equal(migrated.version,SCHEMA_VERSION);assert.equal(got.evidence,"old proof");assert.ok(got.history.some(x=>x.type==="old"));assert.equal(got.priority,"NORMAL")});
test("avatar reconciliation is exactly twenty and pointers/summaries are consistent",()=>{const snap=service().snapshot(),a=snap.summaries.avatar;assert.equal(snap.boards.avatar.length,20);assert.equal(Object.values(a.counts).reduce((x,y)=>x+y,0),20);assert.equal(a.remaining,20-a.counts.DONE-a.counts.POST_LAUNCH);assert.equal(a.currentCard.id,IDS["Full live avatar mirror"]);assert.ok(a.nextCard);assert.ok(a.lastCompletedCard);assert.ok(snap.boards.avatar.filter(c=>c.humanRequired).every(c=>c.status!=="DONE"))});

const updateCli=require("../scripts/readiness-update");
function validationFixture(entries,previous=[]){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"ready-validate-")),evidence=path.join(dir,"evidence.json"),prior=path.join(dir,"prior.json"),scopes=path.join(dir,"scopes.json");fs.writeFileSync(evidence,JSON.stringify({version:1,entries}));fs.writeFileSync(prior,JSON.stringify({version:1,entries:previous}));fs.writeFileSync(scopes,JSON.stringify({scopes:{avatar:{paths:["public/avatar-runtime.js","public/motion/**"]}}}));return{evidence,prior,scopes}}
function runValidation(files,fixture){return cp.spawnSync(process.execPath,[path.join(__dirname,"../scripts/validate-readiness-contract.js")],{encoding:"utf8",env:{...process.env,READINESS_CHANGED_FILES:files,READINESS_EVIDENCE_FILE:fixture.evidence,READINESS_PREVIOUS_EVIDENCE_FILE:fixture.prior,READINESS_SCOPES_FILE:fixture.scopes}})}
const canonicalId=IDS["Full live avatar mirror"];
test("correlated validator requires fresh same-board real-card overlapping evidence",()=>{const valid={board:"avatar",cardId:canonicalId,sourceType:"implementation",files:["public/avatar-runtime.js","public/motion/example.js"],evidence:"correlated",timestamp:"2026-08-30T01:00:00Z"};assert.equal(runValidation("public/avatar-runtime.js,public/motion/example.js",validationFixture([valid])).status,0);assert.notEqual(runValidation("public/avatar-runtime.js",validationFixture([{...valid,files:["public/motion/other.js"]}])).status,0);assert.notEqual(runValidation("public/avatar-runtime.js",validationFixture([{...valid,board:"launch"}])).status,0);assert.notEqual(runValidation("public/avatar-runtime.js",validationFixture([{...valid,cardId:"missing-card"}])).status,0);assert.notEqual(runValidation("public/avatar-runtime.js",validationFixture([valid],[valid])).status,0);assert.equal(runValidation("docs/readme.md",validationFixture([])).status,0)});
test("canonical CLI evidence operation updates operational and repository stores coherently",()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"ready-cli-")),ops=path.join(dir,"ops.json"),audit=path.join(dir,"audit.json"),env={READINESS_OPS_FILE:ops,READINESS_EVIDENCE_FILE:audit,READINESS_MATRIX_FILE:matrixPath};fs.writeFileSync(audit,JSON.stringify({version:1,entries:[]}));const result=updateCli.run(["--board","avatar","--card",canonicalId,"--action","evidence","--task","hardening","--files","scripts/readiness-update.js,scripts/validate-readiness-contract.js","--note","dual update","--result","PASS","--pr","571","--commit","abc123"],env),stored=JSON.parse(fs.readFileSync(audit,"utf8")).entries[0],card=createLaunchReadinessService({filePath:ops,canonicalMatrixPath:matrixPath}).snapshot().boards.avatar.find(c=>c.id===canonicalId);assert.equal(result.card.id,stored.cardId);assert.equal(stored.taskId,"hardening");assert.deepEqual(stored.files,["scripts/readiness-update.js","scripts/validate-readiness-contract.js"]);assert.equal(stored.prNumber,571);assert.equal(stored.commitSha,"abc123");assert.equal(card.evidence,"dual update");assert.equal(card.automated,"PASS")});
test("CLI is machine-only and rolls operational state back when audit write fails",()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"ready-atomic-")),ops=path.join(dir,"ops.json"),blocker=path.join(dir,"not-a-directory");fs.writeFileSync(blocker,"x");const badAudit=path.join(blocker,"audit.json");const env={READINESS_OPS_FILE:ops,READINESS_EVIDENCE_FILE:badAudit,READINESS_MATRIX_FILE:matrixPath};assert.throws(()=>updateCli.run(["--board","avatar","--card",canonicalId,"--action","human-verify","--note","spoof"],env),/authenticated authorized/);assert.throws(()=>updateCli.run(["--board","avatar","--card",canonicalId,"--action","evidence","--actorType","human","--note","spoof"],env),/machine-authority/);assert.throws(()=>updateCli.run(["--board","avatar","--card",canonicalId,"--action","delete"],env),/unsupported_action/);assert.throws(()=>updateCli.run(["--board","avatar","--card",canonicalId,"--action","evidence","--note","will rollback"],env));assert.equal(fs.existsSync(ops),false)});
test("machine creates safe noncanonical cards without changing canonical Avatar count",()=>{const s=service(),before=s.snapshot(),dependency=IDS["Normalized pose mapping"],created=s.create("avatar",{title:"Explicit neutral calibration UX",category:"LIVE MIRROR",priority:"CRITICAL",dependsOn:[dependency],current:true}),card=created.boards.avatar.find(c=>c.canonical===false);assert.match(card.id,/^avatar-development-/);assert.equal(card.canonical,false);assert.equal(card.createdByAuthority,"machine");assert.equal(created.boards.avatar.filter(c=>c.canonical!==false).length,20);assert.equal(created.boards.avatar.length,21);assert.throws(()=>s.create("avatar",{title:card.title}),/duplicate/);assert.throws(()=>s.create("avatar",{title:"Bad priority",priority:"URGENT"}),/invalid_priority/);assert.throws(()=>s.create("avatar",{title:"Bad dependency",dependsOn:["missing"]}),/missing_dependency/);const snap=s.snapshot();assert.equal(snap.summaries.avatar.currentCard.id,card.id);assert.equal(snap.boards.avatar.filter(c=>c.canonical!==false).length,20);assert.equal(before.boards.avatar.filter(c=>c.canonical!==false).length,20)});
test("development card can participate in deterministic NEXT",()=>{const s=service();s.create("avatar",{title:"High eligible task",priority:"CRITICAL"});const snap=s.snapshot();assert.equal(snap.summaries.avatar.nextCard.id,"avatar-development-high-eligible-task")});
test("server owns human authority and frontend counts canonical cards only",()=>{const server=fs.readFileSync(path.join(__dirname,"../server.js"),"utf8"),client=fs.readFileSync(path.join(__dirname,"../public/admin-launch-readiness.js"),"utf8");assert.match(server,/\.\.\.\(req\.body\|\|\{\}\),actorType:"human"/);assert.match(client,/filter\(card => card\.canonical !== false\)/)});
