"use strict";const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");const {createResidentialCommunityService,DAY_MS}=require("../src/services/residentialCommunityService");const read=p=>fs.readFileSync(path.join(__dirname,"..",p),"utf8");
function store(){const users=new Map([["u1",{userId:"u1",email:"one@example.com",residentialWellness:{communicationConsent:true,interests:["yoga"]}}],["u2",{userId:"u2",email:"two@example.com",residentialWellness:{communicationConsent:true,interests:["sound_bath"]}}]]);return{loadUser:id=>users.get(id),listUsers:()=>[...users.values()],updateUser(id,fn){const u=fn(users.get(id));users.set(id,u);return u}}}
test("hub dashboard returns events profile and member stats",()=>{const s=createResidentialCommunityService({userStore:store(),clock:()=>Date.parse("2026-10-06T12:00:00-05:00")}),d=s.dashboard("u1");assert.equal(d.profile.interests[0],"yoga");assert.equal(d.stats.members,2);assert.equal(d.nextEvent,null);assert.deepEqual(d.events,[]);assert.equal(d.wednesdayReset.capacity,14)});
test("chat messages expire after 24 hours",()=>{let now=Date.parse("2026-10-06T12:00:00-05:00");const s=createResidentialCommunityService({userStore:store(),clock:()=>now});s.post("u1",{text:"Hello community"});assert.equal(s.messages("u1").length,1);now+=DAY_MS+1;assert.equal(s.messages("u1").length,0)});
test("proposed events reject RSVP until confirmed",()=>{const s=createResidentialCommunityService({userStore:store(),clock:()=>Date.parse("2026-10-06T12:00:00-05:00")});assert.throws(()=>s.rsvp("u1","wednesday-reset",true),/Event not found/)});
test("member confirmation enters hub instead of marketing page",()=>{assert.match(read("public/residential-wellness.html"),/Enter My Community/);assert.match(read("public/residential-wellness.html"),/community-hub\.html/);assert.doesNotMatch(read("public/residential-wellness.html"),/Back to Community Wellness/)});
test("hub includes calendar chat interests and canonical auth",()=>{const h=read("public/community-hub.html"),j=read("public/community-hub.js");assert.match(h,/COMMUNITY CALENDAR/);assert.match(h,/COMMUNITY CHAT · 24 HOURS/);assert.match(h,/YOUR WELLNESS/);assert.match(j,/AuthStateRuntime/);assert.match(j,/authorization:\`Bearer/)});
test("chat history requires Community Wellness membership",()=>{const st=store();st.updateUser("u2",u=>{u.residentialWellness.communicationConsent=false;return u});const s=createResidentialCommunityService({userStore:st});assert.throws(()=>s.messages("u2"),/Join Community Wellness/)});

test("Wednesday Reset interest votes are saved and count only definite attendance",()=>{const s=createResidentialCommunityService({userStore:store(),clock:()=>Date.parse("2026-10-06T12:00:00-05:00")});s.interest("u1",{attending:"yes",focus:"sound"});s.interest("u2",{attending:"maybe",focus:"yoga"});const w=s.dashboard("u1").wednesdayReset;assert.equal(w.interestedCount,1);assert.equal(w.focusVotes.sound,1);assert.equal(w.focusVotes.yoga,0);assert.equal(w.myVote.focus,"sound");assert.equal(w.remainingToMinimum,6)});
test("Wednesday votes roll over after the evening session",()=>{let now=Date.parse("2026-10-07T18:30:00-05:00");const s=createResidentialCommunityService({userStore:store(),clock:()=>now});s.interest("u1",{attending:"yes",focus:"sound"});assert.equal(s.dashboard("u1").wednesdayReset.interestedCount,1);now=Date.parse("2026-10-07T20:00:00-05:00");assert.equal(s.dashboard("u1").wednesdayReset.interestedCount,0);s.interest("u1",{attending:"yes",focus:"yoga"});assert.equal(s.dashboard("u1").wednesdayReset.interestedCount,1)});
test("Wednesday interest requires consent and valid choices",()=>{const st=store(),s=createResidentialCommunityService({userStore:st});assert.throws(()=>s.interest("u1",{attending:"yes",focus:"invalid"}),/Choose attendance/);st.updateUser("u2",u=>{u.residentialWellness.communicationConsent=false;return u});assert.throws(()=>s.interest("u2",{attending:"yes",focus:"yoga"}),/Join Community Wellness/)});
