"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{pathToFileURL}=require("node:url");
const read=file=>fs.readFileSync(path.join(__dirname,"../public",file),"utf8");
async function uiModule(){const file=`/tmp/route-planning-ui-${process.pid}.mjs`;fs.writeFileSync(file,read("route-planning-ui.js"));return import(pathToFileURL(file));}
test("consumer route labels and match bands are server-score presentations",async()=>{const ui=await uiModule();assert.deepEqual(["verified_geometry","trail_network","park_constrained_walking_route","google_walking_route","place_only"].map(ui.routeSourceLabel),["Verified trail loop","Mapped trail loop","Park-constrained route","Estimated walking loop","Location only"]);assert.deepEqual([95,85,75,65,50,40].map(ui.routeMatchLabel),["Exceptional match","Excellent match","Strong match","Good match","Fair match","Limited match"]);});
test("recommended route is visually elevated without hiding route truth",()=>{const js=read("greatness.js"),css=read("greatness.css");assert.match(js,/is-recommended/);assert.match(js,/Best match/);assert.match(css,/recommendReveal/);assert.match(js,/Numeric quality score/);assert.doesNotMatch(js,/Route quality:/);assert.match(js,/Warnings/);assert.match(js,/routeVerification/);});
test("mobile carousel keeps options accessible and keyboard operable",()=>{const js=read("greatness.js"),css=read("greatness.css");assert.match(js,/role=\\?"listbox/);assert.match(js,/aria-selected/);assert.match(js,/ArrowRight/);assert.match(js,/data-carousel-prev/);assert.match(css,/scroll-snap-type:none!important/);assert.match(css,/overscroll-behavior-inline:contain/);assert.match(css,/@media\(max-width:700px\)/);});
test("staged actions gate Start activity behind selection",()=>{const js=read("greatness.js");const dock=js.indexOf("selected-action-dock");assert.ok(dock>0);assert.match(js,/dock\.hidden=false/);assert.match(js,/Start activity/);assert.match(js,/Preview route/);assert.match(js,/Use route/);});
test("details drawer manages focus, escape, warnings, and safe areas",()=>{const js=read("greatness.js"),css=read("greatness.css");for(const token of ["showModal","dialog.close","lastDetailsInvoker?.focus","addEventListener(\"cancel\""] )assert.ok(js.includes(token));assert.match(css,/env\(safe-area-inset-bottom\)/);assert.match(css,/\.route-details-drawer/);assert.match(js,/detail-warnings/);});
test("planning, fallback, reduced motion, and map reuse protections remain",()=>{const js=read("greatness.js"),css=read("greatness.css"),map=read("trail-map.js");for(const stage of ["Finding nearby paths","Checking loop options","Matching your goal","Validating route quality","Preparing recommendations"])assert.match(js,new RegExp(stage));assert.match(js,/could not build a reliable route/);assert.match(css,/prefers-reduced-motion:reduce/);assert.match(map,/mapStates\.get\(container\)/);assert.match(map,/FORWARD_CLOSED_ARROW/);assert.match(map,/progress_chunks/);});
test("responsive planner prevents page overflow from 320 through 430 widths",()=>{const css=read("greatness.css"),html=read("greatness.html");assert.match(css,/html,body\{max-width:100%;overflow-x:hidden\}/);assert.match(css,/@media\(max-width:350px\)/);assert.match(css,/@media\(max-width:700px\)/);assert.match(html,/viewport-fit=cover/);assert.match(css,/min-width:0/);});
test("route truth distinguishes estimated, mixed, and mapped geometry",async()=>{const ui=await uiModule();assert.equal(ui.routeNotice({routeSource:"google_walking_route"}),"Estimated walking route — may use nearby streets or paths.");assert.equal(ui.routeDisplayLabel({routeSource:"google_walking_route",trailAdherencePercent:40}),"Estimated mixed route");assert.equal(ui.routeDetailNotice({routeSource:"trail_network"}),"Closely follows mapped pedestrian paths.");});
test("carousel uses one inert authoritative card and cancels animation races",()=>{const js=read("route-carousel.js"),css=read("greatness.css");for(const value of ["is-active","aria-hidden","aria-selected","aria-current","tabIndex","inert","cancelAnimationFrame","visibleCardOverlapDetected","duplicateFingerprints"])assert.match(js,new RegExp(value));assert.match(css,/visibility:hidden/);assert.match(css,/pointer-events:none/);assert.match(css,/z-index:2/);});
test("direction preview exposes arrows, progress, overlap, markers, laps and legend",()=>{const js=read("trail-map.js"),page=read("greatness.js");for(const value of ["FORWARD_CLOSED_ARROW","offset_dashed_return","progress_chunks","Route halfway","Route finish","Lap ${lap}"])assert.ok(js.includes(value));for(const value of ["Route legend","Halfway / Turnaround","Outbound","Return","data-route-sequence"])assert.ok(page.includes(value));});
test("the whole page shares telemetry surfaces and control hierarchy",()=>{const css=read("greatness.css");for(const value of ["LIVE ACTIVITY","MODULE ",".recorder .metrics",".actions #start:not(:disabled)",".actions .danger","body>header:after"])assert.ok(css.includes(value));});
