"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {createRunClubDiagnosticsService}=require("../src/diagnostics/runClubDiagnosticsService");
const contract=require("../config/route-authorization-contract");
const {createApp}=require("../server");const {createAuthTokenLib}=require("../src/lib/authToken");
test("Run Club master diagnostics pass backend checks, label visual checks unavailable, redact output, and clean isolation",()=>{const before=new Set(fs.readdirSync(os.tmpdir()).filter(x=>x.startsWith("run-club-diagnostics-"))),report=createRunClubDiagnosticsService({rootDir:path.join(__dirname,".."),routeContract:contract}).run(),after=new Set(fs.readdirSync(os.tmpdir()).filter(x=>x.startsWith("run-club-diagnostics-")));assert.equal(report.overall,"PASS");assert.deepEqual(report.phases.map(x=>x.status),["PASS","PASS","PASS","PASS"]);assert.equal(report.boundary.status,"PASS");assert.equal(report.continuity.status,"PASS");assert.ok(report.phases[2].checks.some(x=>x.status==="NOT AVAILABLE"));assert.deepEqual(after,before);assert.doesNotMatch(JSON.stringify(report),/diagnostic_member|authToken|password|latitude|longitude/);});
test("unsupported Greatness XP producers remain disabled",()=>{const actions=require("../data/gamification/xp-policy.json").policies[0].actions;for(const event of ["greatness.weekly_goal.completed","greatness.personal_best.earned","greatness.club_run.completed","greatness.trail_contribution.helpful_milestone","greatness.referral.activated","greatness.new_trail.completed"])assert.equal(actions[event],undefined,event);});
test("Run Club diagnostics endpoint and page require admin authorization",async t=>{const prior=process.env.AUTHZ_BOOTSTRAP_SUPER_ADMIN_USER_IDS;process.env.AUTHZ_BOOTSTRAP_SUPER_ADMIN_USER_IDS="runclub_admin";t.after(()=>prior==null?delete process.env.AUTHZ_BOOTSTRAP_SUPER_ADMIN_USER_IDS:process.env.AUTHZ_BOOTSTRAP_SUPER_ADMIN_USER_IDS=prior);const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),"runclub-diag-api-")),app=createApp({dataDir}),server=app.listen(0);t.after(()=>server.close());await new Promise(r=>server.once("listening",r));const base=`http://127.0.0.1:${server.address().port}`,auth=createAuthTokenLib({secret:process.env.AUTH_TOKEN_SECRET||"dev-only-secret-change-me"}),member=auth.issueUserToken({userId:"ordinary_member"}).token,admin=auth.issueUserToken({userId:"runclub_admin"}).token;for(const route of ["/admin-run-club-diagnostics.html","/api/admin/diagnostics/run-club/run"]){const method=route.startsWith("/api/")?"POST":"GET";assert.equal((await fetch(base+route,{method})).status,401);assert.equal((await fetch(base+route,{method,headers:{authorization:`Bearer ${member}`}})).status,403);}const response=await fetch(base+"/api/admin/diagnostics/run-club/run",{method:"POST",headers:{authorization:`Bearer ${admin}`}});assert.equal(response.status,201);assert.equal((await response.json()).data.safeMode.cleanup,"automatic");assert.equal((await fetch(base+"/admin-run-club-diagnostics.html",{headers:{authorization:`Bearer ${admin}`}})).status,200);});
test("admin diagnostics UI has one master button and four phase rendering foundation",()=>{const html=fs.readFileSync(path.join(__dirname,"../public/admin-run-club-diagnostics.html"),"utf8"),js=fs.readFileSync(path.join(__dirname,"../public/admin-run-club-diagnostics.js"),"utf8");assert.match(html,/Run Run Club Diagnostics/);assert.equal((html.match(/id="runDiagnostics"/g)||[]).length,1);assert.match(js,/data\.phases/);assert.match(js,/NOT AVAILABLE|check\.status/);});
