"use strict";const test=require("node:test");const assert=require("node:assert/strict");
const {QUICK_BANK}=require("../src/sound-assessment/quick-bank");const {DEEP_BANK}=require("../src/sound-assessment/deep-bank");const I=require("../src/sound-assessment/interpretation");const {selectSoundStrategy}=require("../src/sound-assessment/recipe-engine");
const qa=Object.fromEntries(QUICK_BANK.map((q,i)=>[q.id,i%4])),da=Object.fromEntries(DEEP_BANK.map((q,i)=>[q.id,i%4]));
test("Quick interpretation teaches rather than describing unfinished software",()=>{const r=I.buildQuickInterpretation(qa);assert.equal(r.ok,true);const t=JSON.stringify(r.result);assert.doesNotMatch(t,/engine will|will later|internal scoring|technical assessment codes/i);assert.match(t,/directional rather than final/i);assert.match(t,/Full Sound Assessment/);});
test("Read-more detail adds information beyond preview",()=>{const r=I.buildQuickInterpretation(qa);for(const s of r.result.sections){assert.ok(s.detail.length>s.preview.length);assert.equal(s.actionLabel,"Read more");}});
test("primary and secondary patterns receive an interaction explanation",()=>{const r=I.buildQuickInterpretation(qa);assert.match(r.result.sections[1].title,/How .* connects/);assert.ok(r.result.sections[1].detail.length>120);});
test("Quick CTA explains why the longer assessment is more useful",()=>{const r=I.buildQuickInterpretation(qa);assert.match(r.result.cta.preview,/multiple angles|consistency/i);assert.equal(r.result.cta.actionLabel,"Take the Full Assessment");});
test("Deep interpretation resolves a curated two-bowl foundation",()=>{const r=I.buildDeepInterpretation(da);assert.equal(r.ok,true);assert.equal(r.result.soundFoundation.bowls.length,2);assert.match(r.result.soundFoundation.pairId,/SA_PAIR_/);assert.ok(r.result.soundFoundation.reasonCodes.length>=2);});
test("overactivation grounds before expansion when primary is not grounding",()=>{const fake={dimension_normalized:{CL:90,EF:70,GR:20,AG:10,CO:5,EX:4,SP:3},activation:{state:"OVERACTIVATED"}};const r=selectSoundStrategy(fake);assert.equal(r.ok,true);assert.equal(r.result.anchorDimension,"GR");assert.equal(r.result.partnerDimension,"CL");assert.ok(r.result.reasonCodes.includes("GROUND_BEFORE_EXPANSION"));});
