"use strict";const test=require("node:test");const assert=require("node:assert/strict");
const {QUICK_BANK}=require("../src/sound-assessment/quick-bank");const {DEEP_BANK}=require("../src/sound-assessment/deep-bank");const I=require("../src/sound-assessment/interpretation");const {selectSoundStrategy}=require("../src/sound-assessment/recipe-engine");
const qa=Object.fromEntries(QUICK_BANK.map((q,i)=>[q.id,i%4])),da=Object.fromEntries(DEEP_BANK.map((q,i)=>[q.id,i%4]));
test("Quick interpretation teaches rather than describing unfinished software",()=>{const r=I.buildQuickInterpretation(qa);assert.equal(r.ok,true);const t=JSON.stringify(r.result);assert.doesNotMatch(t,/engine will|will later|internal scoring|technical assessment codes/i);assert.match(t,/directional rather than final/i);assert.match(t,/Full Sound Assessment/);});
test("Read-more detail adds information beyond preview",()=>{const r=I.buildQuickInterpretation(qa);for(const s of r.result.sections){assert.ok(s.detail.length>s.preview.length);assert.equal(s.actionLabel,"Read more");}});
test("primary and secondary patterns receive an interaction explanation",()=>{const r=I.buildQuickInterpretation(qa);assert.match(r.result.sections[1].title,/How .* connects/);assert.ok(r.result.sections[1].detail.length>120);});
test("Quick CTA explains why the longer assessment is more useful",()=>{const r=I.buildQuickInterpretation(qa);assert.match(r.result.cta.preview,/multiple angles|consistency/i);assert.equal(r.result.cta.actionLabel,"Take the Full Assessment");});
test("Deep interpretation resolves a curated two-bowl foundation",()=>{const r=I.buildDeepInterpretation(da);assert.equal(r.ok,true);assert.equal(r.result.soundFoundation.bowls.length,2);assert.match(r.result.soundFoundation.pairId,/SA_PAIR_/);assert.ok(r.result.soundFoundation.reasonCodes.length>=2);});
test("overactivation grounds before expansion when primary is not grounding",()=>{const fake={dimension_normalized:{CL:90,EF:70,GR:20,AG:10,CO:5,EX:4,SP:3},activation:{state:"OVERACTIVATED"}};const r=selectSoundStrategy(fake);assert.equal(r.ok,true);assert.equal(r.result.anchorDimension,"GR");assert.equal(r.result.partnerDimension,"CL");assert.ok(r.result.reasonCodes.includes("GROUND_BEFORE_EXPANSION"));});

test("desired-state answers do not change current-state Deep scores",()=>{const base={...da};base.SAD10=0;base.SAD24=0;base.SAD25=0;const alt={...base,SAD10:3,SAD24:3,SAD25:3};const {scoreDeepAssessment}=require("../src/sound-assessment/deep-bank");const a=scoreDeepAssessment(base),b=scoreDeepAssessment(alt);assert.deepEqual(a.result.dimension_normalized,b.result.dimension_normalized);assert.deepEqual(a.result.activation,b.result.activation);assert.notDeepEqual(a.result.desiredState,b.result.desiredState);});
test("Quick desired answer does not alter current-state score or activation",()=>{const {scoreQuickAssessment}=require("../src/sound-assessment/quick-bank");const a={...qa,SAQ10:0},b={...qa,SAQ10:3};const x=scoreQuickAssessment(a),y=scoreQuickAssessment(b);assert.deepEqual(x.result.dimension_normalized,y.result.dimension_normalized);assert.deepEqual(x.result.activation,y.result.activation);assert.notDeepEqual(x.result.desiredState,y.result.desiredState);});

test("incomplete assessments fail closed before interpretation",()=>{assert.equal(I.buildQuickInterpretation({}).diagnostic.FIRST_FAILURE,"SA_ANSWER_MISSING");assert.equal(I.buildDeepInterpretation({}).diagnostic.FIRST_FAILURE,"SA_ANSWER_MISSING");});
test("customer interpretation does not expose internal dimension ids",()=>{const r=I.buildQuickInterpretation(qa);const text=JSON.stringify(r.result);for(const code of ["GR","EF","AG","CO","EX","CL","SP"])assert.doesNotMatch(text,new RegExp('"id":"'+code+'"'));});
test("curated interaction lookup uses normalized key ordering",()=>{assert.notEqual(I.interaction("AG","CL"),I.interaction("AG","SP"));assert.match(I.interaction("AG","CL"),/next step|energy/i);assert.match(I.interaction("EF","EX"),/emotion|expression/i);});
test("eligible desired state can alter a regulated recipe partner",()=>{const fake={dimension_normalized:{CL:90,EF:70,CO:50,GR:20,AG:10,EX:4,SP:3},activation:{state:"REGULATED"}};const a=selectSoundStrategy(fake,{desiredDimensions:["CO"]}),b=selectSoundStrategy(fake,{desiredDimensions:["EF"]});assert.equal(a.ok,true);assert.equal(b.ok,true);assert.notEqual(a.result.partnerDimension,b.result.partnerDimension);assert.ok(a.result.reasonCodes.includes("DESIRED_STATE_ALIGNMENT"));});
