"use strict";const test=require("node:test");const assert=require("node:assert/strict");const {publicBank,publicResult}=require("../src/routes/soundAssessmentRoutes");const {QUICK_BANK,QUICK_BANK_VERSION}=require("../src/sound-assessment/quick-bank");const {buildQuickInterpretation}=require("../src/sound-assessment/interpretation");
test("public bank exposes customer text without scoring mappings",()=>{const b=publicBank(QUICK_BANK,"quick",QUICK_BANK_VERSION),s=JSON.stringify(b);assert.equal(b.questions.length,10);assert.doesNotMatch(s,/primary_dimension|secondary_dimension|direction_value|activation_value/);});
test("public result strips internal dimension and recipe mechanics",()=>{const answers=Object.fromEntries(QUICK_BANK.map((q,i)=>[q.id,i%4]));const built=buildQuickInterpretation(answers);assert.equal(built.ok,true);const out=publicResult(built.result,"quick"),s=JSON.stringify(out);assert.doesNotMatch(s,/"id":"(?:GR|EF|AG|CO|EX|CL|SP)"|reasonCodes|anchorDimension|partnerDimension/);assert.match(s,/Full Sound Assessment/);});
test("published UI calls real sound assessment APIs and removes modulo placeholder",()=>{const fs=require("node:fs"),j=fs.readFileSync(require("node:path").join(__dirname,"../public/sound-assessment.js"),"utf8");assert.match(j,/\/api\/sound-assessment\/bank/);assert.match(j,/\/api\/sound-assessment\/result/);assert.doesNotMatch(j,/reduce\(\(a,b\)=>a\+b,0\)%/);assert.doesNotMatch(j,/engine will later|finished engine|technical assessment codes/i);});

test("live client renders real Read more sections from API payload",()=>{const fs=require("node:fs"),j=fs.readFileSync(require("node:path").join(__dirname,"../public/sound-assessment.js"),"utf8");assert.match(j,/sections\(d\.sections\)/);assert.match(j,/soundFoundation/);});

test("public answer validation rejects stale or out-of-range choices",()=>{const {validateAnswers}=require("../src/routes/soundAssessmentRoutes");assert.match(validateAnswers(QUICK_BANK,{SAQ01:999}),/Invalid answer/);assert.match(validateAnswers(QUICK_BANK,{UNKNOWN:0}),/Invalid answer/);assert.equal(validateAnswers(QUICK_BANK,{SAQ01:0}),null);});
test("render path re-enables Next after Quick submission",()=>{const fs=require("node:fs"),j=fs.readFileSync(require("node:path").join(__dirname,"../public/sound-assessment.js"),"utf8");assert.match(j,/function render\(\)\{\$\("#next"\)\.disabled=false/);});

test("production static client targets canonical backend service",()=>{const fs=require("node:fs"),j=fs.readFileSync(require("node:path").join(__dirname,"../public/sound-assessment.js"),"utf8");assert.match(j,/mufasa-fitness-node\.onrender\.com/);assert.match(j,/fetch\(api\("\/api\/sound-assessment\/bank/);assert.match(j,/fetch\(api\("\/api\/sound-assessment\/result/);});
