'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../public/workout-progression-runtime.js'),'utf8');
function harness({plan,search='',saved={},completeSession=async()=>{},initialTime=Date.parse('2026-07-23T12:00:00Z')}={}){let time=initialTime,id=0;const timers=new Map(),logs=[],announcements=[],events=[];const store=new Map(Object.entries(saved));const selection=plan||{programId:'p1',scheduledWorkoutId:'w1',title:'Workout',exercises:[{exerciseId:'a',name:'Squat'}]};store.set('ACTIVE_WORKOUT_SELECTION_V1',JSON.stringify(selection));const window={location:{search},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},document:{getElementById:()=>null},console:{info:(...a)=>logs.push(a),log(){},error(){},warn(){}},setInterval:fn=>{const n=++id;timers.set(n,fn);return n;},clearInterval:n=>timers.delete(n),CustomEvent:class{constructor(type,o){this.type=type;this.detail=o.detail}},dispatchEvent:e=>events.push(e),HudRuntime:{render(){}},SessionWrite:{completeSession}};window.window=window;const context=vm.createContext({window,globalThis:window,URLSearchParams,Date,console:window.console});vm.runInContext(source,context);const runtime=window.WorkoutProgressionRuntime;runtime.configure({now:()=>time,onAnnounce:m=>announcements.push(m)});function advance(ms){time+=ms;for(const fn of [...timers.values()])fn();}return{runtime,window,store,logs,announcements,events,advance,get time(){return time}};}
function start(h){h.runtime.prepareWorkoutStart();h.runtime.startWorkout('session-1');}
const flush=()=>new Promise(resolve=>setImmediate(resolve));

test('starts without camera and defaults duration, sets, and tempo',()=>{const h=harness();start(h);const s=h.runtime.getState(),e=h.runtime.getPlan().exercises[0];assert.equal(s.timerStatus,'running');assert.equal(s.remainingSeconds,30);assert.equal(e.sets,3);assert.equal(e.tempo,'3-1-3');assert.match(e.tempoDescription,/3 seconds movement phase/);});
test('valid configured work duration, set count, and tempo are preserved',()=>{const h=harness({plan:{scheduledWorkoutId:'w',exercises:[{id:'x',name:'X',sets:2,targetTime:42,tempo:'2-1-2'}]}});start(h);assert.equal(h.runtime.getState().remainingSeconds,42);assert.equal(h.runtime.getPlan().exercises[0].sets,2);assert.equal(h.runtime.getState().tempo,'2-1-2');});
test('zero completes exactly one set and starts five-second transition without reps',async()=>{const h=harness();start(h);h.advance(30000);h.advance(1);await flush();let s=h.runtime.getState();assert.deepEqual([...s.completedSets],['0:0']);assert.equal(s.setStatus,'transition');assert.equal(s.transitionRemainingSeconds,5);h.runtime.expireInterval();assert.equal(h.runtime.getState().completedSets.length,1);});
test('transition advances automatically in existing straight-set ordering',async()=>{const h=harness();start(h);h.advance(30000);await flush();h.advance(5000);await flush();const s=h.runtime.getState();assert.equal(s.activeExerciseIndex,0);assert.equal(s.activeSetIndex,1);assert.equal(s.setStatus,'active');assert.equal(s.remainingSeconds,30);});
test('pause freezes work and resume continues remaining time',()=>{const h=harness();start(h);h.advance(7000);assert.equal(h.runtime.getState().remainingSeconds,23);h.runtime.pauseWorkout();h.advance(10000);assert.equal(h.runtime.getState().remainingSeconds,23);h.runtime.resumeWorkout();h.advance(3000);assert.equal(h.runtime.getState().remainingSeconds,20);});
test('pause freezes transition countdown',async()=>{const h=harness();start(h);h.advance(30000);await flush();h.advance(2000);h.runtime.pauseWorkout();assert.equal(h.runtime.getState().remainingSeconds,3);h.advance(9000);assert.equal(h.runtime.getState().remainingSeconds,3);});
test('extensions add deterministically while running and paused without reset',()=>{const h=harness();start(h);h.advance(10000);h.runtime.extendTime();assert.equal(h.runtime.getState().remainingSeconds,35);h.runtime.pauseWorkout();h.runtime.extendTime();h.runtime.extendTime();assert.equal(h.runtime.getState().remainingSeconds,65);assert.equal(h.runtime.getState().extensionSeconds,45);});
test('camera denial is irrelevant to authoritative timer',()=>{const h=harness();start(h);h.window.navigator={mediaDevices:{getUserMedia:async()=>{throw new Error('denied')}}};h.advance(1000);assert.equal(h.runtime.getState().remainingSeconds,29);});
test('duplicate expiry events cannot duplicate transition or set',async()=>{const h=harness();start(h);const a=h.runtime.expireInterval(),b=h.runtime.expireInterval();await Promise.all([a,b]);assert.equal(h.runtime.getState().completedSets.length,1);assert.equal(h.runtime.getState().setStatus,'transition');});
test('refresh restores paused timer exactly',()=>{const h=harness();start(h);h.advance(8000);h.runtime.pauseWorkout();const restored=harness({saved:Object.fromEntries(h.store)});restored.runtime.restore();assert.equal(restored.runtime.getState().timerStatus,'paused');assert.equal(restored.runtime.getState().remainingSeconds,22);});
test('refresh reconstructs running timer and expires once',async()=>{const h=harness();start(h);h.advance(12000);const restored=harness({saved:Object.fromEntries(h.store),initialTime:h.time});restored.runtime.restore();assert.equal(restored.runtime.getState().remainingSeconds,18);restored.advance(18000);await flush();assert.equal(restored.runtime.getState().completedSets.length,1);});
test('final set completes and persists existing session completion once',async()=>{let calls=0;const h=harness({plan:{scheduledWorkoutId:'w',exercises:[{id:'x',name:'X',sets:1}]},completeSession:async()=>{calls++;}});start(h);h.advance(30000);await flush();h.advance(5000);await flush();assert.equal(h.runtime.getState().workoutStatus,'completed');assert.equal(calls,1);assert.equal(h.events.filter(e=>e.type==='workout:completed').length,1);await h.runtime.completeWorkoutSession();assert.equal(calls,1);});
test('skip remains distinct and end workout follows early-ended state',()=>{const h=harness({plan:{scheduledWorkoutId:'w',exercises:[{id:'x',name:'X'},{id:'y',name:'Y'}]}});start(h);h.runtime.skipExercise();assert.deepEqual([...h.runtime.getState().skippedExercises],['x']);assert.equal(h.runtime.getState().completedSets.length,0);h.runtime.endWorkout();assert.equal(h.runtime.getState().workoutStatus,'ended_early');});
test('major accessibility announcements are emitted but not every second',async()=>{const h=harness();start(h);h.advance(20000);h.runtime.pauseWorkout();h.runtime.resumeWorkout();h.advance(10000);await flush();assert.ok(h.announcements.includes('Workout started.'));assert.ok(h.announcements.includes('Ten seconds remaining.'));assert.ok(h.announcements.includes('Workout paused.'));assert.ok(h.announcements.includes('Workout resumed.'));assert.ok(h.announcements.includes('Five-second transition started.'));assert.ok(h.announcements.length<10);});
test('safe diagnostics are opt-in and contain no plan/member payload',()=>{const off=harness();start(off);assert.equal(off.logs.length,0);const on=harness({search:'?debugTimedWorkout=1',plan:{scheduledWorkoutId:'private-workout',title:'Private Name',notes:'health note',exercises:[{id:'x',name:'Private Exercise'}]}});start(on);assert.ok(on.logs.length>0);const output=JSON.stringify(on.logs);assert.doesNotMatch(output,/Private Name|health note|Private Exercise|token|email/i);});
test('browser entry points use the cache-busted timed runtime',()=>{for(const file of ['public/workout.html','index.html']){const html=fs.readFileSync(require.resolve(`../${file}`),'utf8');assert.match(html,/workout-progression-runtime\.js\?v=20260723-timed1/);assert.match(html,/workout-runtime\.js\?v=20260723-timed1/);}});
