"use strict";
const test = require("node:test"), assert = require("node:assert/strict"), fs = require("node:fs"), os = require("node:os"), path = require("node:path");
const { createApp } = require("../server");
const { createAuthTokenLib } = require("../src/lib/authToken");
const { createTrainerWorkspaceStore } = require("../src/repositories/trainerWorkspaceStore");
const SECRET = "phase13-trainer-secret-at-least-32-characters";
const token = (id) => createAuthTokenLib({ secret: SECRET }).issueUserToken({ userId: id, providerVerified: true }).token;
async function setup(t) {
  const old = {}; for (const [key,value] of Object.entries({ NODE_ENV:"test", AUTH_TOKEN_SECRET:SECRET, AUTHZ_ADMIN_USER_IDS:"admin", AUTHZ_TRAINER_USER_IDS:"trainer-a,trainer-b" })) { old[key]=process.env[key]; process.env[key]=value; }
  t.after(()=>{for(const [key,value] of Object.entries(old)) value == null ? delete process.env[key] : process.env[key]=value;});
  const root=fs.mkdtempSync(path.join(os.tmpdir(),"trainer-workspace-")); fs.mkdirSync(path.join(root,"public","exercise-db"),{recursive:true}); fs.writeFileSync(path.join(root,"public","exercise-db","index.json"),"[]");
  fs.mkdirSync(path.join(root,"data","users"),{recursive:true}); for(const [id,name] of [["client-a","Alice Assigned"],["client-b","Bob Private"],["trainer-a","Taylor Trainer"],["trainer-b","Morgan Trainer"]]) fs.writeFileSync(path.join(root,"data","users",`${id}.json`),JSON.stringify({userId:id,profile:{displayName:name,email:`${id}@private.test`},journeyProfile:{pathway:"strength",goals:["move"],submittedAt:"2026-01-01",healthFlags:["PRIVATE_FLAG"]},sessions:{},privateMedicalAnswer:"never-list",trainerNotes:["never-list"]}));
  const server=createApp({rootDir:root}).listen(0); await new Promise(resolve=>server.once("listening",resolve)); t.after(()=>server.close());
  const base=`http://127.0.0.1:${server.address().port}`;
  async function request(method,url,user,body){const response=await fetch(base+url,{method,headers:{...(user?{authorization:`Bearer ${token(user)}`} : {}),...(body?{"content-type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{})}); return {status:response.status,json:await response.json().catch(()=>null)};}
  return {root,request};
}

test("assignment repository lifecycle is idempotent, historical, and reactivatable",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"assignment-store-")),store=createTrainerWorkspaceStore({filePath:path.join(root,"store.json")});const first=store.createAssignment({trainerUserId:"t",clientUserId:"c",assignedByUserId:"a"}),duplicate=store.createAssignment({trainerUserId:"t",clientUserId:"c",assignedByUserId:"a"});assert.equal(first.created,true);assert.equal(duplicate.created,false);assert.equal(first.assignment.id,duplicate.assignment.id);store.deactivateAssignment(first.assignment.id,"a");assert.equal(store.hasActiveAccess("t","c"),false);const second=store.createAssignment({trainerUserId:"t",clientUserId:"c",assignedByUserId:"a"});assert.equal(second.created,true);assert.equal(store.listByTrainer("t").length,2);assert.equal(store.listByClient("c").length,2);assert.equal(store.getAssignment(first.assignment.id).deactivatedByUserId,"a");});

test("admin assignment and assigned-client authorization enforce isolation",async t=>{const {request}=await setup(t);assert.equal((await request("POST","/api/admin/trainer-assignments","admin",{trainerUserId:"trainer-a",clientUserId:"client-a"})).status,201);assert.equal((await request("POST","/api/admin/trainer-assignments","admin",{trainerUserId:"trainer-a",clientUserId:"client-a"})).status,200);assert.equal((await request("POST","/api/admin/trainer-assignments","admin",{trainerUserId:"client-a",clientUserId:"client-b"})).status,422);assert.equal((await request("POST","/api/admin/trainer-assignments","admin",{trainerUserId:"trainer-a",clientUserId:"missing"})).status,422);assert.equal((await request("POST","/api/admin/trainer-assignments","admin",{trainerUserId:"trainer-a",clientUserId:"trainer-a"})).status,422);
  const list=await request("GET","/api/trainer/clients","trainer-a");assert.equal(list.status,200);assert.deepEqual(list.json.data.clients.map(c=>c.userId),["client-a"]);assert.equal(JSON.stringify(list.json).includes("PRIVATE_FLAG"),false);assert.equal(JSON.stringify(list.json).includes("privateMedicalAnswer"),false);assert.equal((await request("GET","/api/trainer/clients/client-b","trainer-a")).status,403);assert.equal((await request("GET","/api/trainer/clients/client-a","trainer-b")).status,403);assert.equal((await request("GET","/api/trainer/clients/client-a","client-a")).status,403);assert.equal((await request("GET","/api/trainer/clients/client-a",null)).status,401);
  const assignment=(await request("GET","/api/admin/trainer-assignments","admin")).json.data.assignments[0];assert.equal((await request("DELETE",`/api/admin/trainer-assignments/${assignment.id}`,"admin")).status,200);assert.equal((await request("GET","/api/trainer/clients/client-a","trainer-a")).status,403);assert.equal((await request("GET","/api/admin/trainer-assignments","trainer-a")).status,403);});

test("client overview, programs, notes, filtering, safe text, and history",async t=>{const {request}=await setup(t);await request("POST","/api/admin/trainer-assignments","admin",{trainerUserId:"trainer-a",clientUserId:"client-a"});const detail=await request("GET","/api/trainer/clients/client-a","trainer-a");assert.equal(detail.status,200);assert.equal(detail.json.data.journey.pathway,"strength");assert.equal(detail.json.data.health.reviewRequired,false);assert.ok(detail.json.data.training);assert.ok(detail.json.data.nutrition);assert.ok(detail.json.data.assessments);assert.deepEqual((await request("GET","/api/trainer/clients?search=Bob","trainer-a")).json.data.clients,[]);
  assert.equal((await request("PUT","/api/trainer/clients/client-a/program","trainer-a",{programId:"p1",title:"Foundation"})).status,200);assert.equal((await request("PUT","/api/trainer/clients/client-a/program","trainer-a",{programId:"p2",title:"Progression"})).status,200);const programs=await request("GET","/api/trainer/clients/client-a/program","trainer-a");assert.equal(programs.json.data.active.programId,"p2");assert.equal(programs.json.data.history.length,2);assert.equal(programs.json.data.history[0].status,"inactive");
  const dangerous='<img src=x onerror="alert(1)">';assert.equal((await request("POST","/api/trainer/clients/client-a/notes","trainer-a",{body:dangerous})).status,201);const notes=await request("GET","/api/trainer/clients/client-a/notes","trainer-a");assert.equal(notes.json.data.notes[0].body,dangerous);assert.equal((await request("GET","/api/trainer/clients/client-a/notes","trainer-b")).status,403);assert.equal((await request("POST","/api/trainer/clients/client-a/notes","trainer-a",{body:"x".repeat(4001)})).status,422);assert.equal((await request("PUT","/api/trainer/clients/client-b/program","trainer-a",{programId:"x",title:"x"})).status,403);});

test("admin directory validates, authorizes, orders, paginates, and redacts results",async t=>{const {request}=await setup(t);
  assert.equal((await request("GET","/api/admin/trainer-directory?type=trainer&q=tr","admin")).status,200);
  for(const user of [null,"client-a","trainer-a"]) assert.equal((await request("GET","/api/admin/trainer-directory?type=trainer&q=tr",user)).status,user?403:401);
  for(const query of ["q=x&type=member","q="+"x".repeat(81)+"&type=member","q=alice&type=unknown","q=alice&type=member&limit=0","q=alice&type=member&limit=21","q=alice&type=member&cursor=-1"]) assert.equal((await request("GET",`/api/admin/trainer-directory?${query}`,"admin")).status,422);
  const trainers=(await request("GET","/api/admin/trainer-directory?type=trainer&q=trainer&limit=1","admin")).json.data;
  assert.deepEqual(Object.keys(trainers.results[0]).sort(),["accountStatus","assignmentStatus","displayName","roleType","userId"]); assert.equal(trainers.results[0].displayName,"Morgan Trainer"); assert.equal(trainers.nextCursor,"1");
  const next=(await request("GET",`/api/admin/trainer-directory?type=trainer&q=trainer&limit=1&cursor=${trainers.nextCursor}`,"admin")).json.data; assert.equal(next.results[0].displayName,"Taylor Trainer");
  const member=(await request("GET","/api/admin/trainer-directory?type=member&q=%20%20Alice%20%20Assigned%20%20","admin")).json.data.results[0]; assert.equal(member.userId,"client-a");
  const serialized=JSON.stringify(member); for(const forbidden of ["email","journey","health","note","PRIVATE_FLAG","never-list","permissions"]) assert.equal(serialized.toLowerCase().includes(forbidden.toLowerCase()),false);
  assert.deepEqual((await request("GET","/api/admin/trainer-directory?type=member&q=Nobody","admin")).json.data.results,[]);
});

test("admin directory is independently rate limited",async t=>{const {request}=await setup(t);let result;for(let index=0;index<31;index+=1) result=await request("GET","/api/admin/trainer-directory?type=member&q=alice","admin");assert.equal(result.status,429);assert.equal(result.json.error.code,"RATE_LIMITED");});

test("admin assignment page exposes accessible autocomplete and stale-result protections",()=>{const html=fs.readFileSync(path.join(__dirname,"..","public","admin-trainer-assignments.html"),"utf8"),script=fs.readFileSync(path.join(__dirname,"..","public","admin-trainer-assignments.js"),"utf8");for(const contract of ['role="combobox"','role="listbox"','aria-live="polite"','Selected pair']) assert.ok(html.includes(contract));for(const contract of ["setTimeout(search, 300)","controller?.abort()","current !== requestNumber",'event.key === "ArrowDown"','event.key === "Escape"',"submitting ||"]) assert.ok(script.includes(contract));assert.equal(script.includes("innerHTML"),false);});
