'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const html=fs.readFileSync(require.resolve('../public/workout.html'),'utf8');
const hudSource=fs.readFileSync(require.resolve('../public/hud-runtime.js'),'utf8');
function element(){return{textContent:'',hidden:false,dataset:{},style:{},attrs:{},classList:{toggle(){}},setAttribute(k,v){this.attrs[k]=v},addEventListener(type,fn){this[type]=fn},focus(){}}}
function hudHarness(search=''){const ids=['workoutHud','hudExerciseName','hudSet','hudReps','hudTempo','hudRest','hudTimer','hudTimerState','hudNextExercise','hudCoachCue','workoutDetailsBtn','closeWorkoutDetailsBtn','workoutDetailsPanel','workoutDebugDetails'];const els=Object.fromEntries(ids.map(id=>[id,element()]));els.workoutDetailsPanel.hidden=true;const window={location:{search},document:{getElementById:id=>els[id]||null},console:{log(){},info(){},error(){}},performance:{now:()=>0},URLSearchParams};window.window=window;vm.runInContext(hudSource,vm.createContext({window,globalThis:window,URLSearchParams,Date}));return{runtime:window.HudRuntime,els};}
function renderPhase(phase,timerStatus,seconds=18){const h=hudHarness();h.runtime.render({activeWorkoutPlan:{exercises:[{sets:3,formCues:['Brace.']}]},activeWorkoutState:{currentExercise:'A very long exercise name that safely wraps',activeSetIndex:0,setStatus:phase,timerStatus,remainingSeconds:seconds,repCount:7,targetReps:10,tempo:'3-1-3',nextExercise:'Lunge'}});return h;}
test('large timer renders distinct preparing, running, paused, transition and completed states',()=>{for(const [phase,status,label] of [['preparing','running','Get ready'],['active','running','Running'],['active','paused','Paused'],['transition','running','Transition'],['completed','completed','Completed']]){const h=renderPhase(phase,status);assert.equal(h.els.hudTimer.textContent,'00:18');assert.equal(h.els.hudTimerState.textContent,label);}});
test('rep count is details-only and Details defaults closed without timer mutation',()=>{const h=renderPhase('active','running');assert.equal(h.els.workoutDetailsPanel.hidden,true);assert.match(html,/workoutDetailsPanel[^>]+hidden/);const primary=html.match(/<div class="focus-heading"[^]*?<div id="workoutDetailsPanel"/)[0];assert.doesNotMatch(primary,/hudReps/);const before=h.els.hudTimer.textContent;h.els.workoutDetailsBtn.click();assert.equal(h.els.workoutDetailsPanel.hidden,false);assert.equal(h.els.hudReps.textContent,'7 / 10');h.els.closeWorkoutDetailsBtn.click();assert.equal(h.els.workoutDetailsPanel.hidden,true);assert.equal(h.els.hudTimer.textContent,before);});
test('Focus Mode exposes one authoritative End Workout and one expanded camera exit',()=>{assert.equal((html.match(/id="endWorkoutBtn"/g)||[]).length,1);assert.equal((html.match(/id="exitCameraBtn"/g)||[]).length,1);assert.match(html,/workout-focus #stopWorkoutFsBtn[^}]+display:\s*none/);assert.match(html,/workout-focus #cameraMobileControls[^}]+display:\s*none/);});
test('mobile contract has safe areas, 320-430 support, wrapping and 44px targets',()=>{assert.match(html,/safe-area-inset-bottom/);assert.match(html,/max-width:430px/);assert.match(html,/min-height:44px/);assert.match(html,/overflow-wrap:anywhere/);assert.match(html,/overflow-x:\s*hidden/);});
test('focus overlay excludes render, tracking, score and diagnostics while preserving Details fields',()=>{const focus=html.match(/<div id="workoutHud"[^]*?<div id="cameraFsActions"/)[0];const overlay=focus.split('<div id="workoutDetailsPanel"')[0];assert.doesNotMatch(overlay,/Render mode|Score:|raw pose|diagnostic/i);assert.match(focus,/Detected reps:|Tempo:|Next:/);assert.match(html,/workoutDebugDetails[^>]+hidden/);});
test('focus diagnostics are opt-in and use safe operational labels',()=>{const combined=fs.readFileSync(require.resolve('../public/workout-runtime.js'),'utf8')+hudSource+fs.readFileSync(require.resolve('../public/workout-progression-runtime.js'),'utf8');assert.match(combined,/debugWorkoutFocus/);for(const label of ['focus mode entered','preparation countdown started','preparation countdown completed','begin cue emitted','work timer started','details opened','details closed','expanded view entered','expanded view exited','duplicate control suppressed','focus state restored'])assert.ok(combined.includes(label),label);assert.doesNotMatch(combined,/console\.info\([^\n]*(email|camera frame|pose coordinates|intake)/i);});
test('all browser entry points use focus-mode asset version',()=>{for(const file of ['../public/workout.html','../index.html']){const body=fs.readFileSync(require.resolve(file),'utf8');for(const asset of ['hud-runtime.js','workout-progression-runtime.js','workout-runtime.js','runtime-orchestrator.js'])assert.ok(body.includes(`${asset}?v=20260724-focus1`),`${file}:${asset}`);}});
test('reduced motion, visible equivalents, and assertive major announcements are present',()=>{assert.match(html,/prefers-reduced-motion:reduce/);assert.match(html,/timedWorkoutAnnouncements[^>]+aria-live="assertive"/);assert.match(html,/role="timer"/);assert.match(html,/aria-expanded="false"/);});
