'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../public/workout-form-runtime.js'),'utf8');
function runtime(){const events={};const w={window:null,location:{search:''},console,setTimeout,addEventListener:(n,f)=>events[n]=f};w.window=w;w.globalThis=w;vm.runInContext(source,vm.createContext({window:w,globalThis:w,URLSearchParams,console,setTimeout}));return w.WorkoutFormRuntime;}
function pose(deviation=false,score=.95){const pts=[];for(const side of ['left','right']){pts.push({name:`${side}_shoulder`,x:0,y:0,score},{name:`${side}_hip`,x:1,y:deviation?1:0,score},{name:`${side}_ankle`,x:2,y:0,score});}return {keypoints:pts};}
test('measurement utilities handle expected, mirrored, missing, and invalid geometry',()=>{const m=runtime().measurements;assert.equal(m.angle({x:1,y:0},{x:0,y:0},{x:0,y:1}),90);assert.equal(m.alignmentDeviation({x:0,y:0},{x:1,y:0},{x:2,y:0}),0);assert.equal(m.angle({x:0,y:0},{x:0,y:0},{x:1,y:1}),null);assert.equal(m.angle(null,{},{}),null);assert.equal(m.bestVisibleSide(pose(),['shoulder','hip','ankle'],.75).side,'left');assert.equal(m.bestVisibleSide(pose(),['shoulder','hip','ankle'],.75,{mirrored:true}).side,'right')});
test('disabled, unavailable, unknown and draft profiles are safely gated',async()=>{for(const [opts,status] of [[{enabled:false},'disabled'],[{cameraActive:false},'camera_unavailable'],[{poseAvailable:false},'pose_unavailable']]){const r=runtime();r.startSet({id:'push_up'},0,{enabled:true,cameraActive:true,poseAvailable:true,...opts});assert.equal((await r.finishSet()).analysisStatus,status)}const r=runtime();r.startSet({id:'unknown'},0,{enabled:true,cameraActive:true,poseAvailable:true});assert.equal((await r.finishSet()).analysisStatus,'unsupported_exercise');r.startSet({id:'push_up'},0,{enabled:true,cameraActive:true,poseAvailable:true});assert.equal((await r.finishSet()).suppressedReason,'profile_not_approved')});
test('approved analysis is deterministic, bounded, confidence-aware, and clears samples',async()=>{const r=runtime(),p=r.profiles.push_up;p.approval.status='approved';r.startSet({id:'push_up'},0,{enabled:true,cameraActive:true,poseAvailable:true,startedAt:0});for(let i=0;i<130;i++)r.observe(pose(true),i*125);assert.equal(r.getContext().samples.length,r.constants.MAX_SAMPLES);const result=await r.finishSet();assert.equal(result.analysisStatus,'completed');assert.equal(result.observations.length,1);assert.equal(result.primaryFeedback.status,'needs_attention');assert.equal(r.getContext(),null);p.approval.status='draft'});
test('one abnormal frame and low confidence do not make corrective claims',()=>{const r=runtime(),p=r.profiles.push_up;p.approval.status='approved';r.startSet({id:'push_up'},0,{enabled:true,cameraActive:true,poseAvailable:true,startedAt:0});r.observe(pose(true),0);for(let i=1;i<10;i++)r.observe(pose(false),i*125);assert.notEqual(r.analyze().primaryFeedback.status,'needs_attention');r.cancel();r.startSet({id:'push_up'},0,{enabled:true,cameraActive:true,poseAvailable:true,startedAt:0});assert.equal(r.observe(pose(true,.2),0),false);assert.equal(r.analyze().analysisStatus,'insufficient_data');p.approval.status='draft'});
test('raw frames and landmark arrays are never retained in observations',()=>{const r=runtime(),input=pose();input.frame={private:true};r.profiles.push_up.approval.status='approved';r.startSet({id:'push_up'},0,{enabled:true,cameraActive:true,poseAvailable:true,startedAt:0});r.observe(input,0);const stored=r.getContext().samples[0];assert.equal('frame' in stored,false);assert.equal('keypoints' in stored,false);r.profiles.push_up.approval.status='draft'});
