'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const workoutSource=fs.readFileSync(require.resolve('../public/workout-runtime.js'),'utf8');
const coachSource=fs.readFileSync(require.resolve('../public/coach-runtime.js'),'utf8');
const poseSource=fs.readFileSync(require.resolve('../public/pose-runtime.js'),'utf8');
function classes(){const values=new Set();return{toggle(n,on){on?values.add(n):values.delete(n)},remove(n){values.delete(n)},add(n){values.add(n)},contains:n=>values.has(n)}}
function workoutHarness(){const root={dataset:{},classList:classes()};const body={classList:classes()};const elements={appShell:root,hudFormStatus:{textContent:''}};const w={location:{search:''},document:{body,readyState:'complete',getElementById:id=>elements[id]||null},console,URLSearchParams,Date,setTimeout,clearTimeout};w.window=w;w.globalThis=w;vm.runInNewContext(workoutSource,w);return{w,root,body};}
test('Focus Mode state is applied to actual appShell root and is idempotent',()=>{const h=workoutHarness();h.w.WorkoutRuntime.setWorkoutFocusMode(true,'test');assert.equal(h.root.dataset.workoutFocus,'active');assert.equal(h.root.classList.contains('workout-focus'),true);assert.equal(h.body.classList.contains('workout-focus'),true);vm.runInNewContext(workoutSource,h.w);assert.ok(h.w.WorkoutRuntime);});
test('voice initializes off and makes no backend request until explicitly enabled',()=>{let fetches=0;const w={location:{search:''},document:{getElementById:()=>null,createElement:()=>({appendChild(){},pause(){}}),body:{appendChild(){}}},fetch:async()=>{fetches++;throw Error('should not run')},console,URLSearchParams,setTimeout,clearTimeout};w.window=w;w.globalThis=w;vm.runInNewContext(coachSource,w);w.CoachRuntime.configure();assert.equal(w.CoachRuntime.getState().muted,true);return w.CoachRuntime.speak('Get ready').then(result=>{assert.equal(result.reason,'muted');assert.equal(fetches,0)});});
test('pose loop is single-instance and skips inference while document is hidden',async()=>{let inference=0;let pending=[];const w={location:{search:''},document:{hidden:true,getElementById:()=>null},console,URLSearchParams,Date,CustomEvent:function(){},requestAnimationFrame:fn=>{pending.push(fn);return pending.length},cancelAnimationFrame(){},dispatchEvent(){}};w.window=w;w.globalThis=w;vm.runInNewContext(poseSource,w);const options={detector:{estimatePoses:async()=>{inference++;return[]}},video:{},isRunning:()=>true};const a=w.PoseRuntime.startPoseLoop(options),b=w.PoseRuntime.startPoseLoop(options);assert.equal(a,b);await pending.shift()();assert.equal(inference,0);a.stop();});
test('production and alternate workout shells share corrected cache versions and performance marker loader',()=>{for(const file of ['../public/workout.html','../index.html']){const source=fs.readFileSync(require.resolve(file),'utf8');for(const asset of ['workout-performance-runtime.js','pose-runtime.js','coach-runtime.js','hud-runtime.js','workout-progression-runtime.js','workout-runtime.js','runtime-orchestrator.js'])assert.match(source,new RegExp(asset.replace('.','\\.')+'\\?v=20260724-focus2'));}});
test('active root CSS hides legacy diagnostics and gives camera the workout viewport',()=>{const source=fs.readFileSync(require.resolve('../public/workout.html'),'utf8');for(const id of ['repCount','poseStatus','brainStatus','trackingModeStatus','avatarModeStatus','coach-log','stopWorkoutFsBtn'])assert.match(source,new RegExp(`data-workout-focus="active"[^}]+#${id}`));assert.match(source,/min-height:calc\(100dvh/);});
