"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
function el(id){return{id,textContent:"",dataset:{},style:{},classList:{values:new Set(["hidden"]),remove(v){this.values.delete(v)},toggle(){}},removeAttribute(){},setAttribute(){},getBoundingClientRect:()=>({width:1})};}
function harness(getUserMedia,play=async()=>{}){const ids=["connectBtn","startBtn","fullscreenCameraBtn","video","poseStatus","workoutHud","brainStatus","featureActivationStatus"],elements=Object.fromEntries(ids.map(id=>[id,el(id)]));elements.video.play=play;const window={document:{getElementById:id=>elements[id]||null,body:{classList:{toggle(){},remove(){}}}},navigator:{mediaDevices:{getUserMedia}},isSecureContext:true,location:{search:""},addEventListener(){},dispatchEvent(){},console,URLSearchParams,setTimeout,clearTimeout};window.window=window;vm.runInNewContext(fs.readFileSync(path.join(__dirname,"../public/workout-runtime.js"),"utf8"),{window,globalThis:window,console,URLSearchParams,CustomEvent:function(){},Event:function(){}});window.WorkoutRuntime.configureWorkoutRuntime({afterConnectCamera:async()=>{throw new Error("detector failed")}});return{window,elements};}
test("double taps share one request and detector failure preserves self-view",async()=>{let calls=0,release;const stream={getTracks:()=>[{stop(){}}]},pending=new Promise(r=>release=()=>r(stream)),h=harness(()=>{calls++;return pending});const a=h.window.WorkoutRuntime.connectCamera(),b=h.window.WorkoutRuntime.connectCamera();release();assert.equal(await a,stream);assert.equal(await b,stream);assert.equal(calls,1);assert.equal(h.elements.video.srcObject,stream);});
test("camera permission, busy, and playback failures are visible",async()=>{for(const [name,pattern] of [["NotAllowedError",/denied/i],["NotReadableError",/already in use/i]]){const h=harness(async()=>{throw Object.assign(new Error(name),{name})});await assert.rejects(h.window.WorkoutRuntime.connectCamera());assert.match(h.elements.poseStatus.textContent,pattern);}const p=harness(async()=>({getTracks:()=>[{stop(){}}]}),async()=>{throw new Error("play")});await assert.rejects(p.window.WorkoutRuntime.connectCamera());assert.match(p.elements.poseStatus.textContent,/playback failed/i);});
test("early camera and avatar controls remain actionable",()=>{const elements={connectBtn:el("connectBtn"),avatarCreateBtn:el("avatarCreateBtn"),avatarModal:el("avatarModal"),avatarCreationStatus:el("avatarCreationStatus"),poseStatus:el("poseStatus")};let calls=0;const window={document:{readyState:"complete",getElementById:id=>elements[id]||null},WorkoutRuntime:{connectCamera:()=>calls++}};window.window=window;vm.runInNewContext(fs.readFileSync(path.join(__dirname,"../public/workout-control-activation.js"),"utf8"),{window});elements.connectBtn.onclick();elements.avatarCreateBtn.onclick();assert.equal(calls,1);assert.equal(elements.avatarModal.classList.values.has("hidden"),false);assert.equal(elements.avatarCreationStatus.textContent,"Idle.");});
test("Camera render mode is presentation-only and no second controller exists",()=>{const html=fs.readFileSync(path.join(__dirname,"../public/workout.html"),"utf8"),body=html.slice(html.indexOf("function applyRenderModeSelection"),html.indexOf("function applyLiveAvatarRenderPresentation"));assert.doesNotMatch(body,/connectCamera|getUserMedia/);assert.doesNotMatch(html,/new\s+.*CameraController/);});
test("authenticated opaque member avatar URLs are accepted by the GLB mount path",()=>{const html=fs.readFileSync(path.join(__dirname,"../public/workout.html"),"utf8");assert.match(html,/protectedMemberAvatar = \/\\\/api\\\/me\\\/avatar\\\/assets/);assert.match(html,/loader\.parse\(/);assert.match(html,/authorization: `Bearer \$\{authToken\}`/);});
