"use strict";const test=require("node:test"),assert=require("node:assert/strict"),fs=require("fs"),os=require("os"),path=require("path");const {createUserStore}=require("../src/repositories/userStore");const {createYogaService}=require("../src/services/yogaService");const poses=require("../data/yoga/poses.v1.json").poses,sessions=require("../data/yoga/sessions.v1.json").sessions;
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"yoga-")),store=createUserStore({userDir:dir});store.ensureDirs();return {store,service:createYogaService({userStore:store,poses,sessions,clock:()=>20000})}}
const input={sessionId:"balance-foundations",startedAt:10000,detectorVersion:"movenet-v1",poseResults:["mountain","tree","warrior-ii"].map(poseId=>({poseId,score:88,holdDurationMs:12000,confidenceBand:"high",faultIds:poseId==="tree"?["tree-leftKnee-alignment"]:[],cuesShown:poseId==="tree"?["Use support."]:[]}))};
test("resolves Beginner Full-Body Flow into its ordered pose instructions",()=>{const {service}=setup(),detail=service.sessionDetail("beginner-flow");assert.equal(detail.id,"beginner-flow");assert.equal(detail.steps.length,6);assert.deepEqual(detail.steps.map(step=>step.position),[1,2,3,4,5,6]);assert.deepEqual(detail.steps.map(step=>step.poseId),["mountain","chair","warrior-ii","downward-dog","cobra","bridge"]);assert.equal(detail.steps[0].name,"Mountain Pose");assert.match(detail.steps[0].description,/steady breathing/i);assert.equal(detail.steps[0].holdSeconds,30);assert.equal(detail.steps[0].media,null)});
test("rejects missing sessions and incomplete or reordered completion evidence",()=>{const {service}=setup();assert.throws(()=>service.sessionDetail("missing"),error=>error.status===404);assert.throws(()=>service.complete("member-a",{...input,poseResults:input.poseResults.slice(0,2)}),error=>error.code==="INCOMPLETE_YOGA_SESSION");assert.throws(()=>service.complete("member-a",{...input,poseResults:input.poseResults.slice().reverse()}),error=>error.code==="INCOMPLETE_YOGA_SESSION")});
test("persists bounded derived result only after validation",()=>{const {store,service}=setup(),r=service.complete("member-a",input);assert.equal(r.summary.averageScore,88);const raw=JSON.stringify(store.loadUser("member-a"));assert.doesNotMatch(raw,/video|landmarks|frameData/);assert.equal(service.history("member-a").length,1)});
test("member history is isolated",()=>{const {service}=setup();service.complete("member-a",input);assert.equal(service.history("member-b").length,0)});
test("emits authoritative event after commit",()=>{const {store}=setup();let observed;const service=createYogaService({userStore:store,poses,sessions,eventService:{recordYogaSessionCompleted(f){observed={f,committed:store.loadUser(f.userId).yogaSessions.length}}},clock:()=>20000});service.complete("member-a",input);assert.equal(observed.committed,1)});
test("progression requires session-level evidence",()=>{const {service}=setup();const r=service.complete("member-a",input);assert.equal(r.progression.status,"consistency_required");assert.equal(r.progression.requiredCompletions,3)});
test("idempotent completion persists and emits exactly once",()=>{const {store}=setup();let events=0;const service=createYogaService({userStore:store,poses,sessions,eventService:{recordYogaSessionCompleted(){events++}},clock:()=>20000}),request={...input,idempotencyKey:"launch-yoga-one"};const first=service.complete("member-a",request),retry=service.complete("member-a",request);assert.equal(retry.recordId,first.recordId);assert.equal(service.history("member-a").length,1);assert.equal(events,1)});
