"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {createApp}=require("../server"),{createAuthTokenLib}=require("../src/lib/authToken");
const ROOT=path.join(__dirname,"..");
const source=()=>fs.readFileSync(path.join(ROOT,"public/yoga.js"),"utf8");
test("Yoga library starts a detail request through canonical authenticated runtimes",()=>{const js=source();assert.match(js,/AuthStateRuntime\.whenReady\(\)/);assert.match(js,/MaatApiClient\.request/);assert.match(js,/data-start/);assert.match(js,/\/api\/yoga\/sessions\/\$\{encodeURIComponent\(sessionId\)\}/);assert.doesNotMatch(js,/localStorage|getItem\(|fetch\(/)});
test("Yoga detail renders ordered content and only completes at the final step",()=>{const js=source();assert.match(js,/active\.steps\[index\]/);assert.match(js,/Pose \$\{index\+1\} of \$\{active\.steps\.length\}/);assert.match(js,/step\.description/);assert.match(js,/step\.holdSeconds/);assert.match(js,/media\?\.url/);assert.match(js,/data-next/);assert.match(js,/last\?'<button class="button primary" data-complete>/);assert.match(js,/\/api\/yoga\/sessions\/complete/)});
test("Yoga completion history is loaded from the API and drives persisted completed state",()=>{const js=source();assert.match(js,/request\("\/api\/yoga\/history"\)/);assert.match(js,/history\.map\(item=>item\.sessionId\)/);assert.match(js,/mufasa:gamification-refresh/)});
test("Yoga detail API protects access and returns Beginner Full-Body Flow by encoded identifier",async t=>{const previous=process.env.NODE_ENV;process.env.NODE_ENV="test";t.after(()=>previous==null?delete process.env.NODE_ENV:process.env.NODE_ENV=previous);const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),"yoga-detail-api-")),server=createApp({dataDir}).listen(0);await new Promise(resolve=>server.once("listening",resolve));t.after(()=>server.close());const url=`http://127.0.0.1:${server.address().port}/api/yoga/sessions/${encodeURIComponent("beginner-flow")}`;assert.equal((await fetch(url)).status,401);const token=createAuthTokenLib({secret:process.env.AUTH_TOKEN_SECRET||"dev-only-secret-change-me"}).issueUserToken({userId:"yoga-member"}).token,response=await fetch(url,{headers:{authorization:`Bearer ${token}`}}),payload=await response.json();assert.equal(response.status,200);assert.equal(payload.data.id,"beginner-flow");assert.deepEqual(payload.data.steps.map(step=>step.poseId),["mountain","chair","warrior-ii","downward-dog","cobra","bridge"]);assert.match(payload.data.steps[0].description,/steady breathing/i)});
