'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { createYouthProgramRepository } = require('../src/youth-fitness/runtime/repository');
const { createYouthProgramService } = require('../src/youth-fitness/runtime/service');
const { createLeaderWithinBridgeRepository, createLeaderWithinPocketPtBridge, projectMovementMission, calculateMissionProgress } = require('../src/youth-fitness/integration');

const CLOCK = '2026-08-17T12:00:00.000Z';
function fixture() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'lw-pocketpt-'));
  const youthRepository = createYouthProgramRepository({ filePath: path.join(dir, 'runtime.json') });
  const youth = createYouthProgramService({ repository: youthRepository, clock: () => CLOCK });
  const repository = createLeaderWithinBridgeRepository({ filePath: path.join(dir, 'bridge.json') });
  const bridge = createLeaderWithinPocketPtBridge({ repository, youthProgramService: youth, clock: () => CLOCK });
  const admin = { subject: 'admin', role: 'INTEGRATION_ADMIN', organization_id: 'org-a' };
  const participant = { subject: 'youth-a', role: 'PARTICIPANT', organization_id: 'org-a' };
  const facilitator = { subject: 'facilitator', role: 'LEADER_WITHIN_FACILITATOR', organization_id: 'org-a', permissions: ['LEADER_WITHIN_PARTICIPANT_READ', 'LEADER_WITHIN_MOVEMENT_ASSIGN'] };
  const input = { organization_id: 'org-a', leader_within_participant_id: 'lwp-a', leader_within_enrollment_id: 'enroll-a', leader_id: 'LW-000001', pocketpt_subject: 'youth-a' };
  return { dir, youthRepository, youth, repository, bridge, admin, participant, facilitator, input };
}
function connected(withProgram = true) { const value = fixture(); if (withProgram) value.youth.enrollment('youth-a'); value.mapping = value.bridge.connect(value.admin, value.input); return value; }
function assigned() { const value = connected(); value.assignment = value.bridge.assign(value.facilitator, { leader_within_enrollment_id: 'enroll-a', mission_id: 'mission-a' }); return value; }

test('creates one durable, organization-scoped canonical identity mapping without equating subsystem IDs', () => { const value = connected(); const again = value.bridge.connect(value.admin, value.input); assert.deepEqual(again, value.mapping); assert.notEqual(value.mapping.leader_within_participant_id, value.mapping.pocketpt_participant_id); assert.equal(Object.keys(value.repository.snapshot().mappings).length, 1); });
test('cross-participant and cross-organization bridge reads fail closed', () => { const value = assigned(); assert.throws(() => value.bridge.projection({ subject: 'youth-b', role: 'PARTICIPANT', organization_id: 'org-a' }, { leader_within_enrollment_id: 'enroll-a', mission_id: 'mission-a' }), /bridge_access_denied/); assert.throws(() => value.bridge.projection({ subject: 'youth-a', role: 'PARTICIPANT', organization_id: 'org-b' }, { leader_within_enrollment_id: 'enroll-a', mission_id: 'mission-a' }), /bridge_access_denied/); });
test('program-first assignment links the current planned program slot and never creates an orphan workout', () => { const value = assigned(); const dashboard = value.youth.dashboard('youth-a'); assert.equal(value.assignment.fitness_program_id, dashboard.program_ref); assert.equal(value.assignment.fitness_session_ref, dashboard.today.session_ref); assert.equal(value.youth.view('youth-a', value.assignment.fitness_session_ref).program_id, dashboard.program_ref); });
test('connected participant without a program gets a bounded state and no silent program creation', () => { const value = connected(false); assert.equal(value.bridge.assign(value.facilitator, { leader_within_enrollment_id: 'enroll-a', mission_id: 'm' }), null); const result = value.bridge.projection(value.participant, { leader_within_enrollment_id: 'enroll-a', mission_id: 'm' }); assert.equal(result.connection_status, 'CONNECTED_NO_PROFILE'); assert.equal(value.youthRepository.getProgram('youth-a'), null); });
test('LOCAL movement projection remains unchanged', () => { const local = { status: 'COMPLETED', label: 'Walk outside' }; assert.equal(projectMovementMission({ movement_source: 'LOCAL', local_mission: local }), local); });
test('assignment is explicit, stable, and an unrelated completed session cannot credit it', () => { const value = assigned(); const aggregate = value.youthRepository.getProgram('youth-a'); const otherSlot = aggregate.program.weeks[0].session_slots[1]; const otherRef = value.youth.dashboard('youth-a').week.sessions.find((item) => item.code === otherSlot.session_code).session_ref; value.youth.start('youth-a', otherRef); let other = value.youth.readiness('youth-a', otherRef, { energy: 4, soreness: 'NONE', sleep_quality: 'GOOD', pain: false }); const activity = other.blueprint.blocks.flatMap((block) => block.activities)[0]; value.youth.recordActivity('youth-a', otherRef, activity.activity_id, { completed: true }); value.youth.finish('youth-a', otherRef); assert.equal(value.bridge.projection(value.participant, { leader_within_enrollment_id: 'enroll-a', mission_id: 'mission-a' }).movement_mission.status, 'NOT_STARTED'); });
test('launch is credential-free and does not equal completion', () => { const value = assigned(); const result = value.bridge.projection(value.participant, { leader_within_enrollment_id: 'enroll-a', mission_id: 'mission-a' }); assert.equal(result.movement_mission.launch_url, '/pocketpt/my-program'); assert.equal(result.movement_mission.status, 'NOT_STARTED'); assert.doesNotMatch(result.movement_mission.launch_url, /token|csrf|participant|session|=/i); assert.equal(value.repository.snapshot().credits[value.assignment.assignment_id], undefined); });
test('readiness-incomplete projection is allowlisted and never exposes a stored executable blueprint', () => { const value = assigned(); const stored = value.youthRepository.getSession('youth-a', value.assignment.fitness_session_ref); assert.ok(stored.blueprint); assert.equal(value.youth.view('youth-a', value.assignment.fitness_session_ref).blueprint, null); const projected = value.bridge.projection(value.participant, { leader_within_enrollment_id: 'enroll-a', mission_id: 'mission-a' }); assert.deepEqual(Object.keys(projected).sort(), ['connection_status', 'contract_name', 'contract_version', 'movement_mission', 'participant']); assert.deepEqual(Object.keys(projected.movement_mission).sort(), ['completed_at', 'display_name', 'launch_available', 'launch_url', 'required', 'status']); assert.doesNotMatch(JSON.stringify(projected), /blueprint|readiness|pain|sleep|soreness|token|private/i); });
test('pain produces a bounded safety hold, withholds blueprint, and does not credit MOVE', () => { const value = assigned(); value.youth.readiness('youth-a', value.assignment.fitness_session_ref, { energy: 3, soreness: 'NONE', sleep_quality: 'GOOD', pain: true }); const projected = value.bridge.projection(value.participant, { leader_within_enrollment_id: 'enroll-a', mission_id: 'mission-a' }); assert.equal(projected.connection_status, 'SAFETY_HOLD'); assert.equal(projected.movement_mission.status, 'SAFETY_HOLD'); assert.equal(projected.movement_mission.launch_available, false); assert.equal(value.youth.view('youth-a', value.assignment.fitness_session_ref).blueprint, null); assert.equal(value.repository.getCredit(value.assignment.assignment_id), null); assert.doesNotMatch(JSON.stringify(projected), /pain|readiness|soreness|sleep|reason/i); });
test('valid exact-session completion creates one durable idempotent movement credit', () => { const value = assigned(); let session = value.youth.readiness('youth-a', value.assignment.fitness_session_ref, { energy: 4, soreness: 'NONE', sleep_quality: 'GOOD', pain: false }); const activity = session.blueprint.blocks.flatMap((block) => block.activities)[0]; value.youth.recordActivity('youth-a', session.session_ref, activity.activity_id, { completed: true }); value.youth.finish('youth-a', session.session_ref); const first = value.bridge.projection(value.participant, { leader_within_enrollment_id: 'enroll-a', mission_id: 'mission-a' }); const second = value.bridge.projection(value.participant, { leader_within_enrollment_id: 'enroll-a', mission_id: 'mission-a' }); assert.equal(first.movement_mission.status, 'COMPLETED'); assert.deepEqual(second, first); assert.equal(Object.keys(value.repository.snapshot().credits).length, 1); });
test('canonical five-step mission math advances 3/5 to 4/5 after PocketPT credit', () => { const before = calculateMissionProgress({ featured_story: true, practice_selected: true, practice_completed: true }); const after = calculateMissionProgress({ featured_story: true, practice_selected: true, practice_completed: true, movement_completed: true }); assert.deepEqual(before, { completed: 3, total: 5, percentage: 60 }); assert.deepEqual(after, { completed: 4, total: 5, percentage: 80 }); });
test('facilitator permission gets only the bounded projection; absent permission is denied', () => { const value = assigned(); const allowed = { subject: 'facilitator', role: 'LEADER_WITHIN_FACILITATOR', organization_id: 'org-a', permissions: ['LEADER_WITHIN_PARTICIPANT_READ'] }; assert.equal(value.bridge.projection(allowed, { leader_within_enrollment_id: 'enroll-a', mission_id: 'mission-a' }).movement_mission.status, 'NOT_STARTED'); assert.throws(() => value.bridge.projection({ ...allowed, permissions: [] }, { leader_within_enrollment_id: 'enroll-a', mission_id: 'mission-a' }), /bridge_access_denied/); });
test('PocketPT outage fails unavailable and never produces completion', () => { const value = assigned(); const original = value.youth.view; value.youth.view = () => { throw new Error('offline'); }; const result = value.bridge.projection(value.participant, { leader_within_enrollment_id: 'enroll-a', mission_id: 'mission-a' }); value.youth.view = original; assert.equal(result.connection_status, 'TEMPORARILY_UNAVAILABLE'); assert.equal(result.movement_mission.status, 'UNAVAILABLE'); assert.equal(value.repository.getCredit(value.assignment.assignment_id), null); });
test('bridge repository initialization is additive and preserves mappings and assignments', () => { const value = assigned(); const reopened = createLeaderWithinBridgeRepository({ filePath: path.join(value.dir, 'bridge.json') }); assert.deepEqual(reopened.getMappingByEnrollment('enroll-a'), value.mapping); assert.deepEqual(reopened.getAssignment('enroll-a', 'mission-a'), value.assignment); });
