'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { createYouthProgramRepository } = require('../src/youth-fitness/runtime/repository');
const { createYouthProgramService } = require('../src/youth-fitness/runtime/service');
const { createYouthCsrf } = require('../src/youth-fitness/runtime/csrf');

function fixture() { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'youth-runtime-')); const repository = createYouthProgramRepository({ filePath: path.join(dir, 'runtime.json') }); return { repository, service: createYouthProgramService({ repository, clock: () => '2026-08-17T12:00:00.000Z' }) }; }
function begin(subject = 'youth-a') { const value = fixture(); value.service.enrollment(subject); const dashboard = value.service.dashboard(subject); const session = value.service.start(subject, dashboard.today.session_ref); return { ...value, subject, dashboard, session }; }

test('program dashboard is generated from the Phase 4 journey and compares participant to self', () => { const { dashboard } = begin(); assert.equal(dashboard.total_weeks, 12); assert.equal(dashboard.journey.length, 3); assert.equal(dashboard.journey[0].title, 'Foundation & Movement Confidence'); assert.equal(dashboard.week.target, 3); assert.equal(dashboard.progress.comparison, 'SELF_ONLY'); assert.equal(dashboard.consistency.percentage, 0); });
test('identity is server-derived and cross-participant program/session access fails closed', () => { const { service, session } = begin(); assert.equal(service.publicParticipantRef('youth-a') === service.publicParticipantRef('youth-b'), false); assert.equal(service.view('youth-b', session.session_ref), null); assert.throws(() => service.dashboard('youth-b'), /program_not_found/); });
test('start is idempotent and Phase 5 blueprint is held until readiness and Phase 6 approval', () => { const value = begin(); assert.equal(value.service.start(value.subject, value.session.session_ref).session_ref, value.session.session_ref); assert.equal(value.service.view(value.subject, value.session.session_ref).blueprint, null); const ready = value.service.readiness(value.subject, value.session.session_ref, { energy: 4, soreness: 'NONE', sleep_quality: 'GOOD', pain: false }); assert.equal(ready.safety_validation.ok, true); assert.equal(ready.blueprint.version, 1); assert.ok(ready.blueprint.blocks.flatMap((block) => block.activities).length); });
test('poor readiness reduces server-side workload and adjusted blueprint is revalidated', () => { const value = begin(); const ready = value.service.readiness(value.subject, value.session.session_ref, { energy: 2, soreness: 'MILD', sleep_quality: 'POOR', pain: false }); assert.equal(ready.readiness_adjustment, 'REDUCED_WORKLOAD'); assert.equal(ready.safety_validation.ok, true); assert.ok(ready.blueprint.blocks.flatMap((block) => block.activities).every((activity) => activity.prescription.sets === 1)); });
test('pain routes calmly to coach review without delivering a session', () => { const value = begin(); const ready = value.service.readiness(value.subject, value.session.session_ref, { energy: 3, soreness: 'NONE', sleep_quality: 'GOOD', pain: true, safety_approved: true }); assert.equal(ready.status, 'COACH_REVIEW_REQUIRED'); assert.equal(ready.blueprint, null); assert.equal(value.service.view(value.subject, value.session.session_ref).blueprint, null); assert.doesNotMatch(JSON.stringify(ready.activity_results), /diagnos|push through/i); });
test('actual quality work, technique stop, persistence, finish adaptation, consistency, and duplicate finish work', () => { const value = begin(); let ready = value.service.readiness(value.subject, value.session.session_ref, { energy: 4, soreness: 'NONE', sleep_quality: 'GOOD', pain: false }); const activity = ready.blueprint.blocks.flatMap((block) => block.activities)[0]; value.service.recordActivity(value.subject, ready.session_ref, activity.activity_id, { completed: true, sets: [12, 9] }); value.service.stopActivity(value.subject, ready.session_ref, activity.activity_id, { reason: 'TECHNIQUE', quality_reps: 9 }); const resumed = value.service.view(value.subject, ready.session_ref); assert.deepEqual(resumed.activity_results[activity.activity_id].quality_reps, [12, 9]); const first = value.service.finish(value.subject, ready.session_ref, { effort: 'MODERATE' }); const second = value.service.finish(value.subject, ready.session_ref, { effort: 'TOO_HARD' }); assert.equal(first.session_result.session_result_id, second.session_result.session_result_id); assert.equal(first.adaptation.ok, true); assert.equal(first.adaptation.future_delivery_requires_phase_6_validation, true); assert.equal(first.future_delivery.safety_validation.validator_version, 1); assert.equal(value.service.dashboard(value.subject).week.completed, 1); });
test('unknown activities cannot be persisted and zero eligible denominator is represented accurately', () => { const value = begin(); value.service.readiness(value.subject, value.session.session_ref, { energy: 4, soreness: 'NONE', sleep_quality: 'GOOD', pain: false }); const record = value.service.recordActivity(value.subject, value.session.session_ref, 'UNKNOWN', { completed: true, sets: [12] }); assert.equal(record.activity_results.UNKNOWN, undefined); const aggregate = value.repository.getProgram(value.subject); aggregate.current_week = 0; value.repository.saveProgram(value.subject, aggregate); /* dashboard normally begins at week one; profile helper owns true zero semantics */ assert.equal(require('../src/youth-fitness').profiles.calculateConsistencyPercentage({ eligible_scheduled_sessions: 0, eligible_completed_sessions: 0 }), null); });
test('CSRF requires matching subject-bound header and cookie', () => { const csrf = createYouthCsrf({ secret: 'test' }); const token = csrf.issue('a'); let status = null; const req = { auth: { userId: 'a' }, get(name) { return name === 'x-pocketpt-csrf' ? token : name === 'cookie' ? `pocketpt_youth_csrf=${token}` : null; } }; csrf.requireToken(req, { status(code) { status = code; return this; }, json() {} }, () => { status = 204; }); assert.equal(status, 204); req.auth.userId = 'b'; csrf.requireToken(req, { status(code) { status = code; return this; }, json() {} }, () => {}); assert.equal(status, 403); });
test('mobile participant markup has labels, touch controls, cards, and no table/leaderboard', () => { const html = fs.readFileSync(path.join(__dirname, '..', 'public', 'pocketpt-my-program.html'), 'utf8'); const js = fs.readFileSync(path.join(__dirname, '..', 'public', 'pocketpt-youth-program.js'), 'utf8'); const css = fs.readFileSync(path.join(__dirname, '..', 'public', 'pocketpt-youth-program.css'), 'utf8'); assert.match(html, /viewport/); assert.match(js, /<label>/); assert.match(js, /Stop this exercise safely/); assert.doesNotMatch(js, /<table|leaderboard/i); assert.match(css, /min-height:48px/); });
test('browser identity, level, and safety claims cannot override canonical enrollment or delivery', () => { const { service } = fixture(); const enrolled = service.enrollment('canonical-owner', { participant_id: 'foreign', participant_ref: 'foreign', training_level: 'PROGRESSION', safety_approved: true }); assert.equal(enrolled.owner_subject, 'canonical-owner'); assert.equal(enrolled.participant_ref, service.publicParticipantRef('canonical-owner')); assert.equal(enrolled.profile.training_level, 'FOUNDATION'); assert.equal(enrolled.profile.safety_approved, undefined); const dashboard = service.dashboard('canonical-owner'); const started = service.start('canonical-owner', dashboard.today.session_ref); assert.equal(started.blueprint, null); });
test('pain stop immediately removes executable delivery while preserving readiness and stop state', () => { const value = begin(); const ready = value.service.readiness(value.subject, value.session.session_ref, { energy: 4, soreness: 'NONE', sleep_quality: 'GOOD', pain: false }); const activity = ready.blueprint.blocks.flatMap((block) => block.activities)[0]; const stopped = value.service.stopActivity(value.subject, ready.session_ref, activity.activity_id, { reason: 'PAIN', quality_reps: 7, safety_approved: true }); assert.equal(stopped.blueprint, null); assert.equal(stopped.pain_flag, true); assert.equal(stopped.readiness.energy, 4); assert.equal(stopped.stop_events[0].quality_reps, 7); });
test('repository initialization is idempotent and preserves existing Pocket PT youth runtime records', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'youth-migration-')); const filePath = path.join(dir, 'runtime.json'); const first = createYouthProgramRepository({ filePath }); first.saveProgram('owner', { marker: 'preserved' }); const second = createYouthProgramRepository({ filePath }); assert.deepEqual(second.getProgram('owner'), { marker: 'preserved' }); });
