"use strict";
const crypto=require("node:crypto");
const SALES_SCHEMA_VERSION="ai-business-os.sales/1.0.0";
const SHA256=/^[a-f0-9]{64}$/;
const text=v=>typeof v==="string"&&v.trim().length>0;
const obj=v=>v!==null&&typeof v==="object"&&!Array.isArray(v);
const list=v=>Array.isArray(v);
function req(ok,code){if(!ok)throw new Error(`invalid_sales:${code}`)}
function freeze(v,seen=new Set()){if(v&&typeof v==="object"){req(!seen.has(v),"cyclic_value");seen.add(v);Object.values(v).forEach(x=>freeze(x,seen));seen.delete(v);Object.freeze(v)}return v}
function stable(v,seen=new Set()){if(v===null||["string","boolean"].includes(typeof v))return v;if(typeof v==="number"){req(Number.isFinite(v),"non_finite_number");return v}req(typeof v!=="undefined"&&typeof v!=="function"&&typeof v!=="symbol"&&typeof v!=="bigint","non_json_value");req(!seen.has(v),"cyclic_value");seen.add(v);let out;if(Array.isArray(v))out=v.map(x=>stable(x,seen));else{req(Object.getPrototypeOf(v)===Object.prototype||Object.getPrototypeOf(v)===null,"non_plain_object");out=Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k],seen)]))}seen.delete(v);return out}
function digest(v){return crypto.createHash("sha256").update(JSON.stringify(stable(v))).digest("hex")}
function ref(v,field="artifactRef",expectedType=null){req(obj(v),field);for(const k of ["artifactType","artifactId","digest","organizationId","workId"])req(text(v[k]),`${field}.${k}`);req(SHA256.test(v.digest),`${field}.digest`);req(Number.isSafeInteger(v.version)&&v.version>0,`${field}.version`);if(expectedType)req(v.artifactType===expectedType,`${field}.artifactType`);return freeze(structuredClone(v))}
function base(kind,v,required=[]){req(obj(v),kind);req(v.kind===undefined||v.kind===kind,`${kind}.kind`);req(v.salesSchemaVersion===undefined||v.salesSchemaVersion===SALES_SCHEMA_VERSION,`${kind}.schema_version`);for(const k of ["id","organizationId","workId",...required])req(text(v[k]),`${kind}.${k}`);req(Number.isSafeInteger(v.version)&&v.version>0,`${kind}.version`);const r=structuredClone({...v,kind,salesSchemaVersion:SALES_SCHEMA_VERSION});return freeze(r)}
function CustomerNeed(v={}){const r=base("CustomerNeed",v,["statement"]);req(list(r.evidenceRefs)&&r.evidenceRefs.every(text),"CustomerNeed.evidenceRefs");req(list(r.unknowns)&&r.unknowns.every(text),"CustomerNeed.unknowns");return r}
function CommercialOpportunity(v={}){const r=base("CommercialOpportunity",v,["sourceType"]);ref(r.sourceRef,"sourceRef");req(r.sourceRef.organizationId===r.organizationId&&r.sourceRef.workId===r.workId,"CommercialOpportunity.source_scope");req(list(r.needRefs)&&r.needRefs.length>0,"CommercialOpportunity.needRefs");const ids=new Set();r.needRefs.forEach((x,i)=>{ref(x,`needRefs[${i}]`,"CustomerNeed");req(x.organizationId===r.organizationId&&x.workId===r.workId,"CommercialOpportunity.need_scope");req(!ids.has(x.artifactId),"CommercialOpportunity.duplicate_need");ids.add(x.artifactId)});req(list(r.evidenceRefs)&&r.evidenceRefs.every(text),"CommercialOpportunity.evidenceRefs");return r}
function QualificationInput(v={}){const r=base("QualificationInput",v,["opportunityDigest"]);req(SHA256.test(r.opportunityDigest),"QualificationInput.opportunityDigest");ref(r.opportunityRef,"opportunityRef","CommercialOpportunity");req(r.opportunityRef.organizationId===r.organizationId&&r.opportunityRef.workId===r.workId,"QualificationInput.opportunity_scope");req(r.opportunityRef.digest===r.opportunityDigest,"QualificationInput.opportunity_digest");req(list(r.evidenceRefs)&&r.evidenceRefs.every(text),"QualificationInput.evidenceRefs");return r}
function ProposalReference(v={}){const r=base("ProposalReference",v,["proposalId","proposalDigest"]);req(SHA256.test(r.proposalDigest),"ProposalReference.proposalDigest");req(Number.isSafeInteger(r.proposalVersion)&&r.proposalVersion>0,"ProposalReference.proposalVersion");req(r.status==="PROPOSED","ProposalReference.status");req(r.accepted===false&&r.paymentVerified===false&&r.fulfilled===false,"ProposalReference.authority_flags");return r}
function artifactRef(artifact){req(obj(artifact)&&text(artifact.kind)&&text(artifact.id)&&text(artifact.organizationId)&&text(artifact.workId),"artifact");req(artifact.salesSchemaVersion===SALES_SCHEMA_VERSION,"artifact.schema_version");req(Number.isSafeInteger(artifact.version)&&artifact.version>0,"artifact.version");return freeze({artifactType:artifact.kind,artifactId:artifact.id,version:artifact.version,digest:digest(artifact),organizationId:artifact.organizationId,workId:artifact.workId})}
module.exports={SALES_SCHEMA_VERSION,digest,artifactRef,CustomerNeed,CommercialOpportunity,QualificationInput,ProposalReference};
