"use strict";
const {SALES_SCHEMA_VERSION,digest,artifactRef}=require("./contracts");
const DISPOSITIONS=Object.freeze(["QUALIFIED","DISQUALIFIED","NEEDS_MORE_EVIDENCE","ESCALATE"]);
const STATUSES=Object.freeze(["SATISFIED","UNSATISFIED","UNKNOWN","CONTRADICTED"]);
const text=v=>typeof v==="string"&&v.trim().length>0,obj=v=>v&&typeof v==="object"&&!Array.isArray(v);
function req(ok,code){if(!ok)throw new Error(`invalid_sales_qualification:${code}`)}
function freeze(v){if(v&&typeof v==="object"){Object.values(v).forEach(freeze);Object.freeze(v)}return v}
function QualificationCriterion(v={}){req(obj(v),"criterion");for(const k of ["id","question"])req(text(v[k]),k);req(Array.isArray(v.evidenceRefs)&&v.evidenceRefs.every(text),"evidenceRefs");req(STATUSES.includes(v.status),"status");if(["SATISFIED","UNSATISFIED","CONTRADICTED"].includes(v.status))req(v.evidenceRefs.length>0,"decisive_evidence_required");if(v.status==="UNKNOWN")req(v.evidenceRefs.length===0,"unknown_has_no_decisive_evidence");return freeze(structuredClone(v))}
function QualificationAssessment(v={}){req(obj(v),"assessment");for(const k of ["id","organizationId","workId"])req(text(v[k]),k);req(Number.isSafeInteger(v.version)&&v.version>0,"version");req(obj(v.qualificationInputRef)&&v.qualificationInputRef.artifactType==="QualificationInput","qualificationInputRef");for(const k of ["artifactId","digest","organizationId","workId"])req(text(v.qualificationInputRef[k]),`qualificationInputRef.${k}`);req(v.qualificationInputRef.organizationId===v.organizationId&&v.qualificationInputRef.workId===v.workId,"input_scope");req(Array.isArray(v.criteria)&&v.criteria.length>0,"criteria");const criteria=v.criteria.map(QualificationCriterion),ids=new Set();for(const c of criteria){req(!ids.has(c.id),"duplicate_criterion");ids.add(c.id)}req(DISPOSITIONS.includes(v.disposition),"disposition");req(Array.isArray(v.limitations)&&v.limitations.every(text),"limitations");req(Array.isArray(v.missingEvidence)&&v.missingEvidence.every(text),"missingEvidence");const unknown=criteria.some(c=>c.status==="UNKNOWN"),bad=criteria.some(c=>c.status==="UNSATISFIED"),contradicted=criteria.some(c=>c.status==="CONTRADICTED");if(v.disposition==="QUALIFIED")req(!unknown&&!bad&&!contradicted&&v.missingEvidence.length===0,"qualified_requires_complete_support");if(v.disposition==="DISQUALIFIED")req(bad,"disqualified_requires_unsatisfied");if(v.disposition==="NEEDS_MORE_EVIDENCE")req(unknown&&v.missingEvidence.length>0,"needs_evidence_requires_unknown");if(v.disposition==="ESCALATE")req(contradicted,"escalate_requires_contradiction");return freeze({salesSchemaVersion:SALES_SCHEMA_VERSION,kind:"QualificationAssessment",...structuredClone(v),criteria})}
function assessQualification({id,organizationId,workId,version=1,qualificationInputRef,criteria,limitations=[],missingEvidence=[]}={}){req(Array.isArray(criteria)&&criteria.length>0,"criteria");const checked=criteria.map(QualificationCriterion);let disposition;if(checked.some(c=>c.status==="CONTRADICTED"))disposition="ESCALATE";else if(checked.some(c=>c.status==="UNSATISFIED"))disposition="DISQUALIFIED";else if(checked.some(c=>c.status==="UNKNOWN"))disposition="NEEDS_MORE_EVIDENCE";else disposition="QUALIFIED";return QualificationAssessment({id,organizationId,workId,version,qualificationInputRef,criteria:checked,disposition,limitations,missingEvidence})}
module.exports={QUALIFICATION_DISPOSITIONS:DISPOSITIONS,QUALIFICATION_STATUSES:STATUSES,QualificationCriterion,QualificationAssessment,assessQualification};
