"use strict";
const { scoreAssessment }=require("./scoring");
const DEEP_BANK_VERSION="0.1.0-phase6";
const o=(text,p,s,d,a)=>({text,primary_dimension:p,secondary_dimension:s,direction_value:d,activation_value:a});
const Q=(id,cls,prompt,options,meta={})=>({id,class:cls,prompt,options,...meta});
const DEEP_BANK=Object.freeze([
Q("SAD01","ID","How settled do you feel in your body and surroundings?",[o("Very unsettled or on edge","GR","CL",1,1),o("Restless, but I can settle sometimes","CL","GR",.6,1),o("Mostly steady and present","CO","GR",.2,0),o("Calm, grounded, and here","GR","SP",0,-1)],{reverse_pair_id:"SAD11"}),
Q("SAD02","BH","When feelings build up, what usually happens?",[o("I hold them in until they feel heavy","EF","EX",1,-1),o("They spill out faster than I want","EF","GR",1,1),o("I can feel them without getting pulled under","CO","EF",0,0),o("I disconnect or go numb","GR","EF",1,-1)]),
Q("SAD03","SC","After a demanding day, you finally get quiet time. What tends to happen?",[o("My mind keeps racing even though I want rest","CL","GR",1,1),o("I feel drained and have almost no drive","AG","EX",1,-1),o("Feelings I held back start coming up","EF","CO",1,0),o("I feel okay physically, but something feels missing","SP","CO",1,0)]),
Q("SAD04","BH","When you need to say what you really mean, what is most like you?",[o("I usually hold back","EX","CO",1,-1),o("I say it, but sometimes too sharply","EX","GR",1,1),o("I can speak clearly and stay connected","CO","EX",0,0),o("I struggle to know what I want to say","CL","EX",1,-1)],{reverse_pair_id:"SAD14"}),
Q("SAD05","ID","How does your energy feel most days lately?",[o("Low, heavy, or hard to start","AG","GR",1,-1),o("Uneven — bursts followed by crashes","GR","AG",1,1),o("Steady enough for what I need to do","AG","CO",0,0),o("High, but hard to switch off","GR","AG",1,1)],{reverse_pair_id:"SAD15"}),
Q("SAD06","SC","When you have an important decision to make, what tends to happen?",[o("My thoughts get noisy and I second-guess myself","CL","GR",1,1),o("I know what matters but struggle to act","AG","CL",1,-1),o("I can usually see the next useful step","CL","AG",0,0),o("I look for a deeper sense of meaning before moving","SP","CL",.2,0)]),
Q("SAD07","BH","How connected do you feel to other people lately?",[o("Guarded or distant","CO","GR",1,-1),o("I want connection, but I do not have much room for it","CO","AG",.8,-1),o("Connected without losing myself","GR","CO",0,0),o("I connect easily but sometimes absorb too much","CO","EF",.7,1)],{reverse_pair_id:"SAD17"}),
Q("SAD08","ID","How connected do you feel to meaning, purpose, nature, ancestry, or something larger than yourself?",[o("Disconnected","SP","GR",1,-1),o("I miss that connection","SP","CO",.8,-1),o("Some connection, but it comes and goes","CL","SP",.4,0),o("Meaningfully connected","SP","CL",0,0)],{reverse_pair_id:"SAD18"}),
Q("SAD09","ST","When pressure rises, what happens first?",[o("My body gets tense or restless","GR","AG",1,1),o("My emotions become harder to manage","EF","GR",1,1),o("I shut down or lose energy","AG","EF",1,-1),o("I get stuck in my head","CL","EX",1,1)]),
Q("SAD10","DS","What would you most like to feel after a sound session?",[o("Calm, safe, and grounded","GR","CL",1,-1),o("Lighter and more emotionally open","EF","CO",1,0),o("Clear, energized, and ready to move","AG","CL",1,0),o("Connected, expressive, and spiritually restored","SP","EX",1,0)],{desired_pair_id:"SAD25"}),
Q("SAD11","ID","Even when life is busy, how easy is it to return to a steady center?",[o("I can return fairly easily","GR","SP",0,-1),o("Usually manageable","CO","GR",.2,0),o("It takes me a while","CL","GR",.6,1),o("Very difficult","GR","CL",1,1)],{reverse_pair_id:"SAD01"}),
Q("SAD12","SC","Someone disappoints you. What is your first tendency?",[o("Pull away and protect myself","CO","GR",1,-1),o("Feel it deeply but struggle to express it","EF","EX",1,-1),o("React before I have fully settled","GR","EF",1,1),o("Notice what I feel and decide how to respond","CL","CO",0,0)]),
Q("SAD13","ST","When several responsibilities hit at once, what becomes hardest?",[o("Staying physically calm","GR","AG",1,1),o("Keeping my thoughts organized","CL","GR",1,1),o("Finding enough energy to begin","AG","CL",1,-1),o("Staying emotionally open","EF","CO",1,-1)]),
Q("SAD14","BH","When something important needs to be said, how often can you express it clearly without shutting down or exploding?",[o("Almost always","EX","CO",0,0),o("Most of the time","CO","EX",.2,0),o("Sometimes","EX","CL",.6,0),o("Rarely","EX","GR",1,-1)],{reverse_pair_id:"SAD04"}),
Q("SAD15","ID","How consistently do you have usable energy for the things that matter to you?",[o("Very consistently","AG","CL",0,0),o("Most days","AG","CO",.2,0),o("It varies a lot","GR","AG",.7,1),o("Rarely","AG","GR",1,-1)],{reverse_pair_id:"SAD05"}),
Q("SAD16","SC","When your mind feels crowded, what helps least because it is hardest to access?",[o("Slowing my body down","GR","CL",1,1),o("Naming what I feel","EF","EX",1,-1),o("Choosing one next step","CL","AG",1,0),o("Remembering the bigger picture","SP","CL",1,0)]),
Q("SAD17","ID","How easy is it to stay open to people without feeling drained or losing your boundaries?",[o("Natural and balanced","CO","EF",0,0),o("Usually manageable","GR","CO",.2,0),o("Possible, but tiring","CO","AG",.7,-1),o("Very difficult","CO","GR",1,-1)],{reverse_pair_id:"SAD07"}),
Q("SAD18","ID","When life feels difficult, how available is your sense of meaning or inner connection?",[o("Still available to me","SP","CL",0,0),o("Present sometimes","CL","SP",.3,0),o("Hard to reach","SP","CO",.7,-1),o("Not available","SP","GR",1,-1)],{reverse_pair_id:"SAD08"}),
Q("SAD19","ST","When you are overwhelmed, which pattern feels most familiar?",[o("Restless and unable to settle","GR","CL",1,1),o("Emotionally flooded","EF","CO",1,1),o("Flat, tired, or withdrawn","AG","EF",1,-1),o("Quiet because I cannot find the words","EX","CL",1,-1)]),
Q("SAD20","SC","You have space to do something just for yourself. What most often gets in the way?",[o("I cannot switch off","GR","CL",1,1),o("I do not have the energy","AG","GR",1,-1),o("I feel guilty or emotionally blocked","EF","CO",1,-1),o("I do not know what I actually need","CL","SP",1,0)]),
Q("SAD21","BH","When you notice a strong feeling, how easily can you put it into words?",[o("Very difficult","EX","EF",1,-1),o("I know something is there but cannot name it","CL","EX",.8,-1),o("Usually I can name it","EF","EX",.2,0),o("I can name it and communicate it clearly","EX","CO",0,0)]),
Q("SAD22","SC","When you feel uncertain about your direction, what do you miss most?",[o("A clear next step","CL","AG",1,0),o("Confidence to act","AG","CL",1,-1),o("Someone or something to feel connected to","CO","SP",1,-1),o("A sense that what I am doing has meaning","SP","CO",1,-1)]),
Q("SAD23","ST","What happens to your breathing and body when stress lingers?",[o("I stay tense or keyed up","GR","AG",1,1),o("I feel heavy or slowed down","AG","GR",1,-1),o("I stop noticing my body much","GR","EF",1,-1),o("I can usually notice tension and soften","CO","GR",0,0)]),
Q("SAD24","DS","Which change would feel most valuable over the next few days?",[o("Feeling more settled in myself","GR","CL",1,-1),o("Letting emotions move instead of carrying them","EF","EX",1,0),o("Having more usable energy and confidence","AG","CO",1,0),o("Feeling clearer, connected, and purposeful","SP","CL",1,0)],{desired_pair_id:"SAD10"}),
Q("SAD25","DS","If this session worked well for you, what would you notice first afterward?",[o("My body feels quieter and safer","GR","CO",1,-1),o("My chest or emotions feel lighter","EF","CO",1,0),o("My mind feels clearer and I can move forward","CL","AG",1,0),o("I feel more connected to myself and what matters","SP","EX",1,0)],{desired_pair_id:"SAD10"})
]);
function scoreDeepAssessment(answers={}){const r=scoreAssessment(DEEP_BANK,answers);if(!r.ok)return r;return {...r,result:{...r.result,bankVersion:DEEP_BANK_VERSION,mode:"deep"}};}
module.exports={DEEP_BANK_VERSION,DEEP_BANK,scoreDeepAssessment};
