"use strict";
const { ApiError } = require("../lib/apiResponse");
const MESSAGE_MAX_LENGTH = 4000;
const DAY = 86400000;
const iso = value => value ? new Date(value).toISOString() : null;

function createClientCrmService({ userStore, authCredentialStore, membershipService, trainerWorkspaceStore, messagingStore, authorizationResolver, clock = () => Date.now() }) {
  const isAdmin = actor => ["super_admin", "admin"].includes(actor.role);
  function allowed(actor, clientId) { return isAdmin(actor) || (actor.role === "trainer" && trainerWorkspaceStore.hasActiveAccess(actor.userId, clientId)); }
  function assertStaff(actor, clientId) { if (!allowed(actor, clientId)) throw new ApiError("CLIENT_ACCESS_DENIED", "Client access is not permitted", 403); }
  function identities() { const map = new Map(userStore.listUsers().map(u => [u.userId, u])); for (const a of authCredentialStore.listIdentities()) { const user = map.get(a.id) || userStore.loadUser(a.id); user.profile = { ...(user.profile || {}), displayName: user.profile?.displayName || a.name, email: user.profile?.email || a.email }; user.createdAt = user.createdAt || Date.parse(a.createdAt); user.accessTier = a.accessTier; map.set(a.id, user); } return [...map.values()]; }
  function workoutDates(user) { return Object.values(user.sessions || {}).map(s => s.completedAt || s.endedAt || s.updatedAt).filter(Boolean).map(Date.parse).filter(Number.isFinite); }
  function bill(user) { const m = membershipService.getMembership(user.userId); const status = String(m.status || "inactive"); const label = status === "active" ? "paid" : status === "trialing" ? "trial" : ["past_due","canceled"].includes(status) ? status : user.accessTier?.startsWith("paid") ? "paid" : user.accessTier ? "free" : "unknown"; return { status: label, tier: m.plan || user.accessTier || null, renewalAt: iso(m.currentPeriodEnd), cancelAtPeriodEnd: Boolean(m.cancelAtPeriodEnd) }; }
  function summary(user) { const dates = workoutDates(user); const lastWorkout = dates.length ? Math.max(...dates) : null; const eventDates=(user.events||[]).map(e=>Date.parse(e.createdAt||e.at||e.timestamp)).filter(Number.isFinite); const lastActive = Math.max(lastWorkout || 0, ...eventDates, 0) || null; const intake = user.journeyIntake || user.retention?.intake || user.journeyProfile || null; const assessments = [...(user.assessments || []), ...(user.ohsa || [])]; const program = user.program || user.selectedProgram || user.generatedWorkoutPlan || null; const challenge = user.challengeEnrollment || user.activeChallenge || null; return { userId:user.userId, displayName:String(user.profile?.displayName || user.profile?.name || user.name || user.userId), email:user.profile?.email || user.email || null, avatarUrl:user.profile?.avatarUrl || null, joinedAt:iso(user.createdAt), lastActiveAt:iso(lastActive), activityStatus:lastActive && clock()-lastActive <= 30*DAY ? "active" : "inactive", accountStatus:user.disabledAt ? "disabled" : "enabled", payment:bill(user), activeProgram:program ? { id:program.programId || program.id || null, title:program.title || program.name || "Active program" } : null, activeChallenge:challenge ? { id:challenge.challengeId || challenge.id || null, title:challenge.title || challenge.name || "Active challenge" } : null, intakeStatus:intake?.status === "submitted" || intake?.submittedAt ? "complete" : "incomplete", assessmentStatus:assessments.some(a => a.completedAt || a.status === "completed") ? "complete" : "incomplete", mostRecentWorkoutAt:iso(lastWorkout), workoutsLast30Days:dates.filter(d => clock()-d <= 30*DAY).length, unreadMessages:messagingStore.listForUser(user.userId).flatMap(c=>messagingStore.listMessages(c.id)).filter(m=>m.senderUserId===user.userId&&!m.readAt).length }; }
  function scoped(actor) { const all = identities().filter(u => !["super_admin","admin","trainer"].includes(authorizationResolver.resolveRole({userId:u.userId,email:u.profile?.email}).role)); return isAdmin(actor) ? all : all.filter(u => trainerWorkspaceStore.hasActiveAccess(actor.userId,u.userId)); }
  function directory(actor, query={}) { let rows=scoped(actor).map(summary); const all=rows; const q=String(query.search||"").trim().toLowerCase(); if(q) rows=rows.filter(x=>`${x.displayName} ${x.email||""}`.toLowerCase().includes(q)); const filter=String(query.filter||"all"); const checks={paid:x=>x.payment.status==="paid",free:x=>x.payment.status==="free",trial:x=>x.payment.status==="trial",active:x=>x.activityStatus==="active",inactive:x=>x.activityStatus==="inactive",program:x=>x.activeProgram,challenge:x=>x.activeChallenge,intake_incomplete:x=>x.intakeStatus==="incomplete",assessment_incomplete:x=>x.assessmentStatus==="incomplete",unread:x=>x.unreadMessages>0}; if(checks[filter]) rows=rows.filter(checks[filter]); const sorts={name:(a,b)=>a.displayName.localeCompare(b.displayName),joined:(a,b)=>String(b.joinedAt).localeCompare(String(a.joinedAt)),last_active:(a,b)=>String(b.lastActiveAt||"").localeCompare(String(a.lastActiveAt||"")),workout:(a,b)=>String(b.mostRecentWorkoutAt||"").localeCompare(String(a.mostRecentWorkoutAt||"")),subscription:(a,b)=>a.payment.status.localeCompare(b.payment.status)}; rows.sort(sorts[query.sort]||sorts.name); const page=Math.max(1,Number.parseInt(query.page,10)||1), pageSize=Math.min(100,Math.max(1,Number.parseInt(query.pageSize,10)||25)); const recent=n=>all.filter(x=>x.joinedAt&&clock()-Date.parse(x.joinedAt)<=n*DAY).length; const noActivity=n=>all.filter(x=>!x.lastActiveAt||clock()-Date.parse(x.lastActiveAt)>n*DAY).length; return { members:rows.slice((page-1)*pageSize,page*pageSize), pagination:{page,pageSize,total:rows.length,totalPages:Math.ceil(rows.length/pageSize)}, metrics:{totalMembers:all.length,activeMembers:all.filter(x=>x.activityStatus==="active").length,inactiveMembers:all.filter(x=>x.activityStatus==="inactive").length,paidMembers:all.filter(x=>x.payment.status==="paid").length,freeMembers:all.filter(x=>x.payment.status==="free").length,trialMembers:all.filter(x=>x.payment.status==="trial").length,new7Days:recent(7),new30Days:recent(30),activePrograms:all.filter(x=>x.activeProgram).length,inChallenges:all.filter(x=>x.activeChallenge).length,intakeIncomplete:all.filter(x=>x.intakeStatus==="incomplete").length,assessmentIncomplete:all.filter(x=>x.assessmentStatus==="incomplete").length,noActivity7Days:noActivity(7),noActivity14Days:noActivity(14),noActivity30Days:noActivity(30)} }; }
  function user(clientId){const value=identities().find(u=>u.userId===clientId);if(!value)throw new ApiError("CLIENT_NOT_FOUND","Client not found",404);return value;}
  function overview(actor,id){assertStaff(actor,id);const u=user(id), s=summary(u); const timeline=[{type:"account_created",at:s.joinedAt},...(u.journeyProfile?.submittedAt?[{type:"intake_completed",at:iso(u.journeyProfile.submittedAt)}]:[]),...(u.assessments||[]).filter(a=>a.completedAt).map(a=>({type:"assessment_completed",at:iso(a.completedAt),label:a.type})),...Object.values(u.sessions||{}).filter(x=>x.completedAt||x.endedAt).map(x=>({type:"workout_completed",at:iso(x.completedAt||x.endedAt)}))].filter(x=>x.at).sort((a,b)=>b.at.localeCompare(a.at)); return {summary:s,goals:u.journeyProfile?.goals||u.journeyProfile?.primaryGoal||null,recentWorkouts:Object.values(u.sessions||{}).slice(-20).map(x=>({id:x.id||x.sessionId,status:x.status||null,completedAt:iso(x.completedAt||x.endedAt)})),program:u.program||u.selectedProgram||null,challenge:u.challengeEnrollment||u.activeChallenge||null,timeline};}
  function intake(actor,id){assertStaff(actor,id);const u=user(id);return {intake:u.journeyIntake||u.retention?.intake||u.journeyProfile||null};}
  function assessments(actor,id){assertStaff(actor,id);const u=user(id);return {assessments:[...(u.assessments||[]),...(u.ohsa||[])]};}
  function conversation(actor,clientId,create=false){if(actor.userId!==clientId)assertStaff(actor,clientId);if(actor.userId===clientId){const c=messagingStore.listForUser(clientId)[0];return c||null;}return messagingStore.conversationFor(clientId,actor.userId,create);}
  function viewMessages(actor,conversationId){const c=messagingStore.getConversation(conversationId);if(!c||!(c.clientUserId===actor.userId||c.participantStaffIds.includes(actor.userId)))throw new ApiError("CONVERSATION_NOT_FOUND","Conversation not found",404);messagingStore.markRead(c.id,actor.userId);return {conversation:c,messages:messagingStore.listMessages(c.id)};}
  function send(actor,conversationId,body){const c=messagingStore.getConversation(conversationId);if(!c||!(c.clientUserId===actor.userId||c.participantStaffIds.includes(actor.userId)))throw new ApiError("CONVERSATION_NOT_FOUND","Conversation not found",404);const text=typeof body==="string"?body.trim():"";if(!text||text.length>MESSAGE_MAX_LENGTH)throw new ApiError("INVALID_MESSAGE",`Message must be 1-${MESSAGE_MAX_LENGTH} characters`,422);return messagingStore.addMessage(c.id,actor.userId,text);}
  return {directory,overview,intake,assessments,assertStaff,conversation,viewMessages,send,MESSAGE_MAX_LENGTH};
}
module.exports={createClientCrmService,MESSAGE_MAX_LENGTH};
