"use strict";

const { ApiError } = require("../lib/apiResponse");
const { validateJourneyPatch, validatePathwayConsistency } = require("../validation/journeyIntakeValidators");

const STEPS = ["pathway_selection","identity_profile","goals","health_safety","training_context","schedule","pathway_details","final_review"];
const placeholder = v => !v || ["n/a","na","none provided"].includes(String(v).trim().toLowerCase());
const present = v => !placeholder(v);
const iso = () => new Date().toISOString();
const LEGACY_GOAL_LABELS = {fat_loss:"Lose body fat",muscle_gain:"Build muscle",strength:"Build strength",mobility:"Improve mobility",endurance:"Improve endurance",rehab_prehab:"Return to activity",general_fitness:"Improve general health"};
const defaults = () => ({
  schemaVersion:1,status:"draft",currentStep:"pathway_selection",completedSteps:[],selectedPathways:[],primaryPathway:null,createdAt:iso(),updatedAt:iso(),submittedAt:null,lastSavedAt:null,
  identity:{fullName:null,preferredName:null,phone:null,cityState:null,preferredCommunication:null,emergencyContactName:null,emergencyContactPhone:null},
  profile:{dateOfBirth:null,genderIdentity:null,genderSelfDescription:null,heightCm:null,weightKg:null}, pathwaySelection:{selected:[],primary:null},
  goals:{primaryGoal:null,secondaryGoals:[],successDefinition:null,importantDate:null},
  healthSafety:{currentPainOrInjury:null,receivingTreatmentOrRehab:null,instructedToAvoidStrenuousExercise:null,concussionHistory:null,conditions:[],details:null,believesExerciseIsSafe:null,coachNotesBeforeTesting:null,medicalDisclaimerConsent:false,healthFlags:[]},
  trainingContext:{activeDaysPerWeek:null,currentTrainingTypes:[],selfRatedFitnessLevel:null,gymAccess:null,fieldTrackAccess:null,availableEquipment:[]},
  schedule:{preferredStartDate:null,availableDays:[],availableTimes:[],realisticSessionsPerWeek:null,limitations:null},
  athletePerformance:{enabled:false,sport:null,sportOther:null,currentLevel:null,performancePriorities:[],currentTeamOrClub:null}, rugbySupplement:{enabled:false,experienceYears:null,formats:[],clubStatus:null,currentOrProspectiveClub:null,playingStatus:null,primaryPosition:null,secondaryPosition:null,highestLevelPlayed:null,previousTeams:null,performanceLimiters:null,previousTestResults:null,preferredCoachingStyle:null,additionalContext:null},
  generalFitness:{enabled:false,weightChangeGoal:null,desiredWeightChange:null,motivation:null}, yogaWellness:{enabled:false,experienceLevel:null,primaryIntentions:[],preferredPracticeTypes:[],mobilityLimitations:null},
  review:{reviewStatus:"not_reviewed",reviewedByUserId:null,reviewedAt:null,reviewNotes:null}, migration:{migratedFromLegacy:false,migratedAt:null,migrationWarnings:[]}
});
function flags(h) { const f=[]; if(present(h.currentPainOrInjury))f.push("CURRENT_PAIN_OR_INJURY"); if(h.receivingTreatmentOrRehab===true)f.push("CURRENT_TREATMENT_OR_REHAB"); if(present(h.instructedToAvoidStrenuousExercise))f.push("EXERCISE_RESTRICTION"); if(present(h.concussionHistory))f.push("CONCUSSION_HISTORY"); if(String(h.believesExerciseIsSafe).toLowerCase()==="unsure")f.push("UNSURE_EXERCISE_IS_SAFE"); if(String(h.believesExerciseIsSafe).toLowerCase()==="no")f.push("EXERCISE_NOT_SAFE"); if(h.conditions.length)f.push("HEALTH_CONDITION_REPORTED"); if(present(h.coachNotesBeforeTesting))f.push("TESTING_REVIEW_REQUIRED"); return f; }
function sectionState(r) {
  const selected=r.pathwaySelection.selected;
  const pathwayComplete = selected.length>0 && selected.every(p => p==="general_fitness" ? present(r.generalFitness.weightChangeGoal) : p==="yoga_wellness" ? present(r.yogaWellness.experienceLevel)&&r.yogaWellness.primaryIntentions.length>0 : present(r.athletePerformance.sport)&&present(r.athletePerformance.currentLevel)&&r.athletePerformance.performancePriorities.length>0) && (!r.rugbySupplement.enabled || present(r.rugbySupplement.experienceYears)&&r.rugbySupplement.formats.length>0&&present(r.rugbySupplement.primaryPosition));
  return {pathway_selection:selected.length>=1&&selected.length<=2&&selected.includes(r.pathwaySelection.primary),identity_profile:present(r.identity.fullName)&&present(r.identity.phone)&&present(r.identity.cityState)&&present(r.identity.preferredCommunication)&&present(r.identity.emergencyContactName)&&present(r.identity.emergencyContactPhone)&&present(r.profile.dateOfBirth)&&r.profile.heightCm!=null,goals:present(r.goals.primaryGoal)&&present(r.goals.successDefinition),health_safety:r.healthSafety.receivingTreatmentOrRehab!==null&&present(r.healthSafety.believesExerciseIsSafe)&&r.healthSafety.medicalDisclaimerConsent===true,training_context:present(r.trainingContext.activeDaysPerWeek)&&present(r.trainingContext.selfRatedFitnessLevel),schedule:r.schedule.availableDays.length>0&&r.schedule.availableTimes.length>0&&present(r.schedule.realisticSessionsPerWeek),pathway_details:pathwayComplete,final_review:["submitted","needs_review","approved"].includes(r.status)};
}
function recalc(r) { r.healthSafety.healthFlags=flags(r.healthSafety); const states=sectionState(r); r.completedSteps=STEPS.filter(s=>states[s]); const next=STEPS.find(s=>!states[s])||null; return {totalRequiredSteps:STEPS.length,completedCount:r.completedSteps.length,currentStep:r.currentStep,nextRequiredStep:next,sectionStatuses:Object.fromEntries(STEPS.map(s=>[s,states[s]?"complete":(s===r.currentStep?"in_progress":"not_started")])),overallStatus:r.status,healthReviewStatus:r.healthSafety.healthFlags.length?"review_required":"not_required",selectedPathways:r.pathwaySelection.selected}; }
function migrate(user) { const r=defaults(), p=user.profile||{}, i=user.clientIntake||{}, g=user.goalsBaseline||{}, warnings=[]; r.identity.fullName=present(i.name)?i.name:null; r.profile.heightCm=i.heightCm??p.height_cm??p.heightCm??null; r.profile.weightKg=i.weightKg??p.weight_kg??p.weightKg??null; r.goals.primaryGoal=present(g.goal)?(LEGACY_GOAL_LABELS[g.goal]||g.goal):null; r.goals.secondaryGoals=(i.goals||[]).filter(present).slice(0,3); r.healthSafety.currentPainOrInjury=(i.injuries||[]).filter(present).join("; ")||null; r.healthSafety.details=(p.injuries||[]).filter(present).join("; ")||null; r.healthSafety.medicalDisclaimerConsent=i.medicalDisclaimerConsent===true; r.trainingContext.availableEquipment=(i.equipment||[]).filter(x=>present(x)&&String(x).toLowerCase()!=="bodyweight"); r.schedule.limitations=present(i.schedule)?i.schedule:null; if(r.goals.primaryGoal) warnings.push("Legacy goal retained for member confirmation; no pathway was inferred."); r.migration={migratedFromLegacy:Boolean(user.profile||user.clientIntake||user.goalsBaseline),migratedAt:iso(),migrationWarnings:warnings}; return r; }
function deepMerge(base, patch) { const out={...base}; for(const [k,v] of Object.entries(patch)) out[k]=v&&typeof v==="object"&&!Array.isArray(v)?deepMerge(base[k]||{},v):v; return out; }
function createJourneyIntakeService({userStore}) {
  function ensure(userId) { let r; userStore.updateUser(userId,u=>{ if(!u.memberJourneyProfile)u.memberJourneyProfile=migrate(u); r=u.memberJourneyProfile; return u; }); return r; }
  function get(userId){const intake=ensure(userId);return{userId,intake,progress:recalc(intake)};}
  function patch(userId,input){const clean=validateJourneyPatch(input);let intake;userStore.updateUser(userId,u=>{const prior=u.memberJourneyProfile||migrate(u); intake=deepMerge(prior,clean); const selected=intake.pathwaySelection.selected; const expectedGeneral=selected.includes("general_fitness"),expectedYoga=selected.includes("yoga_wellness"),expectedAthlete=selected.includes("athlete_performance"),expectedRugby=expectedAthlete&&String(intake.athletePerformance.sport).toLowerCase()==="rugby"; for(const [name,expected] of [["generalFitness",expectedGeneral],["yogaWellness",expectedYoga],["athletePerformance",expectedAthlete],["rugbySupplement",expectedRugby]]) if(clean[name]&&Object.hasOwn(clean[name],"enabled")&&clean[name].enabled!==expected) throw new ApiError("VALIDATION_ERROR",`${name}.enabled must match pathway selection`,400,{field:`${name}.enabled`}); intake.selectedPathways=[...selected];intake.primaryPathway=intake.pathwaySelection.primary; intake.generalFitness.enabled=expectedGeneral;intake.yogaWellness.enabled=expectedYoga;intake.athletePerformance.enabled=expectedAthlete; intake.rugbySupplement.enabled=expectedRugby; validatePathwayConsistency(intake); intake.updatedAt=iso();intake.lastSavedAt=intake.updatedAt;recalc(intake);u.memberJourneyProfile=intake;return u;});return{userId,intake,progress:recalc(intake)};}
  function submit(userId){let result;userStore.updateUser(userId,u=>{const r=u.memberJourneyProfile||migrate(u);validatePathwayConsistency(r);const progress=recalc(r);const missing=Object.entries(progress.sectionStatuses).filter(([k,v])=>k!=="final_review"&&v!=="complete").map(([field])=>field);if(missing.length)throw new ApiError("VALIDATION_ERROR","Intake is incomplete",400,{fields:missing});r.completedSteps=[...STEPS];r.status=r.healthSafety.healthFlags.length?"needs_review":"submitted";r.submittedAt=iso();r.updatedAt=r.submittedAt;r.currentStep="final_review";u.memberJourneyProfile=r;result={userId,intake:r,progress:recalc(r)};return u;});return result;}
  return {get,patch,submit,progress:userId=>{const x=get(userId);return{userId,...x.progress};}};
}
module.exports={createJourneyIntakeService,STEPS};
