"use strict";

const { ApiError } = require("../lib/apiResponse");
const { validateJourneyPatch, validatePathwayConsistency } = require("../validation/journeyIntakeValidators");
const { deriveJourneyProfile } = require("./journeyRecommendationEngine");
const { GENERATOR_VERSION } = require("./programGenerationEngine");
const { buildWorkoutPlan, PLAN_GENERATOR_VERSION } = require("../workouts/workoutPlanBuilder");

const STEPS = ["pathway_selection","identity_profile","goals","health_safety","training_context","schedule","pathway_details","final_review"];
const placeholder = v => !v || ["n/a","na","none provided"].includes(String(v).trim().toLowerCase());
const present = v => !placeholder(v);
const iso = () => new Date().toISOString();
const LEGACY_GOAL_LABELS = {fat_loss:"Lose body fat",muscle_gain:"Build muscle",strength:"Build strength",mobility:"Improve mobility",endurance:"Improve endurance",rehab_prehab:"Return to activity",general_fitness:"Improve general health"};
const defaults = () => ({
  schemaVersion:1,status:"draft",currentStep:"pathway_selection",completedSteps:[],selectedPathways:[],primaryPathway:null,createdAt:iso(),updatedAt:iso(),submittedAt:null,lastSavedAt:null,
  identity:{fullName:null,preferredName:null,phone:null,cityState:null,preferredCommunication:null,emergencyContactName:null,emergencyContactPhone:null},
  profile:{dateOfBirth:null,genderIdentity:null,genderSelfDescription:null,heightCm:null,weightKg:null}, pathwaySelection:{selected:[],primary:null},
  goals:{primaryGoal:null,secondaryGoals:[],successDefinition:null,importantDate:null},
  healthSafety:{currentPainOrInjury:null,receivingTreatmentOrRehab:null,instructedToAvoidStrenuousExercise:null,concussionHistory:null,conditions:[],details:null,believesExerciseIsSafe:null,coachNotesBeforeTesting:null,medicalDisclaimerConsent:false,healthFlags:[]},
  trainingContext:{activeDaysPerWeek:null,currentTrainingTypes:[],selfRatedFitnessLevel:null,gymAccess:null,fieldTrackAccess:null,availableEquipment:[]},
  schedule:{preferredStartDate:null,availableDays:[],availableTimes:[],realisticSessionsPerWeek:null,preferredSessionMinutes:null,limitations:null},
  athletePerformance:{enabled:false,sport:null,sportOther:null,currentLevel:null,performancePriorities:[],currentTeamOrClub:null}, rugbySupplement:{enabled:false,experienceYears:null,formats:[],clubStatus:null,currentOrProspectiveClub:null,playingStatus:null,primaryPosition:null,secondaryPosition:null,highestLevelPlayed:null,previousTeams:null,performanceLimiters:null,previousTestResults:null,preferredCoachingStyle:null,additionalContext:null},
  generalFitness:{enabled:false,weightChangeGoal:null,desiredWeightChange:null,motivation:null}, yogaWellness:{enabled:false,experienceLevel:null,primaryIntentions:[],preferredPracticeTypes:[],mobilityLimitations:null},
  review:{reviewStatus:"not_reviewed",reviewedByUserId:null,reviewedAt:null,reviewNotes:null}, migration:{migratedFromLegacy:false,migratedAt:null,migrationWarnings:[]}
});
function flags(h) { const f=[]; if(present(h.currentPainOrInjury))f.push("CURRENT_PAIN_OR_INJURY"); if(h.receivingTreatmentOrRehab===true)f.push("CURRENT_TREATMENT_OR_REHAB"); if(present(h.instructedToAvoidStrenuousExercise))f.push("EXERCISE_RESTRICTION"); if(present(h.concussionHistory))f.push("CONCUSSION_HISTORY"); if(String(h.believesExerciseIsSafe).toLowerCase()==="unsure")f.push("UNSURE_EXERCISE_IS_SAFE"); if(String(h.believesExerciseIsSafe).toLowerCase()==="no")f.push("EXERCISE_NOT_SAFE"); if(h.conditions.length)f.push("HEALTH_CONDITION_REPORTED"); if(present(h.coachNotesBeforeTesting))f.push("TESTING_REVIEW_REQUIRED"); return f; }
function sectionState(r) {
  const selected=r.pathwaySelection.selected;
  const pathwayComplete = selected.length>0 && selected.every(p => p==="general_fitness" ? present(r.generalFitness.weightChangeGoal) : p==="yoga_wellness" ? present(r.yogaWellness.experienceLevel)&&r.yogaWellness.primaryIntentions.length>0 : present(r.athletePerformance.sport)&&present(r.athletePerformance.currentLevel)&&r.athletePerformance.performancePriorities.length>0) && (!r.rugbySupplement.enabled || present(r.rugbySupplement.experienceYears)&&r.rugbySupplement.formats.length>0&&present(r.rugbySupplement.primaryPosition));
  return {pathway_selection:selected.length>=1&&selected.length<=2&&selected.includes(r.pathwaySelection.primary),identity_profile:present(r.identity.fullName)&&present(r.identity.phone)&&present(r.identity.cityState)&&present(r.identity.preferredCommunication)&&present(r.identity.emergencyContactName)&&present(r.identity.emergencyContactPhone)&&present(r.profile.dateOfBirth)&&r.profile.heightCm!=null,goals:present(r.goals.primaryGoal)&&present(r.goals.successDefinition),health_safety:r.healthSafety.receivingTreatmentOrRehab!==null&&present(r.healthSafety.believesExerciseIsSafe)&&r.healthSafety.medicalDisclaimerConsent===true,training_context:present(r.trainingContext.activeDaysPerWeek)&&present(r.trainingContext.selfRatedFitnessLevel),schedule:r.schedule.availableDays.length>0&&r.schedule.availableTimes.length>0&&present(r.schedule.realisticSessionsPerWeek),pathway_details:pathwayComplete,final_review:["submitted","needs_review","approved"].includes(r.status)};
}
function incompleteIssues(r) {
  const issues=[]; const add=(step,path,message)=>issues.push({step,path,message});
  if(!r.pathwaySelection.selected.length)add("pathway_selection","pathwaySelection.selected","Pathway Selection: Choose at least one pathway.");
  else if(!r.pathwaySelection.selected.includes(r.pathwaySelection.primary))add("pathway_selection","pathwaySelection.primary","Pathway Selection: Choose a primary pathway.");
  for(const [path,message] of [["identity.fullName","Enter your full name."],["identity.phone","Enter your phone number."],["identity.cityState","Enter your city and state."],["identity.preferredCommunication","Enter your preferred communication method."],["identity.emergencyContactName","Enter an emergency contact name."],["identity.emergencyContactPhone","Enter an emergency contact phone number."],["profile.dateOfBirth","Enter your date of birth."],["profile.heightCm","Enter your height."]])if(!present(path.split(".").reduce((v,k)=>v?.[k],r)))add("identity_profile",path,`Identity Profile: ${message}`);
  if(!present(r.goals.primaryGoal))add("goals","goals.primaryGoal","Goals: Enter your primary goal."); if(!present(r.goals.successDefinition))add("goals","goals.successDefinition","Goals: Describe what success looks like.");
  if(r.healthSafety.receivingTreatmentOrRehab===null)add("health_safety","healthSafety.receivingTreatmentOrRehab","Health & Safety: Answer whether you are receiving treatment or rehab."); if(!present(r.healthSafety.believesExerciseIsSafe))add("health_safety","healthSafety.believesExerciseIsSafe","Health & Safety: Answer whether you believe exercise is safe for you."); if(r.healthSafety.medicalDisclaimerConsent!==true)add("health_safety","healthSafety.medicalDisclaimerConsent","Health & Safety: Confirm the fitness guidance disclaimer.");
  if(!present(r.trainingContext.activeDaysPerWeek))add("training_context","trainingContext.activeDaysPerWeek","Training Context: Enter how many days per week you currently train."); if(!present(r.trainingContext.selfRatedFitnessLevel))add("training_context","trainingContext.selfRatedFitnessLevel","Training Context: Enter your self-rated fitness level.");
  if(!r.schedule.availableDays.length)add("schedule","schedule.availableDays","Schedule: Choose at least one available day."); if(!r.schedule.availableTimes.length)add("schedule","schedule.availableTimes","Schedule: Choose at least one available time."); if(!present(r.schedule.realisticSessionsPerWeek))add("schedule","schedule.realisticSessionsPerWeek","Schedule: Enter how many sessions per week you can realistically complete.");
  const selected=r.pathwaySelection.selected; if(selected.includes("general_fitness")&&!present(r.generalFitness.weightChangeGoal))add("pathway_details","generalFitness.weightChangeGoal","Pathway Details: Choose your General Fitness objective."); if(selected.includes("yoga_wellness")){if(!present(r.yogaWellness.experienceLevel))add("pathway_details","yogaWellness.experienceLevel","Pathway Details: Enter your Yoga & Wellness experience level.");if(!r.yogaWellness.primaryIntentions.length)add("pathway_details","yogaWellness.primaryIntentions","Pathway Details: Choose a Yoga & Wellness intention.");} if(selected.includes("athlete_performance")){if(!present(r.athletePerformance.sport))add("pathway_details","athletePerformance.sport","Pathway Details: Choose your sport.");if(!present(r.athletePerformance.currentLevel))add("pathway_details","athletePerformance.currentLevel","Pathway Details: Enter your current level.");if(!r.athletePerformance.performancePriorities.length)add("pathway_details","athletePerformance.performancePriorities","Pathway Details: Choose a performance priority.");} if(r.rugbySupplement.enabled){if(!present(r.rugbySupplement.experienceYears))add("pathway_details","rugbySupplement.experienceYears","Pathway Details: Enter your rugby experience.");if(!r.rugbySupplement.formats.length)add("pathway_details","rugbySupplement.formats","Pathway Details: Choose a rugby format.");if(!present(r.rugbySupplement.primaryPosition))add("pathway_details","rugbySupplement.primaryPosition","Pathway Details: Enter your primary position.");}
  return issues;
}
function recalc(r) { r.healthSafety.healthFlags=flags(r.healthSafety); const states=sectionState(r); r.completedSteps=STEPS.filter(s=>states[s]); const next=STEPS.find(s=>!states[s])||null; return {totalRequiredSteps:STEPS.length,completedCount:r.completedSteps.length,currentStep:r.currentStep,nextRequiredStep:next,sectionStatuses:Object.fromEntries(STEPS.map(s=>[s,states[s]?"complete":(s===r.currentStep?"in_progress":"not_started")])),overallStatus:r.status,healthReviewStatus:r.healthSafety.healthFlags.length?"review_required":"not_required",selectedPathways:r.pathwaySelection.selected}; }
function migrate(user) { const r=defaults(), p=user.profile||{}, i=user.clientIntake||{}, g=user.goalsBaseline||{}, warnings=[]; r.identity.fullName=present(i.name)?i.name:null; r.profile.heightCm=i.heightCm??p.height_cm??p.heightCm??null; r.profile.weightKg=i.weightKg??p.weight_kg??p.weightKg??null; r.goals.primaryGoal=present(g.goal)?(LEGACY_GOAL_LABELS[g.goal]||g.goal):null; r.goals.secondaryGoals=(i.goals||[]).filter(present).slice(0,3); r.healthSafety.currentPainOrInjury=(i.injuries||[]).filter(present).join("; ")||null; r.healthSafety.details=(p.injuries||[]).filter(present).join("; ")||null; r.healthSafety.medicalDisclaimerConsent=i.medicalDisclaimerConsent===true; r.trainingContext.availableEquipment=(i.equipment||[]).filter(x=>present(x)&&String(x).toLowerCase()!=="bodyweight"); r.schedule.limitations=present(i.schedule)?i.schedule:null; if(r.goals.primaryGoal) warnings.push("Legacy goal retained for member confirmation; no pathway was inferred."); r.migration={migratedFromLegacy:Boolean(user.profile||user.clientIntake||user.goalsBaseline),migratedAt:iso(),migrationWarnings:warnings}; return r; }
function deepMerge(base, patch) { const out={...base}; for(const [k,v] of Object.entries(patch)) out[k]=v&&typeof v==="object"&&!Array.isArray(v)?deepMerge(base[k]||{},v):v; return out; }
function normalizeLegacyNumbers(r) {
  for (const [section,key,min,max] of [["trainingContext","activeDaysPerWeek",1,7],["schedule","realisticSessionsPerWeek",1,7],["schedule","preferredSessionMinutes",15,180]]) {
    const value=r[section]?.[key];
    if (typeof value === "string" && /^\d+$/.test(value.trim())) { const n=Number(value); if(Number.isSafeInteger(n)&&n>=min&&n<=max)r[section][key]=n; }
  }
  return r;
}
function createJourneyIntakeService({userStore}) {
  function ensure(userId) { let r; userStore.updateUser(userId,u=>{ if(!u.memberJourneyProfile)u.memberJourneyProfile=migrate(u); r=normalizeLegacyNumbers(u.memberJourneyProfile); return u; }); return r; }
  function get(userId){const intake=ensure(userId);const progress=recalc(intake);const journeyProfile=deriveJourneyProfile(intake);return{userId,intake,progress,journeyProfile};}
  function patch(userId,input){const clean=validateJourneyPatch(input);let intake;userStore.updateUser(userId,u=>{const prior=u.memberJourneyProfile||migrate(u); intake=deepMerge(prior,clean); const selected=intake.pathwaySelection.selected; const expectedGeneral=selected.includes("general_fitness"),expectedYoga=selected.includes("yoga_wellness"),expectedAthlete=selected.includes("athlete_performance"),expectedRugby=expectedAthlete&&String(intake.athletePerformance.sport).toLowerCase()==="rugby"; for(const [name,expected] of [["generalFitness",expectedGeneral],["yogaWellness",expectedYoga],["athletePerformance",expectedAthlete],["rugbySupplement",expectedRugby]]) if(clean[name]&&Object.hasOwn(clean[name],"enabled")&&clean[name].enabled!==expected) throw new ApiError("VALIDATION_ERROR",`${name}.enabled must match pathway selection`,400,{field:`${name}.enabled`}); intake.selectedPathways=[...selected];intake.primaryPathway=intake.pathwaySelection.primary; intake.generalFitness.enabled=expectedGeneral;intake.yogaWellness.enabled=expectedYoga;intake.athletePerformance.enabled=expectedAthlete; intake.rugbySupplement.enabled=expectedRugby; validatePathwayConsistency(intake); intake.updatedAt=iso();intake.lastSavedAt=intake.updatedAt;recalc(intake);u.memberJourneyProfile=intake;return u;});return{userId,intake,progress:recalc(intake)};}
  function submit(userId){let result;userStore.updateUser(userId,u=>{const r=u.memberJourneyProfile||migrate(u);validatePathwayConsistency(r);const progress=recalc(r);const incomplete=incompleteIssues(r);if(incomplete.length)throw new ApiError("VALIDATION_ERROR","Intake is incomplete",400,{fields:[...new Set(incomplete.map(x=>x.step))],incomplete});r.completedSteps=[...STEPS];r.status=r.healthSafety.healthFlags.length?"needs_review":"submitted";r.submittedAt=iso();r.updatedAt=r.submittedAt;r.currentStep="final_review";u.memberJourneyProfile=r;u.journeyProfile=deriveJourneyProfile(r);u.programRecommendation={recommendedProgram:u.journeyProfile.recommendedProgram,generatedAt:r.submittedAt,generatorVersion:GENERATOR_VERSION,journeyProfileVersion:u.journeyProfile.version};u.generatedWorkoutPlan={plan:buildWorkoutPlan(u.journeyProfile,u.journeyProfile),generatedAt:r.submittedAt,generatorVersion:PLAN_GENERATOR_VERSION,journeyProfileVersion:u.journeyProfile.version,recommendationOnly:true};result={userId,intake:r,progress:recalc(r),journeyProfile:u.journeyProfile,programRecommendation:u.programRecommendation,generatedWorkoutPlan:u.generatedWorkoutPlan};return u;});return result;}
  return {get,patch,submit,progress:userId=>{const x=get(userId);return{userId,...x.progress};}};
}
module.exports={createJourneyIntakeService,STEPS};
