"use strict";
const crypto=require("crypto");
const DAY_MS=24*60*60*1000;
const clean=(v,max=500)=>String(v==null?"":v).trim().slice(0,max);
const iso=v=>new Date(v).toISOString();
// Events must be explicitly confirmed and published; do not present seeded demonstrations as real sessions.
const DEFAULT_EVENTS=Object.freeze([]);
const WEDNESDAY_RESET=Object.freeze({eventId:"wednesday-reset",title:"Wednesday Reset",type:"wellness",dayOfWeek:3,startTime:"18:30",endTime:"19:30",timeZone:"America/Chicago",location:"Vitruvian Park, Addison (pending city approval)",status:"interest_only",minInterested:7,capacity:14,memberPriceCents:0,guestPriceCents:1500,monthlyMembershipCents:2000,description:"Choose a yoga-led flow with sound bowls or a sound-led session with gentle yoga, pranayama and meditation. Interest is not a reservation; sessions require host confirmation."});
function createResidentialCommunityService({userStore,clock=()=>Date.now()}){
 if(!userStore)throw Error("Community Hub requires canonical userStore");
 const ensure=user=>{user.residentialCommunity||={schemaVersion:1,rsvps:[],messages:[]};user.residentialCommunity.rsvps||=[];user.residentialCommunity.messages||=[];user.residentialCommunity.messages=user.residentialCommunity.messages.filter(m=>Date.parse(m.expiresAt)>clock());return user.residentialCommunity};
 const member=user=>Boolean(user?.residentialWellness?.communicationConsent);
 const events=()=>DEFAULT_EVENTS.map(e=>({...e}));
 const weekKey=()=>{const d=new Date(clock());const parts=Object.fromEntries(new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d).filter(p=>p.type!=="literal").map(p=>[p.type,Number(p.value)]));const local=new Date(Date.UTC(parts.year,parts.month-1,parts.day));const hour=Number(new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",hour:"2-digit",hourCycle:"h23"}).format(d));const delta=(3-local.getUTCDay()+7)%7+(local.getUTCDay()===3&&hour>=19?7:0);local.setUTCDate(local.getUTCDate()+delta);return local.toISOString().slice(0,10)};
 function dashboard(userId){const user=userStore.loadUser(userId);if(!member(user))throw Error("Join Community Wellness first");const d=ensure(user),now=clock(),upcoming=events().filter(e=>Date.parse(e.startAt)>=now).sort((a,b)=>Date.parse(a.startAt)-Date.parse(b.startAt));const users=userStore.listUsers().filter(member);const votes=users.map(u=>u.residentialCommunity?.wednesdayInterest).filter(v=>v?.attending==="yes"&&v.weekKey===weekKey());return{wednesdayReset:{...WEDNESDAY_RESET,interestedCount:votes.length,remainingToMinimum:Math.max(0,WEDNESDAY_RESET.minInterested-votes.length),remainingCapacity:Math.max(0,WEDNESDAY_RESET.capacity-votes.length),focusVotes:{yoga:votes.filter(v=>v.focus==="yoga").length,sound:votes.filter(v=>v.focus==="sound").length},myVote:d.wednesdayInterest?.weekKey===weekKey()?d.wednesdayInterest:null},profile:user.residentialWellness,events:upcoming,rsvps:[...d.rsvps],nextEvent:upcoming[0]||null,stats:{members:users.length,upcomingEvents:upcoming.length,totalRsvps:users.reduce((n,u)=>n+(u.residentialCommunity?.rsvps?.length||0),0)}}}
 function rsvp(userId,eventId,attending=true){const event=DEFAULT_EVENTS.find(e=>e.eventId===clean(eventId,100));if(!event)throw Error("Event not found");if(event.status!=="confirmed")throw Error("RSVP opens when this event is confirmed");let result;userStore.updateUser(userId,user=>{if(!member(user))throw Error("Join Community Wellness first");const d=ensure(user);d.rsvps=d.rsvps.filter(x=>x.eventId!==event.eventId);if(attending)d.rsvps.push({eventId:event.eventId,status:"going",updatedAt:iso(clock())});result={eventId:event.eventId,status:attending?"going":"not_going"};return user});return result}
 function interest(userId,input={}){const attending=clean(input.attending,10),focus=clean(input.focus,10);if(!["yes","maybe"].includes(attending)||!["yoga","sound"].includes(focus))throw Error("Choose attendance and session focus");let result;const current=weekKey();const active=userStore.listUsers().filter(member).filter(u=>u.residentialCommunity?.wednesdayInterest?.weekKey===current&&u.residentialCommunity.wednesdayInterest.attending==="yes");const previous=userStore.loadUser(userId)?.residentialCommunity?.wednesdayInterest;if(attending==="yes"&&active.length>=WEDNESDAY_RESET.capacity&&!(previous?.weekKey===current&&previous.attending==="yes"))throw Error("Interest list is full for this week");userStore.updateUser(userId,user=>{if(!member(user))throw Error("Join Community Wellness first");const d=ensure(user);d.wednesdayInterest={attending,focus,weekKey:current,updatedAt:iso(clock())};result=d.wednesdayInterest;return user});return result}
 function post(userId,input={}){const body=clean(input.text,1000);if(!body)throw Error("Message cannot be empty");let result;userStore.updateUser(userId,user=>{if(!member(user))throw Error("Join Community Wellness first");const d=ensure(user);const displayName=clean(user.displayName||user.name||user.email?.split("@")[0]||"Community Member",80);result={messageId:"wellness_msg_"+crypto.randomUUID(),userId,displayName,text:body,createdAt:iso(clock()),expiresAt:iso(clock()+DAY_MS)};d.messages.push(result);return user});return result}
 function messages(userId){const reader=userStore.loadUser(userId);if(!member(reader))throw Error("Join Community Wellness first");const all=[];for(const listed of userStore.listUsers().filter(member)){const before=listed.residentialCommunity?.messages?.length||0;const d=ensure(listed);if(d.messages.length!==before)userStore.updateUser(listed.userId,user=>{ensure(user);return user});all.push(...d.messages)}return all.sort((a,b)=>Date.parse(a.createdAt)-Date.parse(b.createdAt))}
 function diagnostic(userId){const user=userStore.loadUser(userId),d=user?ensure(user):null;const checks=[{id:"membership",result:member(user)?"PASS":"FAIL"},{id:"event_catalog",result:Array.isArray(DEFAULT_EVENTS)?"PASS":"FAIL"},{id:"chat_retention",result:d?.messages?.every(m=>Date.parse(m.expiresAt)>clock())?"PASS":"FAIL"}];return{diagnosticVersion:"residential-community-hub-v1",firstFailure:checks.find(c=>c.result==="FAIL")?.id||null,checks}}
 return{dashboard,rsvp,interest,post,messages,diagnostic,DAY_MS};
}
module.exports={createResidentialCommunityService,DEFAULT_EVENTS,DAY_MS};
