"use strict";

const crypto = require("node:crypto");

const SOURCE_RANK=Object.freeze({verified_geometry:0,trail_network:1,park_constrained_walking_route:2,google_walking_route:3,place_only:4});
const SOURCE_POINTS=Object.freeze({verified_geometry:30,trail_network:26,park_constrained_walking_route:20,google_walking_route:12,place_only:0});
const PACES_SECONDS_PER_MILE=Object.freeze({walking:20*60,jogging:12*60,running:9*60});
const DEFAULT_DISTINCTNESS=Object.freeze({coordinatePrecision:5,overlapThreshold:.94,distanceDifferencePercent:2,sampleMeters:25});

const validPoint=p=>Number.isFinite(Number(p?.latitude))&&Number(p.latitude)>=-90&&Number(p.latitude)<=90&&Number.isFinite(Number(p?.longitude))&&Number(p.longitude)>=-180&&Number(p.longitude)<=180;
const geometryKey=(points,precision=5)=>points.map(p=>`${Number(p.latitude).toFixed(precision)},${Number(p.longitude).toFixed(precision)}`).join(";");
function routeFingerprint(route,{coordinatePrecision=5}={}){
  if(!Array.isArray(route?.polyline)||route.polyline.length<2||!route.polyline.every(validPoint))return null;
  const forward=geometryKey(route.polyline,coordinatePrecision),reverse=geometryKey([...route.polyline].reverse(),coordinatePrecision),canonical=forward<reverse?forward:reverse;
  return crypto.createHash("sha256").update(`${route.routeSource||"unknown"}|${canonical}`).digest("hex").slice(0,24);
}
const radians=n=>n*Math.PI/180;
function distance(a,b){const dLat=radians(b.latitude-a.latitude),dLon=radians(b.longitude-a.longitude),q=Math.sin(dLat/2)**2+Math.cos(radians(a.latitude))*Math.cos(radians(b.latitude))*Math.sin(dLon/2)**2;return 12742000*Math.atan2(Math.sqrt(q),Math.sqrt(1-q));}
function geometryOverlap(a,b,{sampleMeters=25}={}){if(!a?.length||!b?.length)return 0;const shorter=a.length<=b.length?a:b,longer=shorter===a?b:a;let matched=0;for(const point of shorter)if(longer.some(other=>distance(point,other)<=sampleMeters))matched++;return matched/shorter.length;}
function routesAreDistinct(a,b,config={}){const settings={...DEFAULT_DISTINCTNESS,...config},af=a.routeId||routeFingerprint(a,settings),bf=b.routeId||routeFingerprint(b,settings);if(af&&af===bf)return false;const ae=a.graphEdgeIds||a.edgeIds,be=b.graphEdgeIds||b.edgeIds;if(Array.isArray(ae)&&Array.isArray(be)){const x=ae.join("|"),y=be.join("|");if(x===y||x===be.slice().reverse().join("|"))return false;}const difference=Math.abs(Number(a.estimatedDistanceMeters)-Number(b.estimatedDistanceMeters))/Math.max(1,Number(a.estimatedDistanceMeters),Number(b.estimatedDistanceMeters))*100;return !(difference<=settings.distanceDifferencePercent&&geometryOverlap(a.polyline,b.polyline,settings)>=settings.overlapThreshold);
}
const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,n));
function component(score,maximum,explanation,available=true){return{score:Math.round(score*10)/10,maximum,available,explanation};}
function scoreRoute(route){
  if(route.routeSource!=="place_only"&&(!Array.isArray(route.polyline)||route.polyline.length<2||!route.polyline.every(validPoint)))return null;
  const source=component(SOURCE_POINTS[route.routeSource]??0,30,`Source tier: ${route.routeSourceLabel||route.routeSource||"unknown"}.`);
  const adherence=route.trailAdherencePercent==null?component(0,22,"Not scored because validated trail geometry is unavailable.",false):component(22*clamp(route.trailAdherencePercent)/100,22,`${Math.round(route.trailAdherencePercent)}% alignment with mapped trail geometry.`);
  const containment=route.parkContainmentPercent==null&&route.insideParkPercent==null?component(6,12,"Neutral score because no usable park boundary is available.",false):component(12*clamp(route.parkContainmentPercent??route.insideParkPercent)/100,12,`${Math.round(route.parkContainmentPercent??route.insideParkPercent)}% inside the mapped park boundary.`);
  const error=clamp(Number(route.distanceErrorPercent)||0,0,100),accuracy=component(18*Math.max(0,1-error/35),18,route.withinTolerance?"Within the configured distance tolerance.":`${error.toFixed(1)}% absolute distance error.`);
  const complexity=Math.max(0,Number(route.instructionComplexity)||0),simplicity=component(8*Math.max(.25,1-complexity/8),8,"Rewards an understandable loop or turnaround structure.");
  const repeated=route.repeatedEdgePercent==null?component(2.5,5,"Neutral score because repeated-edge data is unavailable.",false):component(5*(route.routeType==="out_and_back"?1:1-clamp(route.repeatedEdgePercent)/100),5,route.routeType==="out_and_back"?"Intentional return path is not penalized.":"Rewards avoiding unnecessary repeated edges.");
  const crossings=route.roadCrossingCount==null?component(2.5,5,"Neutral score because road-crossing data is unavailable.",false):component(5*Math.max(0,1-Number(route.roadCrossingCount)/5),5,`${route.roadCrossingCount} mapped road crossing${route.roadCrossingCount===1?"":"s"}.`);
  const qualityComponents={sourceQuality:source,trailAdherence:adherence,parkContainment:containment,distanceAccuracy:accuracy,routeSimplicity:simplicity,repeatedEdgeQuality:repeated,roadCrossingQuality:crossings};
  let qualityScore=Math.round(Object.values(qualityComponents).reduce((sum,item)=>sum+item.score,0));
  if(route.routeSource==="place_only")qualityScore=Math.min(15,qualityScore);if(route.confidence==="low")qualityScore=Math.min(60,qualityScore);if(route.confidence==="unavailable")qualityScore=Math.min(15,qualityScore);if(route.severeWarning)qualityScore=Math.min(45,qualityScore);
  return{qualityScore:clamp(qualityScore),qualityComponents};
}
function reasons(route){const result=[];if(route.trailAdherencePercent>=90)result.push("Stays closely aligned with mapped trails.");if(route.withinTolerance)result.push(`Matches your distance goal within ${Math.max(1,Math.round(route.distanceErrorPercent))}%.`);if(Number.isInteger(route.loopCount)&&route.loopCount>0)result.push(`Uses ${route.loopCount} complete loop${route.loopCount===1?"":"s"}.`);if((route.parkContainmentPercent??route.insideParkPercent)>=80)result.push("Mostly remains inside the mapped park boundary.");if(route.repeatedEdgePercent!=null&&route.repeatedEdgePercent<10)result.push("Avoids unnecessary repeated trail segments.");if(!result.length&&route.routeSource==="google_walking_route")result.push("Best available option, although mapped trail geometry was unavailable.");return result.slice(0,3);}
function unsafeGoogle(route){return route.routeSource==="google_walking_route"&&((route.trailAdherencePercent!=null&&route.trailAdherencePercent<70)||(route.parkContainmentPercent!=null&&route.parkContainmentPercent<70));}
function compareRoutes(a,b){if(unsafeGoogle(a)!==unsafeGoogle(b))return unsafeGoogle(a)?1:-1;const source=(SOURCE_RANK[a.routeSource]??9)-(SOURCE_RANK[b.routeSource]??9);if(source)return source;return (b.trailAdherencePercent??-1)-(a.trailAdherencePercent??-1)||(b.parkContainmentPercent??b.insideParkPercent??-1)-(a.parkContainmentPercent??a.insideParkPercent??-1)||Number(b.withinTolerance)-Number(a.withinTolerance)||Math.abs(a.distanceErrorMeters??Infinity)-Math.abs(b.distanceErrorMeters??Infinity)||(a.roadCrossingCount??Infinity)-(b.roadCrossingCount??Infinity)||(a.repeatedEdgePercent??Infinity)-(b.repeatedEdgePercent??Infinity)||(a.instructionComplexity??Infinity)-(b.instructionComplexity??Infinity)||(b.qualityScore??0)-(a.qualityScore??0);
}
function normalizeOptions(options,{requestedTargetDistanceMeters,goalRevision=0,now=Date.now(),limit=3,distinctness}={}){const prepared=[];for(const original of options||[]){const route={...original};if(route.routeSource!=="place_only"&&(!Array.isArray(route.polyline)||route.polyline.length<2||!route.polyline.every(validPoint)))continue;route.routeFingerprint=routeFingerprint(route);route.routeId=route.routeId||route.routeFingerprint;route.targetDistanceMeters=Number(route.targetDistanceMeters??requestedTargetDistanceMeters);route.requestedTargetDistanceMeters=Number(requestedTargetDistanceMeters??route.targetDistanceMeters);route.start=route.start||route.startPoint||route.polyline?.[0]||null;route.turnaround=route.turnaround??route.turnaroundPoint??null;route.finish=route.finish||route.endPoint||route.polyline?.at?.(-1)||null;route.partialLoopDistanceMeters=route.partialLoopDistanceMeters??route.partialLoopDistance??0;route.parkContainmentPercent=route.parkContainmentPercent??route.insideParkPercent??null;route.repeatedEdgePercent=route.repeatedEdgePercent??null;route.roadCrossingCount=route.roadCrossingCount??route.roadCrossings??null;route.maximumTrailDeviationMeters=route.maximumTrailDeviationMeters??route.maxTrailDeviationMeters??null;const scored=scoreRoute(route);if(!scored)continue;Object.assign(route,scored);const miles=Number(route.estimatedDistanceMeters)/1609.344;route.estimatedDurationWalkingSeconds=Math.round(miles*PACES_SECONDS_PER_MILE.walking);route.estimatedDurationJoggingSeconds=Math.round(miles*PACES_SECONDS_PER_MILE.jogging);route.estimatedDurationRunningSeconds=Math.round(miles*PACES_SECONDS_PER_MILE.running);route.recommendationReasons=reasons(route);route.generatedAt=route.generatedAt||new Date(now).toISOString();route.expiresAt=route.expiresAt??new Date(now+15*60_000).toISOString();route.goalRevision=Number(goalRevision)||0;route.recommended=false;prepared.push(route);}prepared.sort(compareRoutes);const distinct=[];for(const route of prepared)if(distinct.every(existing=>routesAreDistinct(route,existing,distinctness))&&distinct.length<limit)distinct.push(route);if(distinct.length)distinct[0].recommended=true;return distinct;}

module.exports={SOURCE_RANK,SOURCE_POINTS,PACES_SECONDS_PER_MILE,DEFAULT_DISTINCTNESS,routeFingerprint,geometryOverlap,routesAreDistinct,scoreRoute,compareRoutes,normalizeOptions};
