"use strict";
const crypto = require("crypto");
const { ApiError } = require("../lib/apiResponse");
const { ACTIVITY_TYPES, ACTIVE_CHALLENGE_METRICS, DEFAULT_PRIVACY, BADGES, MILE_METERS } = require("../stepping/domain");
const { acceptedPoints, activityMetrics } = require("../stepping/activityMetrics");
const id = (prefix) => `${prefix}_${crypto.randomUUID()}`;
const iso = (value = Date.now()) => new Date(value).toISOString();
const CHALLENGES = Object.freeze([
  { challengeId:"move_10k", name:"Move 10K", metric:"distance", target:10000, startsAt:"2026-01-01T00:00:00.000Z", endsAt:"2027-01-01T00:00:00.000Z", verificationRequirements:"Verified GPS activities only" },
  { challengeId:"three_active_days", name:"Three Active Days", metric:"active_days", target:3, startsAt:"2026-01-01T00:00:00.000Z", endsAt:"2027-01-01T00:00:00.000Z", verificationRequirements:"One or more verified GPS activities on three UTC days" },
  { challengeId:"community_100k", name:"Greatness Together 100K", metric:"community_distance", target:100000, startsAt:"2026-01-01T00:00:00.000Z", endsAt:"2027-01-01T00:00:00.000Z", verificationRequirements:"Active Movement members and verified GPS activities only" }
]);
function ensureDomain(user) { user.steppingIntoGreatness ||= { schemaVersion:2, activities:[], achievements:[], personalBests:{}, memberships:[], feedEvents:[], contributions:[], enrollments:[] }; const d=user.steppingIntoGreatness; d.enrollments ||= []; return d; }
function validateCompletion(input) { const reasons=[]; if((input.gpsQuality?.acceptedSamples||0)<2) reasons.push("insufficient_accepted_points"); if(input.gpsQuality?.suspiciousMovementDetected) reasons.push("suspicious_movement"); if(["poor","unavailable"].includes(input.gpsQuality?.rating)) reasons.push("poor_gps_quality"); if(!Number.isFinite(input.distanceMeters)||input.distanceMeters<0) reasons.push("invalid_distance"); const state=reasons.includes("invalid_distance")||reasons.includes("insufficient_accepted_points")?"invalid":reasons.length?"questionable":"valid"; const eligible=state==="valid"&&input.sourceType==="sig_gps"; return {state,reasons,challengeEligible:eligible,personalBestEligible:eligible,rankingEligible:eligible}; }
function createSteppingIntoGreatnessService({userStore,clock=()=>Date.now()}) {
 const activeMembership=(d)=>d.memberships.find(m=>m.communityId==="greatness_movement"&&m.status==="active")||null;
 function membership(userId){return activeMembership(ensureDomain(userStore.loadUser(userId)));}
 function join(userId,preferences={}){let result; userStore.updateUser(userId,user=>{const d=ensureDomain(user); let m=d.memberships.find(x=>x.communityId==="greatness_movement"); const visibilityPreferences={showActivities:true,showBadges:true,showPersonalRecords:true,showLifetimeDistance:true,...preferences}; if(m)Object.assign(m,{status:"active",visibilityPreferences,leftAt:null});else{m={membershipId:id("membership"),communityId:"greatness_movement",userId,status:"active",joinedAt:iso(clock()),visibilityPreferences};d.memberships.push(m);}result=m;return user;});return result;}
 function leave(userId){let result;userStore.updateUser(userId,user=>{const d=ensureDomain(user);result=d.memberships.find(m=>m.communityId==="greatness_movement");if(!result)throw new ApiError("MEMBERSHIP_NOT_FOUND","Community membership not found",404);result.status="left";result.leftAt=iso(clock());return user;});return result;}
 function enroll(userId,challengeId){const challenge=CHALLENGES.find(c=>c.challengeId===challengeId);if(!challenge)throw new ApiError("CHALLENGE_NOT_FOUND","Challenge not found",404);let result;userStore.updateUser(userId,user=>{const d=ensureDomain(user);result=d.enrollments.find(e=>e.challengeId===challengeId);if(!result){result={enrollmentId:id("enrollment"),challengeId,userId,enrolledAt:iso(clock()),status:"active"};d.enrollments.push(result);}return user;});return result;}
 function challengeList(userId){const d=ensureDomain(userStore.loadUser(userId));return CHALLENGES.map(c=>{const enrollment=d.enrollments.find(e=>e.challengeId===c.challengeId);const contributions=d.contributions.filter(x=>x.challengeId===c.challengeId&&!x.revoked);let progress;if(c.metric==="active_days")progress=new Set(contributions.map(x=>x.activeDay)).size;else progress=contributions.reduce((s,x)=>s+x.amount,0);return {...c,enrolled:Boolean(enrollment),progress,completed:progress>=c.target};});}
 function records(d,activity,now){const candidates={ [`longest_${activity.activityType}`]:{value:activity.distanceMeters,unit:"meters"}, longest_overall_activity:{value:activity.distanceMeters,unit:"meters"}, ...(activity.elevationGainMeters!=null?{greatest_elevation_gain:{value:activity.elevationGainMeters,unit:"meters"}}:{})}; for(const [unit,splits] of [["mile",activity.splits.miles],["kilometer",activity.splits.kilometers]]){const fastest=splits.filter(s=>s.complete).sort((a,b)=>a.durationMs-b.durationMs)[0];if(fastest)candidates[`fastest_${unit}`]={value:fastest.durationMs,unit:"milliseconds"};} for(const [distance,key] of [[5000,"fastest_5k"],[10000,"fastest_10k"]])if(activity.distanceMeters>=distance)candidates[key]={value:activity.movingTimeMs*(distance/activity.distanceMeters),unit:"milliseconds",lower:true}; const earned=[];for(const [recordType,c] of Object.entries(candidates)){const old=d.personalBests[recordType];const improves=!old||(c.lower?c.value<old.value:c.value>old.value);if(improves){d.personalBests[recordType]={recordType,value:c.value,unit:c.unit,activityId:activity.activityId,earnedAt:now,previousValue:old?.value};earned.push(recordType);}}return earned; }
 function complete(userId,input){if(!ACTIVITY_TYPES.includes(input?.activityType))throw new ApiError("INVALID_ACTIVITY_TYPE","Choose walk, jog, run, trail walk, or trail run",400);if(input.stepCount!=null)throw new ApiError("UNTRUSTED_STEP_COUNT","Browser GPS activities cannot submit step counts",400);let result;userStore.updateUser(userId,user=>{const d=ensureDomain(user);const existing=d.activities.find(a=>input.clientSessionId&&a.clientSessionId===input.clientSessionId);if(existing){result={...existing,duplicateCompletion:true};return user;}const now=iso(clock()),validation=validateCompletion({...input,sourceType:"sig_gps"}),privacy={...DEFAULT_PRIVACY,...input.privacy},member=activeMembership(d),points=acceptedPoints(input.samples),computed=activityMetrics(points);const activity={activityId:id("activity"),clientSessionId:input.clientSessionId||null,userId,activityType:input.activityType,status:validation.state==="invalid"?"invalid":"completed",sourceType:"sig_gps",startedAt:iso(input.startedAt),endedAt:iso(input.endedAt),elapsedTimeMs:Math.max(0,Number(input.elapsedTimeMs)||0),movingTimeMs:Math.max(0,Number(input.movingTimeMs)||0),pausedTimeMs:Math.max(0,Number(input.pausedTimeMs)||0),distanceMeters:Math.max(0,Number(input.distanceMeters)||0),elevationGainMeters:computed.elevation?.meters, elevationEstimated:Boolean(computed.elevation),averagePaceSecondsPerKilometer:input.distanceMeters>0?(Number(input.movingTimeMs)/1000)/(input.distanceMeters/1000):undefined,splits:{miles:computed.mileSplits,kilometers:computed.kilometerSplits},route:{points,acceptedPointCount:input.gpsQuality?.acceptedSamples||points.length,rejectedPointCount:input.gpsQuality?.rejectedSamples||0,visibility:"private",simplification:"uniform_limit_2000"},gpsQuality:input.gpsQuality||{rating:"unavailable",acceptedSamples:0,rejectedSamples:0},verificationLevel:validation.state==="valid"?"verified":"unverified",validation,privacy,challengeContributionIds:[],achievementIds:[],personalRecordsEarned:[],schemaVersion:2,createdAt:now,updatedAt:now};d.activities.push(activity);
 if(validation.personalBestEligible){activity.personalRecordsEarned=records(d,activity,now);for(const record of Object.values(d.personalBests))if(record.unit==="meters")record.valueMeters=record.value;}
 if(validation.challengeEligible){for(const enrollment of d.enrollments){const challenge=CHALLENGES.find(c=>c.challengeId===enrollment.challengeId);if(!challenge||clock()<Date.parse(challenge.startsAt)||clock()>=Date.parse(challenge.endsAt)||(challenge.metric==="community_distance"&&!member))continue;const amount=challenge.metric.includes("distance")?activity.distanceMeters:challenge.metric==="duration"?activity.movingTimeMs:1;const contribution={contributionId:id("contribution"),userId,activityId:activity.activityId,challengeId:challenge.challengeId,metric:challenge.metric,amount,activeDay:activity.endedAt.slice(0,10),source:"sig_gps",verificationState:"verified",createdAt:now,revoked:false,revocationReason:null};d.contributions.push(contribution);activity.challengeContributionIds.push(contribution.contributionId);}}
 if(validation.personalBestEligible){const eligible=d.activities.filter(a=>a.validation.personalBestEligible),lifetime=eligible.reduce((s,a)=>s+a.distanceMeters,0),days=[...new Set(eligible.map(a=>a.endedAt.slice(0,10)))].sort(),streak=days.reduce((best,day,i)=>{let n=1;while(i+n<days.length&&(Date.parse(days[i+n])-Date.parse(days[i+n-1]))===86400000)n++;return Math.max(best,n);},0),values={activity_count:eligible.length,walk_count:eligible.filter(a=>["walk","trail_walk"].includes(a.activityType)).length,run_count:eligible.filter(a=>["run","jog","trail_run"].includes(a.activityType)).length,trail_count:eligible.filter(a=>a.activityType.startsWith("trail")).length,single_distance:activity.distanceMeters,lifetime_distance:lifetime,active_day_streak:streak};for(const badge of BADGES)if((values[badge.metric]||0)>=badge.threshold&&!d.achievements.some(a=>a.achievementKey===badge.achievementKey)){const award={achievementId:id("achievement"),achievementKey:badge.achievementKey,name:badge.name,activityId:activity.activityId,earnedAt:now};d.achievements.push(award);activity.achievementIds.push(award.achievementId);}}
 if(member&&privacy.activityVisibleToCommunity&&member.visibilityPreferences.showActivities)d.feedEvents.push({eventId:id("event"),communityId:"greatness_movement",userId,activityId:activity.activityId,eventType:"activity_completed",summaryData:{activityType:activity.activityType,distanceMeters:activity.distanceMeters,durationMs:activity.movingTimeMs,...(privacy.paceVisible?{averagePaceSecondsPerKilometer:activity.averagePaceSecondsPerKilometer}:{})},visibility:"community",createdAt:now});result=activity;return user;});return result;}
 function journey(userId){const d=ensureDomain(userStore.loadUser(userId)),activities=d.activities.map(a=>({...a,route:{...a.route,points:undefined}}));return{activities,personalBests:d.personalBests,achievements:d.achievements,lifetimeDistanceMeters:activities.filter(a=>a.validation.personalBestEligible).reduce((s,a)=>s+a.distanceMeters,0),membership:activeMembership(d)};}
 function activity(userId,activityId){const a=ensureDomain(userStore.loadUser(userId)).activities.find(x=>x.activityId===activityId);if(!a)throw new ApiError("ACTIVITY_NOT_FOUND","Activity not found",404);return{...a,route:{...a.route,points:undefined}};}
 function route(userId,activityId){const a=ensureDomain(userStore.loadUser(userId)).activities.find(x=>x.activityId===activityId);if(!a)throw new ApiError("ACTIVITY_NOT_FOUND","Activity not found",404);return a.route;}
 function feed(userId){if(!membership(userId))throw new ApiError("COMMUNITY_MEMBERSHIP_REQUIRED","Join The Greatness Movement to view the Movement Feed",403);return userStore.listUsers().flatMap(u=>{const d=ensureDomain(u);return activeMembership(d)?d.feedEvents:[];}).filter(e=>e.visibility==="community").sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,50);}
 function weeklySummary(userId){if(!membership(userId))throw new ApiError("COMMUNITY_MEMBERSHIP_REQUIRED","Join The Greatness Movement to view the weekly summary",403);const end=clock(),start=end-(7*86400000),users=userStore.listUsers(),activities=users.flatMap(u=>ensureDomain(u).activities).filter(a=>a.validation?.state==="valid"&&Date.parse(a.endedAt)>=start&&Date.parse(a.endedAt)<=end);return{timezone:"UTC",periodStartsAt:iso(start),periodEndsAt:iso(end),verifiedActivities:activities.length,verifiedCommunityDistanceMeters:activities.reduce((s,a)=>s+a.distanceMeters,0),activeParticipatingMembers:new Set(activities.map(a=>a.userId)).size,personalRecordsEarned:activities.reduce((s,a)=>s+(a.personalRecordsEarned?.length||0),0),greatnessMarksEarned:activities.reduce((s,a)=>s+(a.achievementIds?.length||0),0)};}
 return{join,leave,membership,enroll,challengeList,complete,journey,activity,feed,weeklySummary,route,validateCompletion};
}
module.exports={createSteppingIntoGreatnessService,validateCompletion,ensureDomain,CHALLENGES};
