"use strict";
const { haversineMeters } = require("../trails/geometry");
const { pointInPolygon } = require("./routeCorridorValidator");

const finitePoint=point=>Number.isFinite(point?.latitude)&&point.latitude>=-90&&point.latitude<=90&&Number.isFinite(point?.longitude)&&point.longitude>=-180&&point.longitude<=180;
const accessible=edge=>edge&&edge.access!=="private"&&edge.access!=="no"&&edge.foot!=="no";

function snapToGraph(point,graph,{preferInsidePark=true}={}){
  let best=null;
  for(const node of Object.values(graph?.nodes||{})){if(!finitePoint(node))continue;const distance=haversineMeters(point,node),inside=pointInPolygon(node,graph.parkBoundary),penalty=preferInsidePark&&inside===false?10000:0;if(!best||distance+penalty<best.score)best={node,distanceMeters:distance,score:distance+penalty};}
  return best&&{...best.node,distanceMeters:best.distanceMeters};
}
function validEdge(graph,edge){const a=graph?.nodes?.[edge?.from],b=graph?.nodes?.[edge?.to],measured=finitePoint(a)&&finitePoint(b)?haversineMeters(a,b):NaN;return accessible(edge)&&edge.from!==edge.to&&finitePoint(a)&&finitePoint(b)&&Number.isFinite(edge.lengthMeters)&&edge.lengthMeters>0&&Number.isFinite(measured)&&measured>0;}
function adjacency(graph){const map=new Map();for(const edge of graph?.edges||[]){if(!validEdge(graph,edge))continue;(map.get(edge.from)||map.set(edge.from,[]).get(edge.from)).push({...edge,next:edge.to});(map.get(edge.to)||map.set(edge.to,[]).get(edge.to)).push({...edge,next:edge.from});}return map;}

/* Enumerate vertex-simple undirected cycles. Requiring the closing edge in the
 * adjacency list prevents coordinate proximity from becoming a fictitious jump. */
function detectSimpleCycles(graph,{maxCycles=128,maxDepth=64}={}){
  const adj=adjacency(graph),cycles=[],seen=new Set(),ids=[...adj.keys()].sort((a,b)=>String(a).localeCompare(String(b)));
  const canonical=edges=>{const values=edges.map(edge=>String(edge.id)).sort();return values.join("|");};
  for(const start of ids){
    const visit=(current,nodes,edges,visited)=>{
      if(cycles.length>=maxCycles||nodes.length>maxDepth)return;
      for(const edge of adj.get(current)||[]){const next=edge.next;if(next===start){if(nodes.length<3)continue;const key=canonical([...edges,edge]);if(!seen.has(key)){seen.add(key);cycles.push({nodeIds:[...nodes,start],edges:[...edges,edge]});}continue;}if(visited.has(next)||String(next).localeCompare(String(start))<0)continue;visited.add(next);visit(next,[...nodes,next],[...edges,edge],visited);visited.delete(next);}
    };
    visit(start,[start],[],new Set([start]));
  }
  return cycles.filter(cycle=>cycle.edges.length>=3&&cycle.edges.every(edge=>validEdge(graph,edge))&&cycle.nodeIds.every(id=>finitePoint(graph.nodes[id])));
}
function pathToDistance(graph,startId,wanted){const adj=adjacency(graph),path=[graph.nodes[startId]],used=new Set(),edges=[];let current=startId,total=0;while(total<wanted){const choices=(adj.get(current)||[]).filter(e=>!used.has(e.id)).sort((a,b)=>(b.parkMembership==="inside")-(a.parkMembership==="inside")||a.lengthMeters-b.lengthMeters),edge=choices[0]||(adj.get(current)||[])[0];if(!edge)break;const next=graph.nodes[edge.next],remaining=wanted-total;if(edge.lengthMeters>remaining){const from=graph.nodes[current],ratio=remaining/edge.lengthMeters;path.push({latitude:from.latitude+(next.latitude-from.latitude)*ratio,longitude:from.longitude+(next.longitude-from.longitude)*ratio});total=wanted;break;}used.add(edge.id);edges.push(edge);path.push(next);total+=edge.lengthMeters;current=edge.next;}return{path,distanceMeters:total,edges};}
function cycleMetrics(graph,cycle){
  const length=cycle.edges.reduce((sum,edge)=>sum+edge.lengthMeters,0),verified=cycle.edges.every(edge=>edge.source==="verified_geometry"||edge.verificationStatus==="admin_verified"),trail=cycle.edges.reduce((sum,edge)=>sum+edge.lengthMeters*(edge.trailAdherencePercent??100)/100,0),inside=graph.parkBoundary?cycle.edges.reduce((sum,edge,index)=>{const a=graph.nodes[cycle.nodeIds[index]],b=graph.nodes[cycle.nodeIds[index+1]],mid={latitude:(a.latitude+b.latitude)/2,longitude:(a.longitude+b.longitude)/2};return sum+(pointInPolygon(mid,graph.parkBoundary)===true?edge.lengthMeters:0);},0):null;
  return{length,verified,trailAdherence:length?trail/length*100:0,parkContainment:inside==null?null:inside/length*100,roadCrossings:cycle.edges.reduce((sum,edge)=>sum+(Number(edge.roadCrossings)||Number(edge.crossings)||0),0)};
}
function rotateCycle(cycle,startId){const nodes=cycle.nodeIds.slice(0,-1),index=nodes.indexOf(startId);if(index<0)return null;return{nodeIds:[...nodes.slice(index),...nodes.slice(0,index),startId],edges:[...cycle.edges.slice(index),...cycle.edges.slice(0,index)]};}
function interpolateLoop(graph,cycle,distance){const points=[graph.nodes[cycle.nodeIds[0]]];let remaining=distance;for(let i=0;remaining>1e-9;i=(i+1)%cycle.edges.length){const edge=cycle.edges[i],from=graph.nodes[cycle.nodeIds[i]],to=graph.nodes[cycle.nodeIds[i+1]],take=Math.min(remaining,edge.lengthMeters);if(take<edge.lengthMeters){const ratio=take/edge.lengthMeters;points.push({latitude:from.latitude+(to.latitude-from.latitude)*ratio,longitude:from.longitude+(to.longitude-from.longitude)*ratio});}else points.push(to);remaining-=take;}return points;}
function loopOption({graph,cycle,target,tolerancePercent}){const metrics=cycleMetrics(graph,cycle),full=Math.floor(target/metrics.length),partial=target-full*metrics.length,polyline=interpolateLoop(graph,cycle,target),estimated=full*metrics.length+partial,error=estimated-target,repeated=Math.max(0,full-1)*cycle.edges.length+(partial>0?Math.ceil(partial/metrics.length*cycle.edges.length):0),instructionParts=[full===1?"Complete one full loop":`Complete ${full} full loops`];if(!full)instructionParts[0]="Follow the loop";if(partial>1e-6)instructionParts.push(`continue ${(partial/1609.344).toFixed(2)} miles along the same loop to the marked finish`);
  return{routeSource:metrics.verified?"verified_geometry":"trail_network",routeSourceLabel:metrics.verified?"Verified trail route":"Trail-network loop",source:metrics.verified?"verified_geometry":"trail_network",sourceLabel:metrics.verified?"Verified trail route":"Trail-network loop",routeType:partial>1e-6?"partial_loop":"loop",targetDistanceMeters:target,estimatedDistanceMeters:estimated,estimatedDistance:estimated,distanceErrorMeters:error,distanceErrorPercent:Math.abs(error)/target*100,distanceError:error,withinTolerance:Math.abs(error)/target*100<=tolerancePercent,polyline,startPoint:polyline[0],turnaroundPoint:null,endPoint:polyline.at(-1),loopCount:full,partialLoopDistance:partial,waypointCount:0,warnings:["Follow posted trail signs, closures, and local conditions."],confidence:metrics.verified?"high":"medium",trailAdherencePercent:metrics.trailAdherence,trailAdherence:metrics.trailAdherence,insideParkPercent:metrics.parkContainment,parkContainment:metrics.parkContainment,roadCrossings:metrics.roadCrossings,repeatedEdges:repeated,instructionComplexity:partial>1e-6?2:1,instructions:`${instructionParts.join(", then ")}.`,associationConfidence:"medium",geometrySource:graph.source,attribution:graph.attribution};}
function rankCycles(options){return options.sort((a,b)=>(a.routeSource==="verified_geometry"?-1:0)-(b.routeSource==="verified_geometry"?-1:0)||(b.trailAdherence??0)-(a.trailAdherence??0)||(b.parkContainment??-1)-(a.parkContainment??-1)||Math.abs(a.distanceError??Infinity)-Math.abs(b.distanceError??Infinity)||(a.roadCrossings??0)-(b.roadCrossings??0)||(a.repeatedEdges??0)-(b.repeatedEdges??0)||(a.instructionComplexity??0)-(b.instructionComplexity??0));}
function outAndBack({target,graph,snapped,tolerancePercent}){const out=pathToDistance(graph,snapped.id,target/2);if(out.path.length<2)return null;const polyline=[...out.path,...out.path.slice(0,-1).reverse()],estimated=out.distanceMeters*2,error=estimated-target,errorPercent=Math.abs(error)/target*100,inside=graph.parkBoundary?polyline.slice(0,-1).filter(p=>pointInPolygon(p,graph.parkBoundary)).length/(polyline.length-1)*100:null;return{routeSource:"trail_network",routeSourceLabel:"Trail-network route",source:"trail_network",sourceLabel:"Trail-network route",routeType:"out_and_back",targetDistanceMeters:target,estimatedDistanceMeters:estimated,estimatedDistance:estimated,distanceErrorMeters:error,distanceErrorPercent:errorPercent,distanceError:error,withinTolerance:errorPercent<=tolerancePercent,polyline,startPoint:polyline[0],turnaroundPoint:out.path.at(-1),endPoint:polyline.at(-1),loopCount:0,partialLoopDistance:0,waypointCount:0,warnings:["Follow posted trail signs, closures, and local conditions."],confidence:"high",trailAdherencePercent:100,trailAdherence:100,insideParkPercent:inside,parkContainment:inside,instructions:`Follow known walking paths for ${(out.distanceMeters/1609.344).toFixed(2)} miles, then return along the same path.`,associationConfidence:"medium",geometrySource:graph.source,attribution:graph.attribution};}
function planTrailGraphRoute({targetDistanceMeters,graph,startPoint,routeType="out_and_back",tolerancePercent=5,onTrace=()=>{}}){const snapped=snapToGraph(startPoint,graph),target=Number(targetDistanceMeters);if(!snapped||!Number.isFinite(target)||target<=0){onTrace(snapped?"no_usable_graph":"start_snap_failed");return[];}if(routeType==="loop"){const loops=detectSimpleCycles(graph).map(cycle=>rotateCycle(cycle,snapped.id)).filter(Boolean).map(cycle=>loopOption({graph,cycle,target,tolerancePercent}));if(loops.length){onTrace("loop_found");return rankCycles(loops);}onTrace("no_cycle_at_start");}else onTrace("loop_not_requested");const fallback=outAndBack({target,graph,snapped,tolerancePercent});return fallback?[fallback]:[];}

/* Development capability only: find a real graph connector to a nearby cycle.
 * It returns metadata and never invents a coordinate or enables production use. */
function findConnectedNearbyCycle({graph,startPoint,maxConnectorMeters=1000,maxVisitedNodes=2000}={}){
  const snapped=snapToGraph(startPoint,graph,{preferInsidePark:true});if(!snapped)return null;
  const cycles=detectSimpleCycles(graph),cycleByNode=new Map();for(const cycle of cycles)for(const id of cycle.nodeIds.slice(0,-1))if(!cycleByNode.has(id))cycleByNode.set(id,cycle);
  const adj=adjacency(graph),dist=new Map([[snapped.id,0]]),previous=new Map(),queue=[snapped.id];let destination=null,visited=0;
  while(queue.length&&visited++<maxVisitedNodes){queue.sort((a,b)=>dist.get(a)-dist.get(b));const current=queue.shift(),currentDistance=dist.get(current);if(currentDistance>maxConnectorMeters)break;if(cycleByNode.has(current)){destination=current;break;}for(const edge of adj.get(current)||[]){const candidate=currentDistance+edge.lengthMeters;if(candidate<=maxConnectorMeters&&candidate<(dist.get(edge.next)??Infinity)){dist.set(edge.next,candidate);previous.set(edge.next,{node:current,edge});queue.push(edge.next);}}}
  if(destination==null)return null;const nodeIds=[destination],edges=[];for(let current=destination;current!==snapped.id;){const step=previous.get(current);if(!step)return null;edges.unshift(step.edge);current=step.node;nodeIds.unshift(current);}const cycle=rotateCycle(cycleByNode.get(destination),destination),connectorDistance=dist.get(destination),cycleDistance=cycle.edges.reduce((sum,edge)=>sum+edge.lengthMeters,0);
  return{snappedStartNodeId:snapped.id,cycleStartNodeId:destination,connectorNodeIds:nodeIds,connectorEdgeIds:edges.map(edge=>edge.id),returnConnectorNodeIds:[...nodeIds].reverse(),returnConnectorEdgeIds:edges.map(edge=>edge.id).reverse(),cycleNodeIds:cycle.nodeIds,cycleEdgeIds:cycle.edges.map(edge=>edge.id),connectorDistanceMeters:connectorDistance,cycleDistanceMeters:cycleDistance,fullyConnected:nodeIds.every((id,index)=>index===0||edges[index-1]?.from===nodeIds[index-1]&&edges[index-1]?.to===id||edges[index-1]?.to===nodeIds[index-1]&&edges[index-1]?.from===id)};
}
module.exports={snapToGraph,detectSimpleCycles,rankCycles,planTrailGraphRoute,findConnectedNearbyCycle};
