"use strict";
const {ApiError}=require("../lib/apiResponse");
const {generateProgram,stableId}=require("./programGenerator");
const {deriveAnalytics}=require("./programAnalytics");
const {dateKey}=require("./scheduleEngine");
function createProgramService({persistence,clock=()=>Date.now(),eventAdapter=null}){
 function assign(userId,input){const program=generateProgram(input,input.history||[]),now=new Date(clock()).toISOString(),existing=persistence.read(userId);if(existing?.program.programId===program.programId)return view(userId);const assignment={assignmentId:`asn_${stableId({userId,programId:program.programId})}`,userId,version:1,status:"active",assignedAt:now,currentWeek:1,currentPhase:"foundation",progressionState:{},substitutions:[],scheduledDeloads:program.mesocycles.flatMap(m=>m.weeks.filter(w=>w.deload).map(w=>w.week)),program};persistence.save(userId,assignment);eventAdapter?.({userId,type:"program.started",assignment,occurredAt:now});return view(userId);}
 function updateSession(userId,sessionId,input={}){const assignment=persistence.read(userId);if(!assignment)throw new ApiError("PROGRAM_NOT_FOUND","No active authoritative program",404);const session=assignment.program.microcycles.flatMap(w=>w.sessions).find(s=>s.sessionId===sessionId);if(!session)throw new ApiError("PROGRAM_SESSION_NOT_FOUND","Session does not belong to this member's program",404);const allowed=["completed","partially_completed","missed","rescheduled","abandoned"];if(!allowed.includes(input.status))throw new ApiError("INVALID_SESSION_STATUS","Unsupported program session status",400);session.status=input.status;session.completedAt=input.status==="completed"?new Date(clock()).toISOString():null;session.completionPercent=input.status==="completed"?100:Math.max(0,Math.min(100,Number(input.completionPercent)||0));assignment.version++;persistence.save(userId,assignment);return view(userId);}
 function view(userId,at=clock()){const a=persistence.read(userId);if(!a)return{available:false,assignment:null,calendar:[],analytics:null};const today=dateKey(at),sessions=a.program.microcycles.flatMap(w=>w.sessions),current=sessions.find(s=>s.date===today)||null,next=sessions.find(s=>s.date>today&&s.type!=="rest"&&s.status==="scheduled")||null,week=a.program.microcycles.find(w=>w.sessions.some(s=>s.date===today))||a.program.microcycles[a.currentWeek-1];a.currentWeek=week?.week||a.currentWeek;a.currentPhase=a.program.mesocycles.find(m=>a.currentWeek>=m.startWeek&&a.currentWeek<=m.endWeek)?.phase||a.currentPhase;const analytics=deriveAnalytics(a),nextRecovery=sessions.find(s=>s.date>=today&&["rest","active_recovery","yoga","mobility"].includes(s.type))||null;return{available:true,assignment:{assignmentId:a.assignmentId,status:a.status,program:a.program,currentWeek:a.currentWeek,currentPhase:a.currentPhase,deloadStatus:Boolean(week?.deload)},today:current,tomorrow:sessions.find(s=>s.date===dateKey(Number(new Date(`${today}T00:00:00Z`))+86400000))||null,nextWorkout:next,nextRecovery,upcoming:sessions.filter(s=>s.date>=today&&s.status==="scheduled").slice(0,10),calendar:a.program.microcycles,analytics,upcomingMilestone:analytics.completionPercentage<50?"50% program completion":"Program completion"};}
 return Object.freeze({assign,updateSession,view});
}
module.exports={createProgramService};
