'use strict';

const { validateEvidenceSource } = require('./models');

const reviewed = '2026-08-17';
const sources = [
  ['SRC001', 'Youth resistance training: updated position statement paper from the National Strength and Conditioning Association', ['Faigenbaum AD', 'Kraemer WJ', 'Blimkie CJR', 'et al.'], 2009, 'Journal of Strength and Conditioning Research', 'https://pubmed.ncbi.nlm.nih.gov/19620931/', 'CONSENSUS_STATEMENT', 'Children and adolescents', ['Appropriately designed and supervised resistance training can be safe and beneficial for youth.', 'Qualified instruction, technique, and gradual progression matter.'], ['A universal set, repetition, load, or effort threshold for every child.', 'That every bodyweight movement is low intensity.'], 'EVIDENCE_CONSENSUS'],
  ['SRC002', 'Position statement on youth resistance training: the 2014 International Consensus', ['Lloyd RS', 'Faigenbaum AD', 'Stone MH', 'et al.'], 2014, 'British Journal of Sports Medicine', 'https://bjsm.bmj.com/content/48/7/498', 'CONSENSUS_STATEMENT', 'Children and adolescents', ['Age-appropriate resistance training with qualified supervision can support health and physical development.', 'Training should reflect technical competency and developmental status.'], ['That chronological age alone prescribes an exact dose.', 'That maximal testing is required for automatic programming.'], 'EVIDENCE_CONSENSUS'],
  ['SRC003', 'Effects and dose-response relationships of resistance training on physical performance in youth athletes: a systematic review and meta-analysis', ['Lesinski M', 'Prieske O', 'Granacher U'], 2016, 'British Journal of Sports Medicine', 'https://pubmed.ncbi.nlm.nih.gov/26851290/', 'SYSTEMATIC_REVIEW_META_ANALYSIS', 'Youth athletes', ['Resistance training is associated with improvements in youth physical performance.', 'Training variables influence observed effects.'], ['One optimal dose for every youth participant.', 'A guarantee of individual improvement or injury prevention.'], 'RESEARCH_SUPPORTED'],
  ['SRC004', 'The Youth Physical Development Model: a new approach to long-term athletic development', ['Lloyd RS', 'Oliver JL'], 2012, 'Strength and Conditioning Journal', 'https://journals.lww.com/nsca-scj/fulltext/2012/06000/the_youth_physical_development_model__a_new.3.aspx', 'DEVELOPMENT_MODEL', 'Children and adolescents across maturation', ['Long-term development should consider maturation and multiple trainable qualities.', 'Programming should be developmentally appropriate rather than a scaled adult plan.'], ['A diagnostic maturity determination from age alone.', 'A single mandatory pathway or exact prescription.'], 'RESEARCH_SUPPORTED'],
  ['SRC005', 'FITNESSGRAM/ACTIVITYGRAM Test Administration Manual', ['Meredith MD', 'Welk GJ'], 2010, 'The Cooper Institute', 'https://library.shapeamerica.org/flipbooks/fitnessgram/files/assets/basic-html/page-1.html', 'ESTABLISHED_TESTING_SYSTEM', 'School-aged youth', ['Standardized field-based procedures can measure components of youth fitness.', 'Consistent administration supports longitudinal comparison.'], ['Clinical diagnosis.', 'That a single composite score captures total youth health.'], 'VALIDATED_TEST_PROTOCOL'],
  ['SRC006', 'Reliability of field-based fitness tests in youth', ['Artero EG', 'España-Romero V', 'Castro-Piñero J', 'et al.'], 2011, 'International Journal of Sports Medicine', 'https://pubmed.ncbi.nlm.nih.gov/21165805/', 'RELIABILITY_STUDY', 'European children and adolescents', ['Selected field tests show useful reliability when protocols are standardized.', 'Protocol consistency is material to repeat measurement.'], ['Perfect measurement precision for an individual.', 'Interchangeability of different tests or protocols.'], 'VALIDATED_TEST_PROTOCOL'],
  ['SRC007', 'Fitness Measures and Health Outcomes in Youth', ['Institute of Medicine'], 2012, 'National Academies Press', 'https://nap.nationalacademies.org/catalog/13483/fitness-measures-and-health-outcomes-in-youth', 'EVIDENCE_REVIEW', 'Children and adolescents', ['Health-related youth fitness measures should be selected by component and evidence quality.', 'Schools and programs should use valid, reliable, feasible measures.'], ['A clinically validated proprietary global fitness score.', 'Diagnosis from movement observations.'], 'EVIDENCE_CONSENSUS'],
  ['SRC008', 'Criterion-related validity of field-based fitness tests in youth: a systematic review', ['Castro-Piñero J', 'Artero EG', 'España-Romero V', 'et al.'], 2010, 'British Journal of Sports Medicine', 'https://pubmed.ncbi.nlm.nih.gov/19364756/', 'SYSTEMATIC_REVIEW', 'Children and adolescents', ['Some field-based tests have evidence of criterion-related validity for specific fitness components.', 'Test selection should match the component being assessed.'], ['That every field test is valid for every population.', 'That a field screen predicts injury or provides anatomical diagnosis.'], 'VALIDATED_TEST_PROTOCOL'],
  ['SRC009', 'Recommended amount of sleep for pediatric populations: a consensus recommendation of the American Academy of Sleep Medicine', ['Paruthi S', 'Brooks LJ', 'D’Ambrosio C', 'et al.'], 2016, 'Journal of Clinical Sleep Medicine', 'https://pubmed.ncbi.nlm.nih.gov/27250809/', 'CONSENSUS_RECOMMENDATION', 'Infants, children, and adolescents', ['Age-banded sleep-duration education supports health and well-being.', 'Sleep recommendations should account for age.'], ['That missed sleep reflects poor character or effort.', 'A medical diagnosis or individualized treatment plan.'], 'EVIDENCE_CONSENSUS'],
  ['SRC010', 'American College of Sports Medicine position stand: Exercise and fluid replacement', ['Sawka MN', 'Burke LM', 'Eichner ER', 'et al.'], 2007, 'Medicine & Science in Sports & Exercise', 'https://pubmed.ncbi.nlm.nih.gov/17277604/', 'POSITION_STATEMENT', 'Physically active people, with individual and environmental variability', ['Hydration needs vary with exercise, environment, and individual sweat losses.', 'Education should avoid both excessive dehydration and overdrinking.'], ['One arbitrary fluid volume appropriate for every child and session.', 'That forced water loading is harmless.'], 'EVIDENCE_CONSENSUS'],
].map(([source_id, title, authors, year, publication, url, source_type, population, supports, does_not_establish, evidence_class_default]) => validateEvidenceSource({ source_id, title, authors, year, publication, url, source_type, population, supports, does_not_establish, evidence_class_default, last_reviewed: reviewed, active: true }));

module.exports = { evidenceSources: Object.freeze(sources) };
