"use strict";
const legacy=require("../../data/exercise.json");
const {SCHEMA_VERSION,assertExercise}=require("./exerciseSchema");
const {slug,classify}=require("./exerciseClassification");
const CONTENT_VERSION="2026.07.1";
const OVERRIDES=Object.freeze({bodyweight_squat:{aliases:["air squat"],movementPattern:"squat"},goblet_squat:{movementPattern:"squat"},front_squat:{movementPattern:"squat"},back_squat:{movementPattern:"squat"},incline_push_up:{aliases:["incline pushup"],movementPattern:"horizontal_push"},push_up:{aliases:["pushup"],movementPattern:"horizontal_push"},bench_press:{aliases:["barbell bench press"],movementPattern:"horizontal_push"},dumbbell_bench_press:{movementPattern:"horizontal_push"},machine_chest_press:{movementPattern:"horizontal_push"},glute_bridge:{movementPattern:"hinge"},dumbbell_rdl:{movementPattern:"hinge"},barbell_deadlift:{movementPattern:"hinge"},band_row:{movementPattern:"horizontal_pull"},one_arm_row:{movementPattern:"horizontal_pull"},barbell_row:{movementPattern:"horizontal_pull"},prone_snow_angel:{movementPattern:"horizontal_pull"},dead_bug:{movementPattern:"core"},plank:{movementPattern:"core"}});
function canonicalize(source){const exerciseId=slug(source.exerciseId||source.id||source.name),override=OVERRIDES[exerciseId]||{},classification=classify({...source,...override});const instructions=(source.instructions||[]).filter(Boolean),cameraSupported=["bodyweight_squat","push_up","incline_push_up"].includes(exerciseId);return assertExercise(Object.freeze({exerciseId,schemaVersion:SCHEMA_VERSION,contentVersion:CONTENT_VERSION,displayName:String(source.displayName||source.name||exerciseId),aliases:Object.freeze([...(override.aliases||[]),...(source.aliases||[])]),description:source.description||instructions[0]||"Authoritative exercise reference.",classification:Object.freeze(classification),jointActions:Object.freeze(source.jointActions||[]),stabilizers:Object.freeze(source.stabilizers||[]),tempoSupport:true,guidance:Object.freeze({repRange:source.repRange||[5,15],sets:source.sets||[2,5],restSeconds:source.restSeconds||[30,180]}),coaching:Object.freeze({primaryCues:instructions.slice(0,3),secondaryCues:[],commonFaults:[],checkpoints:[],setup:instructions[0]||"",execution:instructions.slice(1,-1),finish:instructions.at(-1)||"",breathing:"Breathe continuously; brace before the effort.",tempo:"Use controlled, intentional repetitions.",rangeOfMotion:"Use the pain-free range you can control.",safetyReminders:["Stop if movement causes sharp pain."]}),requirements:Object.freeze({prerequisites:[],mobility:"individual_screen",balance:classification.mechanic==="compound"?"moderate":"low",coreDemand:classification.mechanic==="compound"?"moderate":"low",complexity:classification.difficultyScore}),relationships:Object.freeze({regressions:[],progressions:[],substitutions:[]}),contraindications:Object.freeze(source.contraindications||[]),movementCompatibility:Object.freeze({cameraSupported,supportedDetector:cameraSupported?"movenet":null,requiredLandmarks:cameraSupported?["left_shoulder","right_shoulder","left_hip","right_hip","left_knee","right_knee"]:[],expectedConfidence:cameraSupported?.65:null,availableScoring:cameraSupported?["alignment","range_of_motion"]:[],coachingRules:cameraSupported?["stable_alignment"]:[],poseCompatibility:cameraSupported?"full_body_2d":"not_evaluated",futureLandmarkCoverage:[]}),aiCoach:Object.freeze({purpose:`Develop ${classification.movementPattern} capacity.`,movementIntent:classification.movementPattern,explanationPolicy:"reference_only"}),wearableCompatibility:Object.freeze({status:"future",signals:[]}),searchKeywords:Object.freeze([exerciseId,source.name,...(override.aliases||[]),...classification.primaryMuscles,classification.equipment,classification.movementPattern].filter(Boolean).map(slug)),deprecation:Object.freeze({deprecated:false,replacedBy:null,reason:null})}));}
const supplemental=Object.keys(OVERRIDES).filter(id=>!legacy.some(x=>slug(x.id)===id)).map(id=>({id,name:id.split("_").map(x=>x[0].toUpperCase()+x.slice(1)).join(" "),level:id.includes("incline")||id.includes("bodyweight")?"beginner":"intermediate",equipment:id.includes("barbell")||id.includes("back_squat")||id.includes("front_squat")||id==="bench_press"?"barbell":id.includes("dumbbell")||id.includes("goblet")||id.includes("one_arm")?"dumbbell":id.includes("band")?"band":id.includes("machine")?"machine":"body only",primaryMuscles:[],secondaryMuscles:[],category:"strength",mechanic:"compound",instructions:[]}));
const catalog=Object.freeze([...legacy,...supplemental].map(canonicalize).sort((a,b)=>a.exerciseId.localeCompare(b.exerciseId)));
const byId=new Map(catalog.map(x=>[x.exerciseId,x]));
function getExercise(id){return byId.get(slug(id))||null;} function listExercises(){return catalog.slice();}
module.exports={CONTENT_VERSION,canonicalize,getExercise,listExercises,catalog};
