"use strict";
const crypto=require("node:crypto"),C=require("./contracts"),{createRealWorldStore}=require("./store");
const stable=value=>JSON.stringify(value,Object.keys(value||{}).sort()),hash=value=>crypto.createHash("sha256").update(stable(value)).digest("hex");
const SECRET_KEYS=/authorization|password|secret|api[-_]?key|access[-_]?token|credential/i;
function redact(value){if(Array.isArray(value))return value.map(redact);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,SECRET_KEYS.test(k)?"[REDACTED]":redact(v)]));return typeof value==="string"&&/(bearer\s+\S+|sk-[A-Za-z0-9_-]{8,})/i.test(value)?"[REDACTED]":value}
function createRealWorldAirlock({adapter,clock=()=>new Date(),id=()=>crypto.randomUUID(),store=createRealWorldStore(),mode="DRY_RUN"}={}){if(!adapter?.metadata||!adapter.execute)throw new Error("real_world_adapter_required");if(mode!=="DRY_RUN")throw new Error("phase9a_live_mode_prohibited");const now=()=>clock().toISOString(),d=store.data;
 function request(values){const payload=redact(values.payload);if(hash(payload)!==values.payloadHash)throw new Error("payload_hash_mismatch");const item=C.ExternalActionRequest({...values,payload,requestedAt:values.requestedAt||now()});d.requests.set(item.id,item);return item}
 function approve(values){const item=d.requests.get(values.requestRef);if(!item)throw new Error("request_not_found");const approval=C.ExternalApproval({...values,payloadHash:values.payloadHash||item.payloadHash,approvedAt:values.approvedAt||now(),revoked:Boolean(values.revoked)});d.approvals.set(approval.id,approval);return approval}
 function setKillSwitch(domain,active,evidenceRef="governance") {if(!C.KILL_SWITCH_DOMAINS.includes(domain))throw new Error("unknown_kill_switch_domain");d.killSwitches.set(domain,{domain,active,evidenceRef,changedAt:now()})}
 function validateApproval(item,approval){if(!approval)return "APPROVAL_REQUIRED";if(approval.revoked)return "APPROVAL_REVOKED";if(new Date(approval.expiresAt)<=clock())return "APPROVAL_EXPIRED";if(approval.requestRef!==item.id||approval.actionType!==item.actionType||approval.payloadHash!==item.payloadHash)return "APPROVAL_PAYLOAD_MISMATCH";if(!approval.customerScope.includes(item.customerRef)||!approval.scope.includes(item.resourceScope))return "APPROVAL_SCOPE_MISMATCH";const amount=Number(item.payload.amount||0);if(amount>approval.maximumAmount||item.payload.currency&&item.payload.currency!==approval.currency)return "APPROVAL_MONEY_MISMATCH";if(approval.usage==="SINGLE_USE"&&[...d.receipts.values()].some(x=>x.approvalRef===approval.id))return "APPROVAL_ALREADY_USED";return null}
 async function execute({requestId,authorization,approvalId,killSwitchDomain}){const item=d.requests.get(requestId);if(!item)return {ok:false,code:"REQUEST_NOT_FOUND"};const prior=d.idempotency.get(item.idempotencyKey);if(prior)return {ok:true,replayed:true,receipt:prior};if(item.actionClass===C.ACTION_CLASSES.PROHIBITED||item.actionClass===C.ACTION_CLASSES.OBSERVE)return {ok:false,code:"ACTION_CLASS_NOT_EXECUTABLE"};if(!authorization||authorization.requestRef!==item.id||authorization.actorRef!==item.actorRef||authorization.decision!=="ALLOW"||authorization.policyVersion===undefined)return {ok:false,code:"CURRENT_AUTHORITY_REQUIRED"};if(d.killSwitches.get("ALL_EXTERNAL_ACTIONS")?.active||d.killSwitches.get(killSwitchDomain)?.active)return {ok:false,code:"KILL_SWITCH_ACTIVE"};let approval=null;if(item.actionClass===C.ACTION_CLASSES.HUMAN_APPROVED_EXECUTE){approval=d.approvals.get(approvalId);const error=validateApproval(item,approval);if(error)return {ok:false,code:error}}if(item.actionClass===C.ACTION_CLASSES.PREAUTHORIZED_BOUNDED_EXECUTE)return {ok:false,code:"CLASS_3_NOT_ENABLED_PHASE_9A"};const receipt=await adapter.execute(item);const stored=Object.freeze({...receipt,approvalRef:approval?.id||null});d.receipts.set(stored.id,stored);d.idempotency.set(item.idempotencyKey,stored);return {ok:true,replayed:false,receipt:stored}}
 function observe(values){const clean=redact(values.untrustedData);const evidence=C.ExternalEvidence({id:values.evidenceRef||id(),organizationId:values.organizationId,sourceAdapter:values.adapterRef,externalResourceId:values.externalResourceId,externalEventId:values.externalEventId||null,observedAt:values.observedAt,ingestedAt:values.ingestedAt||now(),rawStatus:values.rawStatus,normalizedInterpretation:values.normalizedInterpretation,verificationStatus:values.verificationStatus||"UNVERIFIED",correlation:values.correlation||{},redaction:{applied:true},confidence:values.confidence??"NOT_APPLICABLE",untrustedData:clean});d.evidence.set(evidence.id,evidence);return C.ExternalObservation({...values,ingestedAt:values.ingestedAt||now(),evidenceRef:evidence.id,untrustedData:clean})}
 return Object.freeze({request,approve,execute,observe,setKillSwitch,store,redact,hash,mode})}
module.exports={createRealWorldAirlock,redact,hash};
