"use strict";
const crypto=require("node:crypto"),C=require("./contracts");
const OFFER=Object.freeze({id:"offer.30-day-fitness-challenge",version:"1.0.0",customerType:"CONSENTED_ADULT_FITNESS_MEMBER",deliverable:"Existing automated 30-day digital fitness challenge access package",price:{amount:50,currency:"USD"},terms:"One digital access package; dry-run only in Phase 9A",scope:["challenge schedule","existing exercise guidance","digital delivery"],exclusions:["medical advice","individual diagnosis","live coaching","guaranteed outcomes"],fulfillmentCapability:"mufasa.digital-fitness-challenge",acceptanceCriteria:["manifest matches offer version","all referenced challenge days resolve","QA evidence attached"],estimatedFulfillmentTime:"PT1H",refundTerms:"Human-reviewed cancellation/refund policy; refund only after externally evidenced settlement",requiredEvidence:["customer acceptance","payment state","independent QA","delivery receipt"],authorityRequirements:["current grant","policy allow","scoped human approval for external effects"]});
const CUSTOMER_ARCHETYPE=Object.freeze({id:"consented-adult-fitness-member/1",description:"An adult member with an already governed contact basis seeking a bounded digital challenge; it exercises discovery through delivery while avoiding medical personalization and new production complexity.",allowedChannel:"EMAIL",consentRequired:true});
function offerSnapshot(offer=OFFER){return structuredClone(offer)}
function createCustomerRecord(values){if(!values.id||!values.organizationId||!values.retentionPolicy)throw new Error("invalid_customer_record");return Object.freeze({...values,externalIdentityRefs:[...(values.externalIdentityRefs||[])],communications:[...(values.communications||[])],orderRefs:[...(values.orderRefs||[])],obligationRefs:[...(values.obligationRefs||[])],paymentRefs:[...(values.paymentRefs||[])],deliveryRefs:[...(values.deliveryRefs||[])],refundRefs:[...(values.refundRefs||[])],evidenceRefs:[...(values.evidenceRefs||[])]})}
function contactEligibility(customer,{channel,now=new Date()}={}){if(customer.suppressed)return {eligible:false,reason:"SUPPRESSED"};if(!customer.contactBasis?.approvedSource)return {eligible:false,reason:"UNAPPROVED_SOURCE"};if(customer.contactBasis.allowedChannel!==channel)return {eligible:false,reason:"CHANNEL_NOT_ALLOWED"};if(customer.contactBasis.expiresAt&&new Date(customer.contactBasis.expiresAt)<=now)return {eligible:false,reason:"CONTACT_BASIS_EXPIRED"};if((customer.contactBasis.contactsToday||0)>=(customer.contactBasis.dailyLimit||1))return {eligible:false,reason:"FREQUENCY_LIMIT"};return {eligible:true,reason:"ELIGIBLE"}}
function acceptOffer({id=crypto.randomUUID(),organizationId,customerRef,offer=OFFER,acceptedAt,deadline,evidenceRefs=[]}){const locked=offerSnapshot(offer);return C.ExternalObligation({id,organizationId,customerRef,offerId:locked.id,offerVersion:locked.version,offerSnapshot:locked,scope:locked.scope,price:locked.price,paymentState:"PAYMENT_PENDING",acceptanceCriteria:locked.acceptanceCriteria,deadline,productionState:"NOT_STARTED",qaState:"NOT_RUN",deliveryState:"DELIVERY_PREPARED",refundTerms:locked.refundTerms,evidenceRefs,status:"ACTIVE",acceptedAt})}
function transitionPayment(obligation,next,evidenceRef){if(!C.PAYMENT_STATES.includes(next))throw new Error("invalid_payment_state");const allowed={PAYMENT_PENDING:["PAYMENT_AUTHORIZED","PAYMENT_SETTLED","PAYMENT_FAILED"],PAYMENT_AUTHORIZED:["PAYMENT_SETTLED","PAYMENT_FAILED"],PAYMENT_SETTLED:["PAYMENT_REFUNDED"],PAYMENT_FAILED:[],PAYMENT_REFUNDED:[]};if(next==="PAYMENT_REFUNDED"&&obligation.paymentState!=="PAYMENT_SETTLED")throw new Error("refund_requires_settlement");if(!((allowed[obligation.paymentState]||[]).includes(next)))throw new Error("invalid_payment_transition");return Object.freeze({...obligation,paymentState:next,evidenceRefs:[...obligation.evidenceRefs,evidenceRef]})}
function recordEconomicEvent(values){if(values.amount===null||values.amount===undefined||Number.isNaN(Number(values.amount)))throw new Error("unknown_amount_not_zero");if(!C.ECONOMIC_STATES.includes(values.classification))throw new Error("invalid_economic_classification");return C.ExternalEconomicEvent(values)}
function recordProduction(obligation,{producerRole,artifactRef,evidenceRef}){if(!artifactRef)return Object.freeze({...obligation,productionState:"BLOCKED"});return Object.freeze({...obligation,productionState:"PRODUCED",producerRole,artifactRef,evidenceRefs:[...obligation.evidenceRefs,evidenceRef]})}
function recordQa(obligation,{reviewerRole,verdict,evidenceRef}){if(reviewerRole===obligation.producerRole)throw new Error("producer_self_qa_forbidden");if(!["PASS","FAIL","BLOCKED","INSUFFICIENT_EVIDENCE"].includes(verdict))throw new Error("invalid_qa_verdict");return Object.freeze({...obligation,qaState:verdict,evidenceRefs:[...obligation.evidenceRefs,evidenceRef]})}
function prepareDelivery(obligation){if(obligation.qaState!=="PASS")throw new Error("qa_pass_required_for_delivery");return Object.freeze({...obligation,deliveryState:"DELIVERY_PREPARED"})}
module.exports={OFFER,CUSTOMER_ARCHETYPE,offerSnapshot,createCustomerRecord,contactEligibility,acceptOffer,transitionPayment,recordEconomicEvent,recordProduction,recordQa,prepareDelivery};
