"use strict";
const {ANALYST_PLATINUM_SCENARIOS}=require("./academy");
const GATES=Object.freeze(["ANALYST_PLATINUM_ARCHITECTURE_READY","ANALYST_INTERNAL_INTEGRATION_VERIFIED","ANALYST_LIVE_EVIDENCE_VERIFIED","ANALYST_PLATINUM_CERTIFIED"]);
const refs=v=>Array.isArray(v)&&v.length>0&&v.every(x=>typeof x==="string"&&x.trim());
function validResult(x){return x&&ANALYST_PLATINUM_SCENARIOS.some(s=>s.id===x.scenarioId)&&x.verdict==="PASS"&&x.assertions?.length&&x.assertions.every(a=>a.status==="PASS")&&x.observations?.length&&x.observations.every(o=>refs(o.evidenceRefs))}
function validIntegration(x){return x?.kind==="AnalystIntegrationEvidence"&&x.status==="PASS"&&refs(x.evidenceRefs)&&refs(x.artifactRefs)&&x.sharedRuntime===true&&x.coordinator===true}
function validLive(x){return x?.kind==="AnalystLiveEvidence"&&x.verificationState==="VERIFIED"&&["VERIFIED_OUTCOME","LIVE_FIRST_PARTY","VERIFIED_PROVIDER"].includes(x.evidenceClassification)&&refs(x.evidenceRefs)}
function validAcceptance(x){return x?.kind==="AnalystHumanAcceptance"&&x.status==="PASS"&&x.actorType==="HUMAN"&&x.recordedBy==="AUTHENTICATED_ADMIN_BOUNDARY"&&refs(x.authenticationEvidenceRefs)&&refs(x.evidenceRefs)}
function analystReadiness({architectureResults=[],integrationEvidence=[],liveEvidence=[],humanAcceptance=null}={}){const passed=new Set(architectureResults.filter(validResult).map(x=>x.scenarioId));const gates={ANALYST_PLATINUM_ARCHITECTURE_READY:ANALYST_PLATINUM_SCENARIOS.every(x=>passed.has(x.id))?"PASS":"BLOCKED",ANALYST_INTERNAL_INTEGRATION_VERIFIED:integrationEvidence.some(validIntegration)?"PASS":"BLOCKED",ANALYST_LIVE_EVIDENCE_VERIFIED:liveEvidence.some(validLive)?"PASS":"BLOCKED"};gates.ANALYST_PLATINUM_CERTIFIED=Object.values(gates).every(x=>x==="PASS")&&validAcceptance(humanAcceptance)?"PASS":"BLOCKED";return Object.freeze({gates,firstFailure:GATES.find(x=>gates[x]!=="PASS")||null,humanAcceptance:{required:true,status:validAcceptance(humanAcceptance)?"PASS":"PENDING_HUMAN",authority:"AUTHENTICATED_ADMIN_ONLY"},evidenceSummary:{academyScenariosPassed:passed.size,academyScenariosRequired:ANALYST_PLATINUM_SCENARIOS.length,internalIntegrations:integrationEvidence.filter(validIntegration).length,verifiedLiveRecords:liveEvidence.filter(validLive).length},limitations:["Architecture readiness is separate from live Platinum certification.","Synthetic and controlled Test A evidence cannot satisfy live evidence.","External account connections and human acceptance remain external gates."]})}
module.exports={GATES,analystReadiness,validResult,validIntegration,validLive,validAcceptance};
