"use strict";
const CAPABILITIES=Object.freeze(["READ_ANALYST_EVIDENCE","READ_ANALYST_MEMORY","ASSESS_OPPORTUNITY","COMPARE_EVIDENCE","REQUEST_ANALYST_EVIDENCE","CREATE_ANALYST_ASSESSMENT","HANDOFF_EXPERIMENT_RECOMMENDATION"]);
const TOOL_MAP=Object.freeze({READ_ANALYST_EVIDENCE:"ANALYST_EVIDENCE_READ",READ_ANALYST_MEMORY:"ANALYST_MEMORY_READ",ASSESS_OPPORTUNITY:"OPPORTUNITY_ASSESS",COMPARE_EVIDENCE:"EVIDENCE_COMPARE",REQUEST_ANALYST_EVIDENCE:"ANALYST_EVIDENCE_REQUEST_CREATE",CREATE_ANALYST_ASSESSMENT:"ANALYST_ASSESSMENT_CREATE",HANDOFF_EXPERIMENT_RECOMMENDATION:"EXPERIMENT_RECOMMENDATION_HANDOFF"});
function registerAnalystTools(registry,organizationId){
 if(!organizationId)throw new Error("organization_required");
 for(const [capabilityId,toolId] of Object.entries(TOOL_MAP)){
  registry.registerTool({id:toolId,organizationId,name:toolId,version:1,description:"Governed Analyst tool definition; no executable adapter is installed",inputSchema:{type:"object",required:["organizationId"]},outputSchema:{type:"object",required:["status","evidenceRefs"]},risk:"LOW",cost:{currency:"USD",amount:0},timeoutMs:5000,retryPolicy:{maxAttempts:1},idempotency:true,authorityRequirements:[`tool.${toolId}`],policyRequirements:["ANALYST_REASONING_POLICY_V1"],sideEffect:["ANALYST_EVIDENCE_REQUEST_CREATE","ANALYST_ASSESSMENT_CREATE","EXPERIMENT_RECOMMENDATION_HANDOFF"].includes(toolId)?"GOVERNED_INTERNAL_ARTIFACT":"READ_ONLY",reversibility:"APPEND_ONLY",limitations:["REGISTERED_DEFINITION_ONLY","No execution adapter is installed","No outreach, publication, spend, activation, Test A execution, or live account mutation"],status:"UNAVAILABLE",verificationRequirements:["EVIDENCE_REFERENCE"],supportedCapabilityIds:[capabilityId],autonomyLevels:["OBSERVE","RECOMMEND"],killSwitchApplicable:true,schemaVersion:"1.0.0"});
  registry.registerCapability({id:capabilityId,organizationId,name:capabilityId,version:1,description:"Designed SMART_ANALYST capability definition; not executable",requiredInputs:["organizationId"],producedOutputs:["status","evidenceRefs"],requiredToolIds:[toolId],optionalToolIds:[],validationStatus:"DESIGNED",limitations:["REGISTERED_DEFINITION_ONLY","No shared execution adapter or verification evidence is installed"],risk:"LOW",estimatedCost:{currency:"USD",amount:0},estimatedDurationMs:5000,autonomyLevel:"RECOMMEND",humanRequiredSteps:[],authorityRequirements:[`tool.${toolId}`],policyRequirements:["ANALYST_REASONING_POLICY_V1"],status:"UNAVAILABLE",schemaVersion:"1.0.0"});
 }
 return Object.freeze({capabilities:CAPABILITIES,tools:Object.values(TOOL_MAP),operationalCapabilities:Object.freeze([]),registrationState:"DEFINITIONS_ONLY"});
}
module.exports={CAPABILITIES,TOOL_MAP,registerAnalystTools};
