'use strict';

const { TRAINING_LEVELS, AGE_PRESENTATION_BANDS } = require('../activities');

function enumValues(values) {
  return Object.freeze(Object.fromEntries(values.map((value) => [value, value])));
}

const GOALS = enumValues(['GENERAL_FITNESS', 'GET_STRONGER', 'IMPROVE_ENDURANCE', 'MOVE_BETTER', 'IMPROVE_COORDINATION', 'IMPROVE_MOBILITY', 'BECOME_MORE_ATHLETIC', 'PREPARE_FOR_SPORT', 'BUILD_CONSISTENCY']);
const TRAINING_EXPERIENCES = enumValues(['NEW', 'BEGINNER', 'SOME_EXPERIENCE', 'EXPERIENCED']);
const PROGRAM_CONTEXTS = enumValues(['GENERAL_YOUTH_FITNESS', 'LEADER_WITHIN_MOVEMENT_SUPPORT', 'SPORT_PREPARATION_GENERAL']);
const MOVEMENT_NEEDS = enumValues(['ANKLE_MOBILITY_CONTROL', 'HIP_MOBILITY_CONTROL', 'THORACIC_SHOULDER_MOBILITY', 'TRUNK_CONTROL', 'LOWER_EXTREMITY_CONTROL', 'LANDING_CONTROL', 'GENERAL_MOVEMENT_SKILL']);
const SORENESS_LEVELS = enumValues(['NONE', 'MILD', 'SIGNIFICANT']);
const SLEEP_QUALITIES = enumValues(['GOOD', 'FAIR', 'POOR']);
const STRESS_TAGS = enumValues(['LOWER_BODY_STRENGTH', 'UPPER_BODY_PUSH', 'UPPER_BODY_PULL', 'IMPACT', 'AEROBIC', 'TRUNK', 'MOBILITY', 'LOW', 'MODERATE', 'HIGH']);
const PROFILE_STATUSES = enumValues(['DRAFT', 'NEEDS_REQUIRED_FIELDS', 'READY_FOR_PROGRAM_PLANNING', 'COACH_REVIEW_REQUIRED', 'UNSUPPORTED']);
const SAFETY_FLAGS = enumValues(['PAIN_REPORTED_REQUIRES_COACH_REVIEW']);

module.exports = { GOALS, TRAINING_EXPERIENCES, TRAINING_LEVELS, AGE_PRESENTATION_BANDS, PROGRAM_CONTEXTS, MOVEMENT_NEEDS, SORENESS_LEVELS, SLEEP_QUALITIES, STRESS_TAGS, PROFILE_STATUSES, SAFETY_FLAGS };
