"use strict";
const ROLE_CONTRACT_VERSION="ai-business-os.role-registry/1.0.0";
const base={version:1,status:"ACTIVE",autonomyCeiling:"RECOMMEND",riskCeiling:"LOW",budgetDefaults:{currency:"USD",maxCost:0,unknownCostBehavior:"ESCALATE"},allowedCapabilities:[],allowedTools:[],authorityReferences:["EXTERNAL_GRANT_REQUIRED"],policyReferences:["ORGANIZATION_POLICY_REQUIRED"],reportingRequirements:["SOURCE_EVIDENCE","PROVENANCE","LIMITATIONS","DIAGNOSTICS","SAFE_REASONING_SUMMARY"],escalationBehavior:"CREATE_HUMAN_OWNED_WORK_OR_PAUSE"};
const specs={
 SMART_SCOUT:{missionTypes:["DISCOVER_CANDIDATE"],contextProfile:{scope:["discovery","opportunity","product-readiness","privacy-limited-outcomes"],sensitivity:["PUBLIC","TEAM_SCOUT"]},memoryProfile:{types:["WORKING","EPISODIC"]},knowledgeProfile:{statuses:["SUPPORTED","VALIDATED","DISPUTED"],freshnessRequired:true},inputArtifactTypes:["SyntheticOpportunitySource","ScoutSourceObservation","ScoutOutcomeFeedback","ProductReadinessSummary","HumanApprovedResearch"],outputArtifactTypes:["OpportunityCandidate","SignalObservation","ScoutSourceObservation","ScoutAssessment"],allowedCapabilities:["READ_APPROVED_SCOUT_SOURCE","READ_SEARCH_CONSOLE_SUMMARY","READ_GA4_ACQUISITION_SUMMARY","READ_PRODUCT_READINESS_SUMMARY","READ_CAPABILITY_READINESS_SUMMARY","READ_SCOUT_OUTCOME_FEEDBACK","IMPORT_HUMAN_APPROVED_RESEARCH","CREATE_SCOUT_OBSERVATION","CREATE_OPPORTUNITY_CANDIDATE","HANDOFF_CANDIDATE_TO_ANALYST"],allowedTools:["SCOUT_SOURCE_READ","SEARCH_CONSOLE_SUMMARY_READ","GA4_ACQUISITION_SUMMARY_READ","PRODUCT_READINESS_SUMMARY_READ","SCOUT_OUTCOME_FEEDBACK_READ","HUMAN_APPROVED_RESEARCH_IMPORT","SCOUT_OBSERVATION_CREATE","OPPORTUNITY_CANDIDATE_CREATE","ANALYST_CANDIDATE_HANDOFF"],policyReferences:["SCOUT_REASONING_POLICY_V1","ORGANIZATION_POLICY_REQUIRED"]},
 SMART_ANALYST:{missionTypes:["ASSESS_EVIDENCE"],contextProfile:{scope:["candidate","evidence-history","product-readiness","outcome-feedback"],sensitivity:["TEAM_ANALYSIS"]},memoryProfile:{types:["WORKING","EPISODIC","DECISION"]},knowledgeProfile:{statuses:["SUPPORTED","VALIDATED","DISPUTED"],freshnessRequired:true},inputArtifactTypes:["OpportunityCandidate","SignalObservation","ScoutSourceObservation","ScoutAssessment","ScoutOutcomeFeedback","ProductReadinessSummary"],outputArtifactTypes:["AnalystAssessment","AnalystEvidenceRequest","ExperimentRecommendation"],allowedCapabilities:["READ_ANALYST_EVIDENCE","READ_ANALYST_MEMORY","ASSESS_OPPORTUNITY","COMPARE_EVIDENCE","REQUEST_ANALYST_EVIDENCE","CREATE_ANALYST_ASSESSMENT","HANDOFF_EXPERIMENT_RECOMMENDATION"],allowedTools:["ANALYST_EVIDENCE_READ","ANALYST_MEMORY_READ","OPPORTUNITY_ASSESS","EVIDENCE_COMPARE","ANALYST_EVIDENCE_REQUEST_CREATE","ANALYST_ASSESSMENT_CREATE","EXPERIMENT_RECOMMENDATION_HANDOFF"],policyReferences:["ANALYST_REASONING_POLICY_V1","ORGANIZATION_POLICY_REQUIRED"]},
 EXPERIMENT_MANAGER:{missionTypes:["DESIGN_EXPERIMENT","INTERPRET_EXPERIMENT"],contextProfile:{scope:["experiment"],sensitivity:["TEAM_EXPERIMENT"]},memoryProfile:{types:["WORKING","EPISODIC","PROCEDURAL"]},knowledgeProfile:{statuses:["SUPPORTED","VALIDATED"]},inputArtifactTypes:["AnalystAssessment"],outputArtifactTypes:["ExperimentProposal","ExperimentResult","ExperimentInterpretation"]},
 ECONOMICS:{missionTypes:["ASSESS_ECONOMICS"],contextProfile:{scope:["cost","value","capacity"],sensitivity:["TEAM_ECONOMICS"]},memoryProfile:{types:["WORKING","EPISODIC"]},knowledgeProfile:{statuses:["SUPPORTED","VALIDATED"]},inputArtifactTypes:["ExperimentResult","CostEvidence","ValueEvidence"],outputArtifactTypes:["EconomicAssessment"]},
 SALES:{missionTypes:["PROPOSE_OFFER"],contextProfile:{scope:["approved-offer","validated-capability","customer-permission"],sensitivity:["TEAM_SALES"]},memoryProfile:{types:["WORKING","PROCEDURAL"]},knowledgeProfile:{statuses:["VALIDATED"]},inputArtifactTypes:["AnalystAssessment","EconomicAssessment","CapabilityEvidence"],outputArtifactTypes:["SalesProposal","OfferProposal"]},
 PRODUCTION:{missionTypes:["PLAN_FULFILLMENT","REMEDIATE_OUTPUT"],contextProfile:{scope:["obligation","capability","procedure","capacity"],sensitivity:["TEAM_PRODUCTION"]},memoryProfile:{types:["WORKING","PROCEDURAL","EPISODIC"]},knowledgeProfile:{statuses:["VALIDATED"]},inputArtifactTypes:["AuthorizedObligation","QAAssessment"],outputArtifactTypes:["ProductionPlan","SyntheticOutput"]},
 INDEPENDENT_QA:{missionTypes:["ASSESS_ACCEPTANCE"],contextProfile:{scope:["acceptance-contract","produced-artifact"],sensitivity:["TEAM_QA"]},memoryProfile:{types:["WORKING","EPISODIC"]},knowledgeProfile:{statuses:["VALIDATED"]},inputArtifactTypes:["SyntheticOutput","AcceptanceContract"],outputArtifactTypes:["QAAssessment"]},
 LEARNING:{missionTypes:["PROPOSE_LEARNING"],contextProfile:{scope:["verified-outcomes","contradictions","failures"],sensitivity:["TEAM_LEARNING"]},memoryProfile:{types:["EPISODIC","DECISION","PROCEDURAL"]},knowledgeProfile:{statuses:["CANDIDATE","SUPPORTED","VALIDATED","DISPUTED"]},inputArtifactTypes:["ExperimentResult","EconomicAssessment","QAAssessment"],outputArtifactTypes:["LearningProposal","KnowledgeCandidate","ProcedureChangeProposal","PromptConfigChangeProposal","CapabilityImprovementProposal","PolicyReviewProposal"]},
 MANAGER:{missionTypes:["COORDINATE_OBJECTIVE"],contextProfile:{scope:["organizational-summary"],sensitivity:["MANAGEMENT_SUMMARY"]},memoryProfile:{types:["WORKING","EPISODIC","DECISION"]},knowledgeProfile:{statuses:["SUPPORTED","VALIDATED","DISPUTED"]},inputArtifactTypes:["RoleArtifact","OrganizationalState"],outputArtifactTypes:["ManagementDirective","RoleDecisionProposal"]}
};
function createRoleConfigurationRegistry({organizationId}){if(!organizationId)throw new Error("organization_required");const roles=new Map();function register(values){if(values.organizationId!==organizationId)throw new Error("cross_organization_role_registration");if(!specs[values.id])throw new Error("unknown_governed_role");const role=Object.freeze({contractVersion:ROLE_CONTRACT_VERSION,...base,...specs[values.id],...values});for(const key of ["missionTypes","contextProfile","memoryProfile","knowledgeProfile","inputArtifactTypes","outputArtifactTypes","allowedCapabilities","allowedTools","authorityReferences","policyReferences","autonomyCeiling","riskCeiling","budgetDefaults","reportingRequirements","escalationBehavior"])if(role[key]===undefined)throw new Error(`invalid_role_configuration:${key}`);roles.set(`${role.id}@${role.version}`,role);return role}function registerDefaults(overrides={}){return Object.keys(specs).map(id=>register({id,organizationId,...(overrides[id]||{})}))}return Object.freeze({register,registerDefaults,get:(id,version=1)=>roles.get(`${id}@${version}`)||null,list:()=>[...roles.values()]})}
module.exports={ROLE_CONTRACT_VERSION,ROLE_IDS:Object.freeze(Object.keys(specs)),createRoleConfigurationRegistry};
