"use strict";
const ROLE_CONTRACT_VERSION="ai-business-os.role-registry/1.0.0";
const base={version:1,status:"ACTIVE",autonomyCeiling:"RECOMMEND",riskCeiling:"LOW",budgetDefaults:{currency:"USD",maxCost:0,unknownCostBehavior:"ESCALATE"},allowedCapabilities:[],allowedTools:[],authorityReferences:["EXTERNAL_GRANT_REQUIRED"],policyReferences:["ORGANIZATION_POLICY_REQUIRED"],reportingRequirements:["SOURCE_EVIDENCE","PROVENANCE","LIMITATIONS","DIAGNOSTICS","SAFE_REASONING_SUMMARY"],escalationBehavior:"CREATE_HUMAN_OWNED_WORK_OR_PAUSE"};
const specs={
 SMART_SCOUT:{missionTypes:["DISCOVER_CANDIDATE"],contextProfile:{scope:["discovery","opportunity"],sensitivity:["PUBLIC","TEAM_SCOUT"]},memoryProfile:{types:["WORKING","EPISODIC"]},knowledgeProfile:{statuses:["SUPPORTED","VALIDATED"],freshnessRequired:true},inputArtifactTypes:["SyntheticOpportunitySource"],outputArtifactTypes:["OpportunityCandidate","SignalObservation","ScoutAssessment"]},
 SMART_ANALYST:{missionTypes:["ASSESS_EVIDENCE"],contextProfile:{scope:["candidate","evidence-history"],sensitivity:["TEAM_ANALYSIS"]},memoryProfile:{types:["WORKING","EPISODIC","DECISION"]},knowledgeProfile:{statuses:["SUPPORTED","VALIDATED","DISPUTED"]},inputArtifactTypes:["OpportunityCandidate","SignalObservation"],outputArtifactTypes:["AnalystAssessment"]},
 EXPERIMENT_MANAGER:{missionTypes:["DESIGN_EXPERIMENT","INTERPRET_EXPERIMENT"],contextProfile:{scope:["experiment"],sensitivity:["TEAM_EXPERIMENT"]},memoryProfile:{types:["WORKING","EPISODIC","PROCEDURAL"]},knowledgeProfile:{statuses:["SUPPORTED","VALIDATED"]},inputArtifactTypes:["AnalystAssessment"],outputArtifactTypes:["ExperimentProposal","ExperimentResult","ExperimentInterpretation"]},
 ECONOMICS:{missionTypes:["ASSESS_ECONOMICS"],contextProfile:{scope:["cost","value","capacity"],sensitivity:["TEAM_ECONOMICS"]},memoryProfile:{types:["WORKING","EPISODIC"]},knowledgeProfile:{statuses:["SUPPORTED","VALIDATED"]},inputArtifactTypes:["ExperimentResult","CostEvidence","ValueEvidence"],outputArtifactTypes:["EconomicAssessment"]},
 SALES:{missionTypes:["PROPOSE_OFFER"],contextProfile:{scope:["approved-offer","validated-capability","customer-permission"],sensitivity:["TEAM_SALES"]},memoryProfile:{types:["WORKING","PROCEDURAL"]},knowledgeProfile:{statuses:["VALIDATED"]},inputArtifactTypes:["AnalystAssessment","EconomicAssessment","CapabilityEvidence"],outputArtifactTypes:["SalesProposal","OfferProposal"]},
 PRODUCTION:{missionTypes:["PLAN_FULFILLMENT","REMEDIATE_OUTPUT"],contextProfile:{scope:["obligation","capability","procedure","capacity"],sensitivity:["TEAM_PRODUCTION"]},memoryProfile:{types:["WORKING","PROCEDURAL","EPISODIC"]},knowledgeProfile:{statuses:["VALIDATED"]},inputArtifactTypes:["AuthorizedObligation","QAAssessment"],outputArtifactTypes:["ProductionPlan","SyntheticOutput"]},
 INDEPENDENT_QA:{missionTypes:["ASSESS_ACCEPTANCE"],contextProfile:{scope:["acceptance-contract","produced-artifact"],sensitivity:["TEAM_QA"]},memoryProfile:{types:["WORKING","EPISODIC"]},knowledgeProfile:{statuses:["VALIDATED"]},inputArtifactTypes:["SyntheticOutput","AcceptanceContract"],outputArtifactTypes:["QAAssessment"]},
 LEARNING:{missionTypes:["PROPOSE_LEARNING"],contextProfile:{scope:["verified-outcomes","contradictions","failures"],sensitivity:["TEAM_LEARNING"]},memoryProfile:{types:["EPISODIC","DECISION","PROCEDURAL"]},knowledgeProfile:{statuses:["CANDIDATE","SUPPORTED","VALIDATED","DISPUTED"]},inputArtifactTypes:["ExperimentResult","EconomicAssessment","QAAssessment"],outputArtifactTypes:["LearningProposal","KnowledgeCandidate","ProcedureChangeProposal","PromptConfigChangeProposal","CapabilityImprovementProposal","PolicyReviewProposal"]},
 MANAGER:{missionTypes:["COORDINATE_OBJECTIVE"],contextProfile:{scope:["organizational-summary"],sensitivity:["MANAGEMENT_SUMMARY"]},memoryProfile:{types:["WORKING","EPISODIC","DECISION"]},knowledgeProfile:{statuses:["SUPPORTED","VALIDATED","DISPUTED"]},inputArtifactTypes:["RoleArtifact","OrganizationalState"],outputArtifactTypes:["ManagementDirective","RoleDecisionProposal"]}
};
function createRoleConfigurationRegistry({organizationId}){if(!organizationId)throw new Error("organization_required");const roles=new Map();function register(values){if(values.organizationId!==organizationId)throw new Error("cross_organization_role_registration");if(!specs[values.id])throw new Error("unknown_governed_role");const role=Object.freeze({contractVersion:ROLE_CONTRACT_VERSION,...base,...specs[values.id],...values});for(const key of ["missionTypes","contextProfile","memoryProfile","knowledgeProfile","inputArtifactTypes","outputArtifactTypes","allowedCapabilities","allowedTools","authorityReferences","policyReferences","autonomyCeiling","riskCeiling","budgetDefaults","reportingRequirements","escalationBehavior"])if(role[key]===undefined)throw new Error(`invalid_role_configuration:${key}`);roles.set(`${role.id}@${role.version}`,role);return role}function registerDefaults(overrides={}){return Object.keys(specs).map(id=>register({id,organizationId,...(overrides[id]||{})}))}return Object.freeze({register,registerDefaults,get:(id,version=1)=>roles.get(`${id}@${version}`)||null,list:()=>[...roles.values()]})}
module.exports={ROLE_CONTRACT_VERSION,ROLE_IDS:Object.freeze(Object.keys(specs)),createRoleConfigurationRegistry};
