"use strict";
const crypto=require("node:crypto");

const VERSION="command-intelligence/3.0.0";
const SECRET=/(sk_(?:live|test)_[a-z0-9_-]+|bearer\s+[a-z0-9._-]+|api[_-]?key\s*[:=]\s*\S+)/ig;
const clean=value=>String(value??"").replace(SECRET,"[REDACTED]").slice(0,12000);
const clone=value=>JSON.parse(JSON.stringify(value));
const state=(value,fallback="UNKNOWN")=>value===undefined||value===null||value===""?fallback:value;
const lifecycle=value=>({CREATED:"BACKLOG",ELIGIBLE:"READY",ASSIGNED:"READY",RUNNING:"ACTIVE",BLOCKED:"BLOCKED",FAILED:"BLOCKED",COMPLETED:"COMPLETE",CANCELLED:"COMPLETE"}[value]||"UNKNOWN");
const PIPELINE_FAILURES=Object.freeze(["BROWSER_CONNECTIVITY","MODEL_GATEWAY_UNAVAILABLE","CONTEXT_ASSEMBLY_FAILURE","INTENT_UNDERSTANDING_FAILURE","TOOL_SELECTION_FAILURE","TOOL_AUTHORITY_DENIED","EVIDENCE_RETRIEVAL_FAILURE","ORGANIZATION_READER_FAILURE","ACADEMY_READER_FAILURE","MEMORY_RETRIEVAL_FAILURE","REASONING_FAILURE","RESPONSE_GROUNDING_FAILURE","ACTION_AUTHORIZATION_REQUIRED"]);

function createCommandCenterService({controlledLiveService,readinessService=null,organizationReader=null,academyReader=null,brain=null,modelGateway=null,clock=()=>new Date(),id=()=>crypto.randomUUID()}={}){
 if(!controlledLiveService)throw new Error("controlled_live_source_required");
 const now=()=>clock().toISOString(),pipeline={last:null};
 const live=()=>controlledLiveService.snapshot();
 const readiness=()=>readinessService?.snapshot?.()||{boards:{},source:"UNAVAILABLE"};
 const org=()=>organizationReader?.()||{status:"NO_ACTIVITY_OBSERVED",objectives:[],work:[],artifacts:[],events:[],roles:[]};
 const academy=()=>academyReader?.()||{status:"NOT_RUN",brainStatus:"UNKNOWN",memoryStatus:"UNKNOWN",runId:null};
 const brainAvailable=()=>Boolean(brain?.available||typeof modelGateway==="function");
 function mapWork(x){return {id:x.id,missionId:x.objectiveRef,type:x.missionType,state:x.state,column:lifecycle(x.state),role:(x.eligibleRoleIds||[]).join(", ")||"UNASSIGNED",priority:x.priority||"UNKNOWN",dependencies:x.dependencyWorkRefs||[],firstFailure:x.firstFailure||null,humanAction:x.humanAction||null,evidenceRefs:x.outputArtifactRefs||x.inputArtifactRefs||[],updatedAt:x.completedAt||x.createdAt||null,nextAction:null}}
 function missions(){const o=org(),work=o.work||[];return (o.objectives||[]).map(objective=>{const items=work.filter(x=>x.objectiveRef===objective.id);return {id:objective.id,title:objective.objective,why:objective.scope||null,status:state(objective.status),priority:state(objective.priority),successCriteria:objective.successCriteria||[],stage:items.some(x=>x.state==="BLOCKED"||x.state==="FAILED")?"BLOCKED":items.length&&items.every(x=>x.state==="COMPLETED")?"COMPLETE":items.some(x=>x.state==="RUNNING")?"ACTIVE":"BACKLOG",work:items.map(mapWork),evidenceRefs:objective.evidenceRefs||[],nextGate:null,humanAction:null}})}
 function organism(){const l=live(),a=academy(),o=org();return [["BRAIN",brainAvailable()?state(a.brainStatus,"CONNECTED"):"UNAVAILABLE","Canonical Cognitive Core and Model Gateway"],["CONSTITUTION","ENFORCING","Constitutional kernel remains the action boundary"],["MEMORY",brain?.available?"CONNECTED":state(a.memoryStatus),"Canonical governed context and memory"],["ORGANIZATION",o.status||((o.objectives||[]).length?"ACTIVE":"NO_ACTIVITY_OBSERVED"),"Canonical Phase 6 organization reader"],["ACADEMY",a.status||"NOT_RUN","Latest canonical Academy run"],["COMMAND INTELLIGENCE",brainAvailable()?"CONNECTED":"DEGRADED","Brain interface; fallback is explicitly identified"],["REAL-WORLD AIRLOCK",l.gates?.PHASE_9A_BODY_ARCHITECTURE_READY==="PASS"?"READY":"UNKNOWN","Phase 9A gate"],["AUTONOMY",l.authorizationState==="AUTHORIZED"?"AUTHORIZED":"BLOCKED","Controlled-live authority"],["LIVE ORGANISM",l.authorizationState==="AUTHORIZED"?"AUTHORIZED / ACTIVE":"DORMANT / AWAITING AUTHORIZATION","Controlled-live state"]].map(([id,status,evidence])=>({id,status,evidence}))}
 function economics(){const l=live(),run=controlledLiveService.raw?.().run,p=run?.payment||{},e=run?.economics||{};return {currency:"USD",projected:null,quoted:l.financialExposure?.maximumCharge??null,requested:p.requested??0,pending:p.state==="PENDING"?(p.requested??null):0,settled:p.settled??0,refunded:p.refund??0,fees:p.fee??null,fulfillmentCost:e.fulfillmentCost??null,netObservedContribution:e.netObservedContribution??null,classificationNote:"Projected and quoted amounts are not earned revenue."}}
 function activity(){const raw=controlledLiveService.raw?.()||{},events=[...(org().events||[]).map((event,index)=>({id:event.id||`org-${index}`,type:event.type,summary:clean(event.summary||event.type),at:event.at,evidenceRef:event.evidenceRef||event.subject||null,source:"ORGANIZATION_RUNTIME"})),...(raw.audit||[]).map((event,index)=>({id:`live-${index}-${event.at}`,type:event.type,summary:clean(event.type.replaceAll("_"," ").toLowerCase()),at:event.at,evidenceRef:event.authorizationId||event.runId||null,source:"CONTROLLED_LIVE_AUDIT"}))];return events.sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,30)}
 function humanActions(){const l=live(),actions=[];if(l.humanActionRequired&&l.humanActionRequired!=="NONE")actions.push({id:"controlled-live",label:l.humanActionRequired,reason:l.firstFailure?.code||`Controlled-live state is ${l.testAState}`,authorityRequired:true,reference:"controlled-live",doesNotAuthorize:["customer contact","charges","purchases","advertising spend","public publishing","independent market tests","policy or autonomy changes"]});return actions}
 function diagnostics(){const l=live(),stages=["AUTHENTICATION","COMMAND_STATE_LOAD","ORGANISM_STATUS","MISSION_LOAD","ACTIVITY_LOAD","DIAGNOSTIC_LOAD","COMMAND_INTELLIGENCE_CONTEXT","MODEL_GATEWAY","TOOL_INVOCATION","RESPONSE_GROUNDING","LIVE_UPDATE","RENDER","HUMAN_ACTION_PRESENTATION"],outcomes={};for(const name of stages)outcomes[name]={status:"NOT_RUN"};for(const name of stages.slice(0,6))outcomes[name]={status:"PASS"};if(pipeline.last)Object.assign(outcomes,pipeline.last.outcomes);const commandFailure=pipeline.last?.firstFailure||(!brainAvailable()?{stage:"MODEL_GATEWAY",code:"MODEL_GATEWAY_UNAVAILABLE",classification:"MODEL_GATEWAY_UNAVAILABLE",downstreamBlocked:["SEMANTIC_INTENT","BRAIN_REASONING"],recommendedNextStep:"Configure and restore the canonical governed Model Gateway; deterministic status remains available but is not Brain reasoning."}:null);const controlled=l.firstFailure?{stage:"CONTROLLED_LIVE",...l.firstFailure,classification:l.firstFailure.code,downstreamBlocked:["LIVE ORGANISM"],recommendedNextStep:"Review observed evidence and obtain authorized human judgment; do not infer root cause."}:null;return {stages,outcomes,firstFailure:commandFailure||controlled,dependencies:["authenticated admin","canonical readiness","canonical Brain/Model Gateway","canonical context/memory","governed readers","controlled-live store"],lastSuccessfulEvent:activity()[0]||null,lastFailedEvent:commandFailure||controlled,raw:{controlledLive:l,commandPipeline:pipeline.last}}}
 function summary(){const l=live(),actions=humanActions(),m=missions(),a=activity();return {schemaVersion:2,generatedAt:now(),freshness:{mechanism:"BOUNDED_POLLING",intervalMs:15000,observedAt:now()},humanActionRequired:actions[0]?.label||"NO ACTION REQUIRED",humanActions:actions,commandIntelligence:{brainStatus:brainAvailable()?"CONNECTED":"UNAVAILABLE",modelConnected:brainAvailable(),mode:brainAvailable()?"MODEL_GATEWAY":"DETERMINISTIC_FALLBACK",evidenceSources:0,materialUnknowns:true,authority:actions.length?"HUMAN ACTION REQUIRED":"NO ACTION REQUIRED",unavailableReason:brain?.unavailableReason||null},whereWeAre:`Controlled live: ${l.testAState}. ${m.length?`${m.length} mission${m.length===1?"":"s"} observed.`:"NO_ACTIVITY_OBSERVED."}`,whatHappened:a[0]?.summary||"NO_ACTIVITY_OBSERVED",whatHappensNext:l.nextAutonomousAction||"No next autonomous action is authorized.",why:actions[0]?.reason||"No authoritative source currently requests human judgment.",organism:organism(),missions:m,work:m.flatMap(x=>x.work),activity:a,firstFailure:diagnostics().firstFailure,economics:economics(),controlledLive:l,readiness:readiness(),academy:academy(),organization:{status:org().status||"UNKNOWN",roles:org().roles||[]},humanLabor:l.automationBudget||{humanApprovals:0,humanInterventions:0,humanMinutes:null,autonomousTransitions:0,escalations:0},intelligence:(org().artifacts||[]).map(x=>({...x,classification:x.classification||"UNKNOWN"}))}}
 const tools={get_command_summary:()=>summary(),get_human_actions:()=>humanActions(),get_organism_status:()=>organism(),get_missions:()=>missions(),get_mission:({id})=>missions().find(x=>x.id===id)||null,get_work:()=>missions().flatMap(x=>x.work),get_first_failure:()=>diagnostics().firstFailure,get_diagnostics:()=>diagnostics(),get_readiness:()=>readiness(),get_brain_certification:()=>academy(),get_academy_status:()=>academy(),get_authority_status:()=>({state:live().authorizationState,humanActions:humanActions()}),get_kill_switches:()=>live().killSwitches,get_controlled_live_status:()=>live(),get_evidence:()=>live().evidence||[],get_audit_summary:()=>activity(),get_economics:()=>economics(),get_learning:()=>summary().intelligence.filter(x=>/learning/i.test(x.artifactType||"")),get_reflection:()=>summary().intelligence.filter(x=>/reflection/i.test(x.artifactType||"")),get_role_status:()=>org().roles||[],get_recent_activity:()=>activity(),search_system_evidence:({query})=>(live().evidence||[]).filter(x=>JSON.stringify(x).toLowerCase().includes(clean(query).toLowerCase())).slice(0,20)};
 const toolCatalog=Object.keys(tools);
 const evidenceRef=(name,result,index)=>({id:`command-evidence:${name}:${index}`,tool:name,source:name.replace(/^get_/,"").toUpperCase(),classification:"OBSERVED_FACT_OR_CANONICAL_STATE",retrievedAt:now(),content:result});
 function fallback(requestId,started){const s=summary(),sources=["get_command_summary","get_first_failure","get_controlled_live_status","get_academy_status"],evidence=sources.map((name,index)=>evidenceRef(name,clone(tools[name]({})),index));pipeline.last={firstFailure:{stage:"MODEL_GATEWAY",code:"MODEL_GATEWAY_UNAVAILABLE",classification:"MODEL_GATEWAY_UNAVAILABLE"},outcomes:{COMMAND_INTELLIGENCE_CONTEXT:{status:"NOT_RUN"},MODEL_GATEWAY:{status:"FAIL",reason:"MODEL_GATEWAY_UNAVAILABLE"},TOOL_INVOCATION:{status:"PASS"},RESPONSE_GROUNDING:{status:"PASS",reason:"DETERMINISTIC_STATUS_ONLY"}}};return {version:VERSION,requestId,answer:`The cognitive Brain is currently unavailable (${brain?.unavailableReason||"MODEL_GATEWAY_UNAVAILABLE"}). I can report deterministic system status, but I cannot perform the requested semantic reasoning. ${s.whereWeAre} Test A authorization is ${s.controlledLive.authorizationState}. ${s.whatHappensNext}`,classification:"DETERMINISTIC_FALLBACK",reasoningOutcomeClassification:"BRAIN_UNAVAILABLE",intent:null,contextReferences:[],toolCalls:sources,evidenceReferences:evidence.map(x=>x.id),evidence,knownFacts:[],inferences:[],unknowns:["The requested Brain reasoning was not performed."],assumptions:[],recommendations:[],authorityRequirements:s.humanActions,modelGatewayUsed:null,responseTimestamp:now(),telemetry:{provider:null,model:null,latencyMs:Date.now()-started,tokenUsage:null,cost:null,fallback:true}}}
 async function converse({actor,question,mode="EXECUTIVE",screenContext=null,conversationId=null}){if(!actor?.userId)throw new Error("authenticated_actor_required");const safeQuestion=clean(question);if(!safeQuestion)throw new Error("question_required");const requestId=id(),started=Date.now(),thread=clean(conversationId||requestId);if(!brain?.available&&typeof modelGateway!=="function")return fallback(requestId,started);
  if(typeof modelGateway==="function"&&!brain){const result=await modelGateway({requestId,question:safeQuestion,mode,screenContext,retrieved:[{name:"get_command_summary",result:summary()}],actor});if(!result?.answer)throw new Error("model_gateway_ungrounded_response");return {version:VERSION,requestId,answer:clean(result.answer),classification:"GROUNDED_EXPLANATION",toolCalls:["get_command_summary"],evidenceReferences:["get_command_summary"],unknowns:[],authorityRequirements:[],telemetry:{provider:"MODEL_GATEWAY",model:null,latencyMs:Date.now()-started,tokenUsage:null,cost:null,fallback:false}}}
  const understood=await brain.understand({actor,question:safeQuestion,mode,screenContext,conversationId:thread,requestId,toolCatalog});if(!understood.ok){pipeline.last={firstFailure:{stage:"COMMAND_INTELLIGENCE_CONTEXT",code:understood.failure,classification:understood.failure},outcomes:{COMMAND_INTELLIGENCE_CONTEXT:{status:"FAIL",reason:understood.failure},MODEL_GATEWAY:{status:"BLOCKED"},TOOL_INVOCATION:{status:"NOT_RUN"},RESPONSE_GROUNDING:{status:"NOT_RUN"}}};return fallback(requestId,started)}
  if(/failure|broken|stopped|wrong|issue|problem|debug|diagnostic|translate|panel|health|healthy/i.test(safeQuestion)){const extra=["get_first_failure","get_diagnostics","get_readiness","get_academy_status","get_controlled_live_status"];understood.intent.toolNames=[...new Set([...(understood.intent.toolNames||[]),...extra])];}\n  const selected=understood.intent.toolNames;if(!Array.isArray(selected)||selected.some(name=>!tools[name])){pipeline.last={firstFailure:{stage:"TOOL_INVOCATION",code:"TOOL_SELECTION_FAILURE",classification:"TOOL_SELECTION_FAILURE"},outcomes:{COMMAND_INTELLIGENCE_CONTEXT:{status:"PASS"},MODEL_GATEWAY:{status:"PASS"},TOOL_INVOCATION:{status:"FAIL",reason:"TOOL_SELECTION_FAILURE"},RESPONSE_GROUNDING:{status:"NOT_RUN"}}};throw new Error("TOOL_SELECTION_FAILURE")}
  const names=[...new Set(selected)],evidence=[];try{for(const [index,name] of names.entries())evidence.push(evidenceRef(name,clone(tools[name](screenContext?.reference?{id:screenContext.reference,query:safeQuestion}:{query:safeQuestion})),index))}catch(error){pipeline.last={firstFailure:{stage:"TOOL_INVOCATION",code:"EVIDENCE_RETRIEVAL_FAILURE",classification:"EVIDENCE_RETRIEVAL_FAILURE"},outcomes:{COMMAND_INTELLIGENCE_CONTEXT:{status:"PASS"},MODEL_GATEWAY:{status:"PASS"},TOOL_INVOCATION:{status:"FAIL"},RESPONSE_GROUNDING:{status:"NOT_RUN"}}};throw error}
  const reasoned=await brain.reason({actor,question:safeQuestion,mode,requestId,intent:understood.intent,evidence,contextPackage:understood.contextPackage});if(!reasoned.ok){pipeline.last={firstFailure:{stage:"MODEL_GATEWAY",code:reasoned.failure,classification:reasoned.failure},outcomes:{COMMAND_INTELLIGENCE_CONTEXT:{status:"PASS"},MODEL_GATEWAY:{status:"FAIL",reason:reasoned.failure},TOOL_INVOCATION:{status:"PASS"},RESPONSE_GROUNDING:{status:"NOT_RUN"}}};return fallback(requestId,started)}
  const content=reasoned.content;if(!content.answer||!Array.isArray(content.unknowns)){pipeline.last={firstFailure:{stage:"RESPONSE_GROUNDING",code:"RESPONSE_GROUNDING_FAILURE",classification:"RESPONSE_GROUNDING_FAILURE"},outcomes:{COMMAND_INTELLIGENCE_CONTEXT:{status:"PASS"},MODEL_GATEWAY:{status:"PASS"},TOOL_INVOCATION:{status:"PASS"},RESPONSE_GROUNDING:{status:"FAIL"}}};throw new Error("RESPONSE_GROUNDING_FAILURE")}
  const authorityRequirements=[...content.authorityRequirements,...(understood.intent.actionRequested?humanActions():[])];brain.remember(actor,thread,requestId,{ownerQuestion:safeQuestion,intent:understood.intent.intent,informationNeeds:understood.intent.informationNeeds,evidenceReferences:evidence.map(x=>x.id),answerSummary:content.answer.slice(0,1200),unknowns:content.unknowns,authorityRequirements});pipeline.last={firstFailure:authorityRequirements.length?{stage:"HUMAN_ACTION_PRESENTATION",code:"ACTION_AUTHORIZATION_REQUIRED",classification:"ACTION_AUTHORIZATION_REQUIRED"}:null,outcomes:{COMMAND_INTELLIGENCE_CONTEXT:{status:"PASS"},MODEL_GATEWAY:{status:"PASS"},TOOL_INVOCATION:{status:"PASS"},RESPONSE_GROUNDING:{status:"PASS"},HUMAN_ACTION_PRESENTATION:{status:"PASS"}}};const invocation=reasoned.gateway.invocations?.at(-1);
  return {version:VERSION,requestId,conversationId:thread,answer:clean(content.answer),classification:"GROUNDED_BRAIN_RESPONSE",reasoningOutcomeClassification:reasoned.gateway.result.metacognitiveState,intent:understood.intent,contextReferences:understood.contextPackage.items.map(x=>x.record.id),toolCalls:names,evidenceReferences:evidence.map(x=>x.id),evidence,knownFacts:content.facts,inferences:content.inferences,unknowns:content.unknowns,assumptions:content.assumptions||[],recommendations:content.recommendations,authorityRequirements,modelGatewayUsed:invocation?{provider:invocation.provider,model:invocation.model,version:invocation.version,invocationId:invocation.id}:null,responseTimestamp:now(),screenContext:screenContext?{type:clean(screenContext.type),reference:clean(screenContext.reference)}:null,telemetry:{provider:invocation?.provider||"MODEL_GATEWAY",model:invocation?.model||null,latencyMs:Date.now()-started,tokenUsage:invocation?.usage||null,cost:invocation?.cost||null,fallback:false}}
 }
 return Object.freeze({summary,missions,diagnostics,economics,tools,converse,VERSION,PIPELINE_FAILURES});
}
module.exports={createCommandCenterService,clean,lifecycle,VERSION,PIPELINE_FAILURES};
