"use strict";
const crypto=require("node:crypto");

const VERSION="command-intelligence/1.0.0";
const SECRET=/(sk_(?:live|test)_[a-z0-9_-]+|bearer\s+[a-z0-9._-]+|api[_-]?key\s*[:=]\s*\S+)/ig;
const clean=value=>String(value??"").replace(SECRET,"[REDACTED]").slice(0,4000);
const clone=value=>JSON.parse(JSON.stringify(value));
const state=(value,fallback="UNKNOWN")=>value===undefined||value===null||value===""?fallback:value;
const lifecycle=value=>({CREATED:"BACKLOG",ELIGIBLE:"READY",ASSIGNED:"READY",RUNNING:"ACTIVE",BLOCKED:"BLOCKED",FAILED:"BLOCKED",COMPLETED:"COMPLETE",CANCELLED:"COMPLETE"}[value]||"UNKNOWN");

function createCommandCenterService({controlledLiveService,readinessService=null,organizationReader=null,academyReader=null,modelGateway=null,clock=()=>new Date(),id=()=>crypto.randomUUID()}={}){
 if(!controlledLiveService)throw new Error("controlled_live_source_required");
 const now=()=>clock().toISOString();
 const live=()=>controlledLiveService.snapshot();
 const commandModelAvailable=()=>typeof modelGateway==="function";
 const readiness=()=>readinessService?.snapshot?.()||{boards:{},source:"UNAVAILABLE"};
 const org=()=>organizationReader?.()||{objectives:[],work:[],artifacts:[],events:[]};
 function missions(){const o=org(),work=o.work||[];return (o.objectives||[]).map(objective=>{const items=work.filter(x=>x.objectiveRef===objective.id);return {id:objective.id,title:objective.objective,why:objective.scope||null,status:state(objective.status),priority:state(objective.priority),successCriteria:objective.successCriteria||[],stage:items.some(x=>x.state==="BLOCKED"||x.state==="FAILED")?"BLOCKED":items.length&&items.every(x=>x.state==="COMPLETED")?"COMPLETE":items.some(x=>x.state==="RUNNING")?"ACTIVE":"BACKLOG",work:items.map(mapWork),evidenceRefs:objective.evidenceRefs||[],nextGate:null,humanAction:null}})}
 function mapWork(x){return {id:x.id,missionId:x.objectiveRef,type:x.missionType,state:x.state,column:lifecycle(x.state),role:(x.eligibleRoleIds||[]).join(", ")||"UNASSIGNED",priority:x.priority||"UNKNOWN",dependencies:x.dependencyWorkRefs||[],firstFailure:x.firstFailure||null,humanAction:x.humanAction||null,evidenceRefs:x.outputArtifactRefs||x.inputArtifactRefs||[],updatedAt:x.completedAt||x.createdAt||null,nextAction:null}}
 function organism(){const l=live(),academy=academyReader?.()||null;return [
  ["BRAIN",academy?.brainStatus||"UNKNOWN","Brain certification evidence"],["CONSTITUTION","ENFORCING","Constitutional kernel is the action boundary"],["MEMORY",academy?.memoryStatus||"UNKNOWN","Governed memory status"],["ORGANIZATION",org().objectives?.length?"ACTIVE":"READY","Canonical organizational objectives"],["ACADEMY",academy?.status||"UNKNOWN","Latest Academy certification"],["COMMAND INTELLIGENCE",commandModelAvailable()?"MODEL CONNECTED":"DETERMINISTIC FALLBACK","Server-side governed explanation capability"],["REAL-WORLD AIRLOCK",l.gates?.PHASE_9A_BODY_ARCHITECTURE_READY==="PASS"?"READY":"UNKNOWN","Phase 9A gate"],["AUTONOMY",l.authorizationState==="AUTHORIZED"?"AUTHORIZED":"BLOCKED","Controlled-live authority"],["LIVE ORGANISM",l.authorizationState==="AUTHORIZED"?"AUTHORIZED / ACTIVE":"DORMANT / AWAITING AUTHORIZATION","Controlled-live state"]
 ].map(([id,status,evidence])=>({id,status,evidence}));}
 function economics(){const l=live(),run=controlledLiveService.raw?.().run,p=run?.payment||{},e=run?.economics||{};return {currency:"USD",projected:null,quoted:l.financialExposure?.maximumCharge??null,requested:p.requested??0,pending:p.state==="PENDING"?(p.requested??null):0,settled:p.settled??0,refunded:p.refund??0,fees:p.fee??null,fulfillmentCost:e.fulfillmentCost??null,netObservedContribution:e.netObservedContribution??null,classificationNote:"Projected and quoted amounts are not earned revenue."}}
 function activity(){const raw=controlledLiveService.raw?.()||{};return (raw.audit||[]).slice(-30).reverse().map((event,index)=>({id:`live-${index}-${event.at}`,type:event.type,summary:clean(event.type.replaceAll("_"," ").toLowerCase()),at:event.at,evidenceRef:event.authorizationId||event.runId||null,source:"CONTROLLED_LIVE_AUDIT"}))}
 function humanActions(){const l=live(),actions=[];if(l.humanActionRequired&&l.humanActionRequired!=="NONE")actions.push({id:"controlled-live",label:l.humanActionRequired,reason:l.firstFailure?.code||`Controlled-live state is ${l.testAState}`,authorityRequired:true,reference:"controlled-live"});return actions}
 function diagnostics(){const l=live(),stages=["AUTHENTICATION","COMMAND_STATE_LOAD","ORGANISM_STATUS","MISSION_LOAD","ACTIVITY_LOAD","DIAGNOSTIC_LOAD","COMMAND_INTELLIGENCE_CONTEXT","MODEL_GATEWAY","TOOL_INVOCATION","RESPONSE_GROUNDING","LIVE_UPDATE","RENDER","HUMAN_ACTION_PRESENTATION"];const outcomes={};for(const stageName of stages)outcomes[stageName]={status:["MODEL_GATEWAY","TOOL_INVOCATION","RESPONSE_GROUNDING","LIVE_UPDATE","RENDER","HUMAN_ACTION_PRESENTATION"].includes(stageName)?"NOT_RUN":"PASS"};const first=l.firstFailure?{stage:"CONTROLLED_LIVE",...l.firstFailure,classification:l.firstFailure.code,downstreamBlocked:["LIVE ORGANISM"],recommendedNextStep:"Review observed evidence and obtain authorized human judgment; do not infer root cause."}:null;return {stages,outcomes,firstFailure:first,dependencies:["authenticated admin","canonical readiness","controlled-live store"],lastSuccessfulEvent:activity()[0]||null,lastFailedEvent:first,raw:{controlledLive:l}}}
 function summary(){const l=live(),actions=humanActions(),m=missions(),a=activity();return {schemaVersion:1,generatedAt:now(),freshness:{mechanism:"BOUNDED_POLLING",intervalMs:15000,observedAt:now()},humanActionRequired:actions[0]?.label||"SYSTEM HEALTHY — NO ACTION REQUIRED",humanActions:actions,commandIntelligence:{modelConnected:commandModelAvailable(),mode:commandModelAvailable()?"MODEL_GATEWAY":"DETERMINISTIC_FALLBACK"},whereWeAre:`Controlled live: ${l.testAState}. ${m.length} mission${m.length===1?"":"s"} observed.`,whatHappened:a[0]?.summary||"No organizational activity observed.",whatHappensNext:l.nextAutonomousAction||"No next autonomous action is authorized.",why:actions[0]?.reason||"No authoritative state currently requests human judgment.",organism:organism(),missions:m,work:m.flatMap(x=>x.work),activity:a,firstFailure:diagnostics().firstFailure,economics:economics(),controlledLive:l,readiness:readiness(),humanLabor:l.automationBudget||{humanApprovals:0,humanInterventions:0,humanMinutes:null,autonomousTransitions:0,escalations:0},intelligence:(org().artifacts||[]).map(x=>({...x,classification:x.classification||"UNKNOWN"}))};}
 const tools={get_command_summary:()=>summary(),get_human_actions:()=>humanActions(),get_organism_status:()=>organism(),get_missions:()=>missions(),get_mission:({id})=>missions().find(x=>x.id===id)||null,get_work:()=>summary().work,get_first_failure:()=>diagnostics().firstFailure,get_diagnostics:()=>diagnostics(),get_readiness:()=>readiness(),get_brain_certification:()=>academyReader?.()||{status:"UNKNOWN"},get_academy_status:()=>academyReader?.()||{status:"UNKNOWN"},get_authority_status:()=>({state:live().authorizationState}),get_kill_switches:()=>live().killSwitches,get_controlled_live_status:()=>live(),get_evidence:()=>live().evidence||[],get_audit_summary:()=>activity(),get_economics:()=>economics(),get_learning:()=>summary().intelligence.filter(x=>/learning/i.test(x.artifactType||"")),get_reflection:()=>summary().intelligence.filter(x=>/reflection/i.test(x.artifactType||"")),get_role_status:()=>[],get_recent_activity:()=>activity(),search_system_evidence:({query})=>(live().evidence||[]).filter(x=>JSON.stringify(x).toLowerCase().includes(clean(query).toLowerCase())).slice(0,20)};
 function chooseTools(question,context){const q=question.toLowerCase(),calls=[];if(/money|revenue|settled|projected|economic/.test(q))calls.push("get_economics");if(/failure|wrong|stop|debug|diagnostic/.test(q)||context?.type==="diagnostic")calls.push("get_first_failure","get_diagnostics");if(/mission|project|blocked/.test(q)||context?.type==="mission")calls.push("get_missions");if(/need me|human|approval|authorize/.test(q))calls.push("get_human_actions","get_authority_status");if(/learn/.test(q))calls.push("get_learning");if(/sales|analyst|role/.test(q))calls.push("get_role_status");if(!calls.length)calls.push("get_command_summary");return [...new Set(calls)];}
 async function converse({actor,question,mode="EXECUTIVE",screenContext=null}){if(!actor?.userId)throw new Error("authenticated_actor_required");const safeQuestion=clean(question);if(!safeQuestion)throw new Error("question_required");const toolCalls=chooseTools(safeQuestion,screenContext),retrieved=toolCalls.map(name=>({name,result:clone(tools[name](screenContext?.reference?{id:screenContext.reference}:{}))}));const requestId=id(),started=Date.now();if(/^\s*(do it|authorize|approve|turn (?:it|them) on)\s*[.!]?$/i.test(safeQuestion))return {version:VERSION,requestId,answer:"I can prepare the governed authorization request, but I cannot authorize it. Review the structured action card and explicitly approve through the authenticated control.",classification:"RECOMMENDATION",actionCard:{action:"Authorize Controlled Live Test A",scope:"1 controlled participant",product:"30-day digital fitness challenge",acquisitionSpend:"$0",maximumCharge:"$50",paymentPath:"Canonical Stripe",expiration:"Human must choose",stopConditions:"Canonical plan stop conditions"},toolCalls,groundedIn:toolCalls,telemetry:{provider:null,model:null,latencyMs:Date.now()-started,tokenUsage:null,cost:null,fallback:false}};
 let answer;if(modelGateway){const result=await modelGateway({requestId,question:safeQuestion,mode,screenContext,retrieved,actor});answer=result?.answer; if(!answer)throw new Error("model_gateway_ungrounded_response");}else{const s=summary();answer=`${s.whereWeAre} ${s.humanActionRequired}. ${s.whatHappensNext} ${s.why}`;}
 return {version:VERSION,requestId,answer:clean(answer),classification:"GROUNDED_EXPLANATION",uncertainty:retrieved.some(x=>JSON.stringify(x.result).includes("UNKNOWN"))?"Some requested state is UNKNOWN.":null,toolCalls,groundedIn:toolCalls,screenContext:screenContext?{type:clean(screenContext.type),reference:clean(screenContext.reference)}:null,telemetry:{provider:modelGateway?"MODEL_GATEWAY":null,model:null,latencyMs:Date.now()-started,tokenUsage:null,cost:null,fallback:!modelGateway}}}
 return Object.freeze({summary,missions,diagnostics,economics,tools,converse,VERSION});
}
module.exports={createCommandCenterService,clean,lifecycle,VERSION};
