'use strict';

function enumValues(values) {
  return Object.freeze(Object.fromEntries(values.map((value) => [value, value])));
}

const PROGRAM_LENGTHS = Object.freeze([8, 12, 32]);
const PROGRAM_STATES = enumValues(['DRAFT', 'READY_FOR_BASELINE', 'BASELINE_IN_PROGRESS', 'READY_TO_START', 'ACTIVE', 'PAUSED', 'REASSESSMENT_DUE', 'COMPLETED', 'ARCHIVED']);
const PHASE_STATES = enumValues(['PLANNED', 'ACTIVE', 'COMPLETED']);
const WEEK_STATES = enumValues(['PLANNED', 'ACTIVE', 'COMPLETED']);
const SESSION_SLOT_STATES = enumValues(['PLANNED', 'READY_FOR_SESSION_PLANNING', 'COMPLETED', 'EXCLUDED']);
const INTENDED_EFFORTS = enumValues(['LOW', 'LOW_TO_MODERATE', 'MODERATE']);
const SESSION_FOCUSES = enumValues(['MOVEMENT_LEARNING_FULL_BODY', 'STRENGTH_ENDURANCE_CONTROL', 'COORDINATION_AEROBIC_MOBILITY', 'BALANCED_FULL_BODY', 'AEROBIC_CAPACITY_MOVEMENT', 'MOVEMENT_CONTROL_MOBILITY']);
const REQUIRED_DOMAINS = enumValues(['MOVEMENT_SKILL', 'STRENGTH', 'AEROBIC_FITNESS', 'MOBILITY', 'COORDINATION', 'RECOVERY']);

module.exports = { PROGRAM_LENGTHS, PROGRAM_STATES, PHASE_STATES, WEEK_STATES, SESSION_SLOT_STATES, INTENDED_EFFORTS, SESSION_FOCUSES, REQUIRED_DOMAINS };
