"use strict";
const crypto=require("node:crypto"),C=require("./contracts"),{createWorldClock}=require("./clock"),{createSeededRandom}=require("./random"),{createSyntheticLedger}=require("./ledger");
const clone=structuredClone;
function createSimulationWorld(input,{id=()=>crypto.randomUUID()}={}){
 const scenario=C.SimulationScenario(input),clock=createWorldClock(scenario.startTime),random=createSeededRandom(scenario.seed);
 const state={scenarioRef:`${scenario.id}@${scenario.version}`,worldVersion:scenario.worldVersion,cycle:0,customers:new Map(scenario.customers.map(x=>[x.id,clone(x)])),opportunities:new Map(scenario.opportunities.map(x=>[x.id,clone(x)])),offers:new Map(),orders:new Map(),obligations:new Map(),deliveries:new Map(),capacity:{...scenario.capacity,reserved:scenario.capacity.reserved||0},transitions:[],failures:[],eventCursor:0};
 const ledger=createSyntheticLedger({startingCash:scenario.startingCash,clock,id});for(const e of scenario.scheduledEvents)clock.schedule(e);
 const observableCustomer=c=>({id:c.id,segment:c.segment,statements:clone(c.observable||[]),satisfaction:c.satisfaction??0});
 const opportunity=o=>({id:o.id,source:o.source,customerRef:o.customerRef,segment:o.segment,problem:o.problem,observableEvidence:clone(o.observableEvidence),potentialValue:o.potentialValue,urgency:o.urgency,risk:o.risk,expiration:o.expiration,requiredCapability:o.requiredCapability,confidence:o.confidence});
 function transition(kind,previous,next,trigger,economicEffect=null,evidenceRefs=[]){const x=Object.freeze({id:id(),kind,previous:clone(previous),next:clone(next),trigger:{actionId:trigger.id,type:trigger.type,actorRef:trigger.actorRef,workRef:trigger.workRef},at:clock.now(),correlationId:trigger.correlationId,causationId:trigger.causationId,economicEffect,evidenceRefs:[...evidenceRefs]});state.transitions.push(x);return x}
 function observe(type,value,evidenceRefs){return C.SimulationObservation({id:id(),type,at:clock.now(),observable:clone(value),evidenceRefs})}
 function validateAction(a){const x=C.SimulationAction(a);if(!C.ACTIONS.includes(x.type))throw new Error("unknown_simulation_action");if(x.at!==clock.now())throw new Error("action_time_not_world_time");if(!x.authority?.allowed)throw Object.assign(new Error("world_action_not_authorized"),{failureClass:"POLICY_AUTHORITY_FAILURE"});return x}
 function act(raw){const a=validateAction(raw),p=a.payload||{};let before,result;
  switch(a.type){
   case "OBSERVE_MARKET": result=observe("MARKET",[...state.opportunities.values()].filter(o=>!o.arrivesAt||o.arrivesAt<=clock.now()).map(opportunity),["world:market"]);break;
   case "INSPECT_OPPORTUNITY":{const o=state.opportunities.get(p.opportunityId);if(!o)throw new Error("opportunity_not_found");result=observe("OPPORTUNITY",{...opportunity(o),discoverable:clone(o.discoverable||{})},[`world:opportunity:${o.id}`]);break}
   case "RUN_SYNTHETIC_EXPERIMENT": result=observe("EXPERIMENT",{opportunityId:p.opportunityId,signal:random.next()<(p.successProbability??.5)?"POSITIVE":"NEGATIVE"},[`world:experiment:${p.opportunityId}`]);break;
   case "MAKE_SYNTHETIC_OFFER":{const o=state.opportunities.get(p.opportunityId),customer=o&&state.customers.get(o.customerRef);if(!o||!customer)throw new Error("offer_target_not_found");if(o.prohibited)throw Object.assign(new Error("policy_prohibited_transaction"),{failureClass:"POLICY_AUTHORITY_FAILURE"});const offer={id:p.offerId,opportunityRef:o.id,customerRef:customer.id,price:p.price,status:"OFFERED",createdAt:clock.now()};state.offers.set(offer.id,offer);ledger.record({type:"REVENUE",classification:"QUOTED",amount:p.price,reference:offer.id,idempotencyKey:`quote:${offer.id}`});const accepted=p.price<=customer.hidden.budget&&customer.hidden.accepts!==false;before=offer.status;offer.status=accepted?"ACCEPTED":"REJECTED";transition("OFFER_RESPONSE",before,offer.status,a,null,[`world:customer-rule:${customer.id}`]);if(!accepted)state.failures.push({class:"MARKET_RESULT",at:clock.now(),reference:offer.id});result=observe("OFFER_RESPONSE",{offerId:offer.id,status:offer.status,customerStatement:accepted?"acceptable":"price feels high"},[`world:offer:${offer.id}`]);break}
   case "ACCEPT_SYNTHETIC_ORDER":{const offer=state.offers.get(p.offerId);if(offer?.status!=="ACCEPTED")throw new Error("offer_not_accepted");if(state.obligations.has(`obligation:${offer.id}`)){result=observe("ORDER_REPLAY",{obligationId:`obligation:${offer.id}`},[`world:obligation:${offer.id}`]);break}const o=state.opportunities.get(offer.opportunityRef),cap=scenario.capabilities.find(x=>x.id===o.requiredCapability);const obligation=C.SyntheticObligation({id:`obligation:${offer.id}`,customerRef:offer.customerRef,offerRef:offer.id,status:"ORDERED",acceptanceCriteria:cap.acceptanceCriteria,deadline:o.expiration,price:offer.price,refundTerms:cap.refundTerms||"DECLARED",productionRequirements:{capabilityRef:cap.id,units:cap.capacityUnits},qaRequirements:cap.qaContract});state.obligations.set(obligation.id,obligation);state.orders.set(`order:${offer.id}`,{id:`order:${offer.id}`,offerRef:offer.id,status:"ORDERED"});ledger.record({type:"REVENUE",classification:"PENDING",amount:offer.price,reference:obligation.id,idempotencyKey:`payment-pending:${offer.id}`});transition("OBLIGATION_CREATED",null,obligation,a,null,[`world:offer:${offer.id}`]);result=observe("ORDER",obligation,[`world:obligation:${obligation.id}`]);break}
   case "ALLOCATE_CAPACITY":{const ob=state.obligations.get(p.obligationId),units=ob?.productionRequirements.units;if(!ob)throw new Error("obligation_not_found");if(ob.status!=="ORDERED")throw new Error("obligation_not_eligible_for_allocation");if(state.capacity.total-state.capacity.reserved<units)throw Object.assign(new Error("capacity_oversubscribed"),{failureClass:"PRODUCTION_FAILURE"});before=clone(state.capacity);state.capacity.reserved+=units;state.capacity.active=(state.capacity.active||0)+units;state.obligations.set(ob.id,Object.freeze({...ob,status:"IN_PRODUCTION"}));transition("CAPACITY_RESERVED",before,state.capacity,a,null,[`world:obligation:${ob.id}`]);result=observe("CAPACITY",state.capacity,[`world:capacity`]);break}
   case "PRODUCE_SYNTHETIC_OUTPUT":{const ob=state.obligations.get(p.obligationId);if(ob?.status!=="IN_PRODUCTION")throw new Error("obligation_not_in_production");const cap=scenario.capabilities.find(x=>x.id===ob.productionRequirements.capabilityRef);if(cap.technicalFailure)throw Object.assign(new Error("synthetic_tool_failure"),{failureClass:"TECHNICAL_FAILURE"});if(cap.unknownCost)throw Object.assign(new Error("production_cost_unknown"),{failureClass:"ECONOMIC_UNCERTAINTY"});ledger.record({type:"COST",classification:"INCURRED",amount:cap.productionCost,reference:ob.id,idempotencyKey:`production:${ob.id}`});const output={id:`output:${ob.id}`,obligationRef:ob.id,producerRef:a.actorRef,quality:cap.outputQuality,criteria:cap.acceptanceCriteria,status:"PRODUCED"};state.deliveries.set(output.id,output);transition("PRODUCTION_COMPLETED",null,output,a,{cost:cap.productionCost},[`world:capability:${cap.id}`]);result=observe("PRODUCTION",output,[`world:output:${output.id}`]);break}
   case "REQUEST_QA":{const out=state.deliveries.get(p.outputId);if(!out)throw new Error("output_not_found");if(a.actorRef===out.producerRef)throw new Error("production_self_qa_prohibited");const pass=out.criteria.every(x=>out.quality?.includes(x));before=out.status;out.status=pass?"QA_PASSED":"QA_REJECTED";const ob=state.obligations.get(out.obligationRef);state.obligations.set(ob.id,Object.freeze({...ob,status:out.status}));if(!pass)state.failures.push({class:"QA_FAILURE",at:clock.now(),reference:out.id});transition("QA_VERDICT",before,out.status,a,null,[`world:output:${out.id}`]);result=observe("QA",{outputId:out.id,verdict:pass?"PASS":"FAIL",failures:pass?[]:out.criteria.filter(x=>!out.quality?.includes(x))},[`world:qa:${out.id}`]);break}
   case "DELIVER_SYNTHETIC_OUTPUT":{const out=state.deliveries.get(p.outputId),ob=out&&state.obligations.get(out.obligationRef);if(out?.status==="DELIVERED"&&ob?.status==="CUSTOMER_ACCEPTED"){ledger.record({type:"REVENUE",classification:"SETTLED",amount:ob.price,reference:ob.id,idempotencyKey:`settlement:${ob.id}`});result=observe("DELIVERY_REPLAY",{outputId:out.id,status:"CUSTOMER_ACCEPTED"},[`world:delivery:${out.id}`]);break}if(out?.status!=="QA_PASSED")throw new Error("qa_pass_required_for_delivery");before=out.status;out.status="DELIVERED";state.obligations.set(ob.id,Object.freeze({...ob,status:"CUSTOMER_ACCEPTED"}));state.capacity.reserved-=ob.productionRequirements.units;state.capacity.active-=ob.productionRequirements.units;ledger.record({type:"REVENUE",classification:"SETTLED",amount:ob.price,reference:ob.id,idempotencyKey:`settlement:${ob.id}`});transition("DELIVERED",before,out.status,a,{settledRevenue:ob.price},[`world:qa:${out.id}`]);result=observe("DELIVERY",{outputId:out.id,status:"CUSTOMER_ACCEPTED"},[`world:delivery:${out.id}`]);break}
   case "ISSUE_SYNTHETIC_REFUND":{const ob=state.obligations.get(p.obligationId);if(!ob)throw new Error("obligation_not_found");if(ob.status==="REFUNDED"){result=observe("REFUND_REPLAY",{obligationId:ob.id,status:"REFUNDED"},[`world:refund:${ob.id}`]);break}const settled=ledger.entries().some(x=>x.type==="REVENUE"&&x.classification==="SETTLED"&&x.reference===ob.id);if(!settled)throw Object.assign(new Error("refund_requires_settled_payment"),{failureClass:"ECONOMIC_UNCERTAINTY"});const previous=ob.status;state.obligations.set(ob.id,Object.freeze({...ob,status:"REFUNDED"}));if(["IN_PRODUCTION","QA_REJECTED","QA_PASSED"].includes(previous)){state.capacity.reserved-=ob.productionRequirements.units;state.capacity.active-=ob.productionRequirements.units}ledger.record({type:"REFUND",classification:"REFUNDED",amount:ob.price,reference:ob.id,idempotencyKey:`refund:${ob.id}`});transition("REFUNDED",previous,"REFUNDED",a,{refund:ob.price},[`world:obligation:${ob.id}`]);result=observe("REFUND",{obligationId:ob.id,status:"REFUNDED"},[`world:refund:${ob.id}`]);break}
   case "CANCEL_WORK": result=observe("CANCELLATION",{reference:p.reference,status:"CANCELLED"},[`world:cancellation:${p.reference}`]);break;
  }return result
 }
 function advance(ms){const events=clock.advance(ms);for(const e of events){state.eventCursor++;if(e.type==="CAPACITY_CHANGE")state.capacity.total=e.payload.total;if(e.type==="OPPORTUNITY_ARRIVAL")state.opportunities.set(e.payload.opportunity.id,clone(e.payload.opportunity));}state.cycle++;return clone(events)}
 function snapshot(){return {state:{...clone(state),customers:[...state.customers],opportunities:[...state.opportunities],offers:[...state.offers],orders:[...state.orders],obligations:[...state.obligations],deliveries:[...state.deliveries]},clock:clock.snapshot(),randomState:random.snapshot(),ledger:ledger.snapshot()}}
 function checkpoint(){return C.SimulationCheckpoint({id:id(),cycleNumber:state.cycle,worldState:snapshot().state,clock:clock.snapshot(),randomState:random.snapshot(),eventCursor:state.eventCursor,ledger:ledger.snapshot()})}
 return Object.freeze({scenario,clock,act,advance,checkpoint,snapshot,ledger,state,publicState:()=>({scenarioRef:state.scenarioRef,cycle:state.cycle,customers:[...state.customers.values()].map(observableCustomer),opportunities:[...state.opportunities.values()].map(opportunity),obligations:[...state.obligations.values()].map(x=>clone(x)),capacity:clone(state.capacity),ledger:ledger.entries(),transitions:clone(state.transitions),failures:clone(state.failures)})});
}
module.exports={createSimulationWorld};
