'use strict';

function enumValues(items) {
  return Object.freeze(Object.fromEntries(items.map((item) => [item, item])));
}

const COMPLETION_STATUSES = enumValues(['COMPLETED', 'PARTIAL', 'SKIPPED', 'STOPPED_EARLY', 'BLOCKED_BY_SAFETY', 'COACH_REVIEW_REQUIRED']);
const COMPLETION_QUALITIES = enumValues(['SUCCESSFUL', 'SUCCESSFUL_WITH_WARNINGS', 'TOO_EASY', 'TOO_HARD', 'FORM_BREAKDOWN', 'PAIN_REPORTED', 'FATIGUE_LIMITED', 'INCOMPLETE', 'NOT_ASSESSED']);
const REPORTED_EFFORTS = enumValues(['EASY', 'MODERATE', 'TOO_HARD', 'NOT_REPORTED']);
const TECHNIQUE_QUALITIES = enumValues(['CONTROLLED', 'ACCEPTABLE', 'FORM_BREAKDOWN', 'NOT_ASSESSED']);
const ADAPTATION_DECISIONS = enumValues(['MAINTAIN', 'PROGRESS_ONE_VARIABLE', 'REGRESS', 'REDUCE_VOLUME', 'REDUCE_IMPACT', 'REPEAT_OBJECTIVE', 'SUBSTITUTE_LOWER_STRESS_ACTIVITY', 'REQUIRE_COACH_REVIEW', 'BLOCK_UNTIL_REVIEW', 'NO_CHANGE_SKIPPED_SESSION', 'DELAY_REASSESSMENT', 'READY_FOR_REASSESSMENT']);
const ADJUSTMENT_TYPES = enumValues(['INCREASE_REPS', 'INCREASE_DURATION', 'INCREASE_SETS', 'ADJUST_REST', 'ADJUST_RANGE_OF_MOTION', 'ADJUST_TEMPO_CONTROL', 'PROGRESS_ACTIVITY', 'REGRESS_ACTIVITY', 'REDUCE_VOLUME', 'REDUCE_IMPACT', 'REPEAT_OBJECTIVE']);
const ADJUSTMENT_SCOPES = enumValues(['SESSION', 'BLOCK', 'ACTIVITY']);

module.exports = { COMPLETION_STATUSES, COMPLETION_QUALITIES, REPORTED_EFFORTS, TECHNIQUE_QUALITIES, ADAPTATION_DECISIONS, ADJUSTMENT_TYPES, ADJUSTMENT_SCOPES };
