"use strict";
const crypto=require("node:crypto");
const {SIGNAL_TYPES,ScoutSourceObservation}=require("./contracts");
const forbidden=/\b(password|secret|bearer|card(number)?|cvv|bank[_ -]?account|routing[_ -]?number|api[_ -]?key|access[_ -]?token|refresh[_ -]?token)\b/i;
const hash=v=>crypto.createHash("sha256").update(JSON.stringify(v)).digest("hex");
function configuredAdapter({sourceId,configuration,reader}){if(typeof reader!=="function")throw new Error("source_reader_required");return Object.freeze({sourceId,async read(request={}){if(!configuration?.authorizationVerified||!configuration?.resourceVerified)return {sourceId,status:"HUMAN_CONFIGURATION_REQUIRED",records:[],evidenceRefs:[],firstFailure:"SOURCE_AUTHORIZED",humanActionRequired:true};try{const result=await reader(request);if(!result||!Array.isArray(result.records)||!Array.isArray(result.evidenceRefs)||!result.evidenceRefs.length)return {sourceId,status:"UNVERIFIED",records:[],evidenceRefs:[],firstFailure:"SOURCE_VERIFIED",humanActionRequired:true};return {sourceId,...result,status:result.status||"READ",humanActionRequired:false}}catch(error){return {sourceId,status:"DEGRADED",records:[],evidenceRefs:[],firstFailure:"SOURCE_READ",reason:error?.message||"source_read_failed",humanActionRequired:true}}}})}
function createSearchConsoleAdapter(options={}){return configuredAdapter({...options,sourceId:"GOOGLE_SEARCH_CONSOLE"})}
function createGA4Adapter(options={}){return configuredAdapter({...options,sourceId:"GA4"})}
function productReadinessSummary(records=[]){return records.map(x=>Object.freeze({organizationId:x.organizationId,productId:x.productId,version:x.version,intendedCustomer:x.intendedCustomer,intendedProblem:x.intendedProblem,readiness:x.readiness,missingCapabilities:x.missingCapabilities||[],humanTestRequirements:x.humanTestRequirements||[],knownLimitations:x.knownLimitations||[]}))}
function outcomeFeedbackSummary(records=[]){return records.map(x=>Object.freeze({id:x.id,organizationId:x.organizationId,kind:x.kind,version:x.version,opportunityFamily:x.opportunityFamily,experimentRefs:x.experimentRefs,audience:x.audience,product:x.product,resultClassification:x.resultClassification,qualifiedInterestCount:x.qualifiedInterestCount,conversionCount:x.conversionCount,completionCount:x.completionCount,continuationCount:x.continuationCount,refundClassification:x.refundClassification,revenueClassification:x.revenueClassification,contributionClassification:x.contributionClassification,evidenceRefs:x.evidenceRefs,confidence:x.confidence,limitations:x.limitations,observationWindow:x.observationWindow,provenance:x.provenance}))}
function importHumanApprovedResearch(records,{organizationId,now=()=>new Date().toISOString()}={}){if(!organizationId)throw new Error("organization_required");if(!Array.isArray(records))throw new Error("research_import_array_required");return records.map((x,i)=>{for(const k of ["source","collector","collectionTime","basis","evidenceReference","limitations","approvalReference","statement"])if(x[k]===undefined||x[k]===null||x[k]==="")throw new Error(`invalid_research_import:${i}:${k}`);if(!["PUBLIC","CONSENTED","APPROVED_NATIVE_EXPORT"].includes(x.basis))throw new Error(`unsupported_research_basis:${i}`);if(forbidden.test(JSON.stringify(x))||x.personalData)throw new Error(`private_or_credential_bearing_research:${i}`);const signalType=x.signalType||"ANECDOTE";if(!SIGNAL_TYPES.includes(signalType))throw new Error(`invalid_research_import:${i}:signalType`);return ScoutSourceObservation({id:x.id||`research:${hash(x).slice(0,16)}`,organizationId,sourceId:"HUMAN_APPROVED_RESEARCH",sourceVersion:"1.0.0",sourceResourceRef:x.source,sourceEvidenceRefs:[x.evidenceReference,x.approvalReference],observedAt:x.collectionTime,ingestedAt:now(),geographicScope:x.geographicScope||"UNKNOWN",audienceScope:x.audienceScope||"UNKNOWN",productFamilyRelevance:x.productFamilyRelevance||[],signalType,evidenceClassification:"HUMAN_APPROVED_RESEARCH",rawStateRef:hash(x),normalizedStatement:x.statement,reliabilityBasis:{collector:x.collector,basis:x.basis},freshnessState:"UNASSESSED",limitations:Array.isArray(x.limitations)?x.limitations:[x.limitations],contradictionRefs:[],privacy:{redacted:true,piiIncluded:false},provenance:{collector:x.collector,approvalReference:x.approvalReference},correlationId:x.correlationId||`import:${hash(x).slice(0,12)}`,causationId:x.approvalReference,status:"NORMALIZED",version:1})})}
module.exports={configuredAdapter,createSearchConsoleAdapter,createGA4Adapter,productReadinessSummary,outcomeFeedbackSummary,importHumanApprovedResearch};
