"use strict";
const crypto=require("node:crypto");
const forbidden=/\b(password|secret|authorization|bearer|card(number)?|cvv|bank[_ -]?account|routing[_ -]?number)\b/i;
const hash=v=>crypto.createHash("sha256").update(JSON.stringify(v)).digest("hex");
function configuredAdapter({sourceId,configuration,reader}){return Object.freeze({sourceId,async read(request={}){if(!configuration?.authorizationVerified||!configuration?.resourceVerified)return {status:"HUMAN_CONFIGURATION_REQUIRED",records:[],firstFailure:"SOURCE_AUTHORIZED",humanActionRequired:true};const result=await reader(request);return {...result,status:result.status||"READ",humanActionRequired:false}}})}
function createSearchConsoleAdapter(options={}){return configuredAdapter({sourceId:"GOOGLE_SEARCH_CONSOLE",...options})}
function createGA4Adapter(options={}){return configuredAdapter({sourceId:"GA4",...options})}
function productReadinessSummary(records=[]){return records.map(x=>Object.freeze({productId:x.productId,version:x.version,intendedCustomer:x.intendedCustomer,intendedProblem:x.intendedProblem,readiness:x.readiness,missingCapabilities:x.missingCapabilities||[],humanTestRequirements:x.humanTestRequirements||[],knownLimitations:x.knownLimitations||[]}))}
function outcomeFeedbackSummary(records=[]){return records.map(x=>Object.freeze({opportunityFamily:x.opportunityFamily,experimentRefs:x.experimentRefs,resultClassification:x.resultClassification,qualifiedInterestCount:x.qualifiedInterestCount,conversionCount:x.conversionCount,completionCount:x.completionCount,continuationCount:x.continuationCount,refundClassification:x.refundClassification,revenueClassification:x.revenueClassification,contributionClassification:x.contributionClassification,evidenceRefs:x.evidenceRefs,confidence:x.confidence,limitations:x.limitations,observationWindow:x.observationWindow,provenance:x.provenance}))}
function importHumanApprovedResearch(records,{organizationId,now=()=>new Date().toISOString()}={}){if(!Array.isArray(records))throw new Error("research_import_array_required");return records.map((x,i)=>{for(const k of ["source","collector","collectionTime","basis","evidenceReference","limitations","approvalReference","statement"])if(x[k]===undefined||x[k]===null||x[k]==="")throw new Error(`invalid_research_import:${i}:${k}`);if(!["PUBLIC","CONSENTED","APPROVED_NATIVE_EXPORT"].includes(x.basis))throw new Error(`unsupported_research_basis:${i}`);if(forbidden.test(JSON.stringify(x))||x.personalData)throw new Error(`private_or_credential_bearing_research:${i}`);return Object.freeze({id:x.id||`research:${hash(x).slice(0,16)}`,organizationId,sourceId:"HUMAN_APPROVED_RESEARCH",sourceVersion:"1.0.0",sourceResourceRef:x.source,sourceEvidenceRefs:[x.evidenceReference,x.approvalReference],observedAt:x.collectionTime,ingestedAt:now(),geographicScope:x.geographicScope||"UNKNOWN",audienceScope:x.audienceScope||"UNKNOWN",productFamilyRelevance:x.productFamilyRelevance||[],signalType:x.signalType||"ANECDOTE",evidenceClassification:"HUMAN_APPROVED_RESEARCH",rawStateRef:hash(x),normalizedStatement:x.statement,reliabilityBasis:{collector:x.collector,basis:x.basis},freshnessState:"UNASSESSED",limitations:Array.isArray(x.limitations)?x.limitations:[x.limitations],contradictionRefs:[],privacy:{redacted:true,piiIncluded:false},provenance:{collector:x.collector,approvalReference:x.approvalReference},correlationId:x.correlationId||`import:${hash(x).slice(0,12)}`,causationId:x.approvalReference,status:"NORMALIZED",version:1})})}
module.exports={createSearchConsoleAdapter,createGA4Adapter,productReadinessSummary,outcomeFeedbackSummary,importHumanApprovedResearch};
