"use strict";
const CONTRACT_VERSION="ai-business-os.scout/1.0.0";
const SIGNAL_TYPES=Object.freeze(["TRANSACTION","RETENTION","EXPLICIT_INTENT","PROBLEM_STATEMENT","ACTIVE_COMPARISON","BEHAVIORAL_INTEREST","ATTENTION","ANECDOTE","UNKNOWN"]);
const DISPOSITIONS=Object.freeze(["SEND_TO_ANALYST","NEEDS_MORE_EVIDENCE","PRODUCT_NOT_READY","STALE_SIGNAL","CONTRADICTORY","INSUFFICIENT_EVIDENCE","REJECT_UNSUPPORTED","ESCALATE_SOURCE_PROBLEM"]);
const SOURCE_STATUSES=Object.freeze(["OPERATIONAL","CONFIGURED_UNVERIFIED","HUMAN_CONFIGURATION_REQUIRED","AUTHORIZATION_REQUIRED","RATE_LIMITED","DEGRADED","BLOCKED","DESIGNED","NOT_CONFIGURED","REVOKED"]);
function record(kind,v,required){for(const key of required)if(v[key]===undefined||v[key]===null||v[key]==="")throw new Error(`invalid_${kind}:${key}`);return Object.freeze({contractVersion:CONTRACT_VERSION,kind,...v})}
const define=(kind,required)=>v=>record(kind,v||{},required);
const ScoutSourceObservation=define("ScoutSourceObservation",["id","organizationId","sourceId","sourceVersion","sourceResourceRef","sourceEvidenceRefs","observedAt","ingestedAt","geographicScope","audienceScope","productFamilyRelevance","signalType","evidenceClassification","rawStateRef","normalizedStatement","reliabilityBasis","freshnessState","limitations","contradictionRefs","privacy","provenance","correlationId","causationId","status","version"]);
const OpportunityCandidate=define("OpportunityCandidate",["id","organizationId","audience","problem","motivation","customerLanguage","productRefs","requiredCapabilityRefs","productReadiness","evidenceRefs","contradictions","unknowns","sourceDiversity","intentClassification","geography","recency","confidence","confidenceBasis","historicalOutcomeSummaryRefs","recommendedAnalystQuestion","limitations","status","version"]);
const ScoutOutcomeFeedback=define("ScoutOutcomeFeedback",["id","organizationId","opportunityFamily","experimentRefs","audience","product","resultClassification","qualifiedInterestCount","conversionCount","completionCount","continuationCount","refundClassification","revenueClassification","contributionClassification","evidenceRefs","confidence","limitations","observationWindow","provenance","version"]);
const ScoutSourceHealth=define("ScoutSourceHealth",["sourceId","sourceVersion","authorizationState","lastSuccessfulRead","lastVerifiedRecord","freshness","rateLimitState","paginationCompleteness","errorState","firstFailure","humanActionRequired","knownLimitations"]);
module.exports={CONTRACT_VERSION,SIGNAL_TYPES,DISPOSITIONS,SOURCE_STATUSES,ScoutSourceObservation,OpportunityCandidate,ScoutOutcomeFeedback,ScoutSourceHealth};
