"use strict";
const {SOURCE_STATUSES}=require("./contracts");
const required=["id","type","version","purpose","owner","provider","dataClassification","authorizationMethod","requiredScopes","permittedOperations","prohibitedOperations","freshnessPolicy","rateLimitBehavior","paginationBehavior","retryBehavior","revocationBehavior","verificationMethod","redactionPolicy","retentionPolicy","status","knownLimitations","diagnosticRequirements"];
function createScoutSourceRegistry(){const entries=new Map();return Object.freeze({register(v){for(const k of required)if(v[k]===undefined||v[k]===null||v[k]==="")throw new Error(`invalid_scout_source:${k}`);if(!SOURCE_STATUSES.includes(v.status))throw new Error("invalid_scout_source:status");if(v.status==="OPERATIONAL"&&(!v.authorizationVerified||!v.configurationVerified))throw new Error("operational_source_requires_verified_configuration_and_authorization");const key=`${v.id}@${v.version}`;if(entries.has(key))throw new Error("source_version_exists");const x=Object.freeze({...v});entries.set(key,x);return x},get:(id,version)=>entries.get(`${id}@${version}`)||null,list:()=>[...entries.values()]})}
const common={version:"1.0.0",owner:"BUSINESS_OS",dataClassification:"AGGREGATE_OR_PUBLIC",permittedOperations:["READ_SUMMARY"],prohibitedOperations:["WRITE","CONTACT","PUBLISH","SPEND","SCRAPE","BYPASS_ACCESS_CONTROL"],freshnessPolicy:{maxAgeDays:30},rateLimitBehavior:"HONOR_PROVIDER_AND_REPORT_RATE_LIMITED",paginationBehavior:"REPORT_COMPLETENESS_AND_CURSOR",retryBehavior:"BOUNDED_BACKOFF_NO_EVASION",revocationBehavior:"STOP_IMMEDIATELY_AND_REPORT_REVOKED",redactionPolicy:"REMOVE_CREDENTIALS_AND_UNNECESSARY_PII",retentionPolicy:"REFERENCES_AND_HASHES_ONLY",diagnosticRequirements:["AUTHORIZATION","FRESHNESS","PAGINATION","FIRST_FAILURE"]};
function registerDefaultScoutSources(r){[
 {id:"PRODUCT_CAPABILITY_READINESS",type:"FIRST_PARTY_READINESS",purpose:"Bounded product and capability readiness summary",provider:"CANONICAL_BUSINESS_OS",authorizationMethod:"CONSTITUTIONAL_GRANT",requiredScopes:["read:readiness"],verificationMethod:"CANONICAL_VERSION_REFERENCE",status:"CONFIGURED_UNVERIFIED",knownLimitations:["Read-only summary; no raw repository access"]},
 {id:"SCOUT_OUTCOME_FEEDBACK",type:"PRIVACY_LIMITED_OUTCOME",purpose:"Aggregate independent Learning and Economics outcomes",provider:"LEARNING_ECONOMICS",authorizationMethod:"CONSTITUTIONAL_GRANT",requiredScopes:["read:aggregate-outcomes"],verificationMethod:"EVIDENCE_REFERENCE",status:"CONFIGURED_UNVERIFIED",knownLimitations:["No customer records or payment credentials"]},
 {id:"HUMAN_APPROVED_RESEARCH",type:"APPROVED_IMPORT",purpose:"Approved manual research and native export import",provider:"AUTHORIZED_HUMAN",authorizationMethod:"APPROVAL_REFERENCE",requiredScopes:["import:approved-research"],verificationMethod:"ATTRIBUTION_AND_APPROVAL_VALIDATION",status:"CONFIGURED_UNVERIFIED",knownLimitations:["Human collection limitations preserved"]},
 {id:"GOOGLE_SEARCH_CONSOLE",type:"OWNED_SEARCH_DEMAND",purpose:"Owned-site query and page demand summaries",provider:"GOOGLE",authorizationMethod:"OFFICIAL_OAUTH_OR_SERVICE_ACCOUNT",requiredScopes:["webmasters.readonly"],verificationMethod:"VERIFIED_PROPERTY_AND_RECORD",status:"HUMAN_CONFIGURATION_REQUIRED",knownLimitations:["Impressions and clicks are not purchases"]},
 {id:"GA4",type:"FIRST_PARTY_BEHAVIOR",purpose:"Aggregate acquisition and journey-event summaries",provider:"GOOGLE",authorizationMethod:"OFFICIAL_OAUTH_OR_SERVICE_ACCOUNT",requiredScopes:["analytics.readonly"],verificationMethod:"VERIFIED_PROPERTY_AND_RECORD",status:"HUMAN_CONFIGURATION_REQUIRED",knownLimitations:["Aggregate discovery evidence only; funnel diagnosis is Analyst-owned"]},
 ...["TIKTOK","INSTAGRAM","FACEBOOK"].map(id=>({id,type:"FUTURE_SOCIAL",purpose:"Future authorized account insight or approved native export",provider:id,authorizationMethod:"OFFICIAL_API_BUSINESS_ACCOUNT_APP_REVIEW_OR_APPROVED_EXPORT",requiredScopes:["provider-approved-read-scope"],verificationMethod:"AUTHORIZED_ACCOUNT_RECORD",status:"DESIGNED",knownLimitations:["No scraping, fake accounts, CAPTCHA bypass, credential reuse, or rate-limit evasion"]}))
 ].forEach(x=>r.register({...common,...x}));return r}
module.exports={createScoutSourceRegistry,registerDefaultScoutSources};
