"use strict";
const CAPABILITIES=Object.freeze(["READ_APPROVED_SCOUT_SOURCE","READ_SEARCH_CONSOLE_SUMMARY","READ_GA4_ACQUISITION_SUMMARY","READ_PRODUCT_READINESS_SUMMARY","READ_CAPABILITY_READINESS_SUMMARY","READ_SCOUT_OUTCOME_FEEDBACK","IMPORT_HUMAN_APPROVED_RESEARCH","CREATE_SCOUT_OBSERVATION","CREATE_OPPORTUNITY_CANDIDATE","HANDOFF_CANDIDATE_TO_ANALYST"]);
const TOOL_MAP=Object.freeze({READ_APPROVED_SCOUT_SOURCE:"SCOUT_SOURCE_READ",READ_SEARCH_CONSOLE_SUMMARY:"SEARCH_CONSOLE_SUMMARY_READ",READ_GA4_ACQUISITION_SUMMARY:"GA4_ACQUISITION_SUMMARY_READ",READ_PRODUCT_READINESS_SUMMARY:"PRODUCT_READINESS_SUMMARY_READ",READ_CAPABILITY_READINESS_SUMMARY:"PRODUCT_READINESS_SUMMARY_READ",READ_SCOUT_OUTCOME_FEEDBACK:"SCOUT_OUTCOME_FEEDBACK_READ",IMPORT_HUMAN_APPROVED_RESEARCH:"HUMAN_APPROVED_RESEARCH_IMPORT",CREATE_SCOUT_OBSERVATION:"SCOUT_OBSERVATION_CREATE",CREATE_OPPORTUNITY_CANDIDATE:"OPPORTUNITY_CANDIDATE_CREATE",HANDOFF_CANDIDATE_TO_ANALYST:"ANALYST_CANDIDATE_HANDOFF"});
function registerScoutTools(registry,organizationId,{availableCapabilityIds=[]}={}){
 if(!organizationId)throw new Error("organization_required");const enabled=new Set(availableCapabilityIds);for(const id of enabled)if(!CAPABILITIES.includes(id))throw new Error(`unknown_scout_capability:${id}`);
 const toolIds=[...new Set(Object.values(TOOL_MAP))];
 for(const toolId of toolIds){const supportedCapabilityIds=Object.entries(TOOL_MAP).filter(([,t])=>t===toolId).map(([c])=>c),available=supportedCapabilityIds.some(id=>enabled.has(id));registry.registerTool({id:toolId,organizationId,name:toolId,version:1,description:"Governed Scout read, normalize, record, or handoff boundary",inputSchema:{type:"object",required:["organizationId"]},outputSchema:{type:"object",required:["status","evidenceRefs"]},risk:"LOW",cost:{currency:"USD",amount:0},timeoutMs:5000,retryPolicy:{maxAttempts:2},idempotency:true,authorityRequirements:[`tool.${toolId}`],policyRequirements:["SCOUT_REASONING_POLICY_V1"],sideEffect:["SCOUT_OBSERVATION_CREATE","OPPORTUNITY_CANDIDATE_CREATE","ANALYST_CANDIDATE_HANDOFF"].includes(toolId)?"GOVERNED_INTERNAL_ARTIFACT":"READ_ONLY",reversibility:"APPEND_ONLY",limitations:["No outreach, publication, spend, payments, activation, or unrestricted browsing","Unavailable until implementation, configuration, and verification evidence are supplied"],status:available?"AVAILABLE":"UNAVAILABLE",verificationRequirements:["EVIDENCE_REFERENCE"],supportedCapabilityIds,autonomyLevels:["OBSERVE","RECOMMEND"],killSwitchApplicable:true,schemaVersion:"1.0.0"})}
 for(const capabilityId of CAPABILITIES){const available=enabled.has(capabilityId),toolId=TOOL_MAP[capabilityId];registry.registerCapability({id:capabilityId,organizationId,name:capabilityId,version:1,description:"Narrow Scout capability",requiredInputs:["organizationId"],producedOutputs:["status","evidenceRefs"],requiredToolIds:[toolId],optionalToolIds:[],validationStatus:available?"VALIDATED":"DESIGNED",limitations:["Bounded to approved sources and governed artifacts","Not selectable until explicitly enabled with verification evidence"],risk:"LOW",estimatedCost:{currency:"USD",amount:0},estimatedDurationMs:5000,autonomyLevel:"RECOMMEND",humanRequiredSteps:capabilityId==="IMPORT_HUMAN_APPROVED_RESEARCH"?["approval-reference"]:[],authorityRequirements:[`tool.${toolId}`],policyRequirements:["SCOUT_REASONING_POLICY_V1"],status:available?"AVAILABLE":"UNAVAILABLE",schemaVersion:"1.0.0"})}
 return {capabilities:CAPABILITIES,tools:toolIds,availableCapabilities:[...enabled]}
}
module.exports={CAPABILITIES,TOOL_MAP,registerScoutTools};
