// src/domains/fitness.js
"use strict";

const fs = require("fs");
const path = require("path");

// Optional external brain (FastAPI)
// Keep this if you still want Ma’at coaching. If down, system still works.
const BRAIN_BASE_URL = process.env.MAAT_URL || "https://mufasabrain.onrender.com";
const ASK_URL = `${BRAIN_BASE_URL}/ask`;
const PROFILE_UPSERT_URL = `${BRAIN_BASE_URL}/users/profile/upsert`;
const PROGRAM_GEN_URL = `${BRAIN_BASE_URL}/coach/program/generate`;
const PROGRAM_LIST_URL = `${BRAIN_BASE_URL}/coach/program/list`;
const PROGRAM_GET_URL = `${BRAIN_BASE_URL}/coach/program/get`;

// Local data storage
const ROOT = process.cwd();
const DATA_DIR = path.join(ROOT, "data");
const USER_DIR = path.join(DATA_DIR, "users");

// Exercise DB index (static file generated by scripts/build-exercise-index.js)
const EX_INDEX_PATH = path.join(ROOT, "public", "exercise-db", "index.json");
const PUBLIC_DIR = path.join(ROOT, "public");

if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
if (!fs.existsSync(USER_DIR)) fs.mkdirSync(USER_DIR, { recursive: true });

// ─────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────

function now() {
  return Date.now();
}

function createSessionId() {
  return "sess_" + Date.now();
}

function readJSON(p) {
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

function writeJSON(p, obj) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(obj, null, 2));
}

function getUserPath(userId) {
  return path.join(USER_DIR, `${userId}.json`);
}

function loadUser(userId) {
  const p = getUserPath(userId);
  if (fs.existsSync(p)) return readJSON(p);
  return { userId, createdAt: now(), updatedAt: now(), events: [], sessions: {} };
}

function saveUser(user) {
  user.updatedAt = now();
  writeJSON(getUserPath(user.userId), user);
}

function pushEvent(user, command, payload) {
  user.events = user.events || [];
  user.events.push({ ts: now(), command, payload });
}

function loadExerciseIndexOrNull() {
  if (!fs.existsSync(EX_INDEX_PATH)) return null;
  try {
    return readJSON(EX_INDEX_PATH);
  } catch {
    return null;
  }
}

function findExerciseBySlug(index, slug) {
  const list = index?.exercises || [];
  return list.find(x => x.slug === slug) || null;
}

function safeLower(x) {
  return String(x || "").toLowerCase();
}

// ─────────────────────────────────────────────
// Entry point
// ─────────────────────────────────────────────

async function handleFitnessCommand(context) {
  const { command, userId, payload, app } = context;

  switch (command) {
    case "fitness.startSession":
      return await handleStartSession(userId, payload, app);

    case "fitness.repUpdate":
      return await handleRepUpdate(userId, payload, app);

    case "fitness.endSession":
      return await handleEndSession(userId, payload, app);

    case "fitness.saveProfile":
      return await handleSaveProfile(userId, payload, app);

    case "fitness.ohsaResult":
      return await handleOhsaResult(userId, payload, app);

    case "fitness.generateProgram":
      return await handleGenerateProgram(userId, payload, app);

    case "fitness.listPrograms":
      return await handleListPrograms(userId, payload, app);

    case "fitness.getProgram":
      return await handleGetProgram(userId, payload, app);

    case "fitness.askCoach":
      return await handleAskCoach(userId, payload, app);

    // NEW: Exercise DB actions
    case "fitness.listExercises":
      return await handleListExercises(payload);

    case "fitness.searchExercises":
      return await handleSearchExercises(payload);

    case "fitness.getExercise":
      return await handleGetExercise(payload);

    default:
      throw new Error("Unknown fitness command: " + command);
  }
}

// ─────────────────────────────────────────────
// Session + Telemetry (LOCAL FIRST)
// ─────────────────────────────────────────────

async function handleStartSession(userId, payload, app) {
  if (!userId) throw new Error("fitness.startSession requires userId");

  const broadcast = app?.locals?.broadcast;
  const { programId } = payload || {};
  const sessionId = payload?.sessionId || createSessionId();

  const user = loadUser(userId);
  pushEvent(user, "fitness.startSession", payload);

  user.sessions = user.sessions || {};
  user.sessions[sessionId] = {
    sessionId,
    programId: programId || null,
    startedAt: now(),
    endedAt: null,
    repUpdates: []
  };

  saveUser(user);

  if (broadcast) {
    broadcast({
      event: "fitness.sessionStarted",
      userId,
      sessionId,
      programId: programId || null
    });
  }

  return { ok: true, sessionId, programId: programId || null, message: "Session started" };
}

async function handleRepUpdate(userId, payload, app) {
  if (!userId) throw new Error("fitness.repUpdate requires userId");

  const broadcast = app?.locals?.broadcast;
  const { sessionId, exerciseId, repsThisSet, totalReps, depthScore, goodForm } = payload || {};

  const user = loadUser(userId);
  pushEvent(user, "fitness.repUpdate", payload);

  if (sessionId) {
    user.sessions = user.sessions || {};
    user.sessions[sessionId] = user.sessions[sessionId] || { sessionId, startedAt: now(), repUpdates: [] };
    user.sessions[sessionId].repUpdates.push({
      ts: now(),
      exerciseId: exerciseId || null,
      repsThisSet: repsThisSet ?? null,
      totalReps: totalReps ?? null,
      depthScore: depthScore ?? null,
      goodForm: goodForm ?? null
    });
  }

  saveUser(user);

  // 1) Broadcast raw telemetry
  if (broadcast) {
    broadcast({
      event: "fitness.repUpdate",
      userId,
      sessionId,
      exerciseId,
      repsThisSet,
      totalReps,
      depthScore,
      goodForm
    });
  }

  // 2) Optional Ma’at coaching (won’t break if down)
  let coachingText = null;
  try {
    if (process.env.MAAT_DISABLE !== "1") {
      coachingText = await callMaatForCoaching({
        userId,
        sessionId,
        exerciseId,
        repsThisSet,
        totalReps,
        depthScore,
        goodForm
      });
    }
  } catch (err) {
    console.error("Ma’at coaching call failed (non-fatal):", err.message || err);
  }

  // 3) Broadcast coaching
  if (broadcast && coachingText) {
    broadcast({
      event: "fitness.coaching",
      userId,
      sessionId,
      exerciseId,
      repsThisSet,
      totalReps,
      depthScore,
      goodForm,
      coaching: coachingText
    });
  }

  return { ok: true, coaching: coachingText, message: "Rep update processed" };
}

async function handleEndSession(userId, payload, app) {
  if (!userId) throw new Error("fitness.endSession requires userId");

  const broadcast = app?.locals?.broadcast;
  const { sessionId, repsCompleted, exerciseId } = payload || {};

  const user = loadUser(userId);
  pushEvent(user, "fitness.endSession", payload);

  if (sessionId && user.sessions?.[sessionId]) {
    user.sessions[sessionId].endedAt = now();
    user.sessions[sessionId].summary = {
      repsCompleted: repsCompleted || 0,
      exerciseId: exerciseId || null
    };
  }

  saveUser(user);

  if (broadcast) {
    broadcast({
      event: "fitness.sessionEnded",
      userId,
      sessionId,
      repsCompleted: repsCompleted || 0,
      exerciseId: exerciseId || null
    });
  }

  return { ok: true, message: "Session ended" };
}

// ─────────────────────────────────────────────
// Profile (LOCAL FIRST + optional remote sync)
// ─────────────────────────────────────────────

async function handleSaveProfile(userId, payload, app) {
  if (!userId) throw new Error("fitness.saveProfile requires userId");

  const broadcast = app?.locals?.broadcast;
  const profile = (payload && payload.profile) || {};

  const user = loadUser(userId);
  pushEvent(user, "fitness.saveProfile", payload);

  user.profile = {
    age: profile.age ?? null,
    height_cm: profile.height_cm ?? profile.heightCm ?? null,
    weight_kg: profile.weight_kg ?? profile.weightKg ?? null,
    goals: profile.goals || null,
    injuries: profile.injuries || null,
    notes: profile.notes || profile.historyText || null
  };

  saveUser(user);

  // Optional remote sync (non-fatal)
  try {
    if (process.env.MAAT_DISABLE !== "1") {
      await remoteProfileUpsert(userId, user.profile);
    }
  } catch (e) {
    console.error("Remote profile sync failed (non-fatal):", e.message || e);
  }

  if (broadcast) {
    broadcast({ event: "fitness.profileSaved", userId, profile: user.profile });
  }

  return { ok: true, profile: user.profile };
}

async function remoteProfileUpsert(userId, profile) {
  const body = {
    user_id: userId,
    age: profile.age ?? null,
    height_cm: profile.height_cm ?? profile.heightCm ?? profile.height_cm ?? null,
    weight_kg: profile.weight_kg ?? profile.weightKg ?? profile.weight_kg ?? null,
    goals: profile.goals || null,
    injuries: profile.injuries || null,
    notes: profile.notes || null
  };

  const resp = await fetch(PROFILE_UPSERT_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body)
  });

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`Profile upsert HTTP ${resp.status}: ${text}`);
  }
  return await resp.json();
}

// ─────────────────────────────────────────────
// OHSA (LOCAL STORE + optional auto program)
// ─────────────────────────────────────────────

async function handleOhsaResult(userId, payload, app) {
  if (!userId) throw new Error("fitness.ohsaResult requires userId");

  const broadcast = app?.locals?.broadcast;
  const { summary, autoProgram = false } = payload || {};
  if (!summary) throw new Error("fitness.ohsaResult requires payload.summary");

  const user = loadUser(userId);
  pushEvent(user, "fitness.ohsaResult", payload);

  user.ohsa = user.ohsa || [];
  user.ohsa.push({ ts: now(), summary, payload });
  saveUser(user);

  if (broadcast) {
    broadcast({ event: "fitness.ohsaResult", userId, summary });
  }

  // Optional program generation
  let program = null;
  let programId = null;

  if (autoProgram && process.env.MAAT_DISABLE !== "1") {
    try {
      const prog = await generateProgramForUser(userId, payload || {});
      program = prog.program;
      programId = prog.program_id;

      if (broadcast) {
        broadcast({
          event: "fitness.programGenerated",
          userId,
          from: "ohsa",
          programId,
          programMeta: {
            title: program?.title,
            goal: program?.goal,
            weeks: program?.weeks,
            days_per_week: program?.days_per_week
          }
        });
      }
    } catch (e) {
      console.error("Auto program generation failed (non-fatal):", e.message || e);
    }
  }

  return { ok: true, summary, programId, program };
}

// ─────────────────────────────────────────────
// Program generation / listing / fetch (REMOTE)
// ─────────────────────────────────────────────

async function generateProgramForUser(userId, opts) {
  const body = {
    user_id: userId,
    goal: opts.goal || "General strength and wellness program.",
    weeks: opts.weeks || 8,
    days_per_week: opts.daysPerWeek || opts.days_per_week || 3,
    home_only: opts.homeOnly !== undefined ? opts.homeOnly : true,
    yoga_heavy: opts.yogaHeavy !== undefined ? opts.yogaHeavy : true,
    assessment_summary: opts.assessmentSummary || opts.assessment_summary || null,
    extra_context: opts.extraContext || opts.extra_context || ""
  };

  const resp = await fetch(PROGRAM_GEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body)
  });

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`Program generate HTTP ${resp.status}: ${text}`);
  }

  const data = await resp.json();
  return { program_id: data.program_id, program: data.program };
}

async function handleGenerateProgram(userId, payload, app) {
  if (!userId) throw new Error("fitness.generateProgram requires userId");
  if (process.env.MAAT_DISABLE === "1") throw new Error("MAAT is disabled on this server.");

  const broadcast = app?.locals?.broadcast;
  const prog = await generateProgramForUser(userId, payload || {});

  if (broadcast) {
    broadcast({
      event: "fitness.programGenerated",
      userId,
      from: "command",
      programId: prog.program_id,
      programMeta: {
        title: prog.program?.title,
        goal: prog.program?.goal,
        weeks: prog.program?.weeks,
        days_per_week: prog.program?.days_per_week
      }
    });
  }

  return { ok: true, programId: prog.program_id, program: prog.program };
}

async function handleListPrograms(userId) {
  if (!userId) throw new Error("fitness.listPrograms requires userId");
  if (process.env.MAAT_DISABLE === "1") throw new Error("MAAT is disabled on this server.");

  const url = `${PROGRAM_LIST_URL}?user_id=${encodeURIComponent(userId)}`;
  const resp = await fetch(url);

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`Program list HTTP ${resp.status}: ${text}`);
  }

  const data = await resp.json();
  return { ok: true, programs: data.programs || [] };
}

async function handleGetProgram(_userId, payload) {
  const { programId } = payload || {};
  if (!programId) throw new Error("fitness.getProgram requires programId");
  if (process.env.MAAT_DISABLE === "1") throw new Error("MAAT is disabled on this server.");

  const url = `${PROGRAM_GET_URL}?program_id=${encodeURIComponent(programId)}`;
  const resp = await fetch(url);

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`Program get HTTP ${resp.status}: ${text}`);
  }

  const data = await resp.json();
  return { ok: true, program: data.program || null };
}

// ─────────────────────────────────────────────
// Ask Coach (REMOTE, but safe)
// ─────────────────────────────────────────────

async function handleAskCoach(userId, payload, app) {
  const broadcast = app?.locals?.broadcast;
  const { question, telemetry, context, sessionId, mode = "chat" } = payload || {};
  if (!question) throw new Error("fitness.askCoach requires payload.question");

  if (process.env.MAAT_DISABLE === "1") {
    return { ok: true, answer: "Coach is offline right now. Keep going—focus on form + steady reps.", actions: [] };
  }

  const body = {
    question,
    user_id: userId || "anonymous",
    session_id: sessionId || null,
    telemetry: telemetry || null,
    context: typeof context === "string" ? context : JSON.stringify(context || {}),
    mode
  };

  const resp = await fetch(ASK_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body)
  });

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`Ma’at /ask HTTP ${resp.status}: ${text}`);
  }

  const data = await resp.json();
  const answer = data.answer || data.response || "";
  const actions = Array.isArray(data.actions) ? data.actions : [];

  if (broadcast) {
    broadcast({ event: "fitness.llmAnswer", userId, question, answer, actions });
  }

  return { ok: true, answer, actions };
}

async function callMaatForCoaching({
  userId,
  sessionId,
  exerciseId,
  repsThisSet,
  totalReps,
  depthScore,
  goodForm
}) {
  const question = [
    "You are Ma’at 2.0, a concise, encouraging Pan-African coach.",
    "Given this live telemetry, give one or two short coaching cues",
    "in second person (you...), mixing encouragement with 1 clear form tip.",
    "",
    `userId: ${userId || "unknown"}`,
    `sessionId: ${sessionId || "none"}`,
    `exerciseId: ${exerciseId || "unknown"}`,
    `repsThisSet: ${repsThisSet != null ? repsThisSet : "unknown"}`,
    `totalReps: ${totalReps != null ? totalReps : "unknown"}`,
    `depthScore (0-1): ${depthScore != null ? depthScore : "unknown"}`,
    `goodForm: ${goodForm !== undefined ? goodForm : "unknown"}`
  ].join("\n");

  const telemetry = {
    exercise_id: exerciseId || "unknown",
    reps: totalReps ?? repsThisSet ?? 0,
    depth_score: depthScore ?? 0,
    good_form: goodForm ?? false
  };

  const body = {
    question,
    user_id: userId || "anonymous",
    session_id: sessionId || null,
    telemetry,
    mode: "chat"
  };

  const resp = await fetch(ASK_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body)
  });

  if (!resp.ok) throw new Error(`Ma’at /ask HTTP ${resp.status}`);
  const data = await resp.json();
  return data.answer || null;
}

// ─────────────────────────────────────────────
// Exercise DB Commands (LOCAL)
// ─────────────────────────────────────────────

async function handleListExercises(payload) {
  const idx = loadExerciseIndexOrNull();
  if (!idx) throw new Error("Missing public/exercise-db/index.json. Run build:exercise-index and commit it.");

  const limit = Number(payload?.limit || 200);
  return {
    ok: true,
    total: idx.totalFolders || (idx.exercises || []).length,
    results: (idx.exercises || []).slice(0, Math.max(1, Math.min(limit, 2000)))
  };
}

async function handleSearchExercises(payload) {
  const idx = loadExerciseIndexOrNull();
  if (!idx) throw new Error("Missing public/exercise-db/index.json. Run build:exercise-index and commit it.");

  const q = safeLower(payload?.q || "").trim();
  const limit = Number(payload?.limit || 100);

  if (!q) {
    return { ok: true, q: "", results: (idx.exercises || []).slice(0, Math.max(1, Math.min(limit, 2000))) };
  }

  const list = idx.exercises || [];
  const results = list.filter(x => {
    const n = safeLower(x.name);
    const c = safeLower(x.category);
    const e = safeLower(x.equipment);
    const t = safeLower(x.target);
    return n.includes(q) || c.includes(q) || e.includes(q) || t.includes(q);
  });

  return {
    ok: true,
    q,
    totalMatches: results.length,
    results: results.slice(0, Math.max(1, Math.min(limit, 2000)))
  };
}

async function handleGetExercise(payload) {
  const idx = loadExerciseIndexOrNull();
  if (!idx) throw new Error("Missing public/exercise-db/index.json. Run build:exercise-index and commit it.");

  const slug = payload?.slug;
  if (!slug) throw new Error("fitness.getExercise requires payload.slug");

  const meta = findExerciseBySlug(idx, slug);
  if (!meta) throw new Error("Unknown exercise slug: " + slug);

  if (!meta.json) {
    return { ok: true, meta, data: null, warning: "No JSON file mapped for this exercise folder." };
  }

  const jsonPath = path.join(PUBLIC_DIR, meta.json);
  if (!fs.existsSync(jsonPath)) {
    throw new Error("Exercise JSON missing on disk: " + jsonPath);
  }

  const data = readJSON(jsonPath);
  return { ok: true, meta, data };
}

module.exports = { handleFitnessCommand };
